### ISSUE TITLE
admob: json: cannot unmarshal array into Go value of type admob.GenerateMediationReportResponse

### ISSUE THREAD

**Issue by chornij** [googleapis/google-api-go-client#1010]
When I try to get estimated earnings grouped by date, country, and platform googleapis server returning an error:

> json: cannot unmarshal array into Go value of type admob.GenerateMediationReportResponse

Instead of returning a single GenerateMediationReportResponse object (with single ReportFooter, ReportHeader and ReportRow props), it returning an array of objects (one ReportFooter, one ReportHeader and multiple ReportRow).

The actual result can be viewed in [oauth playground](https://developers.google.com/oauthplayground/) with a request:
```
{
    "reportSpec": {
        "dateRange": {
            "endDate": {
                "day": 2,
                "month": 4,
                "year": 2021
            },
            "startDate": {
                "day": 2,
                "month": 4,
                "year": 2021
            }
        },
        "dimensions": [
            "DATE",
            "APP",
            "COUNTRY",
            "PLATFORM"
        ],
        "metrics": [
            "ESTIMATED_EARNINGS"
        ]
    }
}
```

Actual response structure:
```
[
    {
        "header": {}
    },
    {
        "row": {}
    },
    {
        "row": {}
    },
    {
        "footer": {}
    }
]
```

**Comment by codyoss** [comment]
Hey,

It does appear that the response object is not correct for this call, thank you for the report. This appears to be a problem with the published API  spec and not the client library that is generated from that spec. There was another similar issue to this it appears: #468. I am going to close this issue in favor of updating that one thread. I have re-bumped internal bug 154313078. I will report back on the linked bug when I hear more.
