### ISSUE TITLE
Not able to filter Firewall Rules  by targetTags,sourceTags,  or other list properties

### ISSUE THREAD

**Issue by SamuelNeves** [googleapis/google-api-go-client#1019]
Hello I am trying to filter  firewall rules, by sourceTags,targetTags an other fields that are lists and I am receiving the following error:

Piece of code:
`req := computeService.Firewalls.List(project).Filter("sourceTags=allow-http-tag")`

error:
`2021/05/12 15:10:04 googleapi: Error 400: Invalid value for field 'filter': 'sourceTags[]=*'. Invalid list filter expression., invalid
exit status 1`

If I try to filter by name it works:
`req := computeService.Firewalls.List(project).Filter("name=allow*")`

There is a way to check the correct filters syntax? I am trying to use filters following the pattern described in this doc https://cloud.google.com/sdk/gcloud/reference/topic/filters

**Comment by codyoss** [comment]
Hey, thanks for the report. I don't believe that this is an issue with our generated client, but possibly the API itself. I have filed http://issuetracker.google.com/issues/188066355 for tracking.
