### ISSUE TITLE
Documentation: Using Proxy-Authorization in idtoken library.

### ISSUE THREAD

**Issue by eahrend** [googleapis/google-api-go-client#1020]
Currently the only documentation regarding Proxy-Authorization is listed here:
https://cloud.google.com/iap/docs/authentication-howto#authenticating_from_proxy-authorization_header

I'm not sure if it's just me but the documentation on GCP's page was kind of vague and I spent a decent amount of time seeing how I could prevent the idtoken http client from overriding my authorization header, and while I figured it out, I didn't see any explicit examples so if possible can we add an example for this? This was my solution, but if there is a more generic or better written example that would work too.

```GO


func main() {
	ctx := context.Background()
	audience := "longstring.apps.googleusercontent.com"
	ts, err := idtoken.NewTokenSource(ctx, audience)
	if err != nil {
		// handle error
	}
	// can't use the idtoken httpclient since it will override your authorization header
	client := &http.Client{}
	req, err := http.NewRequest("GET","https://iap-secured.example.com",nil)
	if err != nil {
		// handle error
	}
	token,err := ts.Token()
	if err != nil {
		// handle error
	}
	req.Header.Set("Proxy-Authorization", fmt.Sprintf("Bearer %s", token.AccessToken))
	req.SetBasicAuth("username", "password")
	resp, err := client.Do(req)
	if err != nil {
		// handle error
	}
	// do something with resp
}
```

**Comment by codyoss** [comment]
@eahrend Thank you for the feedback. I think the best place for an example like this might be along side the IAP documentation. I will keep this issue open for tracking purposed for now, but may close and file an internal issue in the future. Thank you for bringing this use case up!

**Comment by eahrend** [comment]
@codyoss No worries! Appreciate it.

**Comment by codyoss** [comment]
This is now being tracked internally at b/195938959. Closing this issue. Thanks again for this feedback!
