### ISSUE TITLE
drive.Service.Files.List() does not have .PageSize(n), quickstart guide not working

### ISSUE THREAD

**Issue by liamvdv** [googleapis/google-api-go-client#1037]
Hi, I'm trying out the drive api with the official quickstart guide (https://developers.google.com/drive/api/v3/quickstart/go). 
It doesn't work, because `drive.Service.Files.List()` returns `*FilesListCall`, which **does not** have a `PageSize(n)` method. Thus the code example provided doesn't work.

Reading the `drive-gen.go` source code didn't give me a clue to what other function I should use instead. `FilesListCall.urlParams_` isn't exported.
How should I set the page size param?

Thank you for your help.

Machine info:
Platform: wsl/ubuntu
Go-Version: Go@1.16.3
Mod-Version: google.golang.org/api v0.47.0 of which google.golang.org/api/drive/v2 is part.

**Comment by codyoss** [comment]
Hey @liamvdv it looks like you are using `google.golang.org/api/drive/v2` but that quickstart is for v3. I double checked and v3 does have the PageSize method. Hope that helps!

**Comment by liamvdv** [comment]
Okey great, thanks! I didn't think of that. Have a nice day!
