### ISSUE TITLE
androidpublisher: purchases.products.acknowledge return 400 and 409 sometime

### ISSUE THREAD

**Issue by richzw** [googleapis/google-api-go-client#1077]
We try to do acknowledge google play purchase on the server-side through [purchases.products.acknowledge](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.products/acknowledge) with golang

However, the following errors come up sometime 

```
googleapi: Error 409: The operation could not be performed since the object was 
already in the process of being updated., concurrentUpdate
```

```
googleapi: Error 400: The purchase is not in a valid state to perform the desired operation
```

Is there anything am I missing? or how to solve those errors?

**Comment by codyoss** [comment]
Hey @richzw sorry you are having issues using this API. This issue tracker is primary for the generated client itself and not for questions about this API. I am currently unable to find a support page for this API though so I have opened an internal bug to find out where the correct place to ask this question. Internal bug 191748868.

**Comment by codyoss** [comment]
Please reach out via this form: https://support.google.com/googleplay/android-developer/gethelp?visit_id=637599741297094070-2434654640&rd=1#. It can be found under the [Getting started](https://developers.google.com/android-publisher) section on the API overview page.
