### ISSUE TITLE
idtoken package has been broken since v0.49.0 when service_account credential is used

### ISSUE THREAD

**Issue by apstndb** [googleapis/google-api-go-client#1092]
#### Environment details

  - Programming language: Go 
  - OS: macOS
  - Language runtime version: Go 1.16.2
  - Package version: v0.49.0

#### Steps to reproduce

Minimal reproducible code.

```
package main

import (
	"context"
	"log"

	"google.golang.org/api/idtoken"
)

func main() {
	_, err := idtoken.NewTokenSource(context.Background(), "https://example.com")
	if err != nil {
		log.Fatalln(err)
	}
}
```
In `v0.49.0`:
```
$ GOOGLE_APPLICATION_CREDENTIALS=sa.json go run ./
2021/06/28 18:28:33 neither scopes or audience are available for the self-signed JWT
```

In `v0.48.0`, it succeed.

It seems to be related with this comment https://github.com/googleapis/google-api-go-client/pull/1075#discussion_r653919814 and `idtoken` package doesn't specify `WithAudience`.

**Comment by bweston92** [comment]
I opened an issue on the docs that is a temporary work around for this: https://github.com/GoogleCloudPlatform/golang-samples/issues/2125

**Comment by codyoss** [comment]
Thank you for the report, I will investigate why this is happening.

**Comment by codyoss** [comment]
https://github.com/googleapis/google-api-go-client/releases/tag/v0.50.0 includes the fix!

**Comment by bweston92** [comment]
Hey @codyoss thanks for taking the time to put a fix in :) appreciated.

**Comment by codyoss** [comment]
Of course! 😸
