### ISSUE TITLE
AutoComplete for the Compute package

### ISSUE THREAD

**Issue by denissimonovski** [googleapis/google-api-go-client#1094]
I'm using a JetBrains IDE. I can't make auto complete work for the Compute package. 
Some packages work ok, like networkmanagement. 
For compute I tried go get, git clone locally, go install nothing works. 
I say compute.NewService(ctx) and NewService is not found.
Can someone tell me why this is?

**Comment by codyoss** [comment]
@denissimonovski I am not sure why this would be that way, but my best guess would be that Goland is having a hard time computing auto complete for such a large single package. I would suggest opening up an issue with JetBrains. Sorry I could not be of more help.
