### ISSUE TITLE
Adsense v2 api

### ISSUE THREAD

**Issue by jacklberk** [googleapis/google-api-go-client#1144]
Hi apologies if this has been asked, google is currently sunsetting 1.4 api, is v2 api for adsense in progress?

https://developers.google.com/adsense/management/migrating

**Comment by codyoss** [comment]
If this is the client you are referring to it looks like it already exists. https://github.com/googleapis/google-api-go-client/tree/master/adsense/v2. Let me know if you have further questions. Closing as I believe this is what you are referencing.

**Comment by jacklberk** [comment]
OK thanks let me check it out
