### ISSUE TITLE
Add ability to create an Anonymous user from the Go Auth Client.

### ISSUE THREAD

**Issue by jarrodhroberson** [googleapis/google-api-go-client#1158]
I would like the ability to create "Anonymous" user accounts from Go code on the server side.

Right now the only way I can see to create them is with the JavaScript client, or one of the mobile clients, which I am not using.

Only workaround I can see is possibly using a Cloud Function written in JavaScript so I can use the JavaScript client.
But that is a hack workaround that will just lower cohesion, increase maintenance efforts and more to hold in your head about how this are supposed to work.

**Comment by codyoss** [comment]
Hey @jarrodhroberson, thanks for taking time to file an issue. Can you help me better understand what you mean by Anonymous user accounts. Are you talking about google accounts? If you could link me to an example of the equivalent in JS that may be helpful and\or the JS client you are talking about.

**Comment by jarrodhroberson** [comment]
Like explained here.

[firebase.auth.Auth#signinanonymously](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signinanonymously)

`firebase.auth().signInAnonymously().catch(function(error) {
  // Handle Errors here.
  var errorCode = error.code;
  var errorMessage = error.message;

  if (errorCode === 'auth/operation-not-allowed') {
    alert('You must enable Anonymous auth in the Firebase Console.');
  } else {
    console.error(error);
  }
});`

If you try and create a user with the Go client it refuses to create a user because all the UserToCreate files are required to have something valid in them. Empty Strings throw errors.

**Comment by jarrodhroberson** [comment]
I figured out how to do this with the raw REST api.

```
func createAnonymousAccount(ctx context.Context) (string, error) {
    apiKey := secret.GetSecretAsString(ctx, secret.FIREBASE_WEB_API_KEY)
	req, err := json.Marshal(map[string]interface{}{
		"returnSecureToken": true,
	})
	if err != nil {
        return "", err
	}
    resp, err := postRequest(fmt.Sprintf("https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=%s", apiKey), req)
	if err != nil {
        return "", err
	}
	var respBody struct {
		IDToken string `json:"idToken"`
	}
	if err := json.Unmarshal(resp, &respBody); err != nil {
        return "", err
	}
    return respBody.IDToken, err
}
```

This is obviously not the best way to do this, I totally expect it to break at some point because of changes.

A well documented method on the existing client to do this would be greatly appreciated.

**Comment by jarrodhroberson** [comment]
I figured out how to do what I wanted with the Go client after MUCH trial and error and by accident. Apparently if you send in `""` for the "required" fields it fails because it tries to validate them. If you just do not include those fields it creates an anonymous account. This completely violates the "principal of least astonishment", if a field is marked "required" in the docs but you can leave it out then it is not "required".
