### ISSUE TITLE
How to configure API key in the recommended way when using option.WithHTTPClient

### ISSUE THREAD

**Issue by anoriqq** [googleapis/google-api-go-client#1170]
I'm using youtube.Service with API key authentication.
Currently, I'm creating youbute.Service by passing my own configured HTTPClient to youtube.New.

```go
c := &http.Client{
	Transport: &transport.APIKey{Key: key}, // transport.APIKey is deprecated
}
// ... Configure http.Client uniquely
s, err := youtube.New(c) // youtube.New is deprecated
```

youtube.New and transport.APIKey are deprecated, so I'm trying to replace them with youtube.NewService.
However, if I use option.WithHTTPClient for youtube.NewService, option.WithAPIKey will be ignored.

Is there any other way than to continue using transport.APIKey as deprecated?

Thank You

May be related
- https://github.com/googleapis/google-api-go-client/issues/340

**Comment by codyoss** [comment]
Hey @anoriqq thanks for reaching out. Are you doing anything special with your HTTP client where you need to pass in a custom client? If not, I would recommend just doing

```
youtube.NewService(context.Background(), option.("some-key"))
```

The default client should work great for most use-cases.

**Comment by anoriqq** [comment]
Thank you for answering.

> Are you doing anything special with your HTTP client where you need to pass in a custom client?

I'm applying Prometheus and AWS X-Ray by wrapping http.Roundtripper for monitoring and analysis.
Also changing timeout.

**Comment by codyoss** [comment]
In that case you may want to make use of one of the methods in this package: https://pkg.go.dev/google.golang.org/api/transport/http. Specifically the NewTransport method might be what you are looking for. Then you can create a new http.Client with that transport and send it in to the service with the HTTP client option. Will that fix your use case?

**Comment by anoriqq** [comment]
Solved in my use case! :100:
Thank you very much for providing us with useful information!
