### ISSUE TITLE
idtoken: Using NewValidator with Google credentials in the environments means you can't validate tokens

### ISSUE THREAD

**Issue by peterwillis** [googleapis/google-api-go-client#1187]
#### Environment details

  - Programming language: Go
  - OS: Linux
  - Language runtime version: 1.17
  - Package version: v0.54.0

#### Steps to reproduce

When I create a validator with `idtoken.NewValidator(ctx)` and then use `v.Validate(ctx, "valid token", "valid audience")` there is an error that shows the certs endpoint is returning a 400. I think this is because library picks up `GOOGLE_APPLICATION_CREDENTIALS` in the environment and adds an authorization header to the request made to the certs endpoint at `https://www.googleapis.com/oauth2/v3/certs` which is not accepted as it's invalid to pass credentials to that public endpoint.

If I don't use `NewValidator` and instead use `idtoken.Validate(ctx, "valid token", "valid audience")` then I can see the code is picking `http.DefaultClient` and not adding any authorization headers and everything works.

That means I have to create a validator explicitly overriding the `http.Client` with `idtoken.NewValidator(ctx, idtoken.WithHTTPClient(http.DefaultClient))`. This seems counter intuitive.

**Comment by codyoss** [comment]
@peterwillis You are right, this should be a bug. I opened a PR to fix this issue.
