### ISSUE TITLE
networkconnectivity : Malformed name while trying to create Hub

### ISSUE THREAD

**Issue by venkyfff** [googleapis/google-api-go-client#1192]
I am trying to create a hub in network connectivity center using golang APIs. But i am getting the following error:

```<nil> googleapi: Error 400: Malformed name: 'projects/xxxxxx/locations/global/hubs/', badRequest```

My code is 

```
import (
	"fmt"
	"google.golang.org/api/networkconnectivity/v1alpha1"
)
....
hubsServiceCall := Service.Projects.Locations.Global.Hubs.Create(
		"projects/xxxxxxx/locations/global",
		&networkconnectivity.Hub{
			Name: "TEST",
		},
	)

	hubInfo, err := hubsServiceCall.Do()
	fmt.Println(hubInfo, err)
```

where "projects/xxxxxxx/locations/global" is the parent name.

Could someone help me what is the problem here.

**Comment by codyoss** [comment]
Hey @venkyfff I am not sure what the proper format is here. I would recommend inspecting the error deeper to see if there are more hints to what might be wrong: https://pkg.go.dev/google.golang.org/api#hdr-Inspecting_errors

**Comment by venkyfff** [comment]
Thanks @codyoss. I tried to dig in deeper but couldn't get much info other than the error code being 400

**Comment by codyoss** [comment]
I would recommend reaching out to the product team from their [support page](https://cloud.google.com/network-connectivity/docs/support/getting-support). At the very least I think a documentation change should be made here to clear things up.

**Comment by venkyfff** [comment]
@codyoss  - I tried to reach the support team through email / slack. So far no response.

**Comment by codyoss** [comment]
If you have filed a bug on their issue tracker please feel free to link it here so I can follow as well, I might be able to help nudge things. I don't think there is anything to do from this repos stand point for now though so I am closing this issue. I hope you get a response back soon!
