### ISSUE TITLE
youtube/analytics: Watch Hours per video 

### ISSUE THREAD

**Issue by jasonbronson** [googleapis/google-api-go-client#1197]
I'm looking for watch hours in the API for each video in a channel. 

I've found the api docs show it here. https://developers.google.com/youtube/analytics/metrics?hl=en#Watch_Time_Metrics
But I do not see any references in your docs to grab it. 
Are you planning on implementing it?

**Comment by codyoss** [comment]
Hey @jasonbronson, the clients in this project our auto-generated based on the services public [discovery document spec](https://youtubeanalytics.googleapis.com/$discovery/rest?version=v2). If there are features you would like to see show up in the API I would recommend reaching out from the youtube analytics support page.

**Comment by codyoss** [comment]
Closing this issue as I don't think there is anything to do in this repo for now. Should a feature get added to the API it will get picked up here.
