### ISSUE TITLE
go.sum file size

### ISSUE THREAD

**Issue by enkeyz** [googleapis/google-api-go-client#1213]
I wanted to use "google.golang.org/api/commentanalyzer/v1alpha1" go package, and after adding to my project, I realized that my go.sum file became huge.

File: https://gist.github.com/enkeyz/7a62e439b8b8b18b03e8c7fdcdfd19e9

538 lines of dependency: is this the result of the auto-generated code?

**Comment by codyoss** [comment]
I think this is the result of some circular dependencies we have between this repo and google-cloud-go(cloud.google.com/go). This will be broken in the not too distant future. In practice though MVS will only select and pull in one version per major. So for example if you ran `go mod vendor` you can see it is not pulling in multiple versions of `cloud.google.com/go`.  In general I don't think the sum files should be looked at too closely as it is not meant for humans but machines. `go.mod` on the other hand is more important to look at. Hope that helps, let me know if you have any follow up questions.
