### ISSUE TITLE
best way to get licenses available/assigned

### ISSUE THREAD

**Issue by deadlysyn** [googleapis/google-api-go-client#1214]
- What you're trying to do

in workspace admin > billing > subscriptions i can see "X available / Y assigned" license counts for each subscription. trying to find best way to derive these with sdk.

- What code you've already tried

went through sdk directory index, only things which sounded potentially relevant were admin (useful but don't see anything related to billing), *billing (specific to GCP budgets), license (i can compute assigned license count, but feels kludgey to iterate and can't seem to find available count) and reseller (looks promising since there's at least mention to available/assigned seats, but also a stretch since this is not reselling).

- Any error messages you're getting

no errors, the sdk works great and is amazingly full featured... i have to be missing the right method, since this seems like an easy/common thing to require.

TIA

**Comment by deadlysyn** [comment]
for example, you can do something like this to get an assigned license count:

```go
// ...

var (
	googleWorkspaceLicenses = 0
	scopes = []string{
		licensing.AppsLicensingScope,
		// etc
	}
)

func newGoogleLicenseClient(ctx context.Context, c creds) (*licensing.Service, error) {
	// (c)redentials map loaded from secret manager
	clientSecret := []byte(c["GOOGLE_CLIENT_SECRET"])
	config, err := google.ConfigFromJSON(clientSecret, scopes...)
	if err != nil {
		return nil, err
	}

	tok := &oauth2.Token{}
	cache := []byte(c["GOOGLE_CACHE"])
	err = json.Unmarshal(cache, tok)
	client := config.Client(context.Background(), tok)

	svc, err := licensing.NewService(ctx, option.WithHTTPClient(client))
	if err != nil {
		return nil, err
	}
	return svc, nil
}

// ...

func licenseCount(l *licensing.LicenseAssignmentList) error {
	googleWorkspaceLicenses += len(l.Items)
	return nil
}

func preflight(ctx context.Context, c creds) {
	svc, err := newGoogleLicenseClient(ctx, c)
	if err != nil {
		logger.Fatal(err)
	}
	err = svc.LicenseAssignments.ListForProduct("Google-Apps", "mydomain.tld").Pages(ctx, licenseCount)
	if err != nil {
		logger.Fatal(err)
	}
	fmt.Println(googleWorkspaceLicenses)
}
```

sharing bad code just to clarify what i've been trying...that accurately computes assigned licenses for the product, but is obviously inefficient and still doesn't provide insight into available seats.

would like to figure this out and submit an example since it feels like a common thing for provisioning systems to need.

**Comment by codyoss** [comment]
Hey @deadlysyn if you are looking for help with a question I would suggest reaching out to the product team directly through on of the mechanisms listed on their [support page](https://developers.google.com/admin-sdk/licensing/support). I am not familiar with this API. This issue tracker is primary for Auth related items and for the generated code itself. Sorry I can't be of more help, I hope the link provided gets you the answers you need.
