### ISSUE TITLE
idtoken: validating idtoken with multiple client ids

### ISSUE THREAD

**Issue by nathanramli** [googleapis/google-api-go-client#1221]
Currently, _idtoken_ only support validating with one _client id_. 
In my case, I have multiple client and want to validate idtoken with those client ids.

I think it would be better to be able validating with many client ids, as in Google Auth Library for node.js
[https://developers.google.com/identity/gsi/web/guides/verify-google-id-token#using-a-google-api-client-library](https://developers.google.com/identity/gsi/web/guides/verify-google-id-token#using-a-google-api-client-library)

**Comment by codyoss** [comment]
@bshaffer I think we originally were supporting a single audience, should we be supported multiple aud idtokens?

**Comment by bshaffer** [comment]
I am not aware of any use-case (or any auth libraries which support) the ability to validate multiple audiences or client IDs. The NodeJS example provided invokes `Collections.singletonList`, which only accepts a single item, so this is not accepting multiple audiences.

**Comment by nathanramli** [comment]
Basically I want to check whether the given token is come from one of my client IDs.

**Comment by nathanramli** [comment]
When there's an error because of the audience doesn't matches when I call the validate function, I call again the validate function but with different audience.

**Comment by nathanramli** [comment]
I think I can help to make this one

**Comment by codyoss** [comment]
@nathanramli I don't think this is a use-case we really support right now. I am not sure how well it works in environments like Cloud Run if the token could contain multiple audiences, did some testing and did not seem to work.

If the aud was a list value though that is comma separated I assume you could pass in a concatenated string into the existing function, although I did not test this.

**Comment by nathanramli** [comment]
@codyoss The token only contains one audience. And that's not the problem I'm talking about.

In my case, I only have one backend for authenticating users, but I have multiple clients such as Mobile and Web. The problem is my clients have different client_id (aud). And I need to check If the token contain one of my aud.

With current function I need to call validate function multiple times until the token aud match with one of my aud, and this is not effective.

So I think it would be better if the function can check if the token is come from one of my aud

**Comment by codyoss** [comment]
@nathanramli In this case I would suggest passing an empty string into the aud. This will skip aud validation done by the library. Then you can use the Payload returned to see if your client_id is contained in the Aud field. Hope that helps!
