### ISSUE TITLE
Storage Transfer Service List Transfer Operations Call Malformed URL

### ISSUE THREAD

**Issue by ryanhos** [googleapis/google-api-go-client#1229]
#### Environment details

  - Programming language:  Golang
  - OS: Mac OS
  - Language runtime version: 1.15.3 darwin/amd64
  - Package version: Present in commit `5c56ac8`

#### Steps to reproduce

  1. Setup GCP Project, enable Storage Transfer Service API
  2. Configure Application Default Credentials, set quota project to above
  3.
```
ctx := context.Background()
storagetransferService, _ := storagetransfer.NewService(ctx)
transferOperationFilter := makeTransferOperationFilter()
// The documentation says that List()'s name arg is unused, but it's not
call := storagetransferService.TransferOperations.List("", transferOperationFilter)
response, err := call.Do()
```
  4. The Do() call results in a 404 and HTML response.  The error message includes the URL and clearly the entity type is missing.
  5. Set the first argument in List() to "transferOperations" and it works.

Why I set the Name arg to empty string:
https://github.com/googleapis/google-api-go-client/blob/master/storagetransfer/v1/storagetransfer-gen.go#L2943

Is this the issue?
https://github.com/googleapis/google-api-go-client/blob/master/storagetransfer/v1/storagetransfer-gen.go#L3013

Normally I'd send a Pull Request, but since this is generated code, I'm not sure it'd be useful.

Thanks!

**Comment by codyoss** [comment]
I am not familiar with this API but you are right, something seems not right here. It looks like our path element resolver is confused by the empty string. Still, aside from that I tried to vendor the code and remove that `/{+name}` bit and it still did not work. I am not currently sure the correct way to call this API, let me do some more research and get back to you.

**Comment by fe-ryan** [comment]
Wow, thanks for the prompt response.

Check out the way that the TransferJobsListCall does it: https://github.com/googleapis/google-api-go-client/blob/master/storagetransfer/v1/storagetransfer-gen.go#L2214

The `List()` doesn't have a name argument and the `TransferJobsListCall` struct doesn't have a `name` field.  https://github.com/googleapis/google-api-go-client/blob/master/storagetransfer/v1/storagetransfer-gen.go#L2146

**Comment by codyoss** [comment]
I will file a bug to get the docs updated but if you pass in "transferOperations" for the name field the request should work. I believe that is now the only acceptable value.

**Comment by codyoss** [comment]
I filed an internal bug b/200293347 to track updating the docs. Thanks for bring this to our attention!
