### ISSUE TITLE
How do we find service "mybusiness.googleapis.com" in repo ?

### ISSUE THREAD

**Issue by vuducnghia** [googleapis/google-api-go-client#1230]
Thanks for stopping by to let us know something could be better!

I read this [post](https://developers.google.com/my-business/reference/accountmanagement/rest) and find services: 

- google.golang.org/api/mybusinessaccountmanagement/v1
- google.golang.org/api/mybusinessbusinessinformation/v1

but don't find a similar service as [google.golang.org/api/mybusiness/v4.9](https://developers.google.com/my-business/reference/rest)

Is there a service for that in this repo?

Thank you!

**Comment by codyoss** [comment]
Hey @vuducnghia this repository is auto-generated from apis on the [public discover document listing](https://www.googleapis.com/discovery/v1/apis). If you would like to see this API added please reach out to the My Business API team directly from one of the links provided on their [support page](https://developers.google.com/my-business/content/support). Once they publish their API spec to that list a client will be generated. Hope that helps!

**Comment by proxy-hatch** [comment]
This API appears to be broken as of now. It'd be great if Google can officially support it.

```
2023-08-01T03:18:22.378Z	ERROR	tst/main.go:91	Error listing Google business accounts: Get "https://mybusinessaccountmanagement.googleapis.com/v1/accounts?alt=json&prettyPrint=false": oauth2/google: status code 400: {

"error": {
"code": 400,
"message": "Request contains an invalid argument.",
"status": "INVALID_ARGUMENT"
}
}
```
