### ISSUE TITLE
Make RPCs using google.golang.org/api/... show up in /debug/requests

### ISSUE THREAD

**Issue by razvanm** [googleapis/google-api-go-client#124]
If an app is making calls to Google using this library the RPCs they don't show up anywhere. Ideally they would show be available over HTTP at /debug/requests provided by the [golang.org/x/net/trace](http://golang.org/x/net/trace) package.

**Comment by broady** [comment]
Isn't `/debug/requests` more for incoming requests?

**Comment by devnev** [comment]
No, `/debug/requests` can be used for both sent and received requests. The standard grpc client does this by default.

**Comment by adams-sarah** [comment]
cc @jba @pongad

**Comment by jba** [comment]
These clients are in maintenance mode. We don't plan to address this issue.

@pongad for the next generation of clients.

**Comment by dsymonds** [comment]
Please reconsider this one. While these clients may be in maintenance mode, people are going to be using them for a long time yet (years?) and will be wanting to debug their behaviour.

Consider also that this could be a trial run of what would be helpful to add in the new clients.

**Comment by razvanm** [comment]
Is there an equivalent issue filed for the next generation of clients?

**Comment by jadekler** [comment]
All clients now use a transport which is able to send opencensus stats. To receive debugging information, a user need only set up an exporter. See more info at: https://github.com/census-instrumentation/opencensus-go.

> Is there an equivalent issue filed for the next generation of clients?

The same is true of the newer generation.

----------------------

Closing this for now. Give a shout if there's more to talk about here, or feel free to open a new issue. Per offline chat with @broady, I could see a feature request for /debug/requests specifically, for example.
