### ISSUE TITLE
liveBroadcasts.control method not available 

### ISSUE THREAD

**Issue by saxon-milton** [googleapis/google-api-go-client#1240]
Hello, 
I would like to know what calls to perform to make a slate image appear in the middle of a livestream. Reading the API documentation [here](https://developers.google.com/youtube/v3/live/getting-started), it's suggested that the "control" operation is used to achieve this, however, this operation is not supported by the API in the latest version. I did find this functionality in a prior version (v0.3.2); why would this have been removed and what is the replacement ?
Cheers, 
Saxon

**Comment by codyoss** [comment]
Hey @saxon-milton, I am not too familiar with this API. I suggest reaching out with one of the items listed on the [Live Streaming API Support Page](https://developers.google.com/youtube/v3/live/support).
