### ISSUE TITLE
gensupport.SendRequest missing "req.Close = true"

### ISSUE THREAD

**Issue by ojyaki** [googleapis/google-api-go-client#1245]
#### Environment details

  - Programming language: golang
  - OS: unix
  - Language runtime version:
  - Package version: 0.58

#### Steps to reproduce

  1. instantiate gmail.NewService 
  2.  Call the service, for example use svc.Users.Messages.List.
  3. check open connections via lsof, you'd see open https connection
  4. put step 2 in for loop, you'll see connections leaking

In Do() function, googleapi.CloseBody is being called but we need the http.request to also have Close set to true. This can be done in gensupport.SendRequest. With out Close = true, HTTPS connection remains open till it times out, in a rapid env this is enough to exhaust file descriptors.

**Comment by codyoss** [comment]
I think we actually want to not close the connections. If we set this field we would prevent reuse of TCP connections between requests which I think would slow things down. I am not sure how you are using the client, but clients are thread safe and should be shared if possible. When you are done using a client(service) call it's Close method. This will close all of the underlying connections. Failure to call Close could be the source of your leaked connections.

If you really want this behavior I suggest passing in your own custom HTTP client with a transport configured with Transport.DisableKeepAlives. Hope that helps!

**Comment by ojyaki** [comment]
Thank you for your reply. I take you're recommending the use of WithHTTPClient. I'm using options with WithTokenSource to supply the token obtained through JWTConfigFromJSON. The use of WithHTTPClient overrides the token and auth would fail to proceed. If there's a way to keep the existing options and still add custom transport, then that would work. By the way, I can't find reference to the Close function you are referring to either. having control over when to close would be the best.

**Comment by codyoss** [comment]
You can make use of [NewTransport](https://pkg.go.dev/google.golang.org/api/transport/http#NewTransport) to create an authenticated transport and then wrap that into the provided HTTP client.

> By the way, I can't find reference to the Close function you are referring to either. having control over when to close would be the best.

This is my bad. I misspoke and was referring to a a patten used in our other Go client libraries. Although it seems like adding a close function to the service could be a useful addition in cases like these. I will investigate if it is worth adding that in the future.

**Comment by ojyaki** [comment]
Thank you very much for your guidance. NewTransport worked as I'd need. Will be looking forward for the Close function too :) Please go ahead and close this issue.
