### ISSUE TITLE
Why couldn't I find the function realated to workspace proposal in the tagmanager golang library ?

### ISSUE THREAD

**Issue by layla004** [googleapis/google-api-go-client#1298]
Hi, I am using Google Tag Manager 360 and want to use Request Approval feature REST API.
<img width="644" alt="Screen Shot 2021-11-15 at 16 24 06" src="https://user-images.githubusercontent.com/92920267/141890568-a8679dfd-9dc6-407a-924f-d0b4749e60ea.png">

I found this documentation [https://developers.google.cn/tag-platform/tag-manager/api/v2/reference/accounts/containers/workspaces/getProposal](url) separated from [https://developers.google.cn/tag-platform/tag-manager/api/v2](url) 

but why could not I find the function related to workspace proposal in tagmanager golang library here [https://pkg.go.dev/google.golang.org/api/tagmanager/v1](url) ?
Thanks

**Comment by codyoss** [comment]
Hey, these clients in this repo are auto-generated based off of public discovery doc spec. It a method does not exist in the client it means it is not published in the spec. Maybe this is a beta endpoint? I think a better place to request/ask this is the official support channels for that API: https://developers.google.com/tag-platform/support. Hope that helps.
