### ISSUE TITLE
Add region filter to Get builds function

### ISSUE THREAD

**Issue by Li-ReDBox** [googleapis/google-api-go-client#1303]
Could we have the Cloud Build client to support the feature like this with gcloud:

gcloud builds list --region a_region

Currently, it only takes project_id and build_id: https://github.com/googleapis/google-api-go-client/blob/main/cloudbuild/v1/cloudbuild-gen.go#L4492

Thanks.

**Comment by Li-ReDBox** [comment]
Or I should use Get(name) function instead with some helper function to construct a name?
https://github.com/googleapis/google-api-go-client/blob/main/cloudbuild/v1/cloudbuild-gen.go#L6318
Thanks

**Comment by codyoss** [comment]
Hey @Li-ReDBox, these clients are autogenerated from a public discovery doc spec. If you would like changes made to the API I suggest you request them from the product team [here](https://cloud.google.com/build/docs/support). Closing this issue as there are not changes to be made here. Should a new feature land this client will be automatically updated.
