### ISSUE TITLE
Why does `analytics` package access to the host `analytics.googleapis.com`?

### ISSUE THREAD

**Issue by wacul-yamada** [googleapis/google-api-go-client#1319]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do
    - Update `google.golang.org/api` from `v0.30.0` to `v0.44.0`
- What code you've already tried
    - Using `analytics` packages to access Analytics management API
    - Access through my own proxy server. 
- Any error messages you're getting
    - quotaExceeded

Details:

We are using our own proxy server to limit the flow of access to `www.googleapis.com`.
However, this library tries to access a`nalytics.googleapis.com` instead of `www.googleapis.com` since Dec. 2020.

https://github.com/googleapis/google-api-go-client/blame/0fe30d54c40b6d73215fc3fdd30c397b845d8c56/analytics/v3/analytics-gen.go#L81

In our current configuration, it does access without going through the proxy server.
We can change the configuration, but the Google Analytics MANAGEMENT API Reference (https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference) continues to guide us that `www.googleapis.com` is the hostname.
Therefore, we are skeptical that this change in the library is correct, and we have not been able to take action.
Is this a correct change based on some official announcement?

**Comment by codyoss** [comment]
Hey @wacul-yamada I assume this is likely correct, but I am not an expert on this API. These clients are auto-generated from the public discovery doc listing for the API. I think it might be best to reach out from one of the links on the [support page for the product](https://developers.google.com/analytics/devguides/config/mgmt/v3/help) as the project team will be able to better answer your questions. Hope that helps.
