### ISSUE TITLE
healthcare: HL7v2 Response Messages are not read correctly on the v1alph2 client

### ISSUE THREAD

**Issue by khuong507** [googleapis/google-api-go-client#1340]
#### Environment details

  - Programming language: Go
  - OS: Darwin
  - Language runtime version: 1.16
  - Package version: v0.61.0

#### Steps to reproduce

1. Create a v1alpha2 `healthcareService` and use it to create a `ProjectsLocationsDatasetsHl7V2StoresService`. 
2. Make a list HL7v2 Messages call
```
healthcareService, err := healthcare.NewService(ctx)
...
v2StoreService := healthcare.NewProjectsLocationsDatasetsHl7V2StoresService(healthcareService)
...
resp, err := v2StoreService.Messages.List(parent).Do()
// resp.Messages will be nil
```
resp.Messages will be null due to the struct tag not matching the api response as seen here:
https://github.com/googleapis/google-api-go-client/blob/3799960e6811b42abe4f5b9a76e94e00aba68761/healthcare/v1alpha2/healthcare-gen.go#L3034

**Comment by codyoss** [comment]
@khuong507 Thanks for reporting this issue. It seems like this alpha client should be pulled. I believe the only clients for healthcare that seem to be getting updates right now are v1beta1 and v1. Can you use one of those clients? Looking [here](https://github.com/googleapis/google-api-go-client/tree/main/healthcare) it appears the alphas have not been updated in two years do to their public spec not being updated. The [API Ref docs](https://cloud.google.com/healthcare-api/docs/apis) also only mention the above two clients.

**Comment by khuong507** [comment]
I can switch to one of the other clients thank you for following up.
