### ISSUE TITLE
gRPC DialSettings validation ignores default scopes

### ISSUE THREAD

**Issue by nickgooding** [googleapis/google-api-go-client#1395]
#### Environment details

  - Programming language: Golang
  - OS: All
  - Language runtime version: 1.17
  - Package version: >= v0.32.0

#### Steps to reproduce

Here is a test tha
  1. Define some `ClientOptions` with `ImpersonateCredentials` and `WithDefaultScopes`
  2. Call the `grpc.Dial` method, which will run some validation on the options
Expected: The settings pass validation
Actual: The settings fail validation with the message: `WithImpersonatedCredentials requires scopes being provided`

Is there a reason that `DefaultScopes` is not sufficient to satisfy this validation?

Here is a test demonstrating this:
```
package main

import (
	"context"
	"testing"

	"google.golang.org/api/option"
	"google.golang.org/api/option/internaloption"
	"google.golang.org/api/transport/grpc"
)

func TestDialWithDefaultScopes(t *testing.T) {
	opts := []option.ClientOption{
		option.ImpersonateCredentials("creds-to-impersonate"),
		internaloption.WithDefaultScopes("default-scope"),
	}
	_, err := grpc.Dial(context.Background(), opts...)

	if err != nil {
		t.Logf("dial error: %v", err)
		t.Fail()
	}
}
```

Relevant validation code: https://github.com/googleapis/google-api-go-client/blob/v0.65.0/internal/settings.go#L138
Rather than using `len(ds.Scopes) == 0` here, `len(ds.GetScopes()) == 0` would include configured default scopes.

(maybe also https://github.com/googleapis/google-api-go-client/blob/v0.65.0/internal/settings.go#L107 is affected?)

**Comment by codyoss** [comment]
Hey, a couple of things here.

1. The `internaloption` package is not meant to be used in non-generated code. WithScopes should work fine for your case. Because this package is not meant for external consumption we make assumptions about how it is used.
2. The `ImpersonateCredentials` option has been replaced and upgraded. Please checkout https://pkg.go.dev/google.golang.org/api/impersonate. You should be able to pass the `TokenSource` created by that package to `Dial` and I think things should just work.

Let me know if you have any follow up questions. I hope these tips help!

**Comment by nickgooding** [comment]
Thanks for the quick reply!

> The `internaloption` package is not meant to be used in non-generated code. WithScopes should work fine for your case. Because this package is not meant for external consumption we make assumptions about how it is used.

Just to clarify, we are not using anything from the `internaloption` package directly. I was just trying to provide a succinct reproduction. We are simply trying to create various clients from `cloud.google.com/go`, which use `internaloption.WithDefaultScopes` instead of `option.WithScopes` since v0.74.0. Unfortunately this means we fall foul of the DialSettings validation unless we also include `option.WithScopes` ourselves.

> The `ImpersonateCredentials` option has been replaced and upgraded. Please checkout https://pkg.go.dev/google.golang.org/api/impersonate. You should be able to pass the `TokenSource` created by that package to `Dial` and I think things should just work.

Great. I'll check that out and hopefully this issue is moot 👍

**Comment by codyoss** [comment]
Ah, thanks for the clarification. Hope the impersonate package works for ya! Let me know if not and I can write up a full example for ya.

**Comment by codyoss** [comment]
Closing this issue as I have not heard back that there are still issues here. Please feel free to reopen if you are still having issues.
