### ISSUE TITLE
Buffered upload from S3 file to youtube

### ISSUE THREAD

**Issue by fox-batman121** [googleapis/google-api-go-client#1409]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
We are trying to upload heavy videos to youtube. We are fetching videos from S3. Currently, we need to download the complete video in memory and then push it to youtube. 
There is a feature in php (https://stackoverflow.com/questions/10097105/getting-a-video-from-s3-and-uploading-to-youtube-in-php) which allow the youtube client to read the video in parts using buffer (thus, limiting the memory used by service) and it uploads all those small videos into a single video on youtube. 
Can we please add the same feature in youtube-go-client also ? 

**Describe the solution you'd like**
There is a feature in php (https://stackoverflow.com/questions/10097105/getting-a-video-from-s3-and-uploading-to-youtube-in-php) which allow the youtube client to read the video in parts using buffer (thus, limiting the memory used by service) and it uploads all those small videos into a single video on youtube.

**Describe alternatives you've considered**
Currently, we have increased the memory requirements of the service and we are downloading the complete video in memory and uploading it to youtube.

**Additional context**

**Comment by codyoss** [comment]
Hey, these libraries are currently considered in maintenance mode per the [README](https://github.com/googleapis/google-api-go-client#status). I don't know what the PHP code is doing but I assume it is doing a multi-part/multi-request type flow similar to what we do with our storage client. You can always use these libraries to create an authenticated transport with [NewClient](https://pkg.go.dev/google.golang.org/api/transport/http#NewClient) and then manually make the upload the the rest endpoint referenced in the [docs](https://developers.google.com/youtube/v3/docs/videos/insert). Hope that gets you going in the right direction.
