### ISSUE TITLE
bigquery: How to choose ideal chunk size when uploading to BigQuery using load jobs

### ISSUE THREAD

**Issue by gilsegment** [googleapis/google-api-go-client#1424]
I am using this: https://github.com/googleapis/google-api-go-client/blob/main/bigquery/v2/bigquery-gen.go#L9891

To upload to BigQuery using load jobs. In the options I can specify chunk size.

Is there an ideal number for the chunk size, for me to choose? the files sizes I am using are between 1MB to 100MB

**Comment by codyoss** [comment]
@shollyman Do we have any guidance here?

**Comment by shollyman** [comment]
We don't have any product specific guidance, this is mostly a network consideration.

That said, under the hood, BigQuery and Cloud Storage are using similar upload mechanism(s).

I see storage has some chunksize guidance for their [veneer writer](https://pkg.go.dev/cloud.google.com/go/storage#Writer)
which documents guidance here: https://cloud.google.com/storage/docs/uploads-downloads#size

Hopefully that helps.

**Comment by codyoss** [comment]
Thanks @shollyman. Closing the issue.
