### ISSUE TITLE
How do you set the content type for an Apigee Organization API Create request?

### ISSUE THREAD

**Issue by emarcotte** [googleapis/google-api-go-client#1442]
- What you're trying to do:

Create an API revision from a Zip file using Go code.

- What code you've already tried

I have bundled up a zip file, and try to upload it with code along these lines:

```golang
bodyFile, err := os.Open(zipPath)
if err != nil {
return err
}
defer bodyFile.Close()
bodyContent, err := io.ReadAll(bodyFile)
if err != nil {
   return err
}

action := "validate"
if !validate {
   action = "import"
}

apiSvc := apigee.NewOrganizationsApisService(apigeeService)
body := apigee.GoogleApiHttpBody {
   ContentType: "application/octet-stream",
   Data: string(bodyContent),
}

call := apiSvc.Create(fmt.Sprintf("organizations/%s", params.project), &body)
call = call.Action(action)
call = call.Name(params.api)
call.Header().Set("Content-Type", "application/octet-stream")

pretty.Logln(call)
createResponse, err := call.Do()

pretty.Logln(createResponse)
```

I see this line: https://code.googlesource.com/google-api-go-client/+/refs/heads/master/apigee/v1/apigee-gen.go#11470 might be overriding any content type I set however. Is there some other trick to this?

- Any error messages you're getting:

When I run this I get: ` Error 400: proxy must be encoded as 'application/octet-stream' or 'multipart/form-data'`

Some more context (the debug output) I have is:

```
 googleapihttpbody: &apigee.GoogleApiHttpBody{
        ContentType:     "application/octet-stream",
        Data:            REDACTED BIG UGLY STRING OF DATA,
        Extensions:      nil,
        ServerResponse:  googleapi.ServerResponse{},
        ForceSendFields: nil,
        NullFields:      nil,
    },
    urlParams_: {
        "action": {"validate"},
        "name":   {"Animals"},
    },
    ctx_:    nil,
    header_: {
        "Content-Type": {"application/octet-stream"},
    },
}
2022/02/14 13:02:16 (*apigee.GoogleCloudApigeeV1ApiProxyRevision)(nil)
panic: googleapi: Error 400: proxy must be encoded as 'application/octet-stream' or 'multipart/form-data'
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.RequestInfo",
    "requestId": "1101072630480219717"
  }
]
```
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by codyoss** [comment]
I am not an expert /w with API. I would suggest reaching out on one of the links on the [Apigee Support page](https://cloud.google.com/apigee/docs/support). I do know that some of our other APIs that accept a string of data need to be base64 url encoded for it to properly work. Maybe that needs to be done for the data field here. Hope that helps.
