### ISSUE TITLE
Implement Retryable interface for token endpoint requests

### ISSUE THREAD

**Issue by TimurSadykov** [googleapis/google-api-go-client#1445]
Currently, clients do not have a good way to distinguish retryable errors and implement custom retry strategies. Sometimes this causes infinite retries like here: https://github.com/nwbirnie/gapic-oauth-invalid-hangs. Please prioritize the fix if similar infinite retry is repro here as well. Per [this](https://github.com/golang/oauth2/issues/264) it seems like the case.

More details in the doc: go/auth-correct-retry

**Comment by codyoss** [comment]
I did verify that there is no infinite hang in the Go clients.
