### ISSUE TITLE
admin.New(ctx) deprecated for admin.NewService()

### ISSUE THREAD

**Issue by kp52r11** [googleapis/google-api-go-client#1452]
Hi,
I have been using below feature successfully for few month but now it is broken.  It appears that admin.New() is deprecated.  I am not a google api expert.  I don't quite understand how to use admin.NewService().

Below function was called from my golang main() routine.  It worked fine.  Can someone help as to what exactly needs to be fixed?
I looked at the comments on top of this file (https://github.com/googleapis/google-api-go-client/blob/v0.69.0/admin/directory/v1/admin-gen.go#L178) to see if I can figure out the usage of admin.NewService() but I was unable to figure it out.

Any help is welcome.  Thank you and take care.

func createAdminDirectoryService(serviceAccountFilePath,
	gsuiteAdminUserEmail string) *admin.Service {
	jsonCredentials, _ := ioutil.ReadFile(serviceAccountFilePath)

	//instance of type struct
	config, _ := google.JWTConfigFromJSON(
		jsonCredentials,
		admin.AdminDirectoryGroupReadonlyScope,
		admin.AdminDirectoryUserReadonlyScope,
	)
	config.Subject = gsuiteAdminUserEmail

	ctx := context.Background()
	client := config.Client(ctx)

	srv, _ := admin.New(client)

	return srv
}

**Comment by codyoss** [comment]
Hey,

If you were successfully using the following in the past:

```go
client := http.DefaultClient // actually initialize
service, err := admin.New(client)
```

You could now do something like:

```go
// import "google.golang.org/api/option"
client := http.DefaultClient // actually initialize
ctx := context.Background()
service, err := admin.NewService(ctx, option.WithHTTPClient(client))
```

Hope that helps.
