### ISSUE TITLE
inAppProduct.ManagedProductTaxesAndComplianceSettings.TaxRateInfoByRegionCode Always null

### ISSUE THREAD

**Issue by sabriboughanmi** [googleapis/google-api-go-client#1459]
hello,

im using InAppProduct.ManagedProductTaxesAndComplianceSettings.TaxRateInfoByRegionCode to get taxes by region as my project requires, but it is always returned as null.
At first I thought it was a permission issue, so I added billing and owner.
now I'm starting to think of it as a bug.

Thank you.

**Comment by codyoss** [comment]
Hey @sabriboughanmi I am not too familiar with this API. If you have questions related to a specific API I would suggest reaching out to that APIs support page for help. Hope that helps.
