### ISSUE TITLE
identitytoolkit: howto refresh STS id token?

### ISSUE THREAD

**Issue by andig** [googleapis/google-api-go-client#1484]
I'm using identitytoolkit to retrieve ID tokens for use with an external API:

```go
ctx := context.Background()
identitytoolkitService, err := identitytoolkit.NewService(ctx, option.WithHTTPClient(helper.Client))
if err != nil {
	return nil, err
}

pwdReq := &identitytoolkit.IdentitytoolkitRelyingpartyVerifyPasswordRequest{
	Email:             cc.User,
	Password:          cc.Password,
	ReturnSecureToken: true,
}

call := identitytoolkitService.Relyingparty.VerifyPassword(pwdReq)

pwdResp, err := call.Do(googleapi.QueryParameter("key", ...))
if err != nil {
	return nil, err
}
```

That works fine and returns id+refresh token.

It's not clear how to use the refresh token to update the id token though. I'm stuck which api to use, ideally to create an `oauth2.TokenSource`?

**Comment by codyoss** [comment]
I am not too familiar with this API, but given it gives back a refresh token maybe you can make sure of [Config.TokenSource](https://pkg.go.dev/golang.org/x/oauth2#Config.TokenSource)? Another option would be to make your own TokenSource that you wrap in a [ReuseTokenSource](https://pkg.go.dev/golang.org/x/oauth2#ReuseTokenSource). You could just keep calling the API when you need to refresh I think? It might be worth reaching out on the API support page for this API for additional help. Hope that gets you going in the right direction.
