### ISSUE TITLE
Between idtoken and oauth2 for openning some public token claims?

### ISSUE THREAD

**Issue by sindysenorita** [googleapis/google-api-go-client#1485]
I am building a simple backend service that read user's email from google's OAuth token. To do the job, I've been using idtoken lib (https://pkg.go.dev/google.golang.org/api/idtoken). It works just fine.
Recently I noticed that there is another library that provides similar functions: OAuth2 (https://pkg.go.dev/google.golang.org/api/oauth2/v2).

From my observation on the pkg doc (haven't done hands-on on OAuth2), OAuth2 seems to have more types and functions, accessing the email via structs. Meanwhile, we work on raw claim maps in idtoken. My initial impression is oauth2 is a superset of idtoken?
But is that really the only difference? Are there any cases where one is better than the others?

Many Thanks!

Extra: Still learning and my work with idtoken is still very basic. Using an API key and WithoutAuthentication seems to work, I think because email is public information. Any feedback would be appreciated. Thanks again!
```
validator := idtoken.NewValidator(ctx, option.WithoutAuthentication())
audience := using Auth 2.0 client id from GCP console
raw, err := validator.Validate(ctx, tokenString, audience)
// some validations and return errors if any
// then accessing the fields as a map 
claims := raw.Claims email := claims["email"]
```

**Comment by codyoss** [comment]
For any work with idtoken, I would keep using that package that you are using. oauth2 is broader and deals /w AccessTokens too, most people will never need to use this library directly.

If you are not customizing the httpClient used by validator I would just use the connivence function instead of creating your own. Hope that helps!
