### ISSUE TITLE
Remove Opencensus in favor of opentelemetry?

### ISSUE THREAD

**Issue by jaronoff97** [googleapis/google-api-go-client#1493]
Hello! I was wondering if there's been any effort or if it would be welcome upstream to remove opencensus as a dependency? Opencensus has been merged with opentracing to create opentelemetry, and opencensus will no longer be receiving security updates soon.

> OpenCensus and OpenTracing have merged to form [OpenTelemetry](https://opentelemetry.io/), which serves as the next major version of OpenCensus and OpenTracing. OpenTelemetry will offer backwards compatibility with existing OpenCensus integrations, and we will continue to make security patches to existing OpenCensus libraries for two years.

If it's welcome, I'd be able to migrate the opentracing usages to otel!

**Comment by codyoss** [comment]
We do plan to support otel in the future, but I don't have a timeline on when this will be. We will need to make sure we don't break existing workflows that might expect opencensus traces etc. Also some of our libraries have needs for metics which is still not supported in the Go client, at least it is not stable.

There is also an issue that our libraries seem to provide more support for older runtimes. So until we support 1.16+ only I don't think we can use the latest versions of otel libraries. I will leave this issue open and post back when I know more.

**Comment by jaronoff97** [comment]
great, thank you for letting me know!

**Comment by antoinedeschenes** [comment]
Honestly, providing a generic way to inject any custom Transport would be nice (in parallel to `addOCTransport`). You'd then have the choice to use otel or any other solution.

**Comment by codyoss** [comment]
@antoinedeschenes You can kind of due this today with: https://pkg.go.dev/google.golang.org/api/option#WithHTTPClient

**Comment by tmc** [comment]
Any movement on this?

**Comment by quartzmo** [comment]
Trace context propagation support for OpenTelemetry was introduced in [v0.154.0]https://github.com/googleapis/google-api-go-client/releases/tag/v0.154.0) via PR #2127.

The timeline for removing the trace context propagation support for OpenCensus (as well as the OpenCensus tracing support in several of the libraries in the [google-cloud-go](https://github.com/googleapis/google-cloud-go) repo), is discussed here, along with examples of how to pass options to OpenTelemetry trace context propagation:

https://github.com/googleapis/google-cloud-go/blob/main/debug.md#opencensus

**Comment by jaronoff97** [comment]
awesome, thank you!
