### ISSUE TITLE
Implement pulling labels field for static ip addresses.

### ISSUE THREAD

**Issue by matte29** [googleapis/google-api-go-client#1499]
Hello I was wondering if it would be possible to the labels field from static ip addresses to be pulled.  The structure it would be under is the compute/v1 under the struct Address.  Static ip addresses do have a labels field and most other services you are able to pull the labels field.  So for being able to grab the static ip address related to a label would be a nice feature I believe.  
![Address](https://i.imgur.com/42TX33w.png)

![GCP](https://i.imgur.com/OyIy0yh.png)

**Comment by codyoss** [comment]
Hey @matte29 This api is generated from a public discovery doc spec. If you would like changes to the APIs/models I suggest you reach out on one of the methods listed on the [Compute Engine API Support Page](https://cloud.google.com/compute/docs/getting-support). Closing as there is nothing we can do at this layer. Should the API change the client will get automatically updated.
