### ISSUE TITLE
container: how to update a Cluster to Autopilot

### ISSUE THREAD

**Issue by Feggah** [googleapis/google-api-go-client#1505]
In the release [v0.60.0](https://github.com/googleapis/google-api-go-client/releases/tag/v0.60.0), the field `DesiredAutopilot` [was removed](https://github.com/googleapis/google-api-go-client/pull/1274/files#diff-57851fa3fd45d9595096fcc6e60eb93729ca6bfc0567e884fda4f8b38fdb7f06L1186) from the `ClusterUpdate` struct (see in #1274)

![image](https://user-images.githubusercontent.com/11353912/162414326-17adab5f-a127-4d5d-abbb-752f8cb54f5b.png)

So I was trying to find how can I update a cluster to Autopilot or not, but without this field there is no other way which I can specify whether I want to update the cluster to Autopilot or not.

How can I upgrade my SDK version to `v0.60.0` or later and still be able to update the Autopilot configuration?

**Comment by codyoss** [comment]
I believe configuration was moved to create type as Autopilot is now apart of the cluster object. I am not an expert with this API though. For API specific questions I suggest reaching out to the [APIs Support Page](https://cloud.google.com/kubernetes-engine/docs/support). Hope that helps.
