### ISSUE TITLE
Missing API - purchases.subscriptionsv2

### ISSUE THREAD

**Issue by leearmstrong** [googleapis/google-api-go-client#1542]
I know this has only just been released but I am desperate to use the new APIs here: https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptionsv2

What do I have to do to get it enabled within this repo?

Thanks!

**Comment by codyoss** [comment]
It looks like that client updated today -- it is done so in an automated fashion daily. I am not sure if it has the changes you are looking for, but I am sure it will soon if not yet. If it does you can always go get the library at the sha you want. We generally release tagged versions on Tuesdays. Hope that helps.

**Comment by leearmstrong** [comment]
Thanks, I'll grab from the sha.
