### ISSUE TITLE
Is there a module for Google Cloud Endpoints

### ISSUE THREAD

**Issue by patricksimonian** [googleapis/google-api-go-client#1568]
Howdy team!

I'm struggling to find a module for Google Cloud Endpoints. Does it exist?

**Comment by codyoss** [comment]
I don't think there is one. I am not an expert on this product but by looking at the docs it seems it uses an open spec: https://cloud.google.com/endpoints/docs/openapi#supported_compute_platforms

I assume this means you can generate a client from the spec although I have not tried this. If that works you can make use of our [transport package](https://pkg.go.dev/google.golang.org/api/transport) to create transport with auth built in. Hope that helps.

**Comment by patricksimonian** [comment]
Thank you i'll give that a go :)
