### ISSUE TITLE
How to test code relying on the client

### ISSUE THREAD

**Issue by Goldziher** [googleapis/google-api-go-client#1578]
Hi there,

I would like to ask on how to test code using the api client. 

Specifically, i would like to know how is it possible to emulate responses and errors returned by some of the client methods. I tried doing this by passing in an http.Client with my own transport attached to it, but it still seems to be dialing youtube regardless of the url I am giving it. 

If there are any examples you could point me at it would be awesome.

**Comment by codyoss** [comment]
Hey, please check out [testing.md](https://github.com/googleapis/google-api-go-client/blob/main/testing.md) which was designed for this exact sort of question. The examples there should apply to all clients in this repo. Let me know if you have questions. Hope that helps!
