### ISSUE TITLE
Inconsistency of reviewId format in AndroidPublisher's Review object

### ISSUE THREAD

**Issue by nurcholisart** [googleapis/google-api-go-client#1583]
Hey Google team, we found a `reviewID` format inconsistency in the [Review](https://developers.google.com/android-publisher/api-ref/rest/v3/reviews#Review) object in the Android Publisher API.

Previously, when we tried to list the reviews in our application with requests like the one below:

```shell
curl --location --request GET 'https://www.googleapis.com/androidpublisher/v3/applications/:package_name/reviews?maxResults=1' \                           
--header "$(oauth2l header --json ~/service-account.json androidpublisher)"
```

It will respond with the following data (please take a look on `reviewId`):

```json
{
  "reviews": [
    {
      "reviewId": "gp:AOqpTOHRjYP4XY0u0abF8N-BUot_G08Zooj3_RsH8BIR5lHHblVJoyr2a6TjY8ABIqD-mU5Xd8R8B9e8galpQw",
      "authorName": "Aditya",
      ...
    }
  ]
}
```

However today, when we try to list reviews with same request as above, it will respond with the following data (please take a look on `reviewId`):

```json
{
  "reviews": [
    {
      "reviewId": "f90ffc22-dbac-4c6e-af61-161a8b8a75e3",
      "authorName": "Aditya",
      ...
    }
  ]
}
```

So, my question: Which is the correct `reviewId` format? Is it using `gp:*` or using `UUID`?

Thank you.

> Notes: I know this issue not specifically related to google-api-go-client package. But, since we don't know where to raise this issue and we are using this package, we raise this issue here.

**Comment by codyoss** [comment]
Hey, this client is auto-generated and I don't know much about this API. I suggest reaching out through the android dev support channels: [support](https://support.google.com/googleplay/android-developer/gethelp?visit_id=637908109122972579-2712450579&rd=1#). Hope that helps.

**Comment by nurcholisart** [comment]
Thank you @codyoss, i will reach android dev support channels
