### ISSUE TITLE
drive: Any way to stream the file instead of downloading?

### ISSUE THREAD

**Issue by krypticallusion** [googleapis/google-api-go-client#1588]
Hi, I'm trying to have a proxy api to serve files from gdrive to the end user.
Currently i'm using `s.Files.Get(ID).Download()` which returns a response.

From what I can see, this is a complete download of the file.

Basically I want to pipe the __response from the client library__ to the __response that I will provide to the user.__
How can make my proxy api just stream the file effortlessly instead of the current download to proxy and upload back to the user.

I checked the [docs](https://developers.google.com/drive/api/v2/reference/files/get#go) which albeit for `v2` had a `downloadUrl` property attached drive.File struct. Is there any equivalence in v3 for this? webContentLink is mostly empty.

**Comment by codyoss** [comment]
Sounds like what you might be looking for is [io.Pipe](https://pkg.go.dev/io#Pipe)? The response body returned is a reader which you could feed somewhere else. Hope that helps
