### ISSUE TITLE
Inclusion of libraries in https://pkg.go.dev/search ?

### ISSUE THREAD

**Issue by PaulRashidi** [googleapis/google-api-go-client#1609]
General Go guidance on managing dependencies indicates pkg.go.dev is the primary way of managing dependencies (https://go.dev/doc/modules/managing-dependencies).

When I tried to find Google Drive libraries there the results only show other people's GitHub projects which have included these libraries (https://pkg.go.dev/search?q=google+drive+api&m=package).

Would it make sense to make this repo compatible with pkg.go.dev or try to work on SEO so that the canonical client lib source shows higher (if it's already there)?

**Comment by PaulRashidi** [comment]
I'm a Googler; if you agree this would be beneficial and is technical possible (and relatively simple) I could help out.

**Comment by codyoss** [comment]
I don't think there is much we can do with search optimization for that site. In its current form people search of module paths, package names, or symbols. This site is less about discovery it its current form and more so just about the documentation for projects. If we need to direct users to our libraries we should do that with our own hosted documentation and show that this is the correct library to use via samples. I don't think there is much we can do from this libraries perspective so I am going to close this out.
