### ISSUE TITLE
Patch request is missing for MemoryStore Redis Instance

### ISSUE THREAD

**Issue by fizzafatima24** [googleapis/google-api-go-client#1618]
Hello! Patch or Update service request to update the instance configuration like other services is missing in MemoryStore Redis.

**Comment by codyoss** [comment]
Can you be more specific? There are many libraries in this repository and many request objects. A code example would be nice. 

Also, what do you mean by missing? These libraries are auto-generated from the public API specs. If you would like something added to the backend service itself I would reach out on the redis api support page: https://cloud.google.com/memorystore/docs/redis/getting-support

**Comment by fizzafatima24** [comment]
library: https://pkg.go.dev/google.golang.org/api@v0.86.0/redis/v1beta1
Object: https://pkg.go.dev/google.golang.org/api@v0.86.0/redis/v1beta1#Instance
Code:
```
instance := redis.Instance{
   AuthEnabled: true
}
```
// trying to update auth enable the field of Redis instance
// but no patch or update function available

**Comment by codyoss** [comment]
From what I can tell there seems to be one: https://pkg.go.dev/google.golang.org/api@v0.87.0/redis/v1beta1#ProjectsLocationsInstancesService.Patch

Hope that helps
