### ISSUE TITLE
Add additional FileType: SERVICE_CONFIG_JSONPB

### ISSUE THREAD

**Issue by jankrynauw** [googleapis/google-api-go-client#1621]
Add an option to submit a FileType of say SERVICE_CONFIG_JSONPB to the following:

https://github.com/googleapis/google-api-go-client/blob/948b3c3e99a73c29ee4d51546704ebbaa3cd24ad/servicemanagement/v1/servicemanagement-gen.go#L1048

The underlying object (i.e. a Service) referred to is already well defined in a proto.  Here's a go example:
https://github.com/googleapis/go-genproto/blob/042d03aeabc99d8b6d6f740db51b5e61e93313dc/googleapis/api/serviceconfig/service.pb.go#L66

With the current YAML only option for Service, the downstream examples (like the ESPv2) need to convert this YAML back to a Service object using protojson, **with hand crafted AnyResolvers**.  This is not ideal and here is an example: 
https://github.com/GoogleCloudPlatform/esp-v2/blob/b2d2351c48b59cf1f3e090e9dbdbeb5c271fc1ab/src/go/util/marshal.go#L173

This additional file type will enable one to automatically and more elegantly Marshall and Unmarshall the Service object using https://google.golang.org/protobuf/encoding/protojson.  It will avoid having to go 'via YAML' when passing the Service object between endpoints.

**Comment by codyoss** [comment]
Hey, maybe it would be easier if you were already working with protos? You can use the gRPC based client here if so: https://pkg.go.dev/cloud.google.com/go/servicemanagement/apiv1

If you have a feature request for the API itself though I suggest reaching out on that APIs support page: https://cloud.google.com/service-infrastructure/docs/support. This repo just synthesizes the public specs to code. Hope that helps.

**Comment by jankrynauw** [comment]
Thank you @codyoss, I will reach out as suggested.

We are already using the gRPC based client - the high level of consistency across all Google gRPC clients is really great:

```go
op, err := client.SubmitConfigSource(ctx, &servicemanagementpb.SubmitConfigSourceRequest{
		ConfigSource: &servicemanagementpb.ConfigSource{
			Files: []*servicemanagementpb.ConfigFile{
				{
					FileContents: descriptorBytes,
					FilePath:     "descriptor.pb",
					FileType:     servicemanagementpb.ConfigFile_PROTO_FILE,
				},
				{
					FileContents: serviceConfigYamlBytes,
					FilePath:     "api_config.yaml",
					FileType:     servicemanagementpb.ConfigFile_SERVICE_CONFIG_YAML,
				},
			},
		},
		ValidateOnly: false,
	})
```
