### ISSUE TITLE
Add domain public admin.directory.User.CustomSchemas to people.Person

### ISSUE THREAD

**Issue by achie27** [googleapis/google-api-go-client#1623]
**Is your feature request related to a problem? Please describe.**
As a non-admin user in a workspace/organization, I can view the assigned public custom schemas/fields for a contact/person on contacts.google.com. However, currently, custom schemas are not available via the People API and you have to use the Admin Directory API (as a non-admin) to get them. I think custom schemas should also be present in the Person resource for completeness otherwise the extra Admin API call leads to increased network bandwidth and maintenance of another service on the console.

**Describe the solution you'd like**
For domain public custom schema/fields to be added to the Person resource

**Comment by codyoss** [comment]
Hey, this repo just snthesizes the public spec for the API and is not a source a truth or a good place to request features for a given API. I suggest reaching out with a feature request on the [support page](https://developers.google.com/people/support) for the API you are talking about. Hope that helps!
