### ISSUE TITLE
seems the path for RunReport is missing /properties

### ISSUE THREAD

**Issue by nomoonx** [googleapis/google-api-go-client#1628]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Is this a client library issue or a product issue? We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - Programming language: Go
  - OS: 
  - Language runtime version: Go 1.18
  - Package version:0.88

#### Steps to reproduce

https://github.com/googleapis/google-api-go-client/blob/1beaeacb1d6f31a491c4263ce6b5153567b81f78/analyticsdata/v1beta/analyticsdata-gen.go#L3706

I think this line is missing `/properties` after `v1beta` 

it's giving 404 right now.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by codyoss** [comment]
When creating the call you must have propertyid in the form of "properties/*". Hope that helps

Ref: https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runReport

**Comment by nomoonx** [comment]
isn't this ambiguous?

**Comment by codyoss** [comment]
What do you mean?
