### ISSUE TITLE
Specifying option.WithScopes is ignored when using option.WithTokenSource

### ISSUE THREAD

**Issue by salrashid123** [googleapis/google-api-go-client#1644]
If you use both

*  https://pkg.go.dev/google.golang.org/api/option#WithScopes
* https://pkg.go.dev/google.golang.org/api/option#WithTokenSource

at the same time as shown below, the scopes settings from the tokensource is used.

The following works for cloudidentity api because the "books" api scope is simply ignored

```golang
    configci, err := google.JWTConfigFromJSON(serviceAccountJSON, cloudidentity.CloudPlatformScope, cloudidentity.CloudIdentityGroupsReadonlyScope)

    tsci := configci.TokenSource(ctx)

    cisvc, err := cloudidentity.NewService(ctx, option.WithTokenSource(tsci), option.WithScopes("https://www.googleapis.com/auth/books"))
```

but if you invert it, you'll see a scopes error since the actual token from the config is used

```golang
    configci, err := google.JWTConfigFromJSON(serviceAccountJSON, "https://www.googleapis.com/auth/books")
    tsci := configci.TokenSource(ctx)

    cisvc, err := cloudidentity.NewService(ctx, option.WithTokenSource(tsci), option.WithScopes(cloudidentity.CloudPlatformScope, cloudidentity.CloudIdentityGroupsReadonlyScope))
```

consider throwing an error if both are set

---

```
$ go version
go version go1.17.1 linux/amd64
```

```golang
module main

go 1.17

require (
	golang.org/x/oauth2 v0.0.0-20220722155238-128564f6959c
	google.golang.org/api v0.91.0
)
```

**Comment by codyoss** [comment]
The end behavior is intentional here, but I agree this could lead to hard to track down bugs. I think we should have a fast fail here and disallow passing both of these options at the same time as whatever is specified in the TS will always win.

**Comment by eisandbar** [comment]
It can be something analogous to this

https://github.com/googleapis/google-api-go-client/blob/d6ee425a65668ee28ff97c6fb70f3497865d6572/internal/settings.go#L107-L109

```
if len(ds.Scopes) > 0 && ds.TokenSource != nil {
    return errors.New("WithScopes is incompatible with WithTokenSource")
}
```

**Comment by codyoss** [comment]
I commented this on the linked PR but wanted to make sure the same comment was captured in this issue as well

"
Although I think is a good change to make, it can't be made just yet. We will first need to audit our libraries to ensure we are not passing scopes via the WithScopes client option. I know where are in clients in this repo and may still have places where this is done in our sister repo as well. Adding this check would cause people to never be able to pass the TokenSource option right now in these instances.

I also due worry thinking more about this that there may be libraries built on libraries where these options are passed today. Once we have a better logging solution in place it may be better to log a warning in cases like this. I will need to think about this a little more.
"

**Comment by salrashid123** [comment]
fwiw, i'd be happy if its just documented in the links above (no need at the moment to aggressively throw `err`)

**Comment by codyoss** [comment]
Yeah, I think that may be the best option for now. @eisandbar If you are willing to make that change I think that is a way we can move forward for now.

**Comment by eisandbar** [comment]
Should I add it to both WithScopes and WithTokenSource, or only WithScopes?

**Comment by codyoss** [comment]
I think just withscopes would be fine -- noting that it has no effect when used with tokensource opt.
