### ISSUE TITLE
Cannot use types in google.golang.org/genproto/googleapis/cloud/compute/v1

### ISSUE THREAD

**Issue by neara** [googleapis/google-api-go-client#1659]
Following this [guide](https://cloud.google.com/go/docs/reference/cloud.google.com/go/compute/latest/apiv1#cloud_google_com_go_compute_apiv1_InstancesClient_Insert), I imported `computepb "google.golang.org/genproto/googleapis/cloud/compute/v1"`, but I'm getting `Unresolved type 'InsertInstanceRequest` for `computepb.InsertInstanceRequest'`. 

Using `cloud.google.com/go/compute v1.8.0`.

How to import the type or how else can I call compute api to create an instance?

**Comment by codyoss** [comment]
Hey, I think you are looking for googleapis/google-cloud-go, but I can still help here. I can get the types to resolve with the following in my go.mod:

```
require (
	cloud.google.com/go/compute v1.8.0
	google.golang.org/genproto v0.0.0-20220810155839-1856144b1d9c
)
```

Hope that helps!

**Comment by neara** [comment]
In the end, the issue was with Goland. The types file is too big and wasn't parsed. The default limit is set to ~6MB and the file `compute.pb.go` is ~9MB. Once I extended the default limit to 20MB, the types stopped appearing as non-existent. 


@codyoss Thank you for you help 🙏🏻
