### ISSUE TITLE
identitytoolkit v3 setProjectConfig returns 404

### ISSUE THREAD

**Issue by wolzey** [googleapis/google-api-go-client#1679]
#### Environment details

  - Programming language: go
  - Language runtime version: 1.19
  - Package version: v0.94.0

#### Steps to reproduce
 I am able to get the project config using the `RelyingParty` `getProjectConfig` but whenever I try `setProjectConfig` I'm getting a 404. I have tried this in this library as well as the NodeJS library to see if there was a bad path. Using the discovery url for version 3 it appears the paths are correct. I'm wondering if there is a required parameter that I'm supposed to send but isn't mentioned anywhere.
 
```go
        service, err := identitytoolkit.NewService(context.TODO(), option.WithCredentialsJSON([]byte("somefancyjsoncreds")))

	if err != nil {
		panic(err)
	}

	/** works as expected */
	rq := service.Relyingparty.GetProjectConfig()
	rq.Fields(googleapi.Field("authorized_domains"))
	rs, err := rq.Do()

	if err != nil {
		panic(err)
	}

	fmt.Println(rs.AuthorizedDomains)

	spr := service.Relyingparty.SetProjectConfig(&identitytoolkit.IdentitytoolkitRelyingpartySetProjectConfigRequest{
		AuthorizedDomains: append(rs.AuthorizedDomains, "google.com"),
	})

	res, err := spr.Do()

	if err != nil {
		// returns a 404
		panic(err)
	}

	fmt.Println(res.ProjectId)
```

Thanks!

**Comment by quartzmo** [comment]
@wolzey Thanks for reporting this, I'll try to reproduce it today.

**Comment by wolzey** [comment]
I should probably mention that I'm using Identity Platform and am trying to add authorized domains.

**Comment by quartzmo** [comment]
> I have tried this in this library as well as the NodeJS library to see if there was a bad path.

And this also did not work for you with the NodeJS client, correct?

**Comment by wolzey** [comment]
> > I have tried this in this library as well as the NodeJS library to see if there was a bad path.
> 
> And this also did not work for you with the NodeJS client, correct?

Correct, so I don't think this is an issue for the Go client unless I'm missing some obvious configuration. Then it's just user error :)

**Comment by quartzmo** [comment]
I reproduced the `404` response exactly as described in this issue. 

This blog post from Oct 2021 also documents it for Go and Python: https://pretired.dazwilkin.com/posts/211026/

**Comment by quartzmo** [comment]
@wolzey I have not been able to find a solution to this. It appears to be beyond the scope of the Go client, as you noted. Can you try the `curl` alternative suggested in the blog post that I linked above?

**Comment by wolzey** [comment]
Sure, let me try that out really quick

**Comment by wolzey** [comment]
@quartzmo this solution works great for my use case. Is there a place I can escalate this issue to the API team?

**Comment by quartzmo** [comment]
Yes please! For most Google Cloud products, the issue tracker can be found in the index at [cloud.google.com/support/docs/issue-trackers](https://cloud.google.com/support/docs/issue-trackers). However, this appears to be a Firebase service to me (I could be wrong), so [firebase.google.com/support/troubleshooter/report/bugs](https://firebase.google.com/support/troubleshooter/report/bugs) seems like a better choice, maybe with "Firebase product" set to "Authentication"?

Thanks again for reporting this issue here, I'm glad to have it in our public knowledgebase for other users who encounter it in the future.
