### ISSUE TITLE
How to add Authorized Urls / Redirect Urls in credentials

### ISSUE THREAD

**Issue by OlivierMary** [googleapis/google-api-go-client#1706]
Hi there,

I need to automate adding url in `authorized_url` / `redirect_url` in oauth2 credential, cause wildcard not authorized.

In google console it's here:
![image](https://user-images.githubusercontent.com/4348675/194584029-9f178270-e712-41b6-a9fb-3c9f00ae053e.png)

I search a long time and I found nothing, I don't know if I just didn't find or if it's impossible with the actual APIs ?

Maybe another way it's to add 1 client id by url, but the same, I didn't find a way to do this with Apis.

Any Ideas?

Thanks for your time and reply.

**Comment by codyoss** [comment]
I am not aware of any apis for this, but I also don't know the context of this page. Although you may have better luck on one of the google cloud issue trackers: https://cloud.google.com/support/docs/issue-trackers
