### ISSUE TITLE
Can not add custom domain to hosting using Golang API

### ISSUE THREAD

**Issue by danh-terra-drone** [googleapis/google-api-go-client#1709]
I try to add a new custom domain to hosting using API. But It seems not to work, even though there is a function in SDK.
{
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"domainName\": Cannot bind query parameter. Field 'domainName' could not be found in request message.",
    "errors": [
      {
        "message": "Invalid JSON payload received. Unknown name \"domainName\": Cannot bind query parameter. Field 'domainName' could not be found in request message.",
        "reason": "invalid"
      }
    ],
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "description": "Invalid JSON payload received. Unknown name \"domainName\": Cannot bind query parameter. Field 'domainName' could not be found in request message."
          }
        ]
      }
    ]
  }
}

**Comment by codyoss** [comment]
@danh-terra-drone Please provide more information from our bug template. 
- What versions are you using?
- Can you show the calling code?

**Comment by codyoss** [comment]
Closing due to lack of response. Please re-open if you can provide more details.
