### ISSUE TITLE
api/admin/directory/v1: Error 403 Not Authorized to access this resource/api

### ISSUE THREAD

**Issue by DarraghDuffy** [googleapis/google-api-go-client#1724]
**Client**

Go

**Environment**

MacOS

**Go Environment**

$ go version
go version go1.19.1 darwin/amd64

$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/darraghduffy/Library/Caches/go-build"
GOENV="/Users/darraghduffy/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/darraghduffy/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/darraghduffy/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xb/4h0gn92x0fq771zgnf010vt80000gn/T/go-build3335230793=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Code**

e.g.
```go
package main

import (
	"fmt"
	"log"

	"golang.org/x/net/context"
	admin "google.golang.org/api/admin/directory/v1"
)

func main() {

	ctx := context.Background()
	client, err := admin.NewService(ctx)

	if err != nil {
		log.Fatalf("Unable to retrieve directory Client %v", err)
	}
	allUsers := client.Users.List().Domain("ACME.com")
	users, err := allUsers.Do()
	if err != nil {
		log.Fatalf("oops error %v", err)
	}
	fmt.Printf("%+v\n", users)
}
```

**Expected behavior**

A list of users in the domain defined.

**Actual behavior**

Error 403 Not Authorized to access this resource/api

**Screenshots**

The Scopes

![1](https://user-images.githubusercontent.com/3587980/197855677-b1484f03-001c-407c-9868-3fe57ca1f3b4.png)

The Error
![image](https://user-images.githubusercontent.com/3587980/197856482-04c58967-db6b-4247-8816-dac4141a5084.png)

The Environment Variable for Credentials

![image](https://user-images.githubusercontent.com/3587980/197856791-38df9590-b463-4647-a96a-6271ab9212a6.png)

**Additional context**

I have the service account created and in above image. you can see the Service Account is bound to the Scopes. The account associated / delegated is an admin account, I have full admin privs on the Organization. When I use the oAuth with my account via https://developers.google.com/admin-sdk/directory/reference/rest/v1/users/list everything is returned as expected, i.e. my account has the priv to list all users of the organization

**Comment by DarraghDuffy** [comment]
Here is some additional information:


My Account is a Super Admin see here:

![image](https://user-images.githubusercontent.com/3587980/197997331-fea265ca-36e5-4d44-97e0-922d4a3ca003.png)


I used my account to create the Service Account, some more details here:

![image](https://user-images.githubusercontent.com/3587980/197997900-8dde222a-b399-4e29-9288-450b69298416.png)

I have also read the following Note:
https://developers.google.com/workspace/guides/create-credentials#desktop-app

I rewrote my Code here it is:

`
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"

	"golang.org/x/net/context"
	"golang.org/x/oauth2/google"
	admin "google.golang.org/api/admin/directory/v1"
)

func main() {

	client := createAdminDirectoryService(os.Getenv("GOOGLE_APPLICATION_CREDENTIALS"), os.Getenv("GOOGLE_APPLICATION_EMAIL"))
	request := client.Users.List().Domain("workvivo.com")
	users, err := request.Do()
	if err != nil {
		log.Fatalf("oops error %v", err)
	}
	fmt.Printf("%+v\n", users)
}

func createAdminDirectoryService(jsonCredentialsFile, email string) *admin.Service {
	jsonCredentials, _ := ioutil.ReadFile(jsonCredentialsFile)

	config, _ := google.JWTConfigFromJSON(
		jsonCredentials,
		admin.AdminDirectoryDomainScope,
	)
	config.Subject = "cloudflare-zero-trust@cloudflare-zero-trust-dpc.iam.gserviceaccount.com"

	ctx := context.Background()
	client := config.Client(ctx)

	srv, _ := admin.New(client)
	return srv
`

And I get the following Error:


![image](https://user-images.githubusercontent.com/3587980/197999395-97cc2bb8-3678-4f00-91f7-90741abb7fbb.png)

**Comment by DarraghDuffy** [comment]
@quartzmo - the standard default method to authenticate is not working as outlined in this. this is either a bug or [the documentation](![image](https://user-images.githubusercontent.com/3587980/198202153-75dfb48e-6af7-46ca-aced-8282aacdd87f.png)) is incorrect,can you clarify?

**Comment by quartzmo** [comment]
@DarraghDuffy I'll try to look into this in great depth as soon as I can. In the meantime, do you see anything helpful in this apparently related issue?

https://github.com/googleapis/google-cloud-go/issues/1892

**Comment by codyoss** [comment]
To use this API with a service account you must use impersonation to be the admin user that can use delegation. You may find this example useful: https://pkg.go.dev/google.golang.org/api/impersonate#example-CredentialsTokenSource-AdminUser

**Comment by ahmadnassri** [comment]
@codyoss thank you for that note on impersonation ... I've been running into this issue with terraform ... curious, where do you find the docs that state that specific resources MUST use impersonation?

**Comment by codyoss** [comment]
I don't recall offhand, but any time you are trying to act on a users behalf with the workspace APIs this is the mechanism to do so.
