### ISSUE TITLE
some questions about androidpublisher/v3-monetization.subscriptions.basePlans.offers(create/list/patch)

### ISSUE THREAD

**Issue by QingsiLiu** [googleapis/google-api-go-client#1735]
Hi! 
I've been trying to call the subscription offer interface recently to manage data in the Google play store, but I've encountered some strange problems and I don't know how to solve them. Hopefully the big guys will be free to help answer them, whether it's a back-end error or an error that happened during my use.

The specific issues are as follows:
1. "google.golang.org/api/androidpublisher/v3:**monetization.subscriptions.basePlans.offers.create**"
When this interface is called, no matter what I do, it always returns 500 errors: "googleapi: Error 500: Internal error encountered. backendError"

2."google.golang.org/api/androidpublisher/v3:**monetization.subscriptions.basePlans.offers.list**"
When this interface is called, when the offer type chooses "acquisitionRule", the "targeting" in the offer structure is always empty, regardless of the settings I choose.

3. "google.golang.org/api/androidpublisher/v3:**monetization.subscriptions.basePlans.offers.patch**"
When this interface is called and "targeting" is updated, if the type is "acquisitionRule"
it always gets an error "googleapi: Error 400: The acquisition targeting rule used an unsupported scope. Must be'This Subscription'or'Any subscription in app', badRequest" has actually set the string correctly

Combining the second and third points, I guess if there are some errors in the back end of the Google API that led to the wrong results in the first point.

**Comment by codyoss** [comment]
Hey, a couple of suggestions that might help.

Have you tried to inspect your errors further? See [Inspecting errors](https://pkg.go.dev/google.golang.org/api#hdr-Inspecting_errors) to try to extract more info out of the errors.

1. Make sure you setting the required fields or else you can get 500s somethings. For this call you must have an offerID
2. I am not sure about this one, see below.
3. I am not sure about this one, see below.

For more product specific guidance I might please reach out via this form: https://support.google.com/googleplay/android-developer/gethelp?visit_id=637599741297094070-2434654640&rd=1#. It can be found under the [Getting started](https://developers.google.com/android-publisher) section on the API overview page.

Hope that helps get you going down the right path.

**Comment by QingsiLiu** [comment]
OK， i'll try to do it
