### ISSUE TITLE
How to set a higher MaxIdleConnsPerHost for idtoken client

### ISSUE THREAD

**Issue by david-gang** [googleapis/google-api-go-client#1744]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do

set a higher MaxIdleConnsPerHost for idtoken client  in order to get a better latency
- What code you've already tried

```
httpTransport := http.DefaultTransport.(*http.Transport).Clone()
	httpTransport.MaxIdleConnsPerHost = 100
	baseClient := http.Client{
		Transport: httpTransport,
	}
client, err := idtoken.NewClient(ctx, aud, option.WithHTTPClient(&baseClient))
```
- Any error messages you're getting

> transport/http: WithHTTPClient passed to NewTransport

The problem is similar to here:

https://github.com/googleapis/google-api-go-client/issues/1074

but the solution does not look applicable as i have no real access to the transport here.

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by quartzmo** [comment]
Hi @david-gang,

Regarding your sample:

```go
client, err := idtoken.NewClient(ctx, aud, option.WithHTTPClient(&baseClient))
```

It seems clear from the error that `option.WithHTTPClient` (or `idtoken.WithHTTPClient`) is not meant to be used with `idtoken.NewClient`. I think that in `idtoken` it is possibly only meant to be used with [idtoken.NewValidator](https://pkg.go.dev/google.golang.org/api/idtoken#NewValidator).

Is this a feature request to add `MaxIdleConnsPerHost` as an option?

**Comment by david-gang** [comment]
Thanks @quartzmo !
