### ISSUE TITLE
Legal check issue with the licensing 

### ISSUE THREAD

**Issue by Kiran-38** [googleapis/google-api-go-client#1763]
Hi, we have a component that uses this package for building the binary and during the legal analysis we have faced some issue with the "Most of the files are licensed under BSD. The file (google.golang.org/api@v0.82.0/api-list.json) has a non-commercial limitation: the Safe Browsing APIs are for non-commercial use only".

I see licensing mentioned in source file (.go) is not in line with json description: https://github.com/googleapis/google-api-go-client/tree/main/safebrowsing/v4

My concern is why to document such restriction https://github.com/googleapis/google-api-go-client/blob/main/safebrowsing/v4/safebrowsing-api.json even though the license looks like a normal BSD-3 license.

**Comment by codyoss** [comment]
Thanks for the question. I will look into this and get back to you.

**Comment by JohnsoNeal2013** [comment]
Can you please and let me know the status please and what can I do to get
all my accounts back safely

**Comment by codyoss** [comment]
The code to access the api/examples etc are BSD licensed. This doesn't confer any right to access the api. Hope that helps.
