### ISSUE TITLE
add response headers to Error reported by CheckMediaResponse

### ISSUE THREAD

**Issue by BrennaEpp** [googleapis/google-api-go-client#1769]
We add them to the [`CheckResponse`](https://github.com/googleapis/google-api-go-client/blob/main/googleapi/googleapi.go#L143) function.

Would it be reasonable to add them to the [`CheckMediaResponse` function](https://github.com/googleapis/google-api-go-client/blob/main/googleapi/googleapi.go#L183) too? This would allow us to surface them to the user on googleapi read errors in the Storage library through apiary.

**Comment by codyoss** [comment]
Seems reasonable to me. Feel free to make a PR
