### ISSUE TITLE
Is it possible to override grpc QuotaProject dynamically?

### ISSUE THREAD

**Issue by damemi** [googleapis/google-api-go-client#1780]
Hi, we're using the cloud trace client and trying to set `x-goog-user-project` dynamically, with a different value per-call, to attribute billing for individual requests to their routed project. This might be a question for the cloud trace team instead, but from my digging I just wanted to see if this was even possible with the underlying grpc clients.

I see that it's possible to set [`QuotaProject`](https://github.com/googleapis/google-api-go-client/blob/2bdb4a9808454c2e43c015b99011a42d084aa02d/internal/settings.go#L53) as a dial setting but haven't found a way to override this for each call.

It looks like the client sets up a dial pool with [this function](https://github.com/googleapis/google-api-go-client/blob/v0.104.0/transport/grpc/dial.go#L82), which ultimately hardcodes a `quotaProject` here: https://github.com/googleapis/google-api-go-client/blob/v0.104.0/transport/grpc/dial.go#L162-L167

I tried a client interceptor to update the `x-goog-user-project` metadata header, but that seems to be getting stomped by [`GetRequestMetadata()`](https://github.com/googleapis/google-api-go-client/blob/v0.104.0/transport/grpc/dial.go#L245)

I also saw [this comment](https://github.com/googleapis/google-api-go-client/blob/v0.104.0/transport/grpc/dial.go#L197) which implies that using interceptors to overwrite quota project isn't possible. I just wanted to confirm if that was the case. Thanks!

**Comment by codyoss** [comment]
I think the way to dynamically set the value would be to ensure there is no default value set at the credential level. Then you could use a gax.CallOption -> grpc.CallOption -> Header. I have not tested this but I think it would work. Would that work in your use case?

**Comment by damemi** [comment]
@codyoss I think that would work. I was hoping the credential default could still be set as a fallback, but maybe in our case we would just need to ensure every request set the header manually. Thanks!

**Comment by codyoss** [comment]
Yeah I don't think this feature was designed with dynamically changing the value in mind so there are some slight rough edges here. But I think it is WAI for now.
