### ISSUE TITLE
bigquery: How to mock for unit testing

### ISSUE THREAD

**Issue by yuseferi** [googleapis/google-api-go-client#1795]
Hey, I'm trying to mock bigquery Client, but I didn't find a good solution for that.
 - https://github.com/googleapis/google-cloud-go-testing it sounds interesting the way but it's outdated and lots of methods have not been updated and the project has been archived recently
- [sample 1 ](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/bigquery/simpleapp/simpleapp_test.go) it's using the real client with just a sample project that is not what I wanted 

is there any sample or way to mock bigquery client for unittesting?

**Comment by shollyman** [comment]
There's not a great mocking story for BigQuery currently.  See https://github.com/googleapis/google-api-go-client/blob/main/testing.md for general guidance for this repo.  Also, it's worth noting that this repo corresponds to the generated REST discovery library `google.golang.org/api/bigquery/v2`, and not the main `cloud.google.com/go/bigquery` library which is largely handwritten and depends on this library.

In `cloud.google.com/go/bigquery` we largely unit test type conversions between this library and the cloud bigquery types via table driven testing.  There's also support in that library's integration testing for doing a version of a replay-style testing: run the tests against the live service and record the traffic, and then subsequent tests can use the recorded traffic.  In practice we tend to test against the live service just to ensure we're maintaining fidelity.

Hope this helps.

**Comment by quartzmo** [comment]
As mentioned above, https://github.com/googleapis/google-api-go-client/blob/main/testing.md demonstrates how to mock these clients, with what I find to be good advice about using the facade pattern to define a higher-level interface. However, unit tests based on mocks at this level may not provide as much value as more integrated approaches, such using a fake `net/http/httptest` in-memory server (also covered in `testing.md`), or replay-style testing, discussed by @shollyman  above.
