### ISSUE TITLE
Google Analytics CloudQuery Source Plugin

### ISSUE THREAD

**Issue by yevgenypats** [googleapis/google-api-go-client#1824]
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are interested in a Google Analytics source plugin, but as we cannot maintain all the plugins ourselves, I was curious if this would be an interesting collaboration, where we would help implement an initial [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), and you will help maintain it.

This will give your users the ability to sync Google Analytics APIs to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by codyoss** [comment]
Hey,

Unfortunately I don't think this project has the bandwidth for such a request. This repo is mainly auto-generated code and the project is considered in maintenance mode: https://github.com/googleapis/google-api-go-client#status
