### ISSUE TITLE
How to set proxy for Google.Apis.YouTube.v3 ? 

### ISSUE THREAD

**Issue by bbqe1314** [googleapis/google-api-go-client#1839]
i want to upload a video to my youtube account, but when i deploy my project to server, i must send http with proxy. but the Transtport doesn't contains Proxy, it is different from net/http's Transport. what shoud i do ?

**Comment by quartzmo** [comment]
Hi @bbqe1314,

Please provide sample code to demonstrate what you are attempting to do. To provide a custom HTTP client, use [option.WithHTTPClient](https://pkg.go.dev/google.golang.org/api/option#WithHTTPClient).

**Comment by quartzmo** [comment]
For example:

```go
youtubeService, err := youtube.NewService(ctx, option.WithHTTPClient(...))
```

**Comment by bbqe1314** [comment]
@quartzmo 
thank you for you comment. i have saw option.WithHTTPClient.
but if i use net/http's Transport, i can set proxy like this 
```go
cli := &http.Client{Transport: &http.Transport{Proxy: myProxyFunc}}
youtubeService, err := youtube.NewService(ctx, option.WithHTTPClient(cli))
```
and for oauth2 package, it's Transport struct just contains Base and Source,  so i can not set proxy.
```go
cli := oauth2.NewClient(ctx, tokenSource(ctx, token))
s, err := youtube.NewService(ctx, option.WithHTTPClient(cli))
```

**Comment by quartzmo** [comment]
Thanks, I think now I understand what you are trying to do. See golang/oauth2#182 and let me know if that works for you.
