### ISSUE TITLE
idtoken.NewValidator() not working with option.WithAPIKey anymore

### ISSUE THREAD

**Issue by henrisson** [googleapis/google-api-go-client#1842]
- Programming language: Go
  - OS: MacOS (applies to all)
  - Language runtime version: 1.19
  - Package version: v106 and over

#### Steps to reproduce

  1. Create a new Validator with an API Key option
  2. Call Validate()

Example
```
	tokenValidator, err := idtoken.NewValidator(context.Background(), option.WithAPIKey(myGoogleAPIKey))
	if err != nil {
		// ...
	}

	payload, err := tokenValidator.Validate(context.Background(), token, c.options.GoogleClientId)
	if err != nil {
		// ...
	}
```

The following commit seems to have introduce the issue: https://github.com/googleapis/google-api-go-client/commit/b35900aff148bb8446ca7e15ed0beb50d749d6c7

The options are appended in the ops slice, which triggers this [check](https://github.com/googleapis/google-api-go-client/blob/4b4c9d468a78cae7a41cbcb14054999dfef31b80/internal/settings.go#L85)

Downgrading to v105 worked

**Comment by codyoss** [comment]
@henrisson Can you explain your use case why you need to pass an apikey to create a new validator? Passing nothing should work I believe.

**Comment by henrisson** [comment]
I need at least one type of credentials. Without any, I get

`creating validator: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.`

Sure I could use $HOME/.config/gcloud/application_default_credentials.json but  reading an API key from a config file and using options.WithAPIKey seems like a reasonable use case as well.

My understanding is that this commit broke  idToken.NewValidatior() with any options that bear any kind of authentication.\
I would consider this as a regression.

**Comment by codyoss** [comment]
I believe the there is no valid case to send a credential with this API. Allowing it in the first place is a bug and could lead to errors from the server. Are you getting that error with the new code? See linked issues for more details.

**Comment by henrisson** [comment]
My bad, it does work with the latest version if I remove the withAPIKey.\
I somehow didn't think Google would leave the token verification API open without at least registering with a project.

My bad a sorry about noise.

**Comment by codyoss** [comment]
No worries, glad it worked!
