### ISSUE TITLE
What's the current status of `firebaseremoteconfig:v1` API code?

### ISSUE THREAD

**Issue by central182** [googleapis/google-api-go-client#1847]
The latest revision of the discovery document of Firebase Remote Config is `"20230206"` according to https://firebaseremoteconfig.googleapis.com/$discovery/rest?version=v1.
> The link can be found at https://firebase.google.com/docs/reference/remote-config/rest.

The revision in this repository is way outdated 
https://github.com/googleapis/google-api-go-client/blob/1651c38b919944699bb8a705311c15b6ada8be11/firebaseremoteconfig/v1/firebaseremoteconfig-api.json#L166
and it seems that the section of `firebaseremoteconfig:v1` was dropped from `api-list.json` in this commit https://github.com/googleapis/google-api-go-client/commit/3caa384156365e545aea85c3dca8c95bc666a94d.

I was able to re-generate the API code by
- bringing back `firebaseremoteconfig:v1` into `api-list.json`
- downloading the latest discovery document of `firebaseremoteconfig:v1`
- running the `google-api-go-generator` tool

It would be great though if the official repository had the latest code and I didn't have to do it manually.

**Comment by codyoss** [comment]
Hey, we do not control what APIs are present in the index -- it is scraped from: `https://www.googleapis.com/discovery/v1/apis`. This sounds like a feature request for that firebase API to be added back to the index. I suggest reaching out to one of their support channels or issues trackers.
