### ISSUE TITLE
ProjectsIosAppsGetConfigCall.Do gets app rather than app config

### ISSUE THREAD

**Issue by megan07** [googleapis/google-api-go-client#1849]
#### Environment details

  - Programming language: Go
  - OS: Mac 11.7
  - Language runtime version: 1.19
  - Package version: v105

#### Steps to reproduce

```
	appName := fmt.Sprintf("projects/%s/iosApps/%s", projectName, appId)

	clientResp, err := client.GetConfig(appName).Do()
```

  1. On run it calls `https://firebase.googleapis.com/v1beta1/projects/<project-name>/iosApps/<app-id>` rather than getting the config

I think the issue lies [here](https://github.com/googleapis/google-api-go-client/blob/main/firebase/v1beta1/firebase-gen.go#L6529) and `/config` needs to be appended to `"v1beta1/{+name}"`

**Comment by codyoss** [comment]
Hey, I think you need to add `/config` to the end of our appName. See the docs: https://pkg.go.dev/google.golang.org/api/firebase/v1beta1#ProjectsIosAppsService.GetConfig

"... in the format: projects/PROJECT_IDENTIFIER/iosApps/APP_ID/config ..."

Hope that helps!
