### ISSUE TITLE
How to get "resourceName" field PeopleApi v1

### ISSUE THREAD

**Issue by jcervantes-genially** [googleapis/google-api-go-client#1855]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do
When I create an user in google contacts using the people API, I use the following call:
```
resource := srv.People.CreateContact(&person)
```
I'm using the variable "resource" trying to reach the resourceName of that createdUser, however I got something like this: 
```
&{0xc0005a2700 0xc00016a000 map[] <nil> map[]}
```

I already tried with the heardes, context and fields options, but, everything is returning a void map[].

How can I get the value?

Why I need the value? This is because we can not find users by phone number, then, If we can not make that search, I keep the resourceName in my BBDD to update after the contact if I need it.

Thank you for the help!

**Comment by quartzmo** [comment]
@jcervantes-genially Thanks for this question. Can you please provide a more complete code sample, showing the imports, the creation of the client, the initialization of `person`, and how you use the response? This will help me reproduce the issue. Thanks you.

**Comment by jcervantes-genially** [comment]
```
func CreateGoogleContact(client entities.People, token *oauth2.Token) {

	srv := GoogleService(token)

	var person people.Person
	var name people.Name
	var phone people.PhoneNumber
	var birthday people.Birthday
	phoneNumber := "+1"

	if client.Data.Customer.Phone != "" {
		phoneNumber = client.Data.Customer.Phone
	} else {
		phoneNumber = "+1" + client.Data.Customer.Phone
	}

	phone.Value = phoneNumber
	phone.Type = "mobile"
	name.FamilyName = client.Data.Customer.FirstName
	name.GivenName = client.Data.Customer.LastName
	birthday.Text = client.Data.Customer.Birthday

	person.Names = []*people.Name{&name}
	person.PhoneNumbers = []*people.PhoneNumber{&phone}
	person.Birthdays = []*people.Birthday{&birthday}

	resource := srv.People.CreateContact(&person)
}
```

The API is returning a *people.PeopleCreateContactCall and the type of that struct said is:

``` 
type PeopleCreateContactCall struct {
	// contains filtered or unexported fields
}
``` 

However, in the [documentation](https://developers.google.com/people/api/rest/v1/people/createContact) said the following answer:

> Response body
> If successful, the response body contains an instance of [Person] (https://developers.google.com/people/api/rest/v1/people#Person)

Then, I don't know if I'm using the wrong API call or I'm doing something incorrect.

Thanks,

**Comment by quartzmo** [comment]
It looks to me that you need to add the chained call to `Do` to the end of your statement, as explained in  [Getting Started with the Google APIs for Go](https://github.com/googleapis/google-api-go-client/blob/main/GettingStarted.md#using-the-service).

```go
resource, err := srv.People.CreateContact(&person).Do()
if err != nil {
    ...
}
```

**Comment by jcervantes-genially** [comment]
Thanks, with the "do()" I got the Person struct.
And additionally, I had to get a new token.
