### ISSUE TITLE
Support timestamps via `time.Time` in `google.golang.org/api/analytics/v3`

### ISSUE THREAD

**Issue by candiduslynx** [googleapis/google-api-go-client#1871]
**Is your feature request related to a problem? Please describe.**
I'm developing a plugin to help extract data from Google Analytics into different destinations (CLoudQuery).
When I look at the API reference I see that some fields are marked as `datetime`. However, the client representation is `string`.

See accounts:
* [API reference](https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/accounts#resource)
* Go code (note `Updated` field): https://pkg.go.dev/google.golang.org/api@v0.110.0/analytics/v3#Account

**Describe the solution you'd like**
I'd like to have a proper `time.Time` (or pointer) in the returned structs.

**Describe alternatives you've considered**
Provide the parsing schema to be used to transform the `datetime` string representation to a `time.Time` value.

**Comment by codyoss** [comment]
That sounds like a breaking change and the auto-generated clients in this module are considered feature complete and in maintenance mode: https://github.com/googleapis/google-api-go-client#status
