### ISSUE TITLE
Improve local user experience for User Credentials

### ISSUE THREAD

**Issue by TimurSadykov** [googleapis/google-api-go-client#1876]
This is part of the bigger work [go/simplified-local-adc](http://goto.google.com/simplified-local-adc)

User Credentials are now recommended for local development per [go/mitigating-cloud-auth-risk](https://goto.google.com/mitigating-cloud-auth-risk)

However, some errors and warnings still refer to service accounts (see section 1.2 of the [go/simplified-local-adc](http://goto.google.com/simplified-local-adc)):

1. When user does not have credential setup, we do not recommend setting up service account, rather we redirect to a new ADC setup page.
2. (if implemented) We show warning about user credentials only if production environment is detected
Reference Java fix: https://github.com/googleapis/google-auth-library-java/pull/1172

**Comment by codyoss** [comment]
@TimurSadykov  We do not log in any of our Go libraries today so I don't think we will be doing 2. As for 1 do you have a link? Today we link to https://developers.google.com/accounts/docs/application-default-credentials in this event.

**Comment by TimurSadykov** [comment]
Hey @codyoss, the proposed text and message for 2 is in the 1.2.2. section of the [go/simplified-local-adc](http://goto.google.com/simplified-local-adc)

**Comment by codyoss** [comment]
https://go-review.git.corp.google.com/c/oauth2/+/473735 updates the URL to the new page.
