### ISSUE TITLE
How to sign a URL impersonating a service account

### ISSUE THREAD

**Issue by krisowski** [googleapis/google-api-go-client#1881]
I can't generate a signed URL using the standard Go example [here](https://cloud.google.com/storage/docs/samples/storage-generate-upload-signed-url-v4#storage_generate_upload_signed_url_v4-go)

I use ADC with impersonation according to the [docs](https://pkg.go.dev/cloud.google.com/go/storage#hdr-Credential_requirements_for_signing):
`gcloud auth application-default login --impersonate-service-account=<SA>` 

But when I run the example and call the `client.Bucket(bucket).SignedURL(...)` I get the following error:
```json
Bucket("<MY BUCKET>").SignedURL: unable to sign bytes: googleapi: Error 403: Permission 'iam.serviceAccounts.signBlob' denied on resource (or it may not exist).
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "iam.googleapis.com",
    "metadata": {
      "permission": "iam.serviceAccounts.signBlob"
    },
    "reason": "IAM_PERMISSION_DENIED"
  }
]
```

The service account that I'm impersonating has the `iam.serviceAccounts.signBlob` permission assigned for sure because it works fine with:
1. Python [example](https://cloud.google.com/storage/docs/samples/storage-generate-upload-signed-url-v4#storage_generate_upload_signed_url_v4-python}
2. the `gutils`: `gsutil -i <SA> signurl -m PUT -c application/octet-stream -d 10m -u gs://<MY BUCKET>/<MY FILE>`

This means that the SA has to have all permissions configured properly

I have debugged the Go client and found that the `defaultSignBytesFunc()` internal method can extract the service token (`GoogleAccessID`) from the token file successfully but it probably can't get the private key from the SA.

Is this an issue with the client or do I use it incorrectly?

**Comment by quartzmo** [comment]
Hi @krisowski,

I think you opened this issue on the wrong repo. 

> I can't generate a signed URL using the standard Go example [here](https://cloud.google.com/storage/docs/samples/storage-generate-upload-signed-url-v4#storage_generate_upload_signed_url_v4-go)

The example you linked uses `cloud.google.com/go/storage`, which is hosted at https://github.com/googleapis/google-cloud-go/tree/main/storage.

Thanks!
