### ISSUE TITLE
Unable to create Interconnect VLAN Attachments

### ISSUE THREAD

**Issue by matthung0807** [googleapis/google-api-go-client#1899]
#### Environment details

  - Programming language: Go
  - OS: macOS Ventura 13.0.1
  - Language runtime version: v1.19
  - Package version: google.golang.org/api v0.79.0

#### Steps to reproduce

  1. Running localhost Go application, use [InterconnectAttachmentsService.Insert](https://pkg.go.dev/google.golang.org/api@v0.79.0/compute/v1#InterconnectAttachmentsService.Insert).[Do](https://pkg.go.dev/google.golang.org/api@v0.79.0/compute/v1#InterconnectAttachmentsInsertCall.Do) to create a Interconnect VLAN attachment doesn't working, and it has no any response error with operation response code 200.
```
vlan := &compute.InterconnectAttachment{
	Name:                   param.Name,
	EdgeAvailabilityDomain: param.EdgeAvailabilityDomain,
	Router:                 param.Router,
	Type:                   "PARTNER",
}

op, cloudErr := c.InterconnectAttachments.
	Insert(projectId, region, vlan).
	RequestId(param.RequestId).
	Do()
```
  2. After execute above statements the VLAN attachment isn't created and it has no error response.
  3. Check on Google Cloud console's [Interconnect](https://console.cloud.google.com/hybrid/interconnects/list), there is no corresponding result.
  4. Create a CloudRouter has no problem.
  5. Use gcloud cli can create VLAN Attachments successfully.

```
gcloud compute interconnects attachments partner create
```

Thanks!

**Comment by codyoss** [comment]
That API returns an async op handler. When it returns the operation is not necessarily done. It needs to be polled for. For better ergonomics I would suggest using the newer version of this library when possible: https://pkg.go.dev/cloud.google.com/go/compute/apiv1

Hope that helps

**Comment by matthung0807** [comment]
@codyoss Thanks for your advice!

**Comment by matthung0807** [comment]
The problem is caused by passing the same requestId for creating CloudRouter, that's why I cannot create VLAN attachment without error.
