### ISSUE TITLE
Error 400 etag is different than the current person.etag

### ISSUE THREAD

**Issue by jcervantes-genially** [googleapis/google-api-go-client#1904]
I'm trying to update the users from my database. I already have the resource name, and as the documentation said, I need to get the etag to make an update. Then, I make `srv.People.Get(resourceName).PersonFields("names").Do()` to get the name and the etag of that user, and with that detail, call the `srv.People.UpdateContact(resourceName,&person).UpdatePersonFields("names,phoneNumbers,birthdays,biographies").Do()`
However, something I got the following error:  `Error 400: Request person.etag is different than the current person.etag. Clear local cache and get the latest person., failedPrecondition` but I make the process in order and it's not happening everytime.

This is part of my code:

```
func getEtag(resourceName string, srv *people.Service) (string, error) {

	user, err := srv.People.Get(resourceName).PersonFields("names").Do()
	if err != nil {
		return "", err
	}
	return user.Etag, nil

}

func UpdateGoogleContact(client entities.User, resourceName string, token *oauth2.Token, srv *people.Service) int {
	person.Etag = ""
	var etagErr error
	person.Etag, etagErr = getEtag(resourceName, srv)
	if etagErr != nil {
		log.Println(etagErr.Error())
		return 0
	}
	_, err := srv.People.UpdateContact(resourceName, &person).UpdatePersonFields("names,phoneNumbers,birthdays,biographies").Do()
	if err!=nil{
		log.Println (err.Error())
	}
	return 1
}
```

Should I do something different?

**Comment by quartzmo** [comment]
Hi @jcervantes-genially,

Can you modify your example to check if the `etag` value returned by `People.Get` is an empty string? If it is not, and you get the error, is there any chance some other process has updated the record concurrently?

**Comment by jcervantes-genially** [comment]
Yes, i can check the etag result, but, if is blank should I call again? wait 5 seconds? What should I do?

I not working in concurrency right now for the same reason.

Regards,

**Comment by quartzmo** [comment]
@jcervantes-genially Every time you update the record, the etag should change. So after updating the name, you need to be sure to read the new etag and use it to update the phone.

**Comment by jcervantes-genially** [comment]
Hi @quartzmo,

Yes, I request the etag everytime, however, my question is: If I make one update, how long should wait until the next update (and etag request).
Regards,

**Comment by jcervantes-genially** [comment]
Then, we can said this is the problem? I should wait to update the same record in a short period of time?

Regards,

**Comment by quartzmo** [comment]
I'm not certain what the problem is, but I believe it would be worthwhile to experiment with retry with incremental backoff and observe what happens.

**Comment by jcervantes-genially** [comment]
ok Thanks,
