### ISSUE TITLE
How to get `Tags` value for Storage Bucket

### ISSUE THREAD

**Issue by ParthaI** [googleapis/google-api-go-client#1920]
Dear team, we are using [this API](https://github.com/googleapis/google-api-go-client/blob/main/storage/v1/storage-gen.go#L4235) for listing out the available Buckets in the console.

This list API returns the `Label` information in the response.

But there is the property called `Tags` which is being displayed in the console but the [LIst](https://github.com/googleapis/google-api-go-client/blob/main/storage/v1/storage-gen.go#L4235)/[Get](https://github.com/googleapis/google-api-go-client/blob/main/storage/v1/storage-gen.go#L3573) API doesn't return this property.

Is there any other API call which will provide this information?

GCP Resource 
![image](https://user-images.githubusercontent.com/26873346/227199469-33cd9477-932c-49b4-a6cb-92fe2c8010ea.png)

Thanks!
Partha

**Comment by codyoss** [comment]
It is called Labels in the API. Both of those apis call return this info. Hope that helps.

**Comment by ParthaI** [comment]
@codyoss We are getting the value of `Lables` only as I have shown in the snap, but not the `Tags` value. `Tags` values are not coming under `Labels` property.
