### ISSUE TITLE
Regional network edge security policy cannot be defined

### ISSUE THREAD

**Issue by NoamGaloz** [googleapis/google-api-go-client#1921]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Is this a client library issue or a product issue? We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - Programming language: golang
  - OS:
  - Language runtime version:
  - Package version: v.0.81
#### Steps to reproduce

  1. create a new Network edge security policy - https://pkg.go.dev/google.golang.org/api@v0.81.0/compute/v1#SecurityPolicy
  2. define the field required for  Network edge security policy-
  policy := &compute.SecurityPolicy{
		Name: policyName,
		Type: "CLOUD_ARMOR_NETWORK",
		Region: "us-west1",
		DdosProtectionConfig: &compute.SecurityPolicyDdosProtectionConfig{
			DdosProtection: "ADVANCED",
		},
	}
3. call -
op, err := client.SecurityPolicies.Insert(project,policy).Context(ctx).Do()

you will get "Invalid value for field 'resource.type': 'CLOUD_ARMOR_NETWORK'. Network Security Policies must be regional."
But there is no way to define the Region. (Documentation says it 'Output Only' and Manuel creation required it)

Thanks!

**Comment by codyoss** [comment]
I think what you want is `client.RegionSecurityPolicies`. Hope that helps!
