### ISSUE TITLE
Google Sheet ID type is wrong: API return error 400 trying to create a Google Sheet

### ISSUE THREAD

**Issue by juanmiguelRuaDev** [googleapis/google-api-go-client#1933]
The Google API returns a 400 error when I am trying to create a Google Sheet with a specified `SheetId` through the `sheet.BatchUpdateSpreadsheetRequest` function. 

```go
v := sheets.BatchUpdateSpreadsheetRequest{
		Requests: []*sheets.Request{
			{
				AddSheet: &sheets.AddSheetRequest{
					Properties: &sheets.SheetProperties{
						Index:   1,
						Title:   "Custom name",
						SheetId: int64(3277956680),
					},
				},
			},
		},
	}
	_, err := srv.Spreadsheets.BatchUpdate(ssid, &v).Do()
```

The error is the following:

```
"Invalid value at 'requests[0].add_sheet.properties.sheet_id.value' (TYPE_INT32), 3277956680",
```
As you can see, the API response says the type of the sheet ID is `TYPE_INT32`however, the  [latest version of  the API](https://pkg.go.dev/google.golang.org/api@v0.116.0/sheets/v4#SheetProperties) specifies this field must be `int64`

**Comment by quartzmo** [comment]
@juanmiguelRuaDev Can you try `int32` to see if it works?

**Comment by codyoss** [comment]
Try not setting SheetId, you are already sending the sheet in the method call signature, and id should not be changed once set.

int64 is just the Go type, but int type information is not preserved when serialized to JSON so I am not sure how related that is. Also I think that number you are setting is outside of the range of an int32, right?

**Comment by juanmiguelRuaDev** [comment]
Hello @codyoss, Exactly. The sheet Id is outside of the range of an int32. In my case, I am explicitly creating the sheetId because I am generating a link to the sheet after the creation and sending it via email.

**Comment by juanmiguelRuaDev** [comment]
Hi @quartzmo, It does not work because of a compilation error:
`cannot use  (value of type int32) as int64 value in struct literalcompiler[IncompatibleAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#IncompatibleAssign)`

**Comment by noahdietz** [comment]
I have a feeling that this is an issue in the API or the infrastructure that does the HTTP transcoding during client request->server. I can't repro any issues with just the JSON library encoding an `int64` (i.e. downgrading it to an int32 somehow, or encoding it differently). The client only uses the plain, stdlib encoding APIs so its going to the service unaltered (perhaps print out the `Marhsal`'d request to verify?).

The only other course of action I can think of is to _not_ explicitly specify the `SheetId`, allow the service to _generate_ you an ID for that new `Sheet`. Then in the request, set `IncludeSpreadsheetInResponse: true`, and navigate the response to find the `SheetId` via `response.UpdatedSpreadsheet.Sheets.[n].SheetProperties.SheetId`. I'm not sure but my guess is that an added `Sheet` will be _appended_ to the existing list of `Sheet`s so perhaps its just about getting the last one in the list. From there you have the `SheetId` to generate a link with.

I'm not sure how much more we can help you here in the client repo though. You should consider opening an [issue here](https://issuetracker.google.com/issues/new?component=191608&template=823916).

**Comment by juanmiguelRuaDev** [comment]
Thank you very much @noahdietz. I'll open an issue there.
