### ISSUE TITLE
error when importing package  google.golang.org/api/content/v2.1

### ISSUE THREAD

**Issue by jhahspu** [googleapis/google-api-go-client#1934]
Hi,
I'm trying to connect my Go app to Google Merchant Content API.
When I run `go get google.golang.org/api/content/v2.1` I get the following error: `panic: internal error: can't find reason for requirement on github.com/golang/snappy@v0.0.1`

Go: 1.18
OS: W11

**Comment by quartzmo** [comment]
I could not reproduce this error:

```
➜  content118 go1.18 version
go version go1.18 darwin/amd64
...
go: creating new go.mod: module example.com/content118
➜  content118 go1.18 get google.golang.org/api/content/v2.1
go: added cloud.google.com/go/compute v1.19.0
go: added cloud.google.com/go/compute/metadata v0.2.3
go: added github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: added github.com/golang/protobuf v1.5.3
go: added github.com/google/uuid v1.3.0
go: added github.com/googleapis/enterprise-certificate-proxy v0.2.3
go: added github.com/googleapis/gax-go/v2 v2.8.0
go: added go.opencensus.io v0.24.0
go: added golang.org/x/net v0.8.0
go: added golang.org/x/oauth2 v0.6.0
go: added golang.org/x/sys v0.6.0
go: added golang.org/x/text v0.8.0
go: added google.golang.org/api v0.116.0
go: added google.golang.org/appengine v1.6.7
go: added google.golang.org/genproto v0.0.0-20230331144136-dcfb400f0633
go: added google.golang.org/grpc v1.54.0
go: added google.golang.org/protobuf v1.30.0
```

**Comment by quartzmo** [comment]
Some background: https://github.com/golang/go/issues/47979

**Comment by jhahspu** [comment]
@quartzmo my installed go version is 1.20, and my app's version is 1.18.

**Comment by codyoss** [comment]
Given that error message it sounds like you have a dep in your go.mod that does not need to be there. That is not a dep of this library so I believe the issue is with another dep you have. Try running `go mod tidy` to fixup before importing. Without a reproducer I don't think we can help further. Hope that helps.
