### ISSUE TITLE
LicenseAssignments.ListForProductAndSku always returns 200 items

### ISSUE THREAD

**Issue by zelda-rageux** [googleapis/google-api-go-client#1967]
Hello,

Every month I use the "google.golang.org/api/licensing/v1" API to create my customers's invoices.

I have a customer who has 299 Google Workspace Business Starter licenses and 1250 Google Workspace Enterprise Standard licenses.

My module makes three calls per execution, 1 for Stater licenses and two for Standard Enterprise licenses.

1 call: starterLic, err:= srv.LicenseAssignments.ListForProductAndSku("Google-Apps", "1010020027", customerID).MaxResults(300).Do()

2 call in a for loop with argument nextPageToken: enterpriseLic, err := srv.LicenseAssignments.ListForProductAndSku("Google-Apps", "1010020026", customerID).MaxResults(1000).PageToken(nextPageToken).Do()

Last month (first days of May) everything worked perfectly.

This month, calls systematically return 200 items with no value for the nextPageToken.

I checked my quota in the GCP project, it is 120 calls per minute for the "Enterprise License Manager API".

Nothing has changed in the module.

I have been running this module without having a problem for several years.

I used go 1.12 and 1.20 with the same result.

For my first uses I had not updated my dependencies.

For my following uses I updated my dependencies:
golang.org/x/oauth2 v0.0.0-20200902213428-5d25da1a8d43
google.golang.org/api v0.33.0

It doesn't change anything.

Thank you in advance for your help.

Best regards

**Comment by noahdietz** [comment]
Hey @zelda-rageux correct me if I'm wrong: It sounds like you haven't changed your code at all, nor have you changed the version of this module that you are using, but you are now experiencing a regression in the behavior of the API?

If that is the case, there isn't much I can do to help you here in the client repo, but I can't find a public issue tracker for the product to forward you to. So I will do what I can to find some support. A few clarifications though:

> Last month (first days of May) everything worked perfectly.

You mean `first days of April` right?

> 1 call: starterLic, err:= srv.LicenseAssignments.ListForProductAndSku("Google-Apps", "1010020027", customerID).MaxResults(300).Do()

Did this request only get 200? Or did it work as expected?

**Comment by noahdietz** [comment]
Thanks for reporting this @zelda-rageux , it will likely help others in the future. Sorry that you had to end up changing things on your end. If I hear anything back from the team, I will let you know here.
