### ISSUE TITLE
Unable to access secret from secret Manager When Workload Identity Enabled

### ISSUE THREAD

**Issue by raghvendra-dixit** [googleapis/google-api-go-client#1969]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Is this a client library issue or a product issue? We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - Programming language: golang
  - OS: We are using 
  - Language runtime version: go 1.18
  - Package version: 
  cloud.google.com/go/secretmanager v1.10.0
  google.golang.org/api v0.118.0

#### Steps to reproduce

  1. I used the simple client library given by google on : https://cloud.google.com/secret-manager/docs/reference/libraries#use
  2. I am able to access the secret setting/mounting GOOGLE_APPLICATION_CREDENTIALS path while mounting on pod init and using key.json.
  
  code ref : https://go.dev/play/p/7oNfjEEcohd
error, with workload identity enabled route and running on GKE:
`google: error getting credentials using well-known file (/dev/null/.config/gcloud/application_default_credentials.json): open /dev/null/.config/gcloud/application_default_credentials.json: not a directory"`

I did some debugging and tried to understand the flow for google client libraries and got to know, it follows a precedence order 
looking for GOOGLE_APPLICATION_CREDENTIALS , then checking the Default path depending on the OS system being used, $HOME in case of linux. 

Apart from this then i tried to modify the client and thought passing the scopeOptions could help or invoking it through NewRestClient code ref here : https://go.dev/play/p/SzirC1TERiZ
In this case i  get the error as :
`"GCP Secret Manager: GCPSMCClient.GetSecret failed with err: googleapi: Error 401: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.\nerror details: name = ErrorInfo reason = CREDENTIALS_MISSING domain = googleapis.com metadata = map[method:google.cloud.secretmanager.v1.SecretManagerService.AccessSecretVersion service:secretmanager.googleapis.com]"`

Additional Info:
- Role assigned to the Service account :
roles/iam.serviceAccountTokenCreator
roles/secretmanager.secretAccessor

- Annotation for binding of KSA to Google service account is also done properly.
`kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: GCP service account`
 - was able to successfully get default token by running curl - 
 `curl -v -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token` - 200 OK with token
 - I checked workload identity configuration was correct and i was able to get "<service-account-name>" response when running the curl from inside the pod : `curl -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/email`
  

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by codyoss** [comment]
This is an edge case that is not well handled in the oauth2 lib today. Made https://go-review.git.corp.google.com/c/oauth2/+/493695

**Comment by codyoss** [comment]
I am going to close this as the CL has been merged. You should be able to mitigate this issue now if you pull oauth2@HEAD. We will take the dependency bump once a new version of that library is published. Thanks for the report!

**Comment by raghvendra-dixit** [comment]
Thanks @codyoss , will test with GKE and see if it works, I will update the comment thread accordingly.
Thanks for your prompt help and investigating the issue.
