### ISSUE TITLE
redis: `redisConfig` not updatable althought the documentation says it is.

### ISSUE THREAD

**Issue by lcguida** [googleapis/google-api-go-client#1983]
Althought the [documentation says](https://cloud.google.com/memorystore/docs/redis/reference/rest/v1/projects.locations.instances/patch#query-parameters) that `redisConfig` is a possible value on the update mask, an update is failing with the following message: 

```
com.google.apps.framework.request.StatusException: <eye3 title='INVALID_ARGUMENT'/> generic::INVALID_ARGUMENT: Invalid option 'redis_config': 'redis_config' cannot be updated on existing instances.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "Invalid value: redis_config",
        "field": "update_mask.paths.0"
      }
    ]
  }
]
, badRequest
```

#### Environment details

  - Programming language: Golang
  - OS: MacOS (Ventura 13.3.1)
  - Language runtime version: go 1.20
  - Package version: 0.122.0

#### Steps to reproduce

  1. Create a redis instance on memory store
  2. Try to update the instance with `redisConfig`
  
  ```golang
ctx := context.Background()
client, _ := redis.redis.NewService(ctx)
instance :=  &redis.Instance{
    MemorySizeGb: 5, 
    RedisConfigs: map[string]string{
        "maxmemory-gb":  "4",
    },
}
_, err  := client.Projects.Locations.Instances.Patch("path/to/instance", instance).UpdateMask("redisConfig,memorySizeGb").Do()
if err != nil {
    log.Fatal(err)
}
  ```

**Comment by quartzmo** [comment]
I wonder if this is a typo in the documentation for `patch`: It lists the field name as `redisConfig`, when in the [Instance documentation](https://cloud.google.com/memorystore/docs/redis/reference/rest/v1/projects.locations.instances#Instance) it is clearly listed as `redisConfigs`. Can you try changing the value in your `UpdateMask` to `redisConfigs` to see if that works?

In any case, this type of issue is almost certainly not related to this client library, which is auto-generated from the API specification. Please file an issue in the product issue tracker if there is not one already (I looked but did not see one): https://issuetracker.google.com/savedsearches/5169231. All cloud issue trackers can be found at https://cloud.google.com/support/docs/issue-trackers .

**Comment by lcguida** [comment]
I can confirm that `redisConfigs` with a `s` works properly. I will open the PR with them, instead. Thanks for pointing that out.
