### ISSUE TITLE
Getting: The requested URL /v1beta/297349982:runReport was not found on this server. That’s all we know. When using the analytics v1 beta library

### ISSUE THREAD

**Issue by DaanvandeHaar** [googleapis/google-api-go-client#1997]
#### Environment details

  - Programming language: Go
  - OS: Windows 11
  - Language runtime version: 1.19
  - Package version: google.golang.org/api v0.124.0 /analyticsdata/v1beta 

#### Steps to reproduce

 1:
 ```
//main.go

	analyticsServiceAPI, err := googleAnalytics.NewService(context.Background(), option.WithCredentialsFile("env/google_analytics.json"))

    analyticsService = analyticsInternal.NewService(*analyticsServiceAPI)
        
//analytics.Servicego
    ga "google.golang.org/api/analyticsdata/v1beta"

	r, err := s.a.Properties.BatchRunReports("297349982", &ga.BatchRunReportsRequest{
		Requests: []*ga.RunReportRequest{{
			DateRanges: []*ga.DateRange{
				{StartDate: "7daysAgo", EndDate: "today"},
			},
			Metrics: []*ga.Metric{
				{Expression: "ga:sessions"},
			},
			Dimensions: []*ga.Dimension{
				{Name: "ga:country"},
			},
		}},
	}).Do()

	if err != nil {
		return 0, err <--- Err
	}
```
  2. 
  ```
Err: 404. That’s an error. The requested URL /v1beta/297349982:batchRunReports?alt=json&prettyPrint=false was not found on this server. That’s all we know.
```

**Comment by noahdietz** [comment]
I think that the `property` argument has a format like `properties/{your id}`. So provide it as as `"properties/297349982"` instead:
```go
r, err := s.a.Properties.BatchRunReports("properties/297349982", &ga.BatchRunReportsRequest{
...
```

The [docs](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/batchRunReports?apix_params=%7B%22property%22%3A%22properties%2F297349982%22%2C%22resource%22%3A%7B%7D%7D) indicate that the segment has a pattern of `properties/*`. The [GoDoc for the method](https://pkg.go.dev/google.golang.org/api/analyticsdata/v1beta#PropertiesService.BatchRunReports) also includes such an example at the very end of the description. Kind of hard to see if you aren't looking for it.

**Comment by DaanvandeHaar** [comment]
That did the trick! Thanks for the help.
