### ISSUE TITLE
CseListCall.Start documentation is incorrect

### ISSUE THREAD

**Issue by PhiloEpisteme** [googleapis/google-api-go-client#2025]
The documentation for CseListCall.Start states that Start sets the index of the first result to return. It further explains that a value of 11 would instruct the results to start at the top of page 2 (assuming 'num' is the default of 10). Then, it closes by stating that the API will never return more than 100 results and that "setting the sum of `start` + `num` to a number greater than 100 will produce an error.". This seems to be in error. From a logical perspective, a user who wishes to get 100 total results must set start=91 and num=10 in order to get the last 10 results. Testing confirms that the documentation does not match the behavior of the endpoint, setting start=91 and num=10 does _not_ result in an error despite their sum being greater than 100.

#### Environment details

  - Programming language: go
  - OS: *
  - Language runtime version: *
  - Package version: v0.127.0

#### Steps to reproduce

  1. Submit a custom search request call, for example something like the following
 ```
cse, _ := customsearch.NewService(ctx, option.WithAPIKey(key))
_, err := cse.List().Cx(cx).Num(10).Q("google").Start(91).Do()
```
  2. Expect that the error above is not nil, but it is.

**Comment by noahdietz** [comment]
Hey @PhiloEpisteme so this documentation is pulled directly from the API itself and is not a client-side feature. This client is entirely auto-generated and does not do any client-side validation of this nature.

The documentation you mentioned is also here on the general API reference docs: https://developers.google.com/custom-search/v1/reference/rest/v1/cse/list

Unfortunately, we cannot help you from this repo. This will have to change in the service itself.

I would recommend browsing https://support.google.com/programmable-search for info or posting in the community linked from there.
