### ISSUE TITLE
Support for video chapters

### ISSUE THREAD

**Issue by LennartOschika** [googleapis/google-api-go-client#2036]
##Lacking feature
As far as I know there is currently no way to get the chapters of a video. 
Considering it has been like 3 years (that is the earliest mention of it I could find with my 2 second google search) it is more than due for it to be added. 

##Ideal solution
The VideosListCall should have another parameter that is possible in the urlParams.
Similar to "snippet" or "contentDetails", there could be another option called "chapters" or "videoChapters" that just returns a list of chapters.

##Alternatives to this solution
There could be some hacky way scraping the website to get this information. However, besides there being 2 ways of adding chapters as a creator, the description and in the creator studio, it is way easier to have a simple access through this API.

I tried seeing if this is something that is just missing in this documentation with the endpoint existing, but I could not find anything trying different names for it.

**Comment by codyoss** [comment]
Hey, this repository just holds generated code from the spec provided by the service. If you have a feature request for the API itself I suggest you reach out on the corresponding APIs support page. I assume you are talking about youtube here so this may be the page you are looking for: https://developers.google.com/youtube/v3/support. Hope that helps get you going in the correct direction.
