### ISSUE TITLE
DialPool ConnPool Implementation 

### ISSUE THREAD

**Issue by kevjumba** [googleapis/google-api-go-client#2071]
Hi,
I am trying to create a dial connection to a grpc endpoint with multiple different connections in a pool. Seems like the only way to do this is via DialPool.

2 things that don't make sense to me.
1. The ConnPool interface says it doesn't ever return a connection to the pool? So we're just creating unlimited connections? What's the point of the pool?
2. I would like to create a client based on the pool but I don't want to create a new client everytime i grab a new connection. Does creating a new client cause extra overhead or is that the correct way to do this. Is there a way to create a client that just uses the pool?
```
conn := connectionPool.Conn()
client := pb.newClient(conn) // If this happens for every request, this has to be a lot of overhead to garbage collect.
```
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by quartzmo** [comment]
> I would like to create a client based on the pool

Which client do you specifically intend to use?

**Comment by quartzmo** [comment]
Rather than using the lower-level "pb" client directly, can you use a client from https://github.com/googleapis/google-cloud-go instead? These ready-to-use clients have the grpc connection pool built in.

**Comment by quartzmo** [comment]
Please re-open if you can provide more information.
