### ISSUE TITLE
Improve GCE detection by checking Google hardware

### ISSUE THREAD

**Issue by TimurSadykov** [googleapis/google-api-go-client#2117]
Current detection has elevated false-negative rate in certain environments and cause unrecoverable errors. To improve that we add a static detection of Google hardware.

Implement the stage 1 proposal per [go/auth-library-noping](http://go/auth-library-noping)

**Comment by codyoss** [comment]
It seems like this got dropped. For many years Go has had the SMIBIOS check for linux, but we still need the check for Windows. We will get this scheduled soon.

**Comment by quartzmo** [comment]
> Package wmi provides a WQL interface for WMI on Windows.

https://github.com/yusufpapurcu/wmi

**Comment by quartzmo** [comment]
DotNet implementation: https://github.com/googleapis/google-api-dotnet-client/blob/main/Src/Support/Google.Apis.Auth/OAuth2/ComputeCredential.cs#L442-L466
