### ISSUE TITLE
Generated compute file is too large for most tooling.

### ISSUE THREAD

**Issue by briantkennedy** [googleapis/google-api-go-client#2124]
The generated compute API source is too large for most tooling.  [GitHub](https://github.com/googleapis/google-api-go-client/blob/main/compute/v1/compute-gen.go) shows a message that you can only view raw content.  Other code browsers have similar issues.

Given that all files in a directory are considered part of the same package, it should be technically possible to split the generated file into several smaller ones while maintaining backwards compatibility.

**Comment by codyoss** [comment]
Responded directly. Closing.
