### ISSUE TITLE
Remove process for appengine

### ISSUE THREAD

**Issue by komem3** [googleapis/google-api-go-client#2128]
**Is your feature request related to a problem? Please describe.**

When deploying to Appengine, I get the following warning even though the source does not use the Appengine API. This may be due to the fact that this package depends on the appengine api.

```sh
Beginning deployment of service [default]...
╔════════════════════════════════════════════════════════════╗
╠═ Uploading 20 files to Google Cloud Storage               ═╣
╚════════════════════════════════════════════════════════════╝
File upload done.
WARNING: There is an indirect dependency on App Engine APIs, but they are not enabled in your app.yaml. You may see runtime errors trying to access these APIs. Set the app_engine_apis property.

```

```sh
go mod why google.golang.org/appengine
# google.golang.org/appengine
# remove my repository
cloud.google.com/go/secretmanager/apiv1
google.golang.org/api/transport/grpc
google.golang.org/appengine
```

**Describe the solution you'd like**

I want you to remove for appengine process that uses appengine build tag.

https://github.com/search?q=repo:googleapis/google-api-go-client%20google.golang.org/appengine&type=code

**Describe alternatives you've considered**

These files seem to be processed for appengine, but this build tag does not seem to be used by 2gen. If it is really not used, then this process is not working in 2gen. 
If this repository is only supported by 2gen, then it seems safe to delete the file.

https://github.com/golang/oauth2/issues/334

**Comment by quartzmo** [comment]
@komem3 Thank you for reporting this issue. We will investigate if these files can be removed.

**Comment by quartzmo** [comment]
Good news, we confirmed with the App Engine team that both `google.golang.org/appengine/socket` and `google.golang.org/appengine/urlfetch` packages are no longer to be used in the App Engine Go second generation runtime (>= Go 1.11). I will proceed now with a PR to remove the conditionally-built hook code.
