### ISSUE TITLE
Insufficient authentication scopes error while using siteverification.googleapis.com

### ISSUE THREAD

**Issue by vishnugth** [googleapis/google-api-go-client#2129]
I'm trying to use the `google.golang.org/api/siteverification/v1` package for site verification. For some reason, I'm getting access scope errors. As per the https://pkg.go.dev/google.golang.org/api/siteverification/v1#hdr-Other_authentication_options it uses the ADC by default and uses all available scopes. Am I doing something wrong below?

- What code you've already tried
```go
package main

import (
	"context"
	"fmt"
	"log"

	"google.golang.org/api/option"
	"google.golang.org/api/siteverification/v1"
)

func main() {
	siteverificationService, err := siteverification.NewService(context.Background(), option.WithScopes(siteverification.SiteverificationScope))
	if err != nil {
		log.Fatal(err)
	}
	resp, err := siteverificationService.WebResource.List().Do()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(resp)
}

```
- Any error messages you're getting
```console
2023/09/01 12:08:48 googleapi: Error 403: Request had insufficient authentication scopes.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "googleapis.com",
    "metadata": {
      "method": "security.irdb.api.VerificationService.List",
      "service": "siteverification.googleapis.com"
    },
    "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT"
  }
]

More details:
Reason: insufficientPermissions, Message: Insufficient Permission
```

**Comment by quartzmo** [comment]
@vishnugth

1. If you remove the `WithScopes` option, and use just `siteverification.NewService(context.Background())`, do you get the same error?
2. What auth method are you using with ADC? From the error message, it appears that your auth token is missing the needed scopes.

**Comment by vishnugth** [comment]
Hi @quartzmo 

> If you remove the WithScopes option, and use just siteverification.NewService(context.Background()), do you get the same error?

Yes, I get the same error.

```
2023/09/07 12:45:52 googleapi: Error 403: Request had insufficient authentication scopes.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "googleapis.com",
    "metadata": {
      "method": "security.irdb.api.VerificationService.List",
      "service": "siteverification.googleapis.com"
    },
    "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT"
  }
]

More details:
Reason: insufficientPermissions, Message: Insufficient Permission
```

> What auth method are you using with ADC? From the error message, it appears that your auth token is missing the needed scopes.

Here are the steps I followed.

- I ran `gcloud auth application-default login` command which created the credentials file under the default location `~/.config/.config/gcloud/application_default_credentials.json`
- I ran the go snippet.


Will this function `siteverification.NewService(context.Background())` take care of getting the auth token?

**Comment by vishnugth** [comment]
@quartzmo Thanks for the response. As you mentioned the token was missing the needed scope.

```shell
gcloud auth application-default login \
--scopes "openid,https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/sqlservice.login,https://www.googleapis.com/auth/siteverification,https://www.googleapis.com/auth/accounts.reauth"
```
