### ISSUE TITLE
How can i parse error from `q.Run(req)` with failed Oauth2?

### ISSUE THREAD

**Issue by amantiwari1** [googleapis/google-api-go-client#2208]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do

I am trying to get status code and error message from err variable
  
 Err.Error() look like
 ```
Post "https://bigquery.googleapis.com/bigquery/v2/projects/super-hide/jobs?alt=json&prettyPrint=false": oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Invalid grant: account not found"}
```
  
- What code you've already tried

I tried two struct which this library provide 

```golang
res, err := q.Run(res)
if err != nil {
var e *googleapi.Error
if ok := errors.As(err, &e); ok {}
}
```

```golang
res, err := q.Run(res)
if err != nil {
var e *googleapi.Error
if ok := errors.As(err, &e); ok {}
}
```
Both didn't work because both ok are said false 

- Any error messages you're getting
 no error

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by quartzmo** [comment]
Hi @amantiwari1, 

Please take a look at the examples here: https://pkg.go.dev/google.golang.org/api#hdr-Inspecting_errors

**Comment by quartzmo** [comment]
I tested this myself just now:

```go
	rs, err := rq.Do()

	if err != nil {
		var aErr *googleapi.Error
		if errors.As(err, &aErr) {
			fmt.Printf("Message: %s\n", aErr.Message)
			fmt.Printf("Status: %d\n", aErr.Code)
		}
	}
```

Output:

```
Message: Request contains an invalid argument.
Status: 400
```

**Comment by quartzmo** [comment]
The example I posted above is for the libraries in this repo. However, for BigQuery, I recommend using https://pkg.go.dev/cloud.google.com/go/bigquery instead of the BigQuery client in this repo.
