### ISSUE TITLE
Integrate google ads into GUI app ?

### ISSUE THREAD

**Issue by SAXN-SYNX** [googleapis/google-api-go-client#2272]
- Trying to work with golang and fyne GUI . (Cross platform)
-  There isn't too many example code to get the ad banner from  ad_unit_ID

Can i get a simple example code to add a banner into a GUI framework ?

**Comment by quartzmo** [comment]
@SAXN-SYNX I think your request is beyond the scope of the client libraries in this project. However, if you want to provide more details relating to how you want to use these client libraries, please do so and re-open this issue, thanks!
