### ISSUE TITLE
androidpublisher/v3 RegionalSubscriptionOfferPhaseConfig missing field 

### ISSUE THREAD

**Issue by zhulingbiezhi** [googleapis/google-api-go-client#2273]
[regionalsubscriptionofferphaseconfig](https://developers.google.com/android-publisher/api-ref/rest/v3/monetization.subscriptions.basePlans.offers?hl=zh-cn#regionalsubscriptionofferphaseconfig)Could you please check the structure "regionalsubscriptionofferphaseconfig" in the `SubscriptionOfferPhase` of the `google.golang.org/api/androidpublisher/v3` library? It seems that the "free" object is missing, which is an important identifier used to mark subscription free trials. 

You can find more information about `regionalsubscriptionofferphaseconfig` in the [official documentation](https://developers.google.com/android-publisher/api-ref/rest/v3/monetization.subscriptions.basePlans.offers?hl=zh-cn#regionalsubscriptionofferphaseconfig).

**Comment by codyoss** [comment]
It is not listed in the schema for this API: https://github.com/googleapis/google-api-go-client/blob/b1c45c2251d9c3d524d7ca0170d5becfda31b1d5/androidpublisher/v3/androidpublisher-api.json#L6487-L6510. These are generated client libraries from the public spec. I filed an internal bug and get back to you if I hear more: 312707405

**Comment by zhulingbiezhi** [comment]
Thank you for your prompt reply. I greatly appreciate your timely response and I am eagerly awaiting your reply.

**Comment by zhulingbiezhi** [comment]
Do you have any updates? I'm feeling a bit confused.

**Comment by codyoss** [comment]
Seems like the type exists now: https://pkg.go.dev/google.golang.org/api/androidpublisher/v3#RegionalSubscriptionOfferPhaseConfig
