### ISSUE TITLE
Firebase remote config fetching has different implementation compared with other languages

### ISSUE THREAD

**Issue by mariusSincovici** [googleapis/google-api-go-client#2274]
Hi,

I've saw that for [objective-c](https://github.com/firebase/firebase-ios-sdk/blob/bbd2d098fb42a726c8d067cfa3aa58b26d0c8dc4/FirebaseRemoteConfig/Sources/RCNConfigFetch.m#L615)  and [c++](https://github.com/firebase/firebase-cpp-sdk/blob/42b57ecd524641c717c9bb3dca658b6697b0b4dd/remote_config/src/desktop/rest.cc#L108) the remote config are fetched differently, compared with the [go implementation](https://github.com/googleapis/google-api-go-client/blob/v0.151.0/firebaseremoteconfig/v1/firebaseremoteconfig-gen.go#L449). This results in different URLs:
* go: `https://firebaseremoteconfig.googleapis.com/v1/PROJECT_ID/remoteConfig`
* obj-c or c++: `https://firebaseremoteconfig.googleapis.com/v1/projects/<id>/namespaces/<id>:fetch?<params>`

As far as I can see this also results in different ways how the data is obtained by, in go is `read` and others `fetch` requests.
Ar there any plans to have the same implementation in go and to support `fetch`?

Thanks

**Comment by codyoss** [comment]
The Go firebaseremoteconfig has not been generated from a new discovery doc in many years it seems. We only regenerate libraries for things that show up in the public listing of APIs, which this one no longer does it seems: https://www.googleapis.com/discovery/v1/apis. 

I have filed an internal bug and report back if I hear anything: 312704899

**Comment by codyoss** [comment]
@mariusSincovici Out of curiosity could you share a little bit about your use case and what sort of environment you are trying to call this from. For example backend server or mobile.

**Comment by mariusSincovici** [comment]
Thanks for your feedback.
We are using it from a Linux desktop application. 
The problem is that using the GO version we are hitting the quota limits for `read`(even if we have some basic caching to limit the request). The other mobile apps don't have this problem because `fetch` is used, and the limits for that are much higher.

**Comment by jklinger-ltq** [comment]
@codyoss is there already an update from the internal ticket? I also just noticed that the "valueType" field is not included in RemoteConfigParameter struct, which leads to all entries being saved as string, instead of respecting the valueType that is set (e.g. boolean). Probably this is also being caused by the library not being regenerated for several years.
Should I create another issue for this?

**Comment by codyoss** [comment]
I think the best thing to do at this point is likely open an issue on the API teams issue tracker. I don't think there is much I can do from here besides be a relay unfortunately. Here is a link to their support page: https://firebase.google.com/support/troubleshooter/report

If you do open an issue please share it here and I can make sure the original internal bug I filed gets properly linked.

**Comment by mariusSincovici** [comment]
I've created a ticket: `10272887`.
thanks

**Comment by mariusSincovici** [comment]
hi @codyoss,
I'm a bit lost on this one and maybe you can help :).

The customer support responded to the ticket and said that there is no SDK in go for clients, but only the Admin SDK. Also only https://firebase.google.com/docs/libraries are the official libraries. Plus they didn't knew about this repo.

So do you know what is with this repo? Is this to use for client apps written in go or it is just an unmaintained repo that should not be used anymore?
Thanks
