### ISSUE TITLE
Unable to publish custom app throwing Error 401: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential 

### ISSUE THREAD

**Issue by srinuu7878** [googleapis/google-api-go-client#2285]
<?php
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
error_reporting(E_ALL);
require __DIR__ . '/vendor/autoload.php'; // Path to the Google API PHP client library
session_start();

		$devAccountId = '6387507453241171720';
        $apkPath = '/opt/bitnami/apache/htdocs/mdm.apk';
        $clientSecretsJson = '/opt/bitnami/apache/htdocs/createapp/Auth_2_credintials.json';
		$scope = 'https://www.googleapis.com/auth/androidpublisher';
		

		$client = new Google_Client();
		$client->setAuthConfig($clientSecretsJson);
		$client->addScope($scope);
   if (isset($_GET['code'])) {
	   $token = $client->fetchAccessTokenWithAuthCode($_GET['code']);
	                     
       $client->getAccessToken($token);
	   $accessToken = $token['access_token'];
	   	   print_r($accessToken);
		
       $app = new Google_Service_Playcustomapp($client);
	   
	   $customApps = $app->accounts_customApps;
	   print_r("Custom accountsstart");
	   print_r($customApps);
	   print_r("Custom accountsstart");
		$customApp = new Google_Service_Playcustomapp_CustomApp();
		$customApp->setTitle('VR Doctors Academy');
		$customApp->setLanguageCode('en_US');
		$customApp->setOrganizations([
									  "organizationId"=> "LC04bt87ss",
									  "organizationName"=> "Prabhak Client-3"
									]);
		$customApp->setPackageName('com.prabhaktech.app'); 
		
		$resp = $customApps->create($devAccountId,$customApp,array("data"=> file_get_contents($apkPath)));

print_r($resp);
   } else {
	   if (isset($_GET['access_token']) && $_GET['access_token']) {
            $client->setAccessToken($_SESSION['access_token']);
        } else {
			echo ("access_token token not availanle \n");
			
        header('Location: ' . filter_var('https://accounts.google.com/o/oauth2/v2/auth?response_type=code&access_type=online&client_id=669680446239-hvb767pgheo3rjubv5h7vcb5ufput0kg.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fmdm.prabhaktech.com%2Fcreateapp%2Fcustomapp.php&state&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fandroidpublisher&approval_prompt=auto', FILTER_SANITIZE_URL));
               }
   }

?>

**Comment by srinuu7878** [comment]
cab some one help me on this, blocked we are working on this from 7 days but till now we did not any solution

**Comment by codyoss** [comment]
This looks similar to #2281. This library is written in Go so I don't think I can be of much help. If you have a support contract I suggest reaching out through that for faster assistance. Again though, I suggest reaching out to the PHP library you are using and having issues with.
