### ISSUE TITLE
content v2.1 create new region

### ISSUE THREAD

**Issue by aaronwow** [googleapis/google-api-go-client#2299]
I tried to create region in merchant center with content v2.1 API, the regionId already included in http body, but always got same error:
```
Failed to create region: googleapi: Error 400: [regionId] Required parameter: regionId
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "global",
    "reason": "required"
  }
]
, badRequest
```

Belowing is the code:
```
func main() {
	ctx := context.Background()

	service, err := content.NewService(ctx, option.WithCredentialsFile("./content-api-key.json"))
	if err != nil {
		log.Fatalf("Failed to create service: %v", err)
	}

	newRegion, err := service.Regions.Create(merchantId, &content.Region{
		DisplayName: "Test",
		MerchantId:  merchantId,
		PostalCodeArea: &content.RegionPostalCodeArea{
			RegionCode: "AU",
			PostalCodes: []*content.RegionPostalCodeAreaPostalCodeRange{
				{Begin: "2000", End: "2010"},
			},
		},
		RegionId:                  "Test",
		RegionalInventoryEligible: true,
		ShippingEligible:          true,
		ForceSendFields:           []string{"RegionId"},
	}).Do()
	if err != nil {
		log.Fatalf("Failed to create region: %v", err)
	}
	log.Printf("Created region: %v", newRegion.DisplayName)
}
```

**Comment by quartzmo** [comment]
https://developers.google.com/shopping-content/reference/rest/v2.1/regions/create

**Comment by quartzmo** [comment]
https://pkg.go.dev/google.golang.org/api@v0.153.0/content/v2.1#RegionsService.Create

**Comment by quartzmo** [comment]
@aaronwow Thanks for reporting this issue. It appears that the `regionId` query param shown in the [API docs](https://developers.google.com/shopping-content/reference/rest/v2.1/regions/create) is not present in the `Create` RPC method ([package docs](https://pkg.go.dev/google.golang.org/api@v0.153.0/content/v2.1#RegionsService.Create)).

I'm busy with urgent deliverables this week, but will look into this when things slow down later this month.

**Comment by aaronwow** [comment]
Thank you for pointing that out, I can temporarily add that param in request on my side. Take your time.

**Comment by codyoss** [comment]
Must be set with: https://pkg.go.dev/google.golang.org/api@v0.153.0/content/v2.1#RegionsCreateCall.RegionId

**Comment by aaronwow** [comment]
> Must be set with: https://pkg.go.dev/google.golang.org/api@v0.153.0/content/v2.1#RegionsCreateCall.RegionId

Thank you
