### ISSUE TITLE
Allow client monitoring to access the invoked method ID

### ISSUE THREAD

**Issue by devnev** [googleapis/google-api-go-client#232]
We use an http client that tracks all outgoing HTTP requests in metrics and tracing. However, the request path is unsuitable for metrics as it contains various names and IDs. I've forked and extended this library to add the method ID to the context, see https://github.com/google/google-api-go-client/compare/master...improbable-io:methodidctx?expand=1

This seems to be useful, it would be great if something of the sort could be included by default.

**Comment by jba** [comment]
We try to avoid adding things to the context. On the other hand, I can't think of a better way to do this. 

@zombiezen, any ideas?

**Comment by zombiezen** [comment]
I haven't thought about this for too long, but this seems like a legitimate use of a Context value to me in that it's plumbing a value through multiple layers not controlled by the library into outbound logic.  I'd be a bit worried if anything else other than a RoundTripper tried to use this Context value, but I can't see a way to restrict that.

**Comment by devnev** [comment]
The only alternatives to directly passing it in context that I can see would be to either
a) Provide a callback that would allow it to be placed into the context. This callback would probably have to return a new context, all of which seems very convoluted for just passing through the method id.
b) Put it in a header instead. Changing the request itself for this feature seems a bit odd though.

**Comment by Helcaraxan** [comment]
@zombiezen @jba Friendly ping on this issue?

The maintenance of the fork w.r.t the upstream is quite difficult (or nearly impossible as we can't seem to regenerate the source with the `Makefile` script or other means). I would be more than happy to contribute to upstream the feature once we can agree on the how.

**Comment by jba** [comment]
Now that [OpenCensus](https://godoc.org/go.opencensus.io) is available, we should add OpenCensus tracing to the code generator. I'll prepare a CL.

**Comment by jba** [comment]
What do you all think of https://code-review.googlesource.com/#/c/google-api-go-client/+/21330?

The span names will look like `google.golang.org/api/storage/v1:storage.objects.update`.

**Comment by devnev** [comment]
Looking through the opentracing library, I'm not quite sure how I would extract the span name that your are setting in that CL so that I could use it in a prometheus metric. The name itself seems overly verbose and oddly formatted (why the switching between slashes, colon and dot as separators? what are the parts supposed to mean?) but at least it's unique.

**Comment by zombiezen** [comment]
@rakyll Is it possible/desirable to extract a span's name?

@jba I think we probably also want to place this information in a Context value with a structured accessor — one that separates the target and the method ID.

**Comment by jba** [comment]
OK, I did [tracing](https://godoc.org/go.opencensus.io/trace) but you want [stats](https://godoc.org/go.opencensus.io/stats). I'd like to do that with OpenCensus too. I'll explore how to do that. There is already a [Prometheus exporter](https://godoc.org/go.opencensus.io/exporter/stats/prometheus) so once I add the metrics it should be straightforward to collect them.

What metrics would you like to see?

**Comment by devnev** [comment]
Looking at the opencensus prometheus exporter, it uses its own prometheus registry and only exposes ServerHTTP, so we it would not be included in a metrics page serving the default prometheus registry. Why does it need a custom registry? Could it be extended so we can include it in the default registry and thus the same metrics page as other metrics?

Regarding metrics, we're mainly interested in per-method completion and error counters.

**Comment by jba** [comment]
I'm going to aim for [these metrics](https://godoc.org/go.opencensus.io/plugin/grpc/grpcstats) or a subset thereof.

**Comment by jba** [comment]
@devnev Sorry, it appears that I've ignored your comment, but I simply didn't see it (stale browser window?).  I will include those metrics.

@rakyll will be able to address the prometheus question.

**Comment by jba** [comment]
Take another look at https://code-review.googlesource.com/c/google-api-go-client/+/21330. It now includes stats. The test file demonstrates how to write an exporter, in case the existing ones don't fit your needs.

**Comment by jadekler** [comment]
Looks resolved to me. Closing.
