### ISSUE TITLE
Memory leak in v0.154.0

### ISSUE THREAD

**Issue by songjiaxun** [googleapis/google-api-go-client#2321]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Is this a client library issue or a product issue? We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - Programming language: golang
  - OS: `gcr.io/distroless/base-debian11` image
  - Language runtime version: debian11
  - Package version: [v0.154.0](https://github.com/googleapis/google-api-go-client/releases/tag/v0.154.0)

#### Steps to reproduce

In the [GKE GCS FUSE CSI driver](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/tree/main) project, the `google.golang.org/api` package is used to communicate with the GCS storage API. We found that the feature [feat(transport): add OpenTelemetry context propagation](https://github.com/googleapis/google-api-go-client/pull/2127) might introduce a memory leak.

In our project, we are using `go.opentelemetry.io/otel v1.21.0`, which is the same version [this repo is using](https://github.com/googleapis/google-api-go-client/blob/main/go.mod#L32C2-L32C34).

In our stress test, we found that the `otelgrpc.newConfig` for some reason cannot be cleaned up from the heap. Please see the heap profiling result:

![Bm3NwNiaSiquXso](https://github.com/googleapis/google-api-go-client/assets/31323106/dc9ae71f-db2a-43ff-89d0-bd6e217ae0bf)

As a result, our application memory consumption grows unlimitedly over the time:

![B3VcQdXrEaBoHvF](https://github.com/googleapis/google-api-go-client/assets/31323106/4a7e43f6-b52a-4682-bbd9-e78b3fe8204d)

After we reverted the `google.golang.org/api` package version back to `v0.153.0`, the memory usage went back to normal:

![4WKdJWnQKzVTaJE](https://github.com/googleapis/google-api-go-client/assets/31323106/4734f4e0-b3b3-4771-9b7e-5026f4e29575)

I will DM you for the detailed reproducing and profiling steps.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by codyoss** [comment]
This looks likely like the same issue described here: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4226 .
