### ISSUE TITLE
Unable to create a copy of a presentation using drive client

### ISSUE THREAD

**Issue by nivalderramas** [googleapis/google-api-go-client#2334]
I'm trying to create a copy of a slide using a drive client. First I get the original file, then modify the title and assign a generated id, and execute the copy request. But I get an `generatedIdNotSupported` error. (Ommited error handling for simplicity) 
```
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"

	"golang.org/x/oauth2"
	"google.golang.org/api/drive/v3"
	"google.golang.org/api/option"
)

func main() {
	ctx := context.Background()

	googleCredentials, err := os.ReadFile("tkn.json")
	if err != nil {
		log.Fatalf("error reading token \n %s \n", err)
	}

	driveService, err := drive.NewService(ctx, option.WithCredentialsJSON([]byte(googleCredentials)))
	if err != nil {
		log.Fatalf("error creating drive service \n %s \n", err)
	}

	presentation, err := driveService.Files.Get(masterPresentationLayoutsID).Do()
	if err != nil {
		log.Fatalf("error retrieving presentation \n %s \n", err)
	}

	log.Printf("Success getting slides %s", presentation.Name)

	generatedIds, err := driveService.Files.GenerateIds().Do()
	if err != nil {
		log.Fatalf("error generating id \n %s \n", err)
	}

	presentation.Id = generatedIds.Ids[0]

	newPresentation, err := driveService.Files.Copy(idFileToCopy, presentation).Do()
	if err != nil {
		log.Fatalf("error copying file \n %s \n", err)
	}

	log.Printf("Sucess copying %s", newPresentation.Id)
}
```

Output is:
```
2024/01/05 14:28:26 error copying file 
 googleapi: Error 403: Generated IDs are not supported for Docs Editors formats., generatedIdNotSupported 
```

**Comment by quartzmo** [comment]
@nivalderramas Hi, can you please provide more complete code examples including imports? Please also provide a sample for the `v2` client that works, along with expanded version of the example above that errors. Thanks!

**Comment by nivalderramas** [comment]
@quartzmo  Hi, thanks for your response, I've updated the issue with a complete code sample, that fails. 
I don't have the v2 code version at hand but I reflecting on that I think it's not relevant to what I'm trying to achieve here.

**Comment by nivalderramas** [comment]
Well, I got my error. 
The second parameter of the method `Copy` expects only metadata to be changed (such as the name and parent folder). 
I think documentation is not clear in this regard. btw thanks. I hope this new entry helps someone
