### ISSUE TITLE
Unable to patch false values for sqladmin.Settings{} due to json encoding omitting zerovalues

### ISSUE THREAD

**Issue by scottnemes-branch** [googleapis/google-api-go-client#2347]
#### Environment details

  - Programming language: Go
  - OS: macOS Sonoma 14.2.1
  - Language runtime version: go1.21.5
  - Package version: v0.156.0

#### Steps to reproduce

  1. Provision a CloudSQL MySQL 8.0 Instance with deletion protection enabled
  2. Run the below code to attempt to disable deletion protection

```
package main

import (
	"golang.org/x/net/context"
	sqladmin "google.golang.org/api/sqladmin/v1beta4"
)

func main() {
	project := "<your project id>"
	instance := "<your instance id>"

	ctx := context.Background()
	sqladminService, err := sqladmin.NewService(ctx)
	if err != nil {
		panic(err)
	}

	rb := &sqladmin.DatabaseInstance{
		Settings: &sqladmin.Settings{
			DeletionProtectionEnabled: false,
		},
	}

	_, err = sqladminService.Instances.Patch(project, instance, rb).Context(ctx).Do()
	if err != nil {
		panic(err)
	}
}
```

  3. Note that deletion protection is still enabled

The issue appears to be with the encoding of JSON from the Settings struct and using omitempty. This excludes the false value, which is the expected behavior when encoding/marshaling. However this means that we cannot pass a false value for settings, which is the issue. This occurs on both the v1 and v1beta4 APIs.

Call to JSONReader, which results in an empty settings JSON when passing false, but the correct settings JSON when passing true:
https://github.com/googleapis/google-api-go-client/blob/c3e43a173ab604da8056591a7c2ead184fad22c9/sqladmin/v1beta4/sqladmin-gen.go#L9482

From what I've researched it appears using pointers for the bool values would be a fix, i.e.:

```
type Settings struct {
    DeletionProtectionEnabled *bool `json:"deletionProtectionEnabled,omitempty"`
}
```

This would then require extra validation to check for nil values.

**Comment by codyoss** [comment]
What you are looking for is ForceSendFields on the request struct: https://pkg.go.dev/google.golang.org/api#hdr-ForceSendFields
