### ISSUE TITLE
Remove unneeded guard condition after GAPIC generator rollout of WithDefaultEndpointTemplate

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-api-go-client#2359]
Once the GAPIC generator rollout of WithDefaultEndpointTemplate is complete, remove the following guard condition from around [internal/cba.go#L79](https://github.com/googleapis/google-api-go-client/blob/b9ed8b41df6a07d04758e91a9622b3ec73fc02a3/internal/cba.go#L79):

```
&& settings.DefaultEndpointTemplate != ""
```

And uncomment the error check just below:

```
// if settings.DefaultEndpointTemplate == "" {
// 	return nil, "", errors.New("internaloption.WithDefaultEndpointTemplate is required if option.WithUniverseDomain is not googleapis.com")
// }
```

**Comment by codyoss** [comment]
@quartzmo can this be acted on?

**Comment by quartzmo** [comment]
@codyoss I removed every usage of DefaultEndpointTemplate that I could find. So now is as good as time as any. Thanks for the ping, I'll create a PR.

**Comment by codyoss** [comment]
I believe this has been done for a bit now.
