### ISSUE TITLE
Self test failure on i386 due to 32bit vs 64bit problem

### ISSUE THREAD

**Issue by jas4711** [googleapis/google-api-go-client#2370]
Hi.  I'm helping packaging this project version 0.157.0 for Debian.  It builds on amd64 (64-bit) not not i386 (32-bit).  Ideas?

https://salsa.debian.org/jas/golang-google-api/-/jobs/5194741

```
ok  	google.golang.org/api/internal/third_party/uritemplates	0.005s
# google.golang.org/api/iterator_test [google.golang.org/api/iterator.test]
src/google.golang.org/api/iterator/iterator_test.go:42:9: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in assignment (overflows)
FAIL	google.golang.org/api/iterator [build failed]
```

Any ideas?

Thanks,
Simon

**Comment by quartzmo** [comment]
Background: The failing line is [iterator/iterator_test.go#L42 in v0.157.0](https://github.com/googleapis/google-api-go-client/blob/v0.157.0/iterator/iterator_test.go#L42), which was recently updated in #2342.

Does it make sense to you that `math.MaxInt` would produce this error?

**Comment by quartzmo** [comment]
I can't find `0.157.0` anywhere in this log, how do we know which version is being tested?

https://salsa.debian.org/jas/golang-google-api/-/jobs/5194741

**Comment by quartzmo** [comment]
Please re-open if this is still a problem and you can provide more details as requested above, thank you.
