### ISSUE TITLE
Docs: add examples of waiting on Operation

### ISSUE THREAD

**Issue by zombiezen** [googleapis/google-api-go-client#238]
@ttomsu was writing some code that used the GKE APIs to create a new cluster.  The [`Create(...).Do()`](https://github.com/google/google-api-go-client/blob/532986bc317f5cf61f4e7ef35d9dae8b75b3f56f/container/v1/container-gen.go#L3029) function returns an `*Operation`, which @ttomsu thought would be updated automatically.  Instead, the code needs to make a call to [projects.zones.operations get](https://cloud.google.com/container-engine/reference/rest/v1/projects.zones.operations/get) in order to get the latest operation status.

Since it might not be scalable to add codegen that special-cases long-running operations, it might be good to have sample code that we can point folks to that does it.

/cc @jba @broady

**Comment by bdronneau** [comment]
Any updates ? Looking for examples but with compute

**Comment by broady** [comment]
On mobile right now, (will edit this comment), but you might find some
useful code in github.com/broady/cdbuild.

**Comment by NIHARIKA178** [comment]
This might help you.
take the name of the operation and pass it.
Loop will run until an err or progress is 100.
for{
resp, err := computeService.ZoneOperations.Get(Project,Zone,Name).Context(ctx).Do()
 if err !=nil{
fmt.Println("error in op:")
return false ,err
}
if resp1.Progress==100{
return true,nil
}
}

**Comment by sduskis** [comment]
@enocom, Long running operations are a first class citizen in other languages, and I think that they're baked into the generators.  We should figure out if we can do the same in GoLang.

**Comment by broady** [comment]
@sduskis not sure if it's feasible from discovery doc generation. each API seems to do operations slightly differently.

**Comment by enocom** [comment]
@sduskis For now I've added a simple example, but will keep your point in mind when we rework the examples to be more useful.
