### ISSUE TITLE
Full text search doesn't work when using 'in parents' option

### ISSUE THREAD

**Issue by joeyave** [googleapis/google-api-go-client#2437]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - Programming language: go
  - OS: MacOS, Linux
  - Language runtime version: 1.21.6
  - Package version: v0.167.0

#### Steps to reproduce

Make a query with full text search that searches inside Google Docs file and add "in parents" option. 
Such as

Query:
```
fullText contains 'часом знемагаю' and trashed = false and mimeType = 'application/vnd.google-apps.document' and '1T1CHAx8cyLnGfL1_Yc6O_sJkvCfRnLid' in parents
```

```
Result:
{
  "files": []
}
```

Result is empty files list. But if remove "in parents" part and make another search I get this file. And that file has an ID in parents field.

Query:
```
fullText contains 'часом знемагаю' and trashed = false and mimeType = 'application/vnd.google-apps.document'
```

Result:
```
{
  "files": [
    {
      "parents": [
        "1T1CHAx8cyLnGfL1_Yc6O_sJkvCfRnLid"
      ]
    }
  ]
}
```

Interesting part is that it returns file if full text search query contains words from file's name.

**Comment by codyoss** [comment]
Hey, I am not sure what is going on here but this seems like a better question for the API team as I don't think this is related to the client libraries directly. A good way to test that would be to see if you can reproduce this with curl. To reach out for support with the drive API I would check out their support page and reach out on one of the listed methods: https://developers.google.com/drive/api/support
