### ISSUE TITLE
How does Google define private APIs?

### ISSUE THREAD

**Issue by FPNL** [googleapis/google-api-go-client#2439]
According to issue #597 , I'd like to know where Google defines private APIs? 

For example, this [Business Communications Document](https://developers.google.com/business-communications/business-messages/reference/rest#discovery-document) doesn't appear in this [list](https://www.googleapis.com/discovery/v1/apis). Then, why is it mentioned in the Discovery List? I can only guess that it implies itself as a document for private APIs.

**Comment by codyoss** [comment]
It is not that it is a private API, it is just that team does not host their API spec on the public discovery listing linked in that issue. And we only generate libraries found in that list in this repository.

> Then, why is it mentioned in the Discovery List?

I am not sure what you mean by this.

**Comment by FPNL** [comment]
I thought it's according to Google's policy to decide which project can public their spec on the list. 

And now I know, thanks for  answering.
