### ISSUE TITLE
Missing path element of analyticsdata URL endpoint

### ISSUE THREAD

**Issue by sula7** [googleapis/google-api-go-client#2455]
#### Environment details

  - Programming language: go
  - OS: MacOS 14.3.1
  - Language runtime version: 1.21.8
  - Package version: v0.168.0

#### Steps to reproduce

1. Use this lib to get analytics data ([runReport](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runReport)) by this code snippet:

```go
response, err := analyticsDataService.Properties.RunReport("123456", runReportRequest).Do()
if err != nil {
	log.Fatalf("failed to run request: %v", err)
}
```

2. It returns an html error:
```html
failed to run request: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v1beta/123456:runReport?alt=json&amp;prettyPrint=false</code> was not found on this server.  <ins>That’s all we know.</ins>
```

I checked the source and found this line of code at [analyticsdata-gen.go:4271](https://github.com/googleapis/google-api-go-client/blob/main/analyticsdata/v1beta/analyticsdata-gen.go#L4271):
```go
urls := googleapi.ResolveRelative(c.s.BasePath, "v1beta/{+property}:runReport")
```

I went to analytics doc to check the URL and found the [correct one](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runReport#http-request):
```
POST https://analyticsdata.googleapis.com/v1beta/{property=properties/*}:runReport
```

Looks like [analyticsdata-gen.go:4271](https://github.com/googleapis/google-api-go-client/blob/main/analyticsdata/v1beta/analyticsdata-gen.go#L4271) missing /properties/ in the path, so it should be:
```go
urls := googleapi.ResolveRelative(c.s.BasePath, "v1beta/properties/{+property}:runReport")
```

I also checked it by manual adding missing element of the path to forked lib and ran my client. In that case it returns correct data instead of 404 error.

Looks like other endpoints have the same problem (e.g. runRealtimeReport, runPivotReport, etc.). Please check them all as well.

Thanks!

**Comment by quartzmo** [comment]
@sula7 Thank you for reporting this issue. I'll try to look into it today.

**Comment by quartzmo** [comment]
@sula7 If you change the format of your `property` argument to `properties/1234` (as shown in the [docs](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runReport)), your snippet should work:

```go
response, err := analyticsDataService.Properties.RunReport("properties/123456", runReportRequest).Do()
if err != nil {
	log.Fatalf("failed to run request: %v", err)
}
```

Regarding this snippet, did you write it yourself, or is there an incorrect snippet published somewhere that needs to be fixed?

**Comment by sula7** [comment]
@quartzmo My bad, I missed this part from documentation. Yeah, I did write it myself. Sorry for the false issue
