### ISSUE TITLE
androidpublisher: missing TargetingRuleScope fields 

### ISSUE THREAD

**Issue by hfkang** [googleapis/google-api-go-client#2469]
> **PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Filed Case 50116975 

#### Environment details
  - Programming language: golang
  - OS: linux
  - Language runtime version: go 1.21
  - Package version: v0.114.0

#### Steps to reproduce
The androidpublisher client defines target rules for subscription offers  [here](https://github.com/googleapis/google-api-go-client/blob/67f16b6ada0cd92d94d98bb32f3bec61ca3472c6/androidpublisher/v3/androidpublisher-gen.go#L8066), but only includes `SpecificSubscriptionInApp`. 

It's missing the other targeting rules defined on the developer docs for the androidpublisher API, [defined here](https://developers.google.com/android-publisher/api-ref/rest/v3/monetization.subscriptions.basePlans.offers#targetingrulescope), namely `anySubscriptionInApp` and `thisSubscription`

**Comment by LSalazar82** [comment]
[`[](url)`](url)

**Comment by codyoss** [comment]
You are correct. This API is generated from the public discovery doc listing of this API found here: https://androidpublisher.googleapis.com/$discovery/rest?version=v3 . It seems like the service team here had not published an updated doc. I would recommend filing a bug to that team from the link on their overview page: https://developers.google.com/android-publisher.
