### ISSUE TITLE
androidpublisher/v3 - nondeterministic failure to create subscription with offer

### ISSUE THREAD

**Issue by pboccaccio** [googleapis/google-api-go-client#2493]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Is this a client library issue or a product issue? We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - Programming language: go
  - OS: linux
  - Language runtime version: go 1.21.3
  - Package version: tried v0.114.0 and v0.171.0

#### Steps to reproduce

create a subscription with an offer:
```
other := androidpublisher.OtherRegionsBasePlanConfig{
	EurPrice: &androidpublisher.Money{
		CurrencyCode: "EUR",
		Nanos:        990000000,
		Units:        14,
	},
	NewSubscriberAvailability: true,
	UsdPrice: &androidpublisher.Money{
		CurrencyCode: "USD",
		Nanos:        990000000,
		Units:        14,
	},
}

subscription := &androidpublisher.Subscription{
	PackageName: "package name",
	ProductId:   "sku",
	BasePlans: []*androidpublisher.BasePlan{
		{
			BasePlanId: "p1m",
			RegionalConfigs: []*androidpublisher.RegionalBasePlanConfig{
				{
					NewSubscriberAvailability: true,
					Price: &androidpublisher.Money{
						CurrencyCode: "EUR",
						Nanos:        990000000,
						Units:        14,
					},
					RegionCode: "AT",
				},
			},
			OtherRegionsConfig: &other,
			AutoRenewingBasePlanType: &androidpublisher.AutoRenewingBasePlanType{
				BillingPeriodDuration: "P1M",
				LegacyCompatible:      true,
			},
		},
	},
	Listings: []*androidpublisher.SubscriptionListing{
		{
			LanguageCode: "en-US",
			Title:        "sample title",
		},
	},
}

req := googleClient.Subscriptions.Create("package name", subscription)
req.ProductId("sku")
req.RegionsVersionVersion("2022/02")
```

sometimes this fails with `badRequest`, for example:
- `googleapi: Error 400: p1m: The price for AT must be rounded, badRequest`
- `googleapi: Error 400: p1m: The price for New regions must be rounded, badRequest`

but not for all regions with the same price point.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by quartzmo** [comment]
Is this a client library issue or a product issue? We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

**Comment by quartzmo** [comment]
No response for more info, closing.
