### ISSUE TITLE
maxResults option is not being respected by channel list endpoint

### ISSUE THREAD

**Issue by Dmarcotrigiano** [googleapis/google-api-go-client#2518]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Is this a client library issue or a product issue? We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - Programming language: Go
  - OS: Linux Ubuntu 22.04 LTS
  - Language runtime version: 1.22.2
  - Package version: v0.172.0

#### Steps to reproduce

  1.  
  ```go
  call := y.Service.Channels.List([]string{"snippet", "contentDetails", "statistics"}).Context(ctx).Id(channelIds...).MaxResults(1)
  ```
  2. Create test to check that with a list of IDs larger than 1 returns a `response.Items` of length 1.
  ```go
  		if err != nil {
			t.Errorf("Error getting channel details: %v", err)
		}
		if channels == nil {
			t.Errorf("Channels list is nil")
		}
		if len(channels) == 2 {
			t.Errorf("Expected 1 channel, got 2, %v", channels)
		}
```

Observe debugger:
![image](https://github.com/googleapis/google-api-go-client/assets/79153083/6eb68154-1208-4400-a284-6e9cace238d1)
![image](https://github.com/googleapis/google-api-go-client/assets/79153083/2eb42910-f7fc-4873-83fc-298736a963d9)
![image](https://github.com/googleapis/google-api-go-client/assets/79153083/e64d7bf3-1824-429d-89a7-f2bdb7676134)

  
Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by quartzmo** [comment]
@Dmarcotrigiano Is this a client library issue or a product issue? If the client library is behaving correctly (sending the maxResults option to the service endpoint), then this is a product issue, and does not concern the client library. 

> Is this a client library issue or a product issue? We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

**Comment by Dmarcotrigiano** [comment]
Likely a product issue, apologies.
