### ISSUE TITLE
Can't create client only with API key

### ISSUE THREAD

**Issue by Jofre** [googleapis/google-api-go-client#252]
https://github.com/google/google-api-go-client/blob/b0284fdf28b5e4d7c9aa5c26e67035437f711304/internal/settings.go#L34

If the apiKey is is set, it still tries to get application default credentials.

This produces errors like this: https://play.golang.org/p/tBtH1v-Sj5w

The same call using curl works (no credentials):
```
curl https://vision.googleapis.com/v1/images:annotate?key=<API_KEY>  -H'content-type:application/json' -d'{
 "requests": [
  {
   "image": {
    "source": {
     "imageUri": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1200px-Google_2015_logo.svg.png"
    }
   },
   "features": [
    {
     "type": "LABEL_DETECTION"
    }
   ]
  }
 ]
}'
```

**Comment by 0joshuaolson1** [comment]
I was surprised that GettingStarted says without exception to use Google's OAuth package and no example shows using WithAPIKey on its own.

...now I know why?

**Comment by broady** [comment]
Indeed. I don't think that's implemented for the gRPC client. This would be
better posted over on the google-cloud-go repo, by the way.

**Comment by 0joshuaolson1** [comment]
OTOH, I just found [this example code](https://github.com/google/google-api-go-client/issues/133#issuecomment-192919765) in an issue, so maybe this is possible already?

**Comment by broady** [comment]
I believe the Cloud ML APIs are the only ones that accept API keys.

**Comment by 0joshuaolson1** [comment]
YouTube Data API v3 doesn't need OAuth for some things.

**Comment by broady** [comment]
That code works for the libraries in this repo (JSON over HTTP), but not
for the gRPC libraries (cloud.google.com/go/...).

I'm sorry about this confusion.

**Comment by jadekler** [comment]
This question _seems_ resolved. I'm going to close, but anyone feel free to speak up if we should take another look at this.
