### ISSUE TITLE
SafeBrowsing v5 only supports alt=proto

### ISSUE THREAD

**Issue by lionello** [googleapis/google-api-go-client#2534]
This should be `"default": "proto"`:
https://github.com/googleapis/google-api-go-client/blob/9622a0d432afa4ee791ffc361cb8d3ea13aa6e40/safebrowsing/v5/safebrowsing-api.json#L40

The currently generated SDK will always fail with HTTP 400, response:
```json
{
  "error": {
    "code": 400,
    "message": "Unsupported Output Format",
    "status": "INVALID_ARGUMENT"
  }
}
```

Setting alt to `"proto"` doesn't work, since the SDK always decodes the response as JSON, failing with `invalid character '\x12' looking for beginning of value` trying to decode the protobuf as JSON.

**Comment by quartzmo** [comment]
APIs that publish clients to this repo *should* be sending JSON responses. If the SafeBrowsing v5 API is sending protobuf responses, that is incorrect. Can you provide a full dump of the response?

**Comment by lionello** [comment]
That JSON *was* the full dump of the response. I can capture the HTTP headers later.

**Comment by quartzmo** [comment]
Here is the discovery document for this API: https://safebrowsing.googleapis.com/$discovery/rest?version=v5

We will investigate further.

**Comment by quartzmo** [comment]
I believe the discovery document for this API (linked above) states that JSON is supported:

```json
    "alt": {
      "enumDescriptions": [
        "Responses with Content-Type of application/json",
        "Media download with context-dependent Content-Type",
        "Responses with Content-Type of application/x-protobuf"
      ],
      "default": "json",
      "type": "string",
      "enum": [
        "json",
        "media",
        "proto"
      ],
      "location": "query",
      "description": "Data format for response."
    },
```

Therefore it appears that the service does not honor the contract of the discovery document.

@lionello Can you search the [Cloud SQL issue tracker](https://issuetracker.google.com/savedsearches/559773) for an existing issue, and if not found, create a new issue demonstrating how the service does not support `alt=json`, then link that issue from here?

**Comment by codyoss** [comment]
Closing. As stated above this issue should be reported to the API service team.
