### ISSUE TITLE
searchconsole: How can I know if accurate data is ready？

### ISSUE THREAD

**Issue by TTTragic** [googleapis/google-api-go-client#2592]
Related APIs: searchconsole/v1
Version: v0.172.0
Details: I am trying to query the data using method **Query** of **SearchanalyticsService**. I know from the [help documentation](https://support.google.com/webmasters/answer/7576553) that it takes Google about 3 days to validate the data. When the data is not ready, the method **Query**  returns empty data(len(SearchAnalyticsQueryResponse.Rows)==0), which is the same behavior as if there were no search results for the day.I want to distinguish between the two.

My English is poor, so I'll describe it below in my native language, if you have a Chinese developer, he can understand my question better

相关API：searchconsole/v1
包版本： v0.172.0
问题详情：我打算通过谷歌搜索API来拉取网站的搜索结果，具体是**SearchanalyticsService**服务的**Query**方法。我从谷歌官方的[帮助文档](https://support.google.com/webmasters/answer/7576553)中得知，谷歌需要花费2-3天的时间来复核数据。在复核数据的这段时间里，Query方法返回的结构中，Rows为空切片。如果我的网站某天的访问量为0，Query方法返回的结构中，Rows也为空切片。这两种情况，接口表现是一致的，我怎么区分这两种情况。

**Comment by codyoss** [comment]
I am not sure if there is a way to test this from the API. I think the best place to ask this question is through the [API support page](https://support.google.com/webmasters/community) as this is a question about the service vs the client libraries itself.  Hope that helps you find the correct path to your solution.
