### ISSUE TITLE
Firebase go client - support using json struct tags

### ISSUE THREAD

**Issue by nathanperkins** [googleapis/google-api-go-client#2686]
**Is your feature request related to a problem? Please describe.**

We would prefer that Firebase serializes our objects in a way that is consistent with the JSON or YAML representation and with the [JSON style guide](https://google.github.io/styleguide/jsoncstyleguide.xml#Property_Name_Format).

We use proto to define and generate some of our request structs. We store the request as a field on one of our objects which is then stored in Firebase. These fields use property keys which don't align with the other object fields because the proto generated structs have `json` tags but no `firebase` tags. The default golang representation does not match the JSON style guide.

There is no built-in mechanism for proto to generate arbitrary struct tags, and the feature is rejected by the go proto team. [This comment from 2016](https://github.com/golang/protobuf/issues/52#issuecomment-243606932) shows another engineer having the same exact problem as us.

Besides this issue, it is very, very common for structs to have `json` or `yaml` tags defined. When Firebase ignores those tags, it uses an object representation which doesn't align with the other way those structs are being serialized. We would like it to be consistent.

This issue is particularly problematic for services which involve multiple languages, since the default representation may differ.

**Describe the solution you'd like**

Allow users to configure the client library in a way that it uses the `json` or `yaml` tags when a `firebase` tag is not present. This is a breaking change so it must be opt-in.

**Describe alternatives you've considered**

Setting the `firebase` tag on our protos.

Caveats:

- This isn't supported directly and requires third-party plugins contributed by individual developers. There's no obvious, standout plugin that is well-maintained and battle-tested.
- We have no control over the upstream protos that our protos import, so we still can't achieve consistency across our entire object.

**Comment by codyoss** [comment]
@nathanperkins Can you clarify what library you are using and a small code example?

**Comment by nathanperkins** [comment]
Sorry, I think this needs to be in https://github.com/googleapis/google-cloud-go

**Comment by nathanperkins** [comment]
Opened: https://github.com/googleapis/google-cloud-go/issues/10545
