### ISSUE TITLE
InstanceGroupsService: AggregatedList()/List() API does not return the property `MANAGED`

### ISSUE THREAD

**Issue by ParthaI** [googleapis/google-api-go-client#2689]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
- I am making the API call [InstanceGroupsService: List()](https://pkg.go.dev/google.golang.org/api/compute/v1#InstanceGroupsService.List) or [InstanceGroupsService: AggregatedList()](https://pkg.go.dev/google.golang.org/api/compute/v1#InstancesService.AggregatedList) to list the instance groups.
- I am receiving the result set according to the available instance groups in my project.
- However, there is no way to distinguish whether it is a managed group or an unmanaged group.
- Both APIs return the [InstanceGroup](https://pkg.go.dev/google.golang.org/api/compute/v1#InstanceGroup) struct.

The Gcloud CLI command returns a property named `MANAGED`, which allows us to distinguish between managed and unmanaged groups.
```
➜  ~ gcloud compute instance-groups list        
| NAME             | LOCATION     | SCOPE | NETWORK | MANAGED | INSTANCES |
|------------------|--------------|-------|---------|---------|-----------|
| instance-group-2 | us-central1-a| zone  | demo    | No      | 0         |
| instance-group-1 | us-central1-c| zone  | default | Yes     | 1         |

```

**Describe the solution you'd like**
The `MANAGED` property might have been missed from the API response while mapping the API response to a Go struct.

**Describe alternatives you've considered**
N/A

**Additional context**
The Gcloud version:

```
Google Cloud SDK 483.0.0
alpha 2024.06.28
bq 2.1.6
core 2024.06.28
gcloud-crc32c 1.0.0
gke-gcloud-auth-plugin 0.5.9
gsutil 5.30
```

Any quick response would be greatly appreciated.

Thanks!

**Comment by noahdietz** [comment]
Based on the docs, the API you are calling does not include managed instance groups: 
![image](https://github.com/user-attachments/assets/cdffeb02-ef04-41b4-bb13-c22c52a61e1d)

You must call a separate API to list Managed instances groups. That probably means this API returns the "unmanaged" instance groups.

`gcloud` is likely abstracting this behind multiple API calls, where as the autogenerated client libraries here are directly representing the API surface is it is exposed.

Hope that answers your question.
