### ISSUE TITLE
KIOSK install type Full screen shows back button

### ISSUE THREAD

**Issue by onesick** [googleapis/google-api-go-client#2705]
Per https://developers.google.com/android/management/reference/rest/v1/enterprises.webApps#DisplayMode
KIOSK mode Full screen should disable status bar, and navigation back button. However, as the picture below, the back button is enabled. 
![Untitled design](https://github.com/user-attachments/assets/2fd8f33b-bd89-48b3-8cc0-bce8ab2f8d52)

#### Environment details

  - Programming language: Python
  - OS: Colab
  - Language runtime version:
  - Package version: Followed through https://github.com/google/android-management-api-samples/blob/master/notebooks/codelab_kiosk.ipynb

#### Steps to reproduce

  1. Using quickstart colab, I have created the webapp with displayMode: FULL_SCREEN, with policy of KIOSK install type
  2. the device does not display navigation bar at first. However, when a screen is touched, navigation bar with back button appears

Thanks in advance!

**Comment by codyoss** [comment]
Hey, this appears unrelated to the Go SDK. I suggest reaching out via the support page for the service: https://developers.google.com/android/management/feedback. Hope that gets you going in the right direction.
