### ISSUE TITLE
Why PurchaseType defined as int64 rather than *int64?

### ISSUE THREAD

**Issue by richzw** [googleapis/google-api-go-client#275]
According the PurchaseType definition [here](https://github.com/google/google-api-go-client/blob/master/androidpublisher/v1.1/androidpublisher-gen.go#L135)

```
	// PurchaseType: The type of purchase of the inapp product. This field
	// is only set if this purchase was not made using the standard in-app
	// billing flow. Possible values are:
	// - Test (i.e. purchased from a license testing account)
	// - Promo (i.e. purchased using a promo code)
	PurchaseType int64 `json:"purchaseType,omitempty"`
```

Since this field is only set if this purchase was not made using the standard in-app billing flow, should it better define it as `*int64`? 

When this field is not set, and it type is `int64`, it's value could be 0 after `json.Decode()`. It could cause confuse when this field is set to `0`. Is there better way to distinguish it or anything I am missing?

**Comment by jba** [comment]
Which API is this from?

**Comment by richzw** [comment]
It is used in this  [Do](https://github.com/google/google-api-go-client/blob/master/androidpublisher/v2/androidpublisher-gen.go#L10473) API.

**Comment by danilobuerger** [comment]
@jba this is still happening in the `SubscriptionPurchase` struct.

**Comment by danilobuerger** [comment]
@jba @jadekler I uploaded a patch here: https://code-review.googlesource.com/c/google-api-go-client/+/34710 I don't know how to proceed as I haven't used googles gerrit before.

**Comment by jadekler** [comment]
Thanks for your contribution!
