### ISSUE TITLE
ForceSendFields accepts invalid fieldnames

### ISSUE THREAD

**Issue by paddycarver** [googleapis/google-api-go-client#280]
When using `ForceSendFields`, there doesn't appear to be any validation of the field names supplied. As field names are specified in string format, it's pretty easy to give `ForceSendFields` the wrong field name and have things silently fail on you in unexpected ways. I would expect an error to be returned if the fields listed do not match up to actual fields on the struct.

**Comment by jadekler** [comment]
@broady does this seem reasonable to do client-side? It seems to, from my perspective, but not sure if there's some reason why an API would accept a field that client doesn't know about 🤔

**Comment by codyoss** [comment]
Thinking quickly I think this would require some reflection on the struct to check if said fields exist, this could get expensive. Being these APIs are considered in maintenance mode and this FR has had low traction I am going to close it out as won't fix.

**Comment by paddycarver** [comment]
I don't know a whole lot about the code generation, but I'm under the impression that the structs themselves are generated. Could a `map[string]struct{}{}` of the field names not also be generated, and referenced? Then there would be no need for reflection, just a map lookup.
