### ISSUE TITLE
Calendar Event don't allow setting Overrides for EventReminders

### ISSUE THREAD

**Issue by prasincs** [googleapis/google-api-go-client#281]
When I try to run this 

```
event := &calendar.Event{
		Summary: "Test Event",
		Description: `
TestDescription
`,
		AnyoneCanAddSelf: true,
		Start: &calendar.EventDateTime{
			DateTime: "2018-08-03T06:00:00Z",
		},
		End: &calendar.EventDateTime{
			DateTime: "2018-08-03T07:00:00Z",
		},
		Attendees: []*calendar.EventAttendee{
			&calendar.EventAttendee{
				Email: "prasanna@mistsys.com",
			},
		},
		Reminders: &calendar.EventReminders{
			Overrides: []*calendar.EventReminder{
				&calendar.EventReminder{
					Method:  "email",
					Minutes: 30,
				},
			},
			UseDefault: false,
		},
	}

	event, err = srv.Events.Insert(calendarId, event).Do()
	if err != nil {
		log.Fatalf("Unable to create event. %v\n", err)
	}
	fmt.Printf("Event Created: %s\n", event.HtmlLink)
```

I get the following.. 
```
2018/07/06 10:21:15 Unable to create event. googleapi: Error 400: Cannot specify both default reminders and overrides at the same time., cannotUseDefaultRemindersAndSpecifyOverride
```

Upon closer inspection by serializing the Event, UseDefault is set to `omitempty`  for EventReminders

This means go wont set anything for the field if UseDefault is false.. based on the API behavior it should be a required field. 

I changed the EventReminders struct to this
```
// EventReminders: Information about the event's reminders for the
// authenticated user.
type EventReminders struct {
	// Overrides: If the event doesn't use the default reminders, this lists
	// the reminders specific to the event, or, if not set, indicates that
	// no reminders are set for this event. The maximum number of override
	// reminders is 5.
	Overrides []*EventReminder `json:"overrides,omitempty"`

	// UseDefault: Whether the default reminders of the calendar apply to
	// the event.
	UseDefault bool `json:"useDefault"`

	// ForceSendFields is a list of field names (e.g. "Overrides") to
	// unconditionally include in API requests. By default, fields with
	// empty values are omitted from API requests. However, any non-pointer,
	// non-interface field appearing in ForceSendFields will be sent to the
	// server regardless of whether the field is empty or not. This may be
	// used to include empty fields in Patch requests.
	ForceSendFields []string `json:"-"`

	// NullFields is a list of field names (e.g. "Overrides") to include in
	// API requests with the JSON null value. By default, fields with empty
	// values are omitted from API requests. However, any field with an
	// empty value appearing in NullFields will be sent to the server as
	// null. It is an error if a field in this list has a non-empty value.
	// This may be used to include null fields in Patch requests.
	NullFields []string `json:"-"`
}
```

and the relevant part in calendar-api.json to 
```
            "useDefault": {
                "description": "Whether the default reminders of the calendar apply to the event.",
                "type": "boolean"
                "required": true
            }
```

I'm not sure where the code is generated, but this seems to have the intended effect.

**Comment by jba** [comment]
I'll look into the code generation, but the workaround for now is to write
```
ForceSendFields: []string{"UseDefault"}
```

**Comment by grant** [comment]
For the go library, you must force send falsy fields.

**Comment by jadekler** [comment]
Thanks @grant and @jba. @prasincs I'll close this for now, since it seems like this question is answered. Give a shout if you have further questions.

**Comment by hanneshayashi** [comment]
I am trying to do the exact same this as the OP, but the suggested workaround doesn't seem to work for me. However, it DOES work with "AnyoneCanAddSelf" (`event.ForceSendFields = append(event.ForceSendFields, "AnyoneCanAddSelf")`).
I suspect this mioght be because Reminders is actually an object, so the code can't find it the node if it is just referenced by "UseDefault"? I also tried the following to no avail:
`event.ForceSendFields = append(event.ForceSendFields, "Reminders.UseDefault")
event.ForceSendFields = append(event.ForceSendFields, "Reminders")`
Am I doing something wrong here or has something changed with the logic?

**Comment by codyoss** [comment]
@hanneshayashi, please provide the snippet of code you are trying.

**Comment by hanneshayashi** [comment]
Never mind. I did not realize that every property has its own "ForceSendFields", which totally makes sense. I was setting the top-most property, which (of course) didn't work.
Just in case anyone else is ever confused about this:
You need to set the ForceSendFields property on the same level you want to force-send a field. For example:
`event.**Reminders**.ForceSendFields = append(event.**Reminders**.ForceSendFields, "UseDefault")`

This was totally my fault, but I suppose the documentation could be a little clearer on this...
