### ISSUE TITLE
Bug | Chrome Managment API | Reports

### ISSUE THREAD

**Issue by lironpaz7** [googleapis/google-api-go-client#2821]
### Environment details:
Programming language: Go
OS: Mac OS
Language runtime version: 1.23
Package version: google.golang.org/api/chromemanagement/v1

### Steps to reproduce:
`
maxFetch := int64(50)
pageToken := ""

call := srv.Customers.Reports.CountInstalledApps(gsuite.AdminCustomer).PageSize(maxFetch).PageToken(pageToken)

r, err := call.Do()
`

### Error:
`
googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v1/my_customer/reports:countInstalledApps?alt=json&amp;pageSize=50&amp;pageToken=&amp;prettyPrint=false</code> was not found on this server.  <ins>That’s all we know.</ins>
`

### Solution proposal:
I looked in the [documentation](https://developers.google.com/chrome/management/guides/samples_reportsapi) and found out that the api url should be:
https://chromemanagement.googleapis.com/v1/**customers**/$CUSTOMER/reports:countInstalledApps?...

And as you can see in the error above, the api url is missing the 'customers' right after the v1.

**Comment by codyoss** [comment]
In your example. `gsuite.AdminCustomer` should be formatted to `customers/*` according to https://developers.google.com/chrome/management/reference/rest/v1/customers.reports/countInstalledApps. Hope that helps.

**Comment by lironpaz7** [comment]
Thanks it was unclear since the SDK doc didn't mention that I should add: customers/ on my own
