### ISSUE TITLE
How to compose multiple `ClientOption`?

### ISSUE THREAD

**Issue by iwinux** [googleapis/google-api-go-client#2826]
I'm trying to implement a `WithInternalOptions() option.ClientOption` that, as the name suggests, sets multiple internal API options at once. However, the interface `ClientOption` is defined as:

```go
type ClientOption interface {
	Apply(*internal.DialSettings)
}
```

Unable to import `internal.DialSettings`, it seems impossible to implement it outside of `google.golang.org/api`. Even though I could embed `option.ClientOption` in my struct (idea from https://github.com/googleapis/google-api-go-client/issues/211), there's no way to combine multiple `option.ClientOption` into one.

**Comment by codyoss** [comment]
ClientOptions are not meant to be implemented in user code, but like you said you could embed. For your use case I would just have a function that returns a []option.ClientOption and pass them to the client. Also, i`nternaloption` are only meant to be used by the libraries directly in generated code -- I would be wary setting them yourself as it could lead to  undesired side-effects.

```golang
func myOpts() []option.ClientOption {
  return []option.ClientOption {
    // ...
  }
}

func main() {
  ctx := context.Background()
  somepackage.NewClient(ctx, myOpts()...)

}
``` 

Hope that helps
