### ISSUE TITLE
Add instructions to generate services yourself

### ISSUE THREAD

**Issue by tmathews** [googleapis/google-api-go-client#283]
```
go get google.golang.org/api/google-api-go-generator
go get golang.org/x/net/context
go build google.golang.org/api/google-api-go-generator
./google-api-go-generator -cache=false -install -discoveryurl=<your-discovery.json>
```

I find it very annoying that Google's API generation tools are a mystery to use and that there are APIs left out of the default package without any pointers on how to generate them yourself. The least you can do is point somebody in the right direction on where the actual generator is and how to perform it in your read me. The flag documentation is also quite lousy due to it not knowing which flags depend or affect another. Anyone else that is new to the concept, tools, or don't have a great understanding of the underlying infrastructure will end up racking their brain for hours and run into many road blocks.

May this issue lay here to quicken your escape.

**Comment by jba** [comment]
The idea is that we generate _all_ the APIs so you shouldn't have to. We periodically generate all the APIs available from `https://www.googleapis.com/discovery/v1/apis` (see the [list of commits](https://github.com/google/google-api-go-client/commits/master)). 

Where are you finding your discovery docs?

**Comment by tmathews** [comment]
I'm unsure of what you are asking, sorry.

For more context: We currently generate the APIs from a self hosted JSON feed cloned from the URL you mentioned and tailored with additional private APIs. I should have corrected myself about them being private, my apologies.

On another note, hosting our own discovery JSON allows us to pin the version of software libraries we currently work with - though there are obvious down sides to this.

We can close this issue as I only wanted to achieve the fact that this information would be on the internet for others to find (may it be via Google or searching GitHub issues). And I have doubts that private APIs will be added to the default discovery URL.

**Comment by jba** [comment]
I appreciate your frustration. At this point it doesn't make sense to improve the docs, because we're working on a better code generator. As you say, this issue will serve as a pointer to anyone else trying to do this.

**Comment by jadekler** [comment]
Closing this issue, since we do not intend for users to generate the libraries manually.

**Comment by chaoky** [comment]
> The idea is that we generate _all_ the APIs so you shouldn't have to. We periodically generate all the APIs available from `https://www.googleapis.com/discovery/v1/apis` (see the [list of commits](https://github.com/google/google-api-go-client/commits/master)).
> 
> Where are you finding your discovery docs?

what about private apis such as mybusiness
https://developers.google.com/my-business/content/set-up-java-client

**Comment by chaoky** [comment]
ended up doing this `./google-api-go-generator --api_json_file "/path/to/discover.json" -gendir "."`
