### ISSUE TITLE
Opentelemetry isn't applied when IsNewAuthLibrary is enabled

### ISSUE THREAD

**Issue by jarviliam** [googleapis/google-api-go-client#2869]
Hello, I noticed that when this library has the `IsNewAuthLibrary` flag set to true, it generates a specific auth http.client via the `cloud.google.com/go/auth/httptransport` but the otelhttp wrapper isn't applied to it leading to a lack of traces. 

I'm not too sure if this should be fixed in this library or if it should be addressed in the upstream `cloud.google.com/go/auth/httptransport` libray.  Any guidance would be appreciated.

Context:
https://github.com/googleapis/google-api-go-client/blob/58faff9ac69eb1b15bf9b532eb1447143bc77083/transport/http/dial.go#L51

Thanks!

#### Environment details

  - Programming language: Go
  - OS: MacOS
  - Language runtime version: 1.22.4
  - Package version: v0.205.0

**Comment by codyoss** [comment]
Thanks for the report, we will investigate!

**Comment by codyoss** [comment]
please share your go.mod file. We did have a bug in this space but we thought it was fixed in https://github.com/googleapis/google-cloud-go/pull/10968. This was released in `cloud.google.com/go/auth@v0.9.8`.

**Comment by jarviliam** [comment]
Thanks for the investigation! My go.mod was out of sync, updating it solved it as you pointed out.
Sorry about that!
