### ISSUE TITLE
Cannot get the Metadata for a property in v1beta (client.Properties.GetMetadata(propertyId))

### ISSUE THREAD

**Issue by Abhishek047** [googleapis/google-api-go-client#2878]
Hi,

I am encountering this issue when i try to get the Metadata for a specifc property in the _**"/api/analyticsdata/v1beta"**_. 

  - Programming language: Go
  - OS: MacOs
  - Language runtime version: 1.22.3
  - Package version: 0.203.0

#### Steps to reproduce
Here is how i am calling the **"Do"** Method of the **GetMetadata** function

propertyId := "properties/[id]"

client, err := analyticsdata.NewService(ctx, option.WithTokenSource(tokenSource))
req := client.Properties.GetMetadata(propertyId)

This throws an error of not found
	
After going through the code I have found the source of the Bug, Please let me know if I can make a PR to fix this small issue it's basically the url is not configured well in the **"analyticsdata-gen"** file, for the PropertiesGetMetadataCall **"doRequest"**.

**Comment by quartzmo** [comment]
Hi @Abhishek047,

Thank you for reporting this issue. We need more information please.

> Here is how i am calling the "Do" Method of the GetMetadata function

1. Your example does not show a call to `Do`. Please provide a complete example, thank you.
2. Can you also please provide a full backtrace of the error including source line number.
3. Can you please provide a link to the cause of the issue in the "analyticsdata-gen" file?

**Comment by Abhishek047** [comment]
Hi @quartzmo 
Sure here is the full call what i am doing 
`       tokenSource := oauth2.StaticTokenSource(&oauth2.Token{AccessToken: token})
	client, err := analyticsdata.NewService(ctx, option.WithTokenSource(tokenSource))
	if err != nil {
		return nil, err
	}
	req := client.Properties.GetMetadata(propertyId)
	resp, err := req.Do()
	if err != nil {
		fmt.Println(err)
		return nil, err
	}`
2. I am not able to find the backtrace it is not showing me that, all i am getting this response when i call the do function this is the error i am getting when I log it.
`googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v1beta/properties/249546698?alt=json&amp;prettyPrint=false</code> was not found on this server.  <ins>That’s all we know.</ins>
  `
  3. From the above error message what i thought that there might be some error while calling the googleAPI so for that I found the source of the **v1beta** api ie. "analyticsdata-gen" where on **line:3081** it is calling to for the metadata like this
  `urls := googleapi.ResolveRelative(c.s.BasePath, "v1beta/{+name}")`
  This can be fixed by adding **/metadata in the end**
  `urls := googleapi.ResolveRelative(c.s.BasePath, "v1beta/{+name}/metadata")`
  That is what I think
  
  4. I have access_token of the user to call for the analytics data, I tried calling this for the API_KEY but the error was still there, I think the above fix i mentioned will fix the cause. 
If any more info is need please let me know

**Comment by quartzmo** [comment]
I think the `propertyId` value you are passing to `GetMetadata` is probably incorrect.

Here are the docs for `GetMetadata`:

```
// GetMetadata: Returns metadata for dimensions and metrics available in
// reporting methods. Used to explore the dimensions and metrics. In this
// method, a Google Analytics property identifier is specified in the request,
// and the metadata response includes Custom dimensions and metrics as well as
// Universal metadata. For example if a custom metric with parameter name
// `levels_unlocked` is registered to a property, the Metadata response will
// contain `customEvent:levels_unlocked`. Universal metadata are dimensions and
// metrics applicable to any property such as `country` and `totalUsers`.
//
//   - name: The resource name of the metadata to retrieve. This name field is
//     specified in the URL path and not URL parameters. Property is a numeric
//     Google Analytics property identifier. To learn more, see where to find
//     your Property ID
//     (https://developers.google.com/analytics/devguides/reporting/data/v1/property-id).
//     Example: properties/1234/metadata Set the Property ID to 0 for dimensions
//     and metrics common to all properties. In this special mode, this method
//     will not return custom dimensions and metrics.
```

It provides the example: `properties/1234/metadata`. But it is not completely clear if this is the correct resource name format.

Try setting `propertyId` using this format to see if you can get the right URL path.

**Comment by quartzmo** [comment]
This API reference page lets you try RPC requests in the browser. Use it to determine the working format for the `name` parameter:

https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/getMetadata
