### ISSUE TITLE
Batch requests for compute api

### ISSUE THREAD

**Issue by ishantt** [googleapis/google-api-go-client#290]
GCP supports batching of multiple http requests into a single request and other compute clients like python-api-client supports it. 
https://developers.google.com/resources/api-libraries/documentation/compute/v1/python/latest/index.html#new_batch_http_request

I cannot find anything similar for the compute APIs in google-api-go-client. Is this feature supported?

**Comment by jadekler** [comment]
I'm not aware of any option to batch HTTP requests. I would suggest the same as Brad: small requests should perform well in Go.
