### ISSUE TITLE
Cannot call Projects.AddFirebase

### ISSUE THREAD

**Issue by harunayyildizhadi** [googleapis/google-api-go-client#2915]
#### Environment details

  - Programming language: golang
  - OS: MacOS
  - Language runtime version: 1.22
  - Package version: v0.211.0

#### Steps to reproduce

```
func createFirebaseManagementClient(ctx context.Context, secretJson string) (*firebase.Service, *pkg.AppError) {
	opt := option.WithCredentialsJSON([]byte(secretJson))
	client, err := firebase.NewService(ctx, opt)
	if err != nil {
		appErr := pkg.Errors.GoogleCloudClientError("Couldn't create Firebase Management client")
		log.Error().Err(err).Msg(appErr.Detail)
		return nil, appErr
	}
	return client, nil
}
```

```
func AddFirebase(ctx context.Context, projectId string) *pkg.AppError {
	client, appErr := google_cloud_firebase_management.Client(ctx)
	if appErr != nil {
		return appErr
	}

	_addFirebaseReq := &firebase.AddFirebaseRequest{}
	_, err := client.Projects.AddFirebase(projectId, _addFirebaseReq).Do()
	if err != nil {
		appErr := pkg.Errors.GoogleClientError("Failed to add Firebase to project")
		log.Error().Err(err).Msg(appErr.Detail)
		return appErr
	}

	return nil
}
```

  1. Client is created on the createFirebaseManagementClient method. When I call the AddFirebase method with correct parameters it gives me 404 error. But I can make it work with curl request.
  When I debug it I'm seeing the request url on the sdk is:
  "https://firebase.googleapis.com/v1beta1/[PROJECT_ID]:addFirebase?alt=json&prettyPrint=false"
  
  It seems to me that it should be:
  "https://firebase.googleapis.com/v1beta1/projecst/[PROJECT_ID]:addFirebase?alt=json&prettyPrint=false"

**Comment by codyoss** [comment]
From the docs for that function: `project: The resource name of the Google Cloud `Project` in which Firebase resources will be added and Firebase services enabled, in the format: projects/ PROJECT_IDENTIFIER`. I believe you just need to format the input correctly, the error here is a little confusing. Hope that helps.
