### ISSUE TITLE
Google Safe Browsing v5 missing v5alpha1 new features

### ISSUE THREAD

**Issue by JILeXanDR** [googleapis/google-api-go-client#2917]
#### Steps to reproduce

In docs https://developers.google.com/safe-browsing/reference/rest there are new methods with prefix **v5alpha1** but they are missing in the generated code https://github.com/googleapis/google-api-go-client/blob/main/safebrowsing/v5/safebrowsing-api.json

Same here https://safebrowsing.googleapis.com/$discovery/rest?version=v5 when checking via discovery tool.

**Comment by codyoss** [comment]
These libraries are generated by reading the public discovery for the service. If the features are not there we can't generate. I suggest reaching out via the services support page to report this. Hope that helps.

**Comment by JILeXanDR** [comment]
@codyoss Hi, I mentioned wrong discovery link, it's `v5`, but new API is listed under `v5alpha1`.

https://safebrowsing.googleapis.com/$discovery/rest?version=v5alpha1

This is already available and contains all needed methods to include in this repo.
