### ISSUE TITLE
Please Tag this repo

### ISSUE THREAD

**Issue by Spazjaz98** [googleapis/google-api-go-client#2918]
@codyoss can you tag this repo because I want to resolve some go.mod indirects that use a vulnerable version of golang.org/x/crypto. If you could tag this repo it would be super appreciated!

**Comment by codyoss** [comment]
We may cut a release yet today, or else monday. You can always bump the indirect dep yourself as well though in the meantime.

**Comment by Spazjaz98** [comment]
Yea totally true I could do replace statements but if its happening Monday or today I will wait. Very much appreciated that you responded!

**Comment by Spazjaz98** [comment]
oh, it seems I can bump the indirect without a replace statement, which is probably what you suggested. Makes sense, closing the issue then. Thx for your time
