### ISSUE TITLE
We need option.WithCredentialsJSON(p []byte) 

### ISSUE THREAD

**Issue by jtwatson** [googleapis/google-api-go-client#293]
I have been using a handful of clients from the gocloud packages where I need to provide credentials via service account credentials file. option.WithCredentialsFile() doesn't work for me because I can't have the credential files lying on the file system.

I am aware of the solution that exist such such as:

```
ctx := context.Background()
creds, err := google.CredentialsFromJSON(ctx, []byte("JSON creds"), pubsub.ScopePubSub)
if err != nil {
    // TODO: handle error.
}
client, err := pubsub.NewClient(ctx, "project-id", option.WithCredentials(creds))
```
The problem I have with this solution is that `google.CredentialsFromJSON` requires the **Scopes** to be provided. As I dig through the code to find the scopes required, it feels like a really bad idea to be copying what I would consider internal package details into my code. If the Scopes change for a particular package, I will need to figure this out and update my code. This is not a concern for someone using `option.WithCredentialsFile`

Here are a few examples that hopefully make my concern more clear:

**pubsub.Client**
In the example for the pubsub.Client that I found, it states to use Scope `pubsub.ScopePubSub`. But if you dig into the code this is not what is actually used. The actual scopes come from the following code:
```
package cloud.google.com/go/pubsub/apiv1

// DefaultAuthScopes reports the default set of authentication scopes to use with this package.
func DefaultAuthScopes() []string {
	return []string{
		"https://www.googleapis.com/auth/cloud-platform",
		"https://www.googleapis.com/auth/pubsub",
	}
}
```

**firebase.NewApp**
Tracking down the Scopes for the firebase.App I found them in package firebase.google.com/go/internal, `internal.FirebaseScopes`, which is not accessible from my code. 

I ended up copying this into my code:
```
// FirebaseScopes is the set of OAuth2 scopes used by the Admin SDK.
var FirebaseScopes = []string{
	"https://www.googleapis.com/auth/cloud-platform",
	"https://www.googleapis.com/auth/datastore",
	"https://www.googleapis.com/auth/devstorage.full_control",
	"https://www.googleapis.com/auth/firebase",
	"https://www.googleapis.com/auth/identitytoolkit",
	"https://www.googleapis.com/auth/userinfo.email",
}
```

**PROPOSAL**
I coded up a new option that will take in `[]byte` containing the actual json instead of a file path.

`func WithCredentialsJSON(p []byte) ClientOption`

The actual code changes with unit testing is very small and it works for me.

I would be glad to push a CL for this, but figured I should get some feedback here first.

**Comment by jba** [comment]
I agree, that's definitely a problem. `google.CredentialsFromJSON` was my attempt to resist adding a new option, but I think you've made a good case for it.

@zombiezen, @jadekler Thoughts?

**Comment by jadekler** [comment]
SGTM, makes a lot of sense.

**Comment by jtwatson** [comment]
Just sent Gerrit CL: https://code-review.googlesource.com/c/google-api-go-client/+/33410
