### ISSUE TITLE
SqlAdmin DeletionProtectionEnabled cannot be disabled.

### ISSUE THREAD

**Issue by mofirouz** [googleapis/google-api-go-client#2937]
#### Environment details
  - Programming language: Go
  - OS: MacOS 
  - Language runtime version: Go 1.23.3
  - Package version: main branch

Cannot disable Delete Protection due to `omitempty` tag (or lack of pointer) in the `DatabaseInstance.Settings. DeletionProtectionEnabled ` field.

Code example below:

```
clientOption := option.WithCredentialsJSON([]byte("ServiceAccountJSON"))
ctx := context.Background()
cloudSQLAdminService, _ := sqladmin.NewService(ctx, clientOption)
cloudSQLInstancesService := sqladmin.NewInstancesService(cloudSQLAdminService)

di := &sqladmin.DatabaseInstance{
  Settings: &sqladmin.Settings{
    DeletionProtectionEnabled: protect,
  },
}
_, err := cloudSQLInstancesService.Patch(p.config.ProjectID, dbc.Instance, di).Context(ctx).Do()
```

Please advise on how best to disable delete protection programatically.

**Comment by codyoss** [comment]
You are looking for the ForceSendFields field on the struct. See: https://pkg.go.dev/google.golang.org/api#hdr-ForceSendFields

Hope that helps.

**Comment by mofirouz** [comment]
Thanks so much @codyoss - completely had missed that.

For completion sake, here is the full example:

```
       di := &sqladmin.DatabaseInstance{
		Settings: &sqladmin.Settings{
			DeletionProtectionEnabled: protect,
			ForceSendFields:           []string{"DeletionProtectionEnabled"},
		},
	}
```
