### ISSUE TITLE
monitoring/v3: properly aligning cumulative metrics

### ISSUE THREAD

**Issue by sbsends** [googleapis/google-api-go-client#294]
I am trying to calculate the total number of ml engine version predictions made over a 24 hour period. On Stackdriver, this metric easily calculated with "count" aggregation. When I try to aggregate the metric programmatically, I receive the following error:

```
Could not read time series value, googleapi: Error 400: Field aggregation.perSeriesAligner had an invalid value of "ALIGN_COUNT": The aligner cannot be applied to metrics with kind CUMULATIVE and value type INT64.
```

Code:

```golang
version := "<VERSION_ID>"
start := time.Date(2018, time.September, 29, 0, 0, 0, 0, time.UTC)
end := time.Date(2018, time.September, 30, 0, 0, 0, 0, time.UTC)
resp, err := monitoringService.Projects.TimeSeries.List("projects/<PROJECT_ID>").
	Filter(fmt.Sprintf(`metric.type= "ml.googleapis.com/prediction/prediction_count" AND resource.labels.version_id = "%s"`, version)).
	IntervalStartTime(start.Format(time.RFC3339Nano)).
	IntervalEndTime(end.Format(time.RFC3339Nano)).
	AggregationAlignmentPeriod("300s").
	AggregationPerSeriesAligner("ALIGN_COUNT").
	AggregationCrossSeriesReducer("REDUCE_SUM").
	Do()
```

Obviously, this can be done since the Stackdriver console does it. How should I correctly format my request? Documentation is sparse, so I would appreciate any input. Thank you for your time.

**Comment by sbsends** [comment]
@timburks @blowmage @lukesneeringer

**Comment by sbsends** [comment]
screenshot of Stackdriver console 

<img width="944" alt="screen shot 2018-09-30 at 10 48 46 pm" src="https://user-images.githubusercontent.com/21231577/46268929-3c2dac00-c503-11e8-96b5-9a4c127c940d.png">

**Comment by jba** [comment]
First, you're using a deprecated package. Use `cloud.google.com/go/monitoring/apiv3` instead.

In case that isn't relevant to the problem, I'm contacting the monitoring team to see if they can help.

**Comment by jba** [comment]
Look at the URL in that tab where the graph is plotted. It gives you the perSeriesAligner (which'll be ALIGN_RATE) & crossSeriesReducer (which'll be REDUCE_COUNT). Also, it'll help to click "Show more options" which reveals the aligner ("rate"). Lastly, the chip on top of the graph says "1 hr interval (rate)" indicating the aligner.

The "Aggregation" box is the crossSeriesReducer, not the perSeriesAligner.

**Comment by sbsends** [comment]
Great, thank you @jba! I will hopefully solve this within a few days. Then I will update this issue with a solution for future users.

**Comment by sbsends** [comment]
Okay, I have managed to recreate the Stackdriver console with the new gRPC API with the following code: 

```golang

import (
	"context"
	"fmt"
	"time"

	"cloud.google.com/go/monitoring/apiv3"
	"github.com/golang/protobuf/ptypes"
	"google.golang.org/api/iterator"
	monitoringpb "google.golang.org/genproto/googleapis/monitoring/v3"
)

// GetPredictionCount ...
func GetPredictionCount(ctx context.Context, start time.Time, end time.Time, version string) (int64, error) {
	// creating gRPC monitoring API
	startTime, _ := ptypes.TimestampProto(start)
	endTime, _ := ptypes.TimestampProto(end)

	client, err := monitoring.NewMetricClient(ctx)
	if err != nil {
		return 0, nil
	}

	dura, err := time.ParseDuration("24h")
	if err != nil {
		return 0, nil
	}

	req := &monitoringpb.ListTimeSeriesRequest{
		Name:   "projects/tensortask",
		Filter: fmt.Sprintf(`metric.type= "ml.googleapis.com/prediction/prediction_count" AND resource.labels.version_id = "%s"`, version),
		Interval: &monitoringpb.TimeInterval{
			StartTime: startTime,
			EndTime:   endTime,
		},
		Aggregation: &monitoringpb.Aggregation{
			AlignmentPeriod:    ptypes.DurationProto(dura),
			PerSeriesAligner:   monitoringpb.Aggregation_ALIGN_RATE,
			CrossSeriesReducer: monitoringpb.Aggregation_REDUCE_COUNT,
		},
	}
	it := client.ListTimeSeries(ctx, req)

	for {
		resp, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			return 0, err
		}
		x := resp.GetPoints()
		for _, v := range x {
			fmt.Println()
			fmt.Println(v.Value.GetInt64Value())
			fmt.Println(time.Unix(v.Interval.StartTime.GetSeconds(), 0))
			fmt.Println(time.Unix(v.Interval.EndTime.GetSeconds(), 0))
		}
	}
	return 0, nil
	
}

```

@jba, do you know how to perform secondary aggregation with the new API?

**Comment by syedashrafulla** [comment]
Secondary aggregation is only supported in the UI currently.

**Comment by sbsends** [comment]
<img width="895" alt="screen shot 2018-10-03 at 1 37 20 am" src="https://user-images.githubusercontent.com/21231577/46393946-f57bb580-c6ac-11e8-9cde-5a89882e73dd.png">

I may have stumbled on a larger issue. As I was working with this metric, I noticed that points started disappearing from the results. In the attached screenshot you can see the first peak (on Sep. 24) in the original screenshot is still present, but all of the subsequent points have disappeared. 

I have not deleted any points nor have I performed any operations besides querying the ListTimeSeries endpoint.

**Comment by sbsends** [comment]
@jba

**Comment by sbsends** [comment]
Potentially, however, the points are still missing from the API (using v3api). I will contact stackdriver support. Thanks!
