### ISSUE TITLE
Compute module feels autogenerated and hard to use

### ISSUE THREAD

**Issue by distortedsignal** [googleapis/google-api-go-client#296]
I've been working with the compute module for my job for a week or so now, and it feels clunky. For example, the html at https://godoc.org/google.golang.org/api/compute/v1 is about 6MB - no JS, no CSS, just the HTML.

<img width="726" alt="screen shot 2018-10-16 at 3 30 05 pm" src="https://user-images.githubusercontent.com/2186874/47051330-af1c6100-d158-11e8-88b5-cabb445944f0.png">

The table of contents on that page is about 100 pages on a 15 inch laptop. It takes several seconds to download the html from the server.

<img width="819" alt="screen shot 2018-10-16 at 3 32 57 pm" src="https://user-images.githubusercontent.com/2186874/47051415-0f130780-d159-11e8-8257-16fb3deefe8c.png">
<img width="818" alt="screen shot 2018-10-16 at 3 34 38 pm" src="https://user-images.githubusercontent.com/2186874/47051414-0e7a7100-d159-11e8-8de2-a84bcb8029c4.png">

I think that this should probably be broken up into several modules - perhaps one for Instances, one for Addresses, one for VPCs, etc. Not sure that this would make this package _easy_ to use, but it would probably make it _easier_ to use.

**Comment by distortedsignal** [comment]
I was talking with @ethantkoenig about this over the weekend - he might be able to provide more insight on this if he's not too busy.

**Comment by bradfitz** [comment]
> Compute module feels autogenerated and hard to use

It is auto-generated.

> and it feels clunky

Yes, it is. I did the best I could, generating idiomatic Go from the API description JSON files, but it is what it is.

I welcome and encourage you to write a higher-level wrapper package around it. Or look into other wrappers.

Maybe you want go-cloud (https://github.com/google/go-cloud) or maybe that's too high-level for you.

In any case, there's not much to do here, so closing as Unfortunate.

**Comment by distortedsignal** [comment]
:(

**Comment by broady** [comment]
I think a huge cause of this is that the API itself is just massive, and does a lot of things other than manage what I'd think is compute. For example, all of the load balancing stuff is in the "compute" API.

I don't know if much help the massive size of the package, but I think the gRPC-based APIs are generally easier to navigate (though you have to deal with protobuf a lot more). I don't know if there's already a feature request to expose gRPC for the compute API, but it's something we should look into.

**Comment by distortedsignal** [comment]
I think something that could help is to either break this out into modules (so that a module has RegionalAddresses, another module has GlobalAddresses, another Instances, etc.) or create some sort of `genericService interface` that tells you that you have the `Get, List, Insert, Delete` function pattern on specific objects, and some of your xxxxCall objects could be grouped under `ChangeCallInterface` (for `Insert, Delete`). I get _why_ this is the way that it is - it's basically impossible to autogenerate sane code when you have _this much code to generate_. It just kind of sucks that the options are a) use a library that is released and stable and is pathological (this API) or b) use alpha code that isn't released and has a changing api (in go-cloud).

**Comment by travigd** [comment]
Other unfortunate side effects of this package being so big (7MB in source code alone) is that intellisense is super sluggish (multiple seconds to navigate from a function call to it's definition via Cmd+Click) and otherwise trivial binaries incur a 10MB penalty for using this library, even if only using a small subset thereof.
