### ISSUE TITLE
Google sheets TickBox

### ISSUE THREAD

**Issue by RenatoSerra22** [googleapis/google-api-go-client#299]
Hello,

There seems to be no way to create a a tick box on a google sheet, through the API.
I can read existing values from tick boxes but cant set them up to be a tick box. Any chance this could be added? or a workaround?

Thanks
Renato

**Comment by jadekler** [comment]
Hello! The sheets clients here are programmatically created. Could you file this feature request / question on the sheets issue tracker? https://developers.google.com/sheets/api/support#missing_features
