### ISSUE TITLE
Support Google Cloud Bigtable admin API

### ISSUE THREAD

**Issue by rileykarson** [googleapis/google-api-go-client#300]
https://cloud.google.com/bigtable/docs/reference/admin/rest/

**Comment by enocom** [comment]
Have you see [cloud.google.com/go](https://github.com/GoogleCloudPlatform/google-cloud-go)? It's the hand-written client generally preferable over this repo, which is auto-generated. In particular, it has some nice support for the Bigtable Admin API.

See [here](https://godoc.org/cloud.google.com/go/bigtable).

**Comment by rileykarson** [comment]
Yes! I have. This is a request for an auto-generated client to be generated, my apologies for the lack of context initially.

We're [currently using the handwritten client in the Google provider for Terraform](https://github.com/terraform-providers/terraform-provider-google/blob/2.0.0/google/resource_bigtable_instance.go#L11) and it's not an ideal match for us - every other client we use is the `google-api-go-client`, and they are a perfect match for our use case.

We aren't writing code to interact with the API manually; we're writing code to convert user Terraform configurations into valid API requests, and the handwritten library is often a poor match. For one specific example, converting between strings and enums is [awkward at best](https://github.com/terraform-providers/terraform-provider-google/blob/2.0.0/google/resource_bigtable_instance.go#L251) for us compared to the string-based JSON libraries.

Not having a published API client is also a blocker for converting Cloud Bigtable resources to [GoogleCloudPlatform/MagicModules](https://github.com/GoogleCloudPlatform/magic-modules).

**Comment by mattwhisenhunt** [comment]
The quick and dirty answer is
```
curl 'https://bigtableadmin.googleapis.com/$discovery/rest?version=v2' > bigtableadmin-api.json
google-api-go-generator -api_json_file bigtableadmin-api.json
```
That might be all you are looking for. I don't think there are any plans to check in services for APIs that aren't in the [Discovery directory list](https://www.googleapis.com/discovery/v1/apis).

**Comment by rileykarson** [comment]
Adding this to discovery directory got plumbed through and is generated now, closing out. https://github.com/googleapis/google-api-go-client/tree/master/bigtableadmin/v2
