### ISSUE TITLE
Robot is missing error

### ISSUE THREAD

**Issue by stgleb** [googleapis/google-api-go-client#301]
I try to make an request to protected API returns with an error

```
{"error": "invalid_grant",  "error_description": "Robot is missing a project number."}
```

**Comment by enocom** [comment]
@stgleb Which client are you using and what kind of request did you send?

**Comment by stgleb** [comment]
@enocom Client 

```
		{
			"checksumSHA1": "oK9IOgVH0CByZ8YSAswfZT7StuE=",
			"path": "google.golang.org/api/compute/v1",
			"revision": "7954115fcf34e0dcda6981c9ed8a81a293f0489b",
			"revisionTime": "2018-08-26T00:05:28Z"
		}
```

Request

```
image, err := client.Images.GetFromFamily("ubuntu-os-cloud", "ubuntu-1804-lts").Do()
```

Client scopes configured  in client

```
			clientScopes := []string{
				"https://www.googleapis.com/auth/compute",
				"https://www.googleapis.com/auth/cloud-platform",
				"https://www.googleapis.com/auth/ndev.clouddns.readwrite",
				"https://www.googleapis.com/auth/devstorage.full_control",
			}
```

Token uri

```
https://accounts.google.com/o/oauth2/token
```

Auth URI

```
https://accounts.google.com/o/oauth2/auth
```

**Comment by stgleb** [comment]
This is an example that you can easily run with your credentials

https://gist.github.com/stgleb/4656b16313ddc56b4770c71ae6a58285

**Comment by enocom** [comment]
I've run the example against a test account using the `google.DefaultClient` and haven't been able to reproduce the issue.

I think you've got a configuration problem with your credentials. You might try the default client as a sanity check. See [here](https://github.com/googleapis/google-api-go-client#application-default-credentials-example).

**Comment by enocom** [comment]
To elaborate a bit on that error message, it means your request didn't include a project number. Confirm that your request includes a project number and try again. If you still see that error, feel free to  re-open this.

**Comment by enocom** [comment]
Here's what I tried:

``` go
package main

import (
	"context"
	"log"

	"golang.org/x/oauth2/google"
	"google.golang.org/api/compute/v1"
	dns "google.golang.org/api/dns/v1"
)

const (
	projectId    = "enocom-workspace"
	instanceName = "test"
)

func main() {
	ctx := context.Background()
	scopes := []string{
		compute.ComputeScope,
		compute.CloudPlatformScope,
		dns.NdevClouddnsReadwriteScope,
		compute.DevstorageFullControlScope,
	}
	client, err := google.DefaultClient(ctx, scopes...)
	if err != nil {
		log.Fatal(err)
	}
	computeService, err := compute.New(client)
	if err != nil {
		log.Fatal(err)
	}

	res, err := computeService.Images.GetFromFamily("ubuntu-os-cloud", "ubuntu-1804-lts").Do()
	log.Printf("Got compute.Images.List, err: %#v, %v", res, err)
}
```

**Comment by stgleb** [comment]
@enocom Well, I agree that project number absence is the problem, but looking through the code I can't get how to pass project number.

**Comment by stgleb** [comment]
@enocom Should I open new issue or continue in this thread?

**Comment by enocom** [comment]
Let's continue the discussion here for the time being.

Can you confirm that the sample I posted above does in fact work for you?

**Comment by stgleb** [comment]
No, it doesn't. I have a project number but have no idea how to pass it.

**Comment by sandivilli** [comment]
You have to pass the email provided when you edit a 'Service Account'. 
The URL will be something like this 
https://console.cloud.google.com/iam-admin/serviceaccounts?project=_your-project-id_

**Comment by enocom** [comment]
Have you tried using [Application Default Credentials](https://github.com/googleapis/google-api-go-client#application-default-credentials-example) running locally?
