### ISSUE TITLE
Support Google Ad Manger API

### ISSUE THREAD

**Issue by howie** [googleapis/google-api-go-client#303]
Will you support Google Ad Manager API SDK
https://developers.google.com/ad-manager/api/reference/v201808/LineItemService.LineItem

**Comment by jadekler** [comment]
Regrettably this is not up to us, it's up to the Google Ad Manager team to expose here: https://www.googleapis.com/discovery/v1/apis. If you wouldn't mind, please file an issue at https://cloud.google.com/support/docs/issue-trackers under "Create new Cloud APIs issue" requesting the SDK support you need.
