### ISSUE TITLE
Support for Composer Image and Python Version

### ISSUE THREAD

**Issue by memosstilvi** [googleapis/google-api-go-client#304]
I am trying to use Terraform to create a composer instance with a specific image_version composer-1.3.0-airflow-1.10.0, but Terraform doesn't support that yet.

From what I can understand by looking [here](https://github.com/googleapis/google-api-go-client/blob/master/composer/v1/composer-gen.go) it seems like the Go API Client doesn't support that parameter yet.

Is it possible to add support for that field in the Go API Client?

**Comment by memosstilvi** [comment]
Actually I see that it's in the `v1beta` version.
Is there an ETA on when this is going to make it to the `v1` version?

**Comment by jadekler** [comment]
No ETA, unfortunately. This is up to the backing service. You could open an issue about this on the "Cloud APIs" issue tracker here: https://cloud.google.com/support/docs/issue-trackers.

Closing since this seems out of our purview - give a shout if you have further questions.
