### ISSUE TITLE
TotalMediaItems should now be mediaItemsCount in Google Photos album object

### ISSUE THREAD

**Issue by GuySWatson** [googleapis/google-api-go-client#306]
I am trying to get the total number of media items in an album using the google photos go package and the TotalMediaItems field always returns 0. Through googling I found that there was a field name change which can been seen in the release notes here: https://developers.google.com/photos/library/support/release-notes.

**Comment by jadekler** [comment]
Unfortunately the photoslibrary/v1 client is stable, so it should ideally not change. Ultimately, though, this decision is up to the API team. If you'd like to push on the name change, please file an issue with the API at https://cloud.google.com/support/docs/issue-trackers under "Cloud APIs". I'll close this for now, but let me know if you'd like to discuss further!
