### ISSUE TITLE
SSH key field in the instance request & multiple instance creation at a time

### ISSUE THREAD

**Issue by NIHARIKA178** [googleapis/google-api-go-client#308]
where to add the ssh key in the program to add a new ssh key only to that instance.is there any default attributes of ssh keys in metadata at instance level.can we modify that in the program.to bring up the more than 1 instance at a time of same configuration where to add them.

**Comment by jadekler** [comment]
I'm having a bit of time parsing this question, regrettably. What client are you discussing?

**Comment by NIHARIKA178** [comment]
compute instance creation

**Comment by enocom** [comment]
Try using the [Metadata](https://godoc.org/google.golang.org/api/compute/v1#Instance) field and attach a [MetadataItem](https://godoc.org/google.golang.org/api/compute/v1#Metadata) with the public key. See the documentation under [Adding or removing instance-level public SSH keys](https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys#instance-only) for an overview of how this works.

**Comment by NIHARIKA178** [comment]
I have did the same thing.but the key does not replicated in the ssh  authorized keys.i was not able to login with the key added in the metadata.

**Comment by jadekler** [comment]
@NIHARIKA178 Could you post some code showing what you're doing?

**Comment by NIHARIKA178** [comment]
used the attribute in the metadata
