### ISSUE TITLE
Not able to set Custom Request Header for BackendService via the go-client-api

### ISSUE THREAD

**Issue by rajdhandus** [googleapis/google-api-go-client#315]
Per the Doc https://cloud.google.com/compute/docs/reference/rest/v1/backendServices/get , there is no way to set Custom Request Header.. However, via the Console - there is a way to create the same for the Backend Service..

Per this - https://cloud.google.com/load-balancing/docs/backend-service?hl=en_GB&_ga=2.187041709.-446613136.1541030031#user-defined-request-headers

It looks like API should be exposing this functionality..

**Comment by jadekler** [comment]
It's up to the backend team to make this available in their generated libraries. I've labeled this a feature request and will ping the backend team.

**Comment by rajdhandus** [comment]
actually - never mind.. v0.beta has this functionality exposed.. i was using v1...

**Comment by jadekler** [comment]
Ah! :)
