### ISSUE TITLE
FR : add Firebase Management API

### ISSUE THREAD

**Issue by chemidy** [googleapis/google-api-go-client#316]
Is it possible to add [Firebase Management API ](https://firebase.google.com/docs/projects/api/reference/rest/)

**Comment by jadekler** [comment]
I've followed up with the firebase folks. [Node](https://firebase.google.com/support/release-notes/admin/node), [Java](https://firebase.google.com/support/release-notes/admin/java), and [Python](https://firebase.google.com/support/release-notes/admin/python) recently received this. The team would like to add it to Go, too, but there's no immediate plans to do so. I'll leave this issue open for now as a tracking issue.

**Comment by jadekler** [comment]
Looks like this won't be happening in the foreseeable future, regrettably. :/ Closing this. Please ping if this is still an urgent need and I'll follow-up with the backend team.
