### ISSUE TITLE
Add more to auto-generated package docs

### ISSUE THREAD

**Issue by bradfitz** [googleapis/google-api-go-client#317]
The auto-generated package docs are currently pretty minimal. For example,

https://godoc.org/google.golang.org/api/compute/v1

> Package compute provides access to the Compute Engine API.
>
> See https://developers.google.com/compute/docs/reference/latest/
>
>Usage example:
```
import "google.golang.org/api/compute/v1"
...
computeService, err := compute.New(oauthHttpClient)
```

-----

That makes the big assumption that people already know how to get an "oauthHttpClient" (which, btw, violates the https://github.com/golang/go/wiki/CodeReviewComments#initialisms style rule). We should add a link to:

https://github.com/googleapis/google-api-go-client/blob/master/GettingStarted.md

/cc @jadekler

**Comment by bradfitz** [comment]
Maybe also link to https://github.com/googleapis/google-cloud-go

**Comment by jadekler** [comment]
We've added NewService so users don't have to create authenticated clients, and much more package docs. Closing for now - give a shout if you were thinking more!
