### ISSUE TITLE
Dataproc: impossible to specify a custom image

### ISSUE THREAD

**Issue by lomluca** [googleapis/google-api-go-client#319]
## Client

Dataproc

## Describe Your Environment

Go Docker on GKE

## Expected Behavior

Create a cluster with custom image.

## Actual Behavior

I specify `projects/PROJECT-NAME/global/images/CUSTOM-IMAGE-NAME` in the `ImageUri` field inside `MasterConfig` and `WorkerConfig` (as in the REST request) but the returned error is `"Could not find required format '([^-]\*)-([^-]\*)-([^-]*)$' for Dataproc version on image 'STRING'"`.
I tried also to specify only "CUSTOM-IMAGE-NAME" but the result is the same.

**Comment by jadekler** [comment]
Please see https://cloud.google.com/dataproc/docs/guides/dataproc-images#custom_image_uri: the image name should be `something-like-this` (without any other path elements).
