### ISSUE TITLE
User-Agent combining inverts the ordering convention

### ISSUE THREAD

**Issue by Capstan** [googleapis/google-api-go-client#320]
If you set `Service.UserAgent`, then that gets appended to the user agent string (e.g., "google-api-go-client/0.5"). [RFC 7231 §5.5.3](https://tools.ietf.org/html/rfc7231#section-5.5.3) states,

> By convention, the product identifiers are listed in decreasing order of their significance for identifying the user agent software.

Users of the client library are the most important product (i.e., the application or server software itself), followed by any wrapper libraries that might consume and repackage the go client, then the go client.

Suggest you reverse the order and append the client's agent string to any provided user agent.

**Comment by jadekler** [comment]
Hi @Capstan! Is this in regards to a problem you're experiencing, or more of a semantic concern?

**Comment by Capstan** [comment]
It's just a semantic concern.

**Comment by codyoss** [comment]
Closing this in favor of issue linked above. Thank you for bring this to our attention.
