### ISSUE TITLE
How do I force callers to provide a context?

### ISSUE THREAD

**Issue by Capstan** [googleapis/google-api-go-client#321]
`http.Request.Context()` returns `context.Background()` if the embedded context is `nil`. I am trying to provide generated services to developers within an encompassing framework which is strict about maintaining context transmission (to maintain trace ids, deadlines, etc.) and so I never want some generated `MyMethodCall` object to generate a `http.Request` without a provided context (i.e., by calling `service.Collection.MyMethod().Context(ctx)`), which should be the one we provided them.

So far, I haven't figured out a way to enforce this. The closest I've gotten is `gensupport.RegisterHook`, but then that fails because it bypasses the hooks when there's no context, which is exactly the case I'm trying to protect against. Is there some mechanism I can use for this?

**Comment by jadekler** [comment]
I'm not aware of a way to do this without wrapping. @broady @bradfitz are much more the experts on these than I am, though - do either of y'all know of a way?

**Comment by Capstan** [comment]
If you find one, I would use it in an existing Compute API client in the monorepo that we're using as the model for other Discovery-based APIs that don't have a gRPC endpoint.

**Comment by broady** [comment]
It's surprising that hooks from RegisterHook would be bypassed. That sounds like a bug.
Have you got a quick reproducer for that?

How is your framework providing credentials? You could write a wrapper http.RoundTripper that checks that the request's context has your required keys in it, and return an error if it doesn't.

**Comment by Capstan** [comment]
https://github.com/googleapis/google-api-go-client/blob/master/gensupport/send.go#L41 is where we early out and just run `Do` without any hooks if the `ctx` is `nil`.

**Comment by Capstan** [comment]
@broady re: credentials, it's up to the framework client as to how they want to provide credentials at the moment. The example I know about that led me to this question was someone relying on underlying transport security to authorize them. I'd rather be able to provide a smart option for per-call authentication, in case a client is using multiple service accounts with differing permissions, and "becoming" one for a particular task to avoid confused delegation issues.

Internally, for gRPC, the guidance is to use an explicit call-site annotation telling exactly what authority to use, and never to use Context-likes (e.g., thread-local settings), so you don't accidentally inherit the wrong principal when making your call. There doesn't appear to be an easy way to emulate that here. The best would be a [`googleapi.CallOption`](https://godoc.org/google.golang.org/api/googleapi#CallOption) that was the analog of [`credentials.PerRPCCredentials`](https://godoc.org/google.golang.org/grpc/credentials#PerRPCCredentials), and even better if such an option was generable from an [`oauth2.TokenSource`](https://godoc.org/golang.org/x/oauth2#TokenSource) like gRPC's [`oauth.TokenSource`](https://godoc.org/google.golang.org/grpc/credentials/oauth#TokenSource). But that's a FR unto itself.

What I would do then internally would be to have an internal wrapper that set some shared bool that "yes, the customer specified a credential" and check that flag in the hooks and bail if it was not set.

**Comment by codyoss** [comment]
@Capstan Do you still have open questions here?

**Comment by Capstan** [comment]
`send.go` has migrated to https://github.com/googleapis/google-api-go-client/blob/cfc62336a21b9af45e2830a9898569d8aac1c5cc/internal/gensupport/send.go#L41 but otherwise everything remains the same as last year, save that I'm not actively working on it.

The TL;DR is that I want to enforce state on the context on all calls, and the fact that `SendRequest` skips hooks when there is no context makes it so I cannot do that enforcement. I understand that you're never supposed to call context-taking methods with a nil context, but you've already been called that way so 🤷 .

Do you know whether the `http.Request`s you get already have a context bound to them? If they don't, `http.Client.Do` is just going to issue them with `context.Background()` anyway, so maybe you just use that and call your hooks if you're not generated context-full requests.

**Comment by codyoss** [comment]
Thanks for the quick reply, I will have to look into this more and get back to you.

**Comment by codyoss** [comment]
Since this package has moved internal, is no way for outside users to call `RegisterHooks`. If you are looking to emulate this behavior, even in a case without context, I suggest creating a middleware pre-processor. You can pass in your customized `http.Client` with [option.WithHTTPClient](https://pkg.go.dev/google.golang.org/api/option#WithHTTPClient).

**Comment by Capstan** [comment]
I don't see how that solves my problem, which is people opting out of the middleware processing in general, either by accident or intent. I want to be able to _catch_ those cases, and if I'm never invoked, I can never see the `nil` context or the missing context keys.

**Comment by Capstan** [comment]
Would we at least be able to insert an explicit panic on a nil context in `send.go`? Controllable by configuration?

**Comment by codyoss** [comment]
Following up internally.
