### ISSUE TITLE
publicly writable wiki

### ISSUE THREAD

**Issue by jonatanhal** [googleapis/google-api-go-client#323]
Hello

It appears that anyone can modify your wiki, i took the liberty to create a page of my own [here](https://github.com/googleapis/google-api-go-client/wiki/test) in order to illustrate -- but it appears that [others have already created pages aswell](https://github.com/googleapis/google-api-go-client/wiki/%D9%85%D8%B1%D9%83%D8%B2-%D8%A8%D8%A7%D9%84%D9%84%D8%B3%D9%88%D8%AF-%D9%88%D8%A2%D9%84-%D8%B3%D9%88%D9%8A%D8%AF%D9%8A-%D8%A8%D8%A7%D9%84%D8%B1%D9%85%D9%8A%D8%B6%D8%A9).

Is this intentional, or perhaps a misconfiguration on this repository?

Thank you for your time!

**Comment by jadekler** [comment]
AH. Good to know. Thank you. I've removed the wiki.
