### ISSUE TITLE
Drive Create Chunk still load whole file in memory

### ISSUE THREAD

**Issue by aspacca** [googleapis/google-api-go-client#324]
transfer.sh was reported an issue about memory usage using google api go client for google drive (see: https://github.com/dutchcoders/transfer.sh/issues/185)

While the client supports chunked upload it seems that it still encodes the payload of the whole file in memory: https://github.com/googleapis/google-api-go-client/blob/master/googleapi/googleapi.go#L182 (correct me if I'm wrong)

the resumable upload that actually chunks the request is used only after encoding the body of the file as json: https://github.com/googleapis/google-api-go-client/blob/master/drive/v3/drive-gen.go#L4303 and https://github.com/googleapis/google-api-go-client/blob/master/drive/v3/drive-gen.go#L4319, am I right?

**Comment by aspacca** [comment]
@jadekler any feedback?

**Comment by jadekler** [comment]
@aspacca Sorry, buried in emails. Will try to find some time to investigate this.

**Comment by aspacca** [comment]
@jadekler ping

**Comment by bradfitz** [comment]
I apparently wrote that code 8 years ago, so I guess this is my fault and I should fix it.

I'm a little surprised this JSON wrapper is required to upload chunks to the Drive API but there's no reason we can't make it work efficiently in any case.

**Comment by aspacca** [comment]
@bradfitz apparently the `data` json wrapper is not used, since the `MarshalStyle` is `WithoutDataWrapper` (I didn't pay much attention at the beginning).
I still have to check if `json.NewEncoder(buf).Encode(v)`, while a stream, loads everything in-memory.
if I find any way to fix I can open a PR, but won't be before one month or so

**Comment by bradfitz** [comment]
I don't think the WithoutDataWrapper or json.NewDecoder(buf).Encode(v) parts you highlighted above are related to whatever problem you're seeing. The drive/v3.File struct type doesn't have the file contents in it anywhere. It's a smallish struct and should be fine to JSON encode it all in memory.

Do you have a minimal-ish example code demonstrating the problem?

How are you making your requests?

**Comment by bradfitz** [comment]
I also don't see a problem in the linked issue. I'm removing myself from this for now because I haven't seen a problem yet.

**Comment by aspacca** [comment]
@bradfitz oki, I did some investigation and testing and the problem I found was in https://github.com/googleapis/google-api-go-client/blob/master/gensupport/buffer.go#L43-L56 causing an OOM when the memory available is too near to the default chunk size (see https://github.com/dutchcoders/transfer.sh/issues/185#issuecomment-474065770 for details).
I was mislead when opening the issue looking in the data wrapper.

Thanks for your time
