### ISSUE TITLE
fields in the admin directory API User object are missing type information

### ISSUE THREAD

**Issue by crewjam** [googleapis/google-api-go-client#325]
The User object has a number of fields, e.g. Phones, ExternalIds, etc. which should are generated as `interface{}` but which actually should contain arrays of e.g. UserPhone, UserExternalId, etc. This is because the type in the discovered JSON is listed as "any". 

A temporary fix that works for us is at:

https://github.com/crewjam/google-api-go-client/commit/74b7aa2337e879229cc1c224838b7b25774ed756

But obviously this is the wrong way to fix it, it's the upstream API spec that is broken.

**Comment by jadekler** [comment]
Unfortunately we can't change those types in the v1 packages, since that would be a breaking change to a stable surface. In the meantime, you should also be able to type cast.

**Comment by crewjam** [comment]
Unless I'm missing something, a type cast doesn't work because although the declared type is `interface{}` the actual type that gets assigned is e.g. `[]interface{}` and the items in the list are  `map[string]interface{}`, neither of which are particularly useful.

**Comment by jadekler** [comment]
I might be missing something... if you're trying to access User.Phones, does it not work to use `User.Phones.([]*UserPhone)`?

I'm not entirely sure what you mean by,

> the items in the list are map[string]interface{}, neither of which are particularly useful.

So it's totally possible that I'm missing some crucial detail. Would you mind elaborating?
