### ISSUE TITLE
gtransport.Dial fails on GCE with "unexpected end of JSON input"

### ISSUE THREAD

**Issue by jqll** [googleapis/google-api-go-client#326]
I think it's because google.FindDefaultCredentials returns a cred with empty JSON on GCE so a later call to google.CredentialsFromJSON (https://github.com/googleapis/google-api-go-client/blob/master/internal/creds.go#L54) fails with "unexpected end of JSON input".

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/google-api-go-client/+/37030
