### ISSUE TITLE
CancelReason should be a pointer

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-api-go-client#328]
re: https://github.com/googleapis/google-api-go-client/issues/215

https://github.com/googleapis/google-api-go-client/blob/8001663557ac8d144131ea92d9829a0d8e668ab7/androidpublisher/v3/androidpublisher-gen.go#L1870

**Comment by ont** [comment]
What the status of this issue?  Will it fixed in near future or we must use workaround in code?

**Comment by jadekler** [comment]
Not status as-of-now. Work-around is advised for the meantime.

**Comment by gokhanm** [comment]
@ont  Did you solve that? What is your work-around solution without forking the repo?

Also PaymentState should be a pointer too @jadekler

**Comment by codyoss** [comment]
Looks like you could also inspect the value of `UserCancellationTimeMillis` to see if `CancelReason` is really zero.

**Comment by richzw** [comment]
> Looks like you could also inspect the value of `UserCancellationTimeMillis` to see if `CancelReason` is really zero.

Per the comment of UserCancellationTimeMillis

	// UserCancellationTimeMillis: The time at which the subscription was
	// canceled by the user, in milliseconds since the epoch. Only present
	// if cancelReason is 0.

It seems UserCancellationTimeMillis is only set when cancelReaons is 0

**Comment by codyoss** [comment]
Closing this for now as I think my last comment is still valid.
