### ISSUE TITLE
Writing tests for cloudresourcemanager/sqladmin

### ISSUE THREAD

**Issue by peric** [googleapis/google-api-go-client#330]
I am using cloudresourcemanager/sqladmin API in order to create/list/delete backups from Cloud Sql and all together runs as a Cloud function. 

I want to write tests for this Cloud Function but I do not have a clue how to fake response from cloudresourcemanager/sqladmin.

I like the approach of using `httptest.NewServer` for tests, but I do not see how it would be possible in this example.

Can you give me some tips? Or I should just make real requests in tests?

**Comment by peric** [comment]
I have found a solution so I am closing this.

In my example, I will use a fake client with a mocked `RoundTripper`, basically something like this.

```go
type RoundTripFunc func(req *http.Request) *http.Response

func (f RoundTripFunc) RoundTrip(req *http.Request) (*http.Response, error) {
	return f(req), nil
}

func NewTestClient(fn RoundTripFunc) *http.Client {
	return &http.Client{
		Transport: RoundTripFunc(fn),
	}
}

func TestExample(t *testing.T) {
	fakeClient := NewTestClient(func(req *http.Request) *http.Response {
		// Test request parameters
		fmt.Println(req.URL.String())
		return &http.Response{
			StatusCode: 418,
			// Send response to be tested
			Body:       ioutil.NopCloser(bytes.NewBufferString(`NOT OK`)),
			// Must be set to non-nil value or it panics
			Header:     make(http.Header),
		}
	})

	cloudResourceManagerService, err := cloudresourcemanager.New(fakeClient)
	if err != nil {
		log.Fatal(errors.WithStack(err))
	}

	req := cloudResourceManagerService.Projects.List()

	if err := req.Pages(context.TODO(), func(page *cloudresourcemanager.ListProjectsResponse) error {
		fmt.Println(page)
		return nil
	}); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by jadekler** [comment]
@peric Sorry we weren't able to get to this earlier, but thank you for posting the solution for others that might run into this.
