### ISSUE TITLE
Tag versions?

### ISSUE THREAD

**Issue by parkr** [googleapis/google-api-go-client#331]
Hello!

I am a consumer of this project, and use @dependabot to help keep my dependencies up to date.

Due to the lack of versions in this repository, @dependabot sends me a pull request for _every push made to the repository_. This is quite a lot!

Would it be at all possible to create tagged versions? This will likely be all the more relevant when [Go modules ship in Go 1.13](https://blog.golang.org/modules2019).

**Comment by jadekler** [comment]
@parkr Thanks for mentioning this. That's quite odd - we do in fact have a single version https://github.com/googleapis/google-api-go-client/releases/tag/v0.1.0. o.O

(I am totally unaware of what dependabot is or does, sorry this answer is not very nuanced)

**Comment by parkr** [comment]
Ah, of course, thank you @jadekler! Will this repo have a versioning policy into the future?

Dependabot is a pretty neat way to automate dependency updates (free for open source). 😄

**Comment by jadekler** [comment]
Yes, we will continue releasing versions. We're still experimenting and as such are moving slowly and cautiously before we create new versions.
