### ISSUE TITLE
Subscription create call returns error in google app engine (Error: googleapi: Error 400: Invalid resource name given (name=))

### ISSUE THREAD

**Issue by AshleyBushCoding** [googleapis/google-api-go-client#332]
## Client
 PubSub v1

## Describe Your Environment
Google App Engine Standard Environment (Golang 1.9)

## Expected Behavior
Subscriptions are created using the ProjectsSubscriptionsCreateCall.Do()

## Actual Behavior
An error is returned. "Error: googleapi: Error 400: Invalid resource name given (name=)"

## Long Description of Behavior

Hi all,

I'm running a golang app in app engine standard with the old pubsub. (import "google.golang.org/api/pubsub/v1"). 

Whenever I try to publish a subscription to a topic, I get an error that says "Error: googleapi: Error 400: Invalid resource name given (name=). Refer to https://cloud.google.com/pubsub/docs/admin#resource_names for more information., badRequest Response:: <nil>".  

I am providing a name (pubsub.Subscription struct created with a Name provided) but it doesn't seem to be used in the last function call. I double-checked and put some log statements in, and the name is there until I call the "pSubServicCall.Do()". The "name" returned is the private variable one. 

Here's my code:
```

pTopicsSubsService := pubsub.NewProjectsTopicsSubscriptionsService(pubsubService)

//pubsubTopics is the old topics. The name is (proprietary names replaced):
//  "projects/projectname/topics/projecttopic"

//projectname and projecttopic have only letters, numbers, underscores, and dashes. Both start with letters.

for _, singleTopic := range pubsubTopics {	
		//make the call for the topic
		pTopicsSubServiceListCall := pTopicsSubsService.List(singleTopic.Name)

		topicSubResponse, err := pTopicsSubServiceListCall.Do()

		if (topicNames[singleTopic.Name]) != "" {

			if err != nil {
				//failure
				log.Errorf(ctx, "[ThisFunction] response is an error. Error: %+v", err)
			} else {
				//success
				pSubsService := pubsub.NewProjectsSubscriptionsService(pubsubService)
				log.Infof(ctx, "[ThisFunction] Created Subscription Service. Value: %+v", pSubsService)
				emailTriggerSubs := strings.Split(topicNames[singleTopic.Name], "_")[0] + "_trigger_" + appVER
				// Name: The name of the subscription. It must have the format
				// "projects/{project}/subscriptions/{subscription}". `{subscription}`
				pSubSubscription := pubsub.Subscription{Name: "projects/" + appengine.AppID(ctx) + "/subscriptions/" + emailTriggerSubs}

				pSubServiceCall := pSubsService.Create(pSubSubscription.Name, &pSubSubscription)

				//code fails here--returns an error
				subscriptionResponse, err := pSubServiceCall.Do()

				if err != nil {
					log.Infof(ctx, "[ThisFunction] There was an error at creation. Error: %+v Response:: %+v", err, subscriptionResponse)
				} else {
					log.Infof(ctx, "[ThisFunction] Successfully created a subscription. Response: %+v", subscriptionResponse)
				}
			}
		} else {
			log.Errorf(ctx, "[ThisFunction] The topic was not found in the database. Cannot create subscription.")
			return pubsubService, err
		}
	}


```

Did I miss something obvious, or is there a problem/bug?

Similar code to this works just fine for subscription deletion and topic creation/deletion. I'm at a loss.

**Comment by jadekler** [comment]
Sorry for the troubles! I note that the issue discusses ProjectsSubscriptionsCreateCall but the code does include it. To make it a bit easier to debug, could you provide a minimal repro of this problem?

Also, out of curiousity, is it possible to migrate to cloud.google.com/go/pubsub? It is far more mature and is the only Pub/Sub client that is actively developed.

**Comment by AshleyBushCoding** [comment]
Heya!

The variable name in the code that's failing is "pSubServiceCall", and it is of type pubsub.ProjectsSubscriptionsCreateCall. Sorry I wasn't clear. 

The code fails when I call ```subscriptionResponse, err := pSubServiceCall.Do()```

There is one variable I forgot to put in (I can edit the code if you want). 

I don't have a current repo with this code I can share publically. 

I am looking at migrating to the current pubsub, but it'll require a series of jumps.

Hopefully that helps. Let me know if you need more info.

**Comment by AshleyBushCoding** [comment]
OK. I'll use my workaround and keep moving towards the new gcloud version. Thanks.

**Comment by jadekler** [comment]
Sounds good. As mentioned, give a shout if we can help with the migration.
