### ISSUE TITLE
storage transfer service transferjob get 403

### ISSUE THREAD

**Issue by lordnynex** [googleapis/google-api-go-client#333]
EDIT: Please note when I say "copy/paste" I mean obviously changing the jobName to a valid job. 

Copy/pasting the go example [here](https://cloud.google.com/storage-transfer/docs/reference/rest/v1/transferJobs/get?authuser=1&apix_params=%7B%22jobName%22%3A%22transferJobs%2F15372522094245633299%22%2C%22projectId%22%3A%22processing-2two%22%2C%22fields%22%3A%22description%22%7D) returns

```
{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "errors": [
      {
        "message": "The caller does not have permission",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}
```

I have had numerous people try this with varying levels of project permissions. 

Interestingly, this call works in API explorer to the right of the documentation. I've inspected the call made in the browser and it appears API explorer adds a `key` query param. This is the only difference I see between the UI and this SDK. 

Please note, the service/session is completely valid. The same client can make other calls (most notably TransferOperationsList).

**Comment by izakreuski** [comment]
Looks like this is a bug in a code sample.

The fix for this problem is as simple as providing a project id along with the job name:
https://gist.github.com/izakreuski/79a86355e43fa46a6a22e88ca9609d97

**Comment by jadekler** [comment]
@tbpg Is this sample in your domain?

**Comment by jadekler** [comment]
@tbpg Is this sample in your domain?

**Comment by tbpg** [comment]
Where is the sample code from? I don't see it in this repo or https://github.com/GoogleCloudPlatform/golang-samples. Once we know where it's from, we can update it. :)

**Comment by jadekler** [comment]
Great question... o.O cc @frankyn I don't suppose you know, since it seems storage related?

**Comment by tbpg** [comment]
@izakreuski, where did you see the sample code?

**Comment by izakreuski** [comment]
For posterity, it's embedded into Examples section on the REST API reference: https://cloud.google.com/storage-transfer/docs/reference/rest/v1/transferJobs/get

**Comment by tbpg** [comment]
Thanks. We have an internal bug (132880910) to track this issue - should hopefully be resolved soon.

**Comment by jadekler** [comment]
Closing this in deference of the internal bug. Thanks for reporting it.

**Comment by aruandre** [comment]
has this actually been solved? I'm encountering the same issue. The documented code sample does not mention anything about jobName. https://cloud.google.com/storage-transfer/docs/create-manage-transfer-program#python

**Comment by codyoss** [comment]
The internal bug is still open, I have pinged the issue. Are you getting the same exact error, so slightly different?

**Comment by aruandre** [comment]
> The internal bug is still open, I have pinged the issue. Are you getting the same exact error, so slightly different?

The exact same 403.
