### ISSUE TITLE
GSheets: SheetProperties struct takes int64 while API accepts int32

### ISSUE THREAD

**Issue by nicovillanueva** [googleapis/google-api-go-client#334]
I'm building a thingy to export data to Google Sheets, and this includes automatically creating new sheets.

I'm hashing a string which results in an int64 (I'm using Djb2, which originally gives out uint64, so hacking ensued) in order to use it to create a new `SheetProperties{}`.
The [doc](https://godoc.org/google.golang.org/api/sheets/v4#SheetProperties) says that the SheetID should be an int64. However, when sending the BatchUpdate, it replies:

`Error 400: Invalid value at 'requests[0].add_sheet.properties.sheet_id.value' (TYPE_INT32), 780761912178113017`

So I figure that only int32 is accepted. Sending an int32 casted into a int64 works well.

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/google-api-go-client/+/41831

**Comment by nicovillanueva** [comment]
Yeah, I figured it was a major risk to change this. I just find it odd it wasn't reported before.
Thanks for taking the time to check it out!

**Comment by jadekler** [comment]
We've discussed this and decided that we should not break everyone's code. Instead, we'll recommend you use a smaller value that fits into int32 (which is essentially what would have been required of you if that change went through).

I'll document this at the google.golang.org/api level, too. (CL forthcoming)

Closing for now - let us know if using a smaller value doesn't work.
