### ISSUE TITLE
googleapi: Error 401: Invalid Credentials, authError exit status 1 for servercreate 

### ISSUE THREAD

**Issue by NIHARIKA178** [googleapis/google-api-go-client#339]
i am using service account.i am able to get the servers and networks through the go code.when i try to create a server or network it shows the error:
googleapi: Error 401: Invalid Credentials, authError
exit status 1

**Comment by jadekler** [comment]
Could you post a stack trace?

**Comment by NIHARIKA178** [comment]
root@niharika:~/go_projects/gcp#go run serverget.go
&compute.Instance{CanIpForward:false, CpuPlatform:"Intel Haswell", CreationTimestamp:"2019-02-28T20:50:17.443-08:00", DeletionProtection:false, Description:"", Disks:[]*compute.AttachedDisk{(*compute.AttachedDisk)(0xc00020d180)}, GuestAccelerators:[]*compute.AcceleratorConfig(nil), Hostname:"", Id:0x3381e68182d504e7, Kind:"compute#instance", LabelFingerprint:"42WmSpB8rSM=", Labels:map[string]string(nil), MachineType:"https://www.googleapis.com/compute/v1/projects/proj-211305/zones/us-east1-b/machineTypes/g1-small", Metadata:(*compute.Metadata)(0xc0000e0a10), MinCpuPlatform:"", Name:"niharika", NetworkInterfaces:[]*compute.NetworkInterface{(*compute.NetworkInterface)(0xc0000f6240)}, Scheduling:(*compute.Scheduling)(0xc0000e0d20), SelfLink:"https://www.googleapis.com/compute/v1/projects/proj-211305/zones/us-east1-b/instances/niharika", ServiceAccounts:[]*compute.ServiceAccount{(*compute.ServiceAccount)(0xc0001ca300)}, StartRestricted:false, Status:"RUNNING", StatusMessage:"", Tags:(*compute.Tags)(0xc0001ca2a0), Zone:"https://www.googleapis.com/compute/v1/projects/proj-211305/zones/us-east1-b", ServerResponse:googleapi.ServerResponse{HTTPStatusCode:200, Header:http.Header{"Expires":[]string{"Wed, 06 Mar 2019 05:05:28 GMT"}, "Vary":[]string{"Origin", "X-Origin"}, "X-Xss-Protection":[]string{"1; mode=block"}, "Server":[]string{"GSE"}, "Date":[]string{"Wed, 06 Mar 2019 05:05:28 GMT"}, "Cache-Control":[]string{"private, max-age=0, must-revalidate, no-transform"}, "Etag":[]string{"\"qPRCQERwzHGYsK6LJHvyZPXeh_g=/mhIxFrLSdF4NQB__4UIfS5_is98=\""}, "Content-Type":[]string{"application/json; charset=UTF-8"}, "X-Content-Type-Options":[]string{"nosniff"}, "X-Frame-Options":[]string{"SAMEORIGIN"}}}, ForceSendFields:[]string(nil), NullFields:[]string(nil)}


root@niharika:~/go_projects/gcp/server# go run servercrt.go
2019/03/06 05:05:59 googleapi: Error 401: Invalid Credentials, authError
exit status 1





**I am able to get the details.But not able to create a vm through the go code.**

**Comment by jadekler** [comment]
Sorry, but this does not look like a stack trace. Could you please panic the error you're seeing from our library (without any wrapping on your side) and post the result?

Also, would you mind posting a small code snippet that reproduces this issue?

**Comment by NIHARIKA178** [comment]
Problem with the service account. When i create new service account its working.

**Comment by jadekler** [comment]
Gotcha. Thanks for following up!
