### ISSUE TITLE
deprecate googleapi/transport

### ISSUE THREAD

**Issue by broady** [googleapis/google-api-go-client#340]
We should mark [google.golang.org/api/googleapi/transport](https://godoc.org/google.golang.org/api/googleapi/transport) as deprecated, in favor of 
`NewService(..., option.WithAPIKey(...))`.

**Comment by jadekler** [comment]
This is related to https://code-review.googlesource.com/c/google-api-go-client/+/38650, I presume?

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/google-api-go-client/+/49070
