### ISSUE TITLE
UploadRequest uses the wrong boundary on retries

### ISSUE THREAD

**Issue by fraenkel** [googleapis/google-api-go-client#343]
The boundary used for multipart uploads is set at at https://github.com/googleapis/google-api-go-client/blob/master/gensupport/media.go#L292 using the boundary provided from the initial CombineBodyMedia.

On retries, the getBody will create a new reader via CombineBodyMedia with a new boundary which does not match the boundary set in the content type.

**Comment by bradfitz** [comment]
Thanks for looking into this! On phone now but I assume this is the same as https://github.com/golang/go/issues/30693 ?

**Comment by fraenkel** [comment]
Yes, I just figured I would report it in the correct repo.
I looked at fixing this but it requires to no longer use the public API but create a private one to pass around the boundary details.

**Comment by bradfitz** [comment]
Thanks. I'm working on a CL now.

**Comment by bradfitz** [comment]
https://code-review.googlesource.com/c/google-api-go-client/+/39076 gensupport: fix incorrect MIME boundary being used in bodies on retries
