### ISSUE TITLE
hasMember on an external member of the organization not working

### ISSUE THREAD

**Issue by sneko** [googleapis/google-api-go-client#350]
Hi,

I'm using Google OAuth2 to secure some tools and it works well with Google groups with people of my company.

But today I have tried to add an external user (so not under company @domain) that has a basic @gmail.com address and I get a strange issue:
```
googleapi: Error 400: Invalid Input: memberKey, invalid
```

- I'm entering a valid email address
- I checked the user in the group (Admin SDK)
- My group indeed accepts external user

Is there any specific group setting to set so it works for external people?

Thank you,

EDIT: after testing on https://developers.google.com/admin-sdk/directory/v1/reference/members/hasMember the error is not more meaningful 😢. I'm still looking for the origin of this issue

EDIT2: Seems related to https://github.com/googleapis/google-api-java-client/issues/1082 I don't understand how such an error is possible in Google APIs :/

EDIT3: IssueTracker: https://issuetracker.google.com/issues/109861216

**Comment by jadekler** [comment]
Could you post the import path of the client you're using?

**Comment by sneko** [comment]
@jadekler I'm using:
`admin "google.golang.org/api/admin/directory/v1"`

But as mentioned in my EDITs, this is a known issue when the group domain is different from the email domain. For example:
`hasMember("aaa@mydomain.com","bbb@gmail.com")`

It seems Google teams didn't answer to the issuetracker post. I'm wondering if it's a bug or if this is the wanted behavior 🤔

**Comment by jadekler** [comment]
Thanks @sneko. We don't own any of the backends for the clients, but I'll poke a couple of people and see if they can speak to the issue. :)

**Comment by sneko** [comment]
Hi @jadekler , any news from appropriate team?

Otherwise I will come back to old way of looking for "submembers with a group type", recursively, but I would rather avoid this since there are pagination and maximum limitation.

**Comment by jadekler** [comment]
@sneko Sorry, haven't heard anything. The teams are all bit hectic right now with Cloud Next this week, though, so I expect people are a bit swamped. Will post back if I hear something!

**Comment by jadekler** [comment]
For posterity I've opened internal bug 135043133.

**Comment by jadekler** [comment]
Closing to defer to internal bug https://issuetracker.google.com/issues/109861216.
