### ISSUE TITLE
Resolve cyclic dependency with opencensus

### ISSUE THREAD

**Issue by kernle32dll** [googleapis/google-api-go-client#351]
While looking at https://github.com/golang-migrate/migrate/issues/202, I got stuck at `google.golang.org/api`.

While I suppose a cycling dependency is not a problem directly with go modules, it ultimately leads to including `go.opencensus.io@v0.19.1`, which then causes https://github.com/golang/lint/issues/436 trough an old version of `google.golang.org/genproto`.

To be honest - I have no idea who should fix this, or how. Even if `go.opencensus.io` would update to `google.golang.org/api@v0.3.0`, that would still cycle back:

```
<start here> google.golang.org/api@v0.3.0
google.golang.org/api@v0.3.0 go.opencensus.io@v0.19.2
go.opencensus.io@v0.19.2 google.golang.org/api@v0.2.0
google.golang.org/api@v0.2.0 go.opencensus.io@v0.19.1
go.opencensus.io@v0.19.1 google.golang.org/genproto@v0.0.0-20181219182458-5a97ab628bfb
```

**Comment by jadekler** [comment]
Thanks - we're actively working on this issue. Please continue to track in https://github.com/googleapis/google-cloud-go/issues/1359.
