### ISSUE TITLE
How to get AuthorChannelId?(youtube v3 API)

### ISSUE THREAD

**Issue by Doarakko** [googleapis/google-api-go-client#352]
I want to get comment `AuthorChannelId`.

- my code
```
call := service.CommentThreads.List("id,snippet").
	VideoId(VideoID).
	Order("relevance").
	MaxResults(maxResults)
response, err := call.Do()
...
for _, item := range response.Items {
	authorID := item.Snippet.TopLevelComment.Snippet.ChannelId.value
	println(authorID)
```
`item.Snippet.TopLevelComment.Snippet.ChannelId.value undefined (type string has no field or method value)`

- `youtube-gen.go`
```
type CommentSnippet struct {
	// AuthorChannelId: The id of the author's YouTube channel, if any.
	AuthorChannelId interface{} `json:"authorChannelId,omitempty"`
```

- [Resource representation](https://developers.google.com/youtube/v3/docs/comments)
```
"authorChannelId": {
      "value": string
    },
```

**Comment by jadekler** [comment]
AuthorChannelId is part of [CommentSnippet](https://godoc.org/google.golang.org/api/youtube/v3#CommentSnippet), which is part of [Comment](https://godoc.org/google.golang.org/api/youtube/v3#Comment), which is part of [CommentListResponse](https://godoc.org/google.golang.org/api/youtube/v3#CommentListResponse), which can be retrieved with [CommentsListCall.Do](https://godoc.org/google.golang.org/api/youtube/v3#CommentsListCall.Do).
