### ISSUE TITLE
storage: GCS bucket created with mysterious ProjectNumber

### ISSUE THREAD

**Issue by wozniakjan** [googleapis/google-api-go-client#353]
Inserting a bucket using function `Insert(projectid, bucket)` passing `ProjectID` creates the bucket with mysterious project number that prevents listing, deletion or any modification to that bucket because of `AccessDeniedException`. Converting project number to string and passing to `Insert()` works well

https://github.com/googleapis/google-api-go-client/blob/0cbcb99a9ea0c8023c794b2693cbe1def82ed4d7/storage/v1/storage-gen.go#L3562-L3567

I think it would be ideal if bucket insertion failed without inserting anything to GCS.

**Comment by jadekler** [comment]
Hello! I don't fully grok:

- Are you creating a bucket with the `Insert` method?
- Could you tell us more about you expected to see, and what you actually saw? It's not clear to me whether the AccessDenied exception is unexpected (what kind of permissions does the account you're using have?), or whether you expected the bucket to be called something else?

**Comment by wozniakjan** [comment]
my apologies for confusing description, I will turn up the verbosity
- as part of a larger system, I was developing a module that should provision GCS buckets on demand. The credentials used for authenticating with GCP were a service account with roles `Storage Admin`, `Storage Object Admin` (and `Cloud SQL Admin`, `Pub/Sub Admin`)
- we currently own two projects, for better clarity, I will give them anonymous but concrete values ProjectID `project-a` and `project-b`, and ProjectNumber `123` and `456`
- the system executed code calling 
https://github.com/googleapis/google-api-go-client/blob/0cbcb99a9ea0c8023c794b2693cbe1def82ed4d7/storage/v1/storage-gen.go#L3562 
where I passed `project-a` as a `projectid` and `&Bucket{Name: "test-bucket"}` as `bucket` arguments to the `Insert().Do()`
- that returned a 403 error, so I tried to create the bucket using `gsutil -p project-a gs://test-bucket` which returns `ServiceException: 409 Bucket test-bucket already exists.`
- so I tried `gsutil rb gs://test-bucket` which returns `AccessDeniedException: 403 jwozniak@drud.com does not have storage.buckets.delete access to project 796536045445.` and that ProjectNumber is unknown to me, `gcloud projects list` doesn't return any project with that number neither for me, nor if I use `--impersonate-service-account=` with the service account that was supposed to created the GCS bucket
- I thought that must have been my coding error and decided to extract that part of logic to a single executable file and debug further
<details>
  <summary>`main.go`</summary>

```go
package main

import (
    "context"
    "fmt"
    "golang.org/x/oauth2/google"
    "google.golang.org/api/googleapi"
    storage "google.golang.org/api/storage/v1"
)

func isNotFound(err error) bool {
    gerr, ok := err.(*googleapi.Error)
    return ok && gerr.Code == 404
}
func main() {
    ctx := context.TODO()
    hc, err := google.DefaultClient(ctx, storage.DevstorageFullControlScope)
    if err != nil {
        panic(fmt.Sprintf("Unable to get GCP client: %v", err))
    }
    s, err := storage.New(hc)
    if err != nil {
        panic(fmt.Sprintf("Unable to sqladmin new: %v", err))
    }
    bucketName := "abc-test-bucket"
    project := "project-a"
    b, err := s.Buckets.Get(bucketName).Do()
    if err != nil && !isNotFound(err) {
        panic(err)
    }
    if err != nil {
        // Not found => insert
        b := &storage.Bucket{Name: bucketName}
        if _, err := s.Buckets.Insert(project, b).Do(); err != nil {
            panic(err)
        }
    } else {
        fmt.Println(b)
    }
}
```
</details>

- this had exactly the same result, returned 403 error but sort of created the bucket, this time in yet another unknown project with ProjectNumber 881144688958
- at that point, I thought maybe I am supposed to pass a ProjectNumber instead of ProjectID to  `Buckets.Insert().Do()` and that works well.
- I yet need to figure out how to delete those two buckets

**Comment by jadekler** [comment]
This is very odd. Paging @frankyn for storage expertise.

**Comment by frankyn** [comment]
Hi @wozniakjan, 
First off, thanks for being very detailed!

Based on the error messages you have shared with us, I suspect you're trying to access/delete buckets owned by other projects (per the unknown project numbers). 

Rationale: When you create a bucket you mentioned a 403 error code which maps back to a Forbidden Error, quoting [docs](https://cloud.google.com/storage/docs/json_api/v1/status-codes) ".. you receive if you try to list the buckets of a non-existent project or one in which you don't have permission to list buckets.". Paraphrasing the quote, the error is returned when accessing a bucket you don't have permission to use.

I'm not sure if these are the bucket names you're trying to use, but if they are, the thing to keep in mind is **"Bucket names are globally unique"** and shared across the platform.

Please let me know if I have answered your question. Thanks for the ping @jadekler

**Comment by wozniakjan** [comment]
> Bucket names are globally unique

mea culpa, of course, that makes absolute sense. I should read the docs more carefully. :)

Thanks for your prompt response, helpful feedback and thorough explanation. Closing with no issue.
