### ISSUE TITLE
photoslibrary api not updated

### ISSUE THREAD

**Issue by smoretto** [googleapis/google-api-go-client#354]
## Client

photoslibrary-api

## Describe Your Environment

Go 1.11

## Expected Behavior

Updated client go library with all fields defined.

## Actual Behavior

Missing field for example filename in MediaItem

## Detail

Actual API version is 2018-05-08 as stated by https://github.com/googleapis/google-api-go-client/blob/master/photoslibrary/v1/photoslibrary-api.json#L399

> "revision": "20180508"

Current version is  2019-04-09 https://photoslibrary.googleapis.com/$discovery/rest?version=v1

> "revision": "20190409"

**Comment by jadekler** [comment]
The reason it's not being updated anymore appears to be because it's no longer listed in https://www.googleapis.com/discovery/v1/apis. I'm going to ping the team internally and will respond here when I find out what's going on. If you'd like, you're also welcome to follow up on the resources listed in https://developers.google.com/photos/library/support/how-to-get-help.

**Comment by jadekler** [comment]
After following up with the photoslibrary team, it looks like the autogenerated client is ready to be sunset (see: https://code-review.googlesource.com/c/google-api-go-client/+/39951). If you currently rely on this library, a good approach forward would be to vendor it. 

Note: whilst all clients in this library are considered beta (see notes in our README and at https://godoc.org/google.golang.org/api), the photoslibrary/v1 API is considered stable and will continued to be thoroughly supported. The photoslibrary team hopes to support Go with a native client in the near future.

Sorry for the hassle! Hopefully we'll have a nicer answer for you soon! Closing this issue but please feel free to respond with any further questions or discussion.

**Comment by perrochon** [comment]
Google Search brought me here with the same issue. I manually added filename into the vendored photoslibrary files. https://github.com/perrochon/gitmoo-goog/commit/07bd92acaa3af14d13c3314e4bf83deae7afd84a
