### ISSUE TITLE
failed to fetch with go mdoules.

### ISSUE THREAD

**Issue by anasanzari** [googleapis/google-api-go-client#355]
getting the following error for go mod download
go: google.golang.org/api@v0.0.0-20181030000543-1d582fd0359e: git -c protocol.version=0 fetch --unshallow -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/9e62a95b0409d58bc0130bae299bdffbc7b7e74f3abe1ecf897474cc474b8bc0: exit status 128:
        fatal: missing tree object 'dcbf3e3c23816703a8f5ebfe6583cc3fc2793526'
        error: remote did not send all necessary objects

**Comment by jadekler** [comment]
Should be fixed as of https://github.com/golang/go/issues/31399
