### ISSUE TITLE
Invalid diskType URL is give as example in many places

### ISSUE THREAD

**Issue by kinghrothgar** [googleapis/google-api-go-client#357]
In several comments through out this library, `project/zones/zone/diskTypes/` is used as an example for diskType URL which is not valid. This led to confusion that took me about an hour to sort out. Instead, `projects/project/zones/zone/diskTypes/` should be used which IS valid. I made a PR https://github.com/googleapis/google-api-go-client/pull/356 and then realized I believe the files I was trying to change are generated so I'm not sure how to fix this.

This invalid example can be found in the core API documentation also https://cloud.google.com/compute/docs/reference/rest/v1/disks/insert :
```
string

URL of the disk type resource describing which disk type to use to create the disk. Provide this when creating the disk. For example: project/zones/zone/diskTypes/pd-standard or pd-ssd
```

**Comment by jadekler** [comment]
Thanks for raising this. I've pinged the compute team.

**Comment by jadekler** [comment]
Thanks again for raising this. The compute team is working on this.

**Comment by kinghrothgar** [comment]
Just glad it's open source and I can report it!

**Comment by jadekler** [comment]
This appears to now be fixed. Closing.
