### ISSUE TITLE
Deprecate healthcare/v1alpha

### ISSUE THREAD

**Issue by raywainman** [googleapis/google-api-go-client#358]
The Cloud Healthcare v1alpha branch is deprecated, could we please have it deleted?
https://github.com/googleapis/google-api-go-client/tree/master/healthcare/v1alpha

Thanks!

**Comment by jadekler** [comment]
Whilst it's still listed in https://www.googleapis.com/discovery/v1/apis, our auto-generator will generate it. Is there a reason in particular you'd like it deleted?

**Comment by jadekler** [comment]
We haven't heard from you in a while, so I'm closing this. Feel free to comment further if you'd like to continue the conversation though.
