### ISSUE TITLE
Update OpenCensus version and run go mod tidy.

### ISSUE THREAD

**Issue by songy23** [googleapis/google-api-go-client#360]
Note in OpenCensus v0.21.0 we removed all exporters from core, and this helped reduce a bunch of transitive dependencies (such as thrift). See a sample PR at https://github.com/googleapis/google-api-go-client/pull/359.

Looks like we don't do PRs in this repo, please kindly help us update the OpenCensus version @jadekler.

/cc @rghetia

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/google-api-go-client/+/40330
