### ISSUE TITLE
sqladmin/v1beta4 filter on name 

### ISSUE THREAD

**Issue by eahrend** [googleapis/google-api-go-client#362]
Hey, I'm attempting to filter a list of databases based on the name parameter. 

```
req := sqladminService.Instances.List(project).Filter("name:my-database")
    if err := req.Pages(ctx, func(page *sqladmin.InstancesListResponse) error {
            for _, databaseInstance := range page.Items {
		fmt.Printf("%+v\n", databaseInstance)				
            }
            return nil
    });
```

I've attempted to change the filter query to "name=my-database" and no results show up. When I remove the filter the database will show up in the response.

Here is the (heavily redacted) response I get. 
```
{
    "backendType": "SECOND_GEN",
    "kind": "sql#instance",
    "name": "my-database"
}
```

When attempting other filters like `backendType=SECOND_GEN` it will still fail to produce any results, however doing something like `name!=my-database` will show all results. 

Is there something I am missing or is this a bug in the beta? We can get around this issue currently by iterating over the list of databases and comparing the  `databaseInstance.Name` parameter, however it's not ideal if we can filter before parsing the list.

**Comment by jadekler** [comment]
cc @kurtisvg
