### ISSUE TITLE
sqladmin/v1beta4 update password returns Error 400: Invalid request

### ISSUE THREAD

**Issue by wozniakjan** [googleapis/google-api-go-client#364]
Getting a user from the API using List and then calling Update on the user fails with an error. Following description summarizes the actions as well as sample source code. Despite the fact `host` should be optional parameter, it doesn't seem to be 
https://cloud.google.com/sql/docs/mysql/admin-api/v1beta4/users/update

Getting a user from list
https://github.com/googleapis/google-api-go-client/blob/9f3a303b451fc0e0f87fe8987a6b8b90e50369b8/sqladmin/v1beta4/sqladmin-gen.go#L9318

and then calling an update with password change
https://github.com/googleapis/google-api-go-client/blob/9f3a303b451fc0e0f87fe8987a6b8b90e50369b8/sqladmin/v1beta4/sqladmin-gen.go#L9470
returns an error
```
googleapi: Error 400: Invalid request: Invalid host in request body., invalid
```
setting `Host` on the `User` structure to `""` returns different error
```
googleapi: Error 400: Invalid request: Host required for MySQL instances., invalid
```
both complaining about the `Host`

Adding this line after 9474 seems to resolve the issue and update goes through successfully.
```
9475     c.urlParams_.Set("host", user.Host)
```
https://github.com/googleapis/google-api-go-client/blob/9f3a303b451fc0e0f87fe8987a6b8b90e50369b8/sqladmin/v1beta4/sqladmin-gen.go#L9474-L9475

attaching sample code used for testing this
<details>
  <summary>main.go</summary>

```go
package main

import (
    "context"
    "fmt"
    "golang.org/x/oauth2/google"
    sqladmin "google.golang.org/api/sqladmin/v1beta4"
)

func main() {
    ctx := context.TODO()
    hc, err := google.DefaultClient(ctx, sqladmin.CloudPlatformScope)
    if err != nil {
        panic(fmt.Sprintf("Unable to get GCP client: %v", err))
    }
    s, err := sqladmin.New(hc)
    if err != nil {
        panic(fmt.Sprintf("Unable to sqladmin new: %v", err))
    }
    project := "project-abc"
    instance := "test-instance"
    users, err := s.Users.List(project, instance).Do()
    if err != nil {
        panic("list users " + err.Error())
    }
    for _, u := range users.Items {
        if u.Name == "test-user" {
            fmt.Println(u)
            u.Password = "pwd_test"
            //u.Host = ""
            _, err := s.Users.Update(project, instance, u.Name, u).Do()
            if err != nil {
                panic("update " + err.Error())
            }
        }
    }
    fmt.Println("changed")
}
```
</details>

**Comment by WTFKr0** [comment]
Hi

Having same problem here while trying to deploy a sql instance via crossplane.io
```
googleapi: Error 400: Invalid request: Invalid host in request body.,
```
When crossplane try to update the root password of instance

**Comment by jadekler** [comment]
cc @kurtisvg

**Comment by kurtisvg** [comment]
Filed with the Cloud SQL team internally at 135045836

**Comment by kurtisvg** [comment]
Update on this: the host command is required for MySQL instances, but option for PostgreSQL instances. We are in the progress of updating the docs to reflect this.

**Comment by displague** [comment]
I worked around this with the following:

```go
cloudsqlclient.Users
    .Update(project, instance, name, user)
    .Host(user.Host)
    .Do()
```

Where user is a `sqladmin.User`.
