### ISSUE TITLE
Massive binaries resulting from the use of ClientOptions

### ISSUE THREAD

**Issue by hiranya911** [googleapis/google-api-go-client#365]
I've been experimenting wit the size of the binaries resulting from the use of this package. It seems use of `google.golang.org/api/option` adds nearly 13MB to the generated binaries.

```
package main

import (
	"log"

	"google.golang.org/api/option"
)

type Foo struct {
	opts []option.ClientOption
}

func main() {
	log.Println("Hello world")
}
```

The compiled binary of the above program is 15MB. If we remove the `opts` field from `Foo`, this goes down to 2.1MB. 

Any idea where this size overhead comes from? Since `ClientOption` type is used to configure pretty much all gcloud and Firebase clients, I would assume this impacts many applications. I can understand a few megabytes of overhead, but 13MB seems a bit too much.

**Comment by jadekler** [comment]
That's a great question. I'm not sure. Might be due to pulling in x/oauth and all of its transitive deps. You can find out by using https://github.com/davecheney/graphpkg or https://github.com/kisielk/godepgraph.
