### ISSUE TITLE
WritersCanShare

### ISSUE THREAD

**Issue by bejaneps** [googleapis/google-api-go-client#366]
**drive-api v2**

    type File struct {
        WritersCanShare bool
    }

The issue is when I'm creating a file with following field set to false, somehow it sends it with true value. I'm using service account to create files.

**EDIT: June 6 - Minimal Reproduction**

**_file:_** https://github.com/bejaneps/agreement-api/blob/master/crud/default.go
So, this is part of my function where I create a file with my google service account

        cnt := auth.GetClient() //getting an instance of service account client (returns *http.Client)

	srv, err := drive.New(cnt) //creates a new google drive service
	if err != nil {
		return nil, err
	}

	file, err = srv.Files.Insert(&drive.File{
		OwnedByMe:       false, //service account can't have gdrive interface, that's why false
		CreatedDate:     time.Now().Format(time.RFC3339),
		MimeType:        "application/vnd.google-apps.document",
		Title:           "sometitle",
		WritersCanShare: false, //TODO: this don't set to false after API call
	}).Do()
	if err != nil {
		return nil, err
	}

After this api call, it creates a file in service account google drive and then I set owner and writers of the file, but the WritersCanShare field doesn't work as I said before.

More info about software that I'm developing on https://github.com/bejaneps/agreement-api

**Comment by jadekler** [comment]
@bejaneps Could you provide a minimal reproduction?

**Comment by bejaneps** [comment]
> @bejaneps Could you provide a minimal reproduction?

added.

**Comment by jadekler** [comment]
Ah ok, right on. This seems like a bug with the API. I hate to be a hassle, but would you mind copy pasting your report and reporting it to the API directly? (this repo is just for the client that talks to the API)

Their issue tracker is at: https://b.corp.google.com/issues?q=status:open%20componentid:191650%2B%20type:bug

**Comment by bejaneps** [comment]
> Ah ok, right on. This seems like a bug with the API. I hate to be a hassle, but would you mind copy pasting your report and reporting it to the API directly? (this repo is just for the client that talks to the API)
> 
> Their issue tracker is at: https://b.corp.google.com/issues?q=status:open%20componentid:191650%2B%20type:bug

Don't you know btw if v3 of gdrive api has same issue ?

**Comment by quranmp4** [comment]
This issue is still unresolved. I succeed in changing other file permissions but not this one.

**Comment by bejaneps** [comment]
Ow, it's been quite a long time, I assumed they fixed it 😅

**Comment by quranmp4** [comment]
Thanks for your quick reply, I hope they fix it soon. My "Writers" keep changing the file permissions and they lock themselves out of access.

**Comment by eigoor** [comment]
For anyone else stumbling over this issue have a look at the ForceSendFields field https://pkg.go.dev/google.golang.org/api#hdr-ForceSendFields
