### ISSUE TITLE
Why package "google.golang.org/api/photoslibrary/v1" is removed?

### ISSUE THREAD

**Issue by mong0520** [googleapis/google-api-go-client#368]
Since I can still get the package via `go get google.golang.org/api/photoslibrary/v1`, but it seems be removed from master, include source and documents.

Could someone share any reason for this? Thank you

**Comment by jadekler** [comment]
Yes - the package is no longer globally listed at https://www.googleapis.com/discovery/v1/apis. We only generate clients from that list. If you still need that package, please vendor it.

**Comment by mong0520** [comment]
@jadekler 
Thanks for the update, may i know why and will it be added in the future?

**Comment by jadekler** [comment]
No problem! I'm not sure I'm afraid - it's up to the photos team. You can enquire about their API plans through their support channels at: https://developers.google.com/photos/library/support/how-to-get-help.

**Comment by huppmann** [comment]
> You can enquire about their API plans through their support channels at: https://developers.google.com/photos/library/support/how-to-get-help.

thanks for the pointer

seems to have been done here:

[Add support for the google-api-<language>-client libraries](https://issuetracker.google.com/138224490)
