### ISSUE TITLE
Chat: get all messages in a thread

### ISSUE THREAD

**Issue by inge4pres** [googleapis/google-api-go-client#369]
Hello 

I wasn't able to find a way to get all messages that are in the same thread in a room with the API in `chat/v1`.
Looking at https://developers.google.com/hangouts/chat/reference/rest/v1/spaces.messages/get I see I can get a message but not a collection of messages from the same thread.
Is there a way of doing it? 
Thank you

**Comment by jadekler** [comment]
Hello! These libraries are just auto-generated stubs around the REST API. Your question seems to be about interacting with the API, as opposed to strictly about these Go auto-generated libraries. Would you mind re-asking your question at https://stackoverflow.com/questions/tagged/hangouts-chat? Several members of the hangouts / chats team monitor this SO I believe.

Closing for now, let me know if there's more about the Go clients we can help with.

**Comment by inge4pres** [comment]
Hi 😄 
thanks for the redirection, the question was asked at the same time
https://stackoverflow.com/questions/tagged/hangouts-chat
