### ISSUE TITLE
compute: godoc is not available for v1 and v0.beta

### ISSUE THREAD

**Issue by rakyll** [googleapis/google-api-go-client#372]
https://godoc.org/google.golang.org/api/compute/v0.beta and https://godoc.org/google.golang.org/api/compute/v1 both displays:

```
The documentation displayed here is incomplete. Use the godoc command to read the complete documentation.
```

instead of rendering the godoc for the packages.

**Comment by broady** [comment]
My guess, too many symbols, so gddo (godoc.org) bailed.

**Comment by rakyll** [comment]
Is there a way we can help? Compute is a major API and many infra tools are written in Go nowadays. It would be great to be able to read the godoc.

**Comment by broady** [comment]
Need to file a bug on gddo. Closing here.
