### ISSUE TITLE
How do I add multiple values to a searchTerms parameter of the YouTube API CommentThreads:list query?

### ISSUE THREAD

**Issue by forucell** [googleapis/google-api-go-client#373]
I am having some issue with Youtube Data API.

I want to get some comment under a certain video based on my keywords. Basically, I want to send multiple (apple OR grape OR banana) values inside searchTerm parameter. So comments should have one of the values of keywords. However, I couldn't find anything about that in the official documentation.

I found the following for video search API however. I tried to use the same syntax with CommentThreads API, it didn't work out.

```
"q": {
              "description": "The q parameter specifies the query term to search for.\n\nYour request can also use the Boolean NOT (-) and OR (|) operators to exclude videos or to find videos that are associated with one of several search terms. For example, to search for videos matching either \"boating\" or \"sailing\", set the q parameter value to boating|sailing. Similarly, to search for videos matching either \"boating\" or \"sailing\" but not \"fishing\", set the q parameter value to boating|sailing -fishing. Note that the pipe character must be URL-escaped when it is sent in your API request. The URL-escaped value for the pipe character is %7C.",
              "location": "query",
              "type": "string"
            },
```

```
videoId='CPW2PCPYzEE'

def get_video_comments_with_searchTerms(video_id, next_page_token=None):
    comments_json = get(
        "commentThreads",
        part="snippet",
        searchTerms="apple|pear|banana",
        fields="items/snippet/topLevelComment/snippet/textOriginal,nextPageToken",
        videoId=video_id,
        maxResults=20,
        pageToken=next_page_token

    )
    return comments_json
```

I'd really appreciate if somebody could point me in the right direction.

Best Regards, Sam

**Comment by jadekler** [comment]
Hello! Would you mind re-filing this issue at https://stackoverflow.com/questions/tagged/youtube-api?

This github page contains the auto-generated clients, but no youtubers are monitoring the issue tracker. The stackoverflow page has a much higher chance of getting seen, and also is easy for other community members to see the question + answer. :)

**Comment by forucell** [comment]
> https://stackoverflow.com/questions/tagged/youtube-api

I did it before posting the issue here. Then I'll wait for answers on stackoverflow. 
Thanks.
