### ISSUE TITLE
Can't figure out how to send large attachments with Gmail API

### ISSUE THREAD

**Issue by bragagia** [googleapis/google-api-go-client#374]
Hello,

I've tried to send an email with attachments using [this method](https://godoc.org/google.golang.org/api/gmail/v1#UsersMessagesService.Send)

I first tried to put my attachments using [github.com/go-mail/mail](https://github.com/go-mail/mail), the code looked like that :
```Go
	m := gomail.NewMessage()
	m.SetAddressHeader("From", email.SenderEmail, email.SenderName)
	m.SetHeader("To", email.To)
	m.SetHeader("Subject", email.Subject)
	m.SetBody("text/plain", email.RawBody)
	for _, attachment := range email.Attachments {
		m.AttachReader(attachment.Name, attachment.File)
	}

	buffer := new(bytes.Buffer)
	if _, err := m.WriteTo(buffer); err != nil {
		return "", "", err
	}

	var message gmail.Message
	service.Users.Messages.Send("me", &gmail.Message{Raw: base64.URLEncoding.EncodeToString(buffer.Bytes())}).Do()
```

It works fine but I got an error 413 Request entity too large if I send a message of a size of more than +/- 6.5Mio.

So I tried to use the `Media` method of `gmail.UsersMessagesSendCall` :

```Go
	m := gomail.NewMessage()
	m.SetAddressHeader("From", email.SenderEmail, email.SenderName)
	m.SetHeader("To", email.To)
	m.SetHeader("Subject", email.Subject)
	m.SetBody("text/plain", email.RawBody)

	buffer := new(bytes.Buffer)
	if _, err := m.WriteTo(buffer); err != nil {
		return "", "", err
	}

	var message gmail.Message
	call := service.Users.Messages.Send("me", &gmail.Message{Raw: base64.URLEncoding.EncodeToString(buffer.Bytes())})
	for _, attachment := range email.Attachments {
		call.Media(attachment.File)
	}
	call.Do()
```

but I got a error : `googleapi: Error 400: Media type 'video/mp4' is not supported. Valid media types: [message/rfc822], badContent`

So I tried to set the mentioned MediaType to the attachments :

```Go
	// ...
		call.Media(attachment.File, googleapi.ContentType("message/rfc822"))
	// ...
```

the call works fine, but there is no attachments on the received mail.

What did I done wrong ? I haven't found any example on the doc on how to send a mail with attachments.

**Comment by codyoss** [comment]
I would suggest taking a look at: https://developers.google.com/gmail/api/guides/uploads#upload-resumable

The example is working with the raw API(not with this Go client library wrapper) but I think it will help figure it out. Closing this issue, if you are still having issue let me know. Thanks.

**Comment by annp87** [comment]
@bragagia : Have you solve this problem? If so, could you please share it?

**Comment by annp87** [comment]
@codyoss : I still have the same issue as @bragagia. Do you have any advice?
