### ISSUE TITLE
Cannot use GSuite Directory API's NewService() with SA due to missing support for user impersonation

### ISSUE THREAD

**Issue by idofl** [googleapis/google-api-go-client#379]
According to the documentation, to use a GCP service account (SA) with GSuite Directory API
(https://github.com/googleapis/google-api-go-client/blob/master/admin/directory/v1/admin-gen.go) you need to provide the SA json credential file, scopes (optional), and the impersonated user's UPN (email).
The implementation of the NewService() function supports client options, but it does not include impersonated user's email.
We need to resort to use the New() function, as explained here:
https://developers.google.com/admin-sdk/directory/v1/guides/delegation

However, this function is documented as "Deprecated: please use NewService instead."

Can the NewService() function get fixed to support SA using GSuite directory APIs?

**Comment by jadekler** [comment]
Impersonated credentials is something we're designing. Please track in https://github.com/googleapis/google-api-go-client/issues/378.

**Comment by jadekler** [comment]
Also, what does SA stand for?

**Comment by idofl** [comment]
yes, SA = Service Account.

**Comment by broady** [comment]
fwiw #378 is for service account impersonation, which iiuc is a different mechanism than the domain-wide user delegation used by gsuite.

i've updated the code sample, it'll go live on the doc site some point in the future.

```

import (
	"fmt"
	"io/ioutil"

	"golang.org/x/net/context"
	"golang.org/x/oauth2/google"

	admin "google.golang.org/api/admin/directory/v1"
	"google.golang.org/api/option"
)

// Path to the Service Account's Private Key file
var ServiceAccountFilePath = "/path/to/<public_key_fingerprint>-privatekey.json"

// Build and returns an Admin SDK Directory service object authorized with
// the service accounts that act on behalf of the given user.
// Args:
//    user_email: The email of the user. Needs permissions to access the Admin APIs.
// Returns:
//    Admin SDK directory service object.
func CreateDirectoryService(userEmail string) (*admin.Service, error) {
	ctx := context.Background()

	jsonCredentials, err := ioutil.ReadFile(ServiceAccountFilePath)
	if err != nil {
		return nil, err
	}

	config, err := google.JWTConfigFromJSON(jsonCredentials, admin.AdminDirectoryUserScope)
	if err != nil {
		return nil, fmt.Errorf("JWTConfigFromJSON: %v", err)
	}
	config.Subject = userEmail

	ts := config.TokenSource(ctx)

	srv, err := admin.NewService(ctx, option.WithTokenSource(ts))
	if err != nil {
		return nil, fmt.Errorf("NewService: %v", err)
	}
	return srv, nil
}
```

**Comment by idofl** [comment]
When using a service account credentials file, the above code works. However, when running this code ainside GCP (on GCE or GCF), we'd like to use the service account used by the environment (either the compute SA for GCE or Appspot SA for GAE/GCF).
Using built-in service account means we don't have a JSON credentials, so we can't call JWTConfigFromJSON. If we call FindDefaultCredentials() the credentials returned can't be used with JWTConfigFromJSON (json property is nil).

Can you provide a code sample that shows how to do this within GCP? Thanks.

**Comment by broady** [comment]
I'm not sure how to do that, I'm not very familiar with domain-wide delegation.

Can you seek help with someone who is? I can help translate into Go.

**Comment by salrashid123** [comment]
you can't get the an access token capable of using gsuites delegation from the metadata server currently.   The target identity you're trying to impersonate needs to be included as the `sub` field in the request...i'd imagine if the featue was there, then the metadata server would be like: `http://metadata/.../token?subject=admin@domain.com` endpoint or something like that.

--

anyway, a bit of a crappy workaround is to manually generate the token by hand using an API

ref
 - https://medium.com/google-cloud/consuming-and-validating-gsuites-audit-push-notification-on-appengine-a98a178ee82e

- https://github.com/salrashid123/gsuites_appengine_events/blob/master/gae_app/default.py#L68

google-cloud go doens't have an easy way to `signJwt()` or for that matter impersonation.  ...if this issue moves forward, i can add `signJwt()` in pretty easily:
   https://github.com/googleapis/google-api-go-client/issues/378

**Comment by idofl** [comment]
Regarding signing the JWT, we should use Google Cloud APIs to sign the JWT with the service account's system-managed private key (as we're not using a credentials file).
https://cloud.google.com/iam/credentials/reference/rest/v1/projects.serviceAccounts/signJwt
This is already available through the Go library:
https://godoc.org/google.golang.org/api/iamcredentials/v1#ProjectsServiceAccountsService.SignJwt

I'm working on writing such a sample, but I don't have much free time to work on it. If anyone can lend a hand, that'll be great.

**Comment by salrashid123** [comment]
you can start with this...it 
https://github.com/googleapis/google-api-go-client/pull/337/files#diff-02b6d1e40a46e40d260eae48cbd536d6R69

just use the source credential and use the signjwt, then do the exchange with the token endpoint manually as shown in python snippet

**Comment by julianvmodesto** [comment]
Here's a working example: https://gist.github.com/julianvmodesto/ed73201703dac8a047ec35a24dce4524

Thanks for the guidance here!

**Comment by salrashid123** [comment]
thanks @julianvmodesto   

@wilsonfan  [ref:](https://gist.github.com/salrashid123/7994be642c466844f85e2f2c68a5dec9#gistcomment-2968833) .  the snippet above is a variation w/o using a json cert file and also if you intend to impersonate

**Comment by idofl** [comment]
Great. Any chance this can be added to the SDK, to enable SA access to GSuite APIs?

**Comment by Pega88** [comment]
+1 on this - we need this to be included as a more simple setup, as simple as adding the SA JSON or scopes to create the service object
`admin.NewService(ctx, option.WithCredentialsFile("creds.json"), option.WithScopes(admin.AdminDirectoryGroupScope, admin.AdminDirectoryGroupMemberScope))`

**Comment by willzjc** [comment]
Appears to be a feature that more and more companies are pursuing - worth to add this feature.

**Comment by logsnitch** [comment]
+1 I need to use domain wide delegation with an impersonated service account. Going to try @julianvmodesto's snippet but this really needs to be in the SDK

**Comment by salrashid123** [comment]
@julianvmodesto  i added in a variation of your code into a set of unofficial oauth2 `TokenSource` that will work with GCP

https://github.com/salrashid123/oauth2#impersonated-credentials-with-domain-wide-delegation
https://github.com/salrashid123/oauth2/blob/master/google/impersonate.go#L137
