### ISSUE TITLE
Cloud Run v1beta1 and v1 APIs do not exist but are present in this module 

### ISSUE THREAD

**Issue by steren** [googleapis/google-api-go-client#382]
Cloud Run `v1beta1` is under constructions and is not public yet.
Cloud Run `v1` API does not exist at the moment.

Please delete: https://github.com/googleapis/google-api-go-client/tree/master/run/v1
And https://github.com/googleapis/google-api-go-client/tree/master/run/v1beta1
to avoid user confusion.

**Comment by steren** [comment]
it is likely that this is due to the discovery document.

I opened issue 138164482 internally to fix this

**Comment by jadekler** [comment]
It is indeed a discovery issue. https://www.googleapis.com/discovery/v1/apis needs to have its listing removed. We can delete it, but it would get auto-generated back into the repo. Give a shout when it's removed from the discovery doc and I'll make the deletion!

**Comment by jadekler** [comment]
Closing this since we haven't heard back from a while. Please ping me when the discovery doc is updated.
