### ISSUE TITLE
404 when using errorReporting Report()

### ISSUE THREAD

**Issue by gm42** [googleapis/google-api-go-client#386]
I believe that ProjectEventsReportCall has a typo in the form of a missing URI component:

If you check the documentation (https://cloud.google.com/error-reporting/reference/rest/v1beta1/projects.events/report):
```
POST https://clouderrorreporting.googleapis.com/v1beta1/projects/example-project/events:report?key=123ABC456
```

You can see that just before the project ID `example-project` there is `/projects/` in the URL.

However `ProjectsEventsReportCall.doRequest` uses:
```
urls := googleapi.ResolveRelative(c.s.BasePath, "v1beta1/{+projectName}/events:report")
```

I have verified experimentally that with the addition of `/projects` the API call works, while without a 404 is returned.

This bug should likely be fixed in the source data used by the generator, or in the generator itself.

Previous (incorrectly reported) PR: #385

**Comment by gm42** [comment]
@jadekler I could add a testcase but I am simply using a service account (with the correct permissions) via JSON credentials and `google.golang.org/api v0.7.0`

**Comment by jadekler** [comment]
Thanks. I think this is a problem with that API's specification. I've filed https://issuetracker.google.com/issues/138784098 - please track there.
