### ISSUE TITLE
What does opencensus do and why is it appearing in my goroutine list?

### ISSUE THREAD

**Issue by ncw** [googleapis/google-api-go-client#388]
I'm using

- google.golang.org/api/drive/v2
- google.golang.org/api/drive/v3
- google.golang.org/api/storage/v1

Which import

- google.golang.org/api/transport/http

Which in turn imports

- go.opencensus.io/plugin/ochttp
- go.opencensus.io/trace
- go.opencensus.io/trace/propagation

It was a surprise to see a goroutine created by opencensus in my goroutines list and with a name like opencensus makes me worry that it might be leaking data.

I'd like to know
- Why is this goroutine created by default? 
- What does it do?
- Can it be turned off or do I need it for something?

Thank you.

```
goroutine 6 [select]:
github.com/rclone/rclone/vendor/go.opencensus.io/stats/view.(*worker).start(0xc00015ea00)
	/home/ncw/go/src/github.com/rclone/rclone/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
created by github.com/rclone/rclone/vendor/go.opencensus.io/stats/view.init.0
	/home/ncw/go/src/github.com/rclone/rclone/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57

```

I see it is started in an init statement in `go.opencensus.io/stats/view/worker.go`

```go
func init() {
	defaultWorker = newWorker()
	go defaultWorker.start()
	internal.DefaultRecorder = record
}
```

**Comment by jadekler** [comment]
Opencensus is a stats collection library. It collects stats that you define and that the library defines, such as traces of your HTTP requests. It only sends data if you create an exporter. So, for the majority of people, it sends no data.

I'm not sure how the under-the-hood of it works, nor why it creates a goroutine. You could ask them directly at https://github.com/census-instrumentation/opencensus-go.

**Comment by jadekler** [comment]
I'll also add that the stats it collects are purely for _your_ debugging. We (Google) do not collect any of these stats.

**Comment by ncw** [comment]
Thank you for taking the time to explain.

I'll make an issue on the opencensus github about the goroutine started on `init()`

**Comment by ncw** [comment]
Actually there is one already! https://github.com/census-instrumentation/opencensus-go/issues/1074

**Comment by james-lawrence** [comment]
@jadekler that package should be removed just because of the panic attack it causes people, at least until it switches to opt in on the background tasks.
