### ISSUE TITLE
gensupport: add SendAndRetryRequest

### ISSUE THREAD

**Issue by odeke-em** [googleapis/google-api-go-client#392]
This issue is a proposal to add a function that retries requests that are sent. Currently we've got SendRequest which is used all around the auto-generated APIs e.g. for storage/v1/storage-gen.go.ObjectsInsertCall.Do
https://github.com/googleapis/google-api-go-client/blob/329ecc3c9c34ac4cbaaf7ada4fd373b3239282ae/storage/v1/storage-gen.go#L10031-L10045
which has an interesting property that the initial POST request in order to get the resumable UploadID session information is never retried, so it is the job of the caller to retry it. However, after that initial request chunks that are uploaded are retried. We saw such a problem in https://github.com/googleapis/google-cloud-go/issues/1507, where the the google-cloud-go/storage had a retry with the innocent premise that ONLY the first request would be retried
```go
                               // We will only retry here if the initial POST, which obtains a URI for
                               // the resumable upload, fails with a retryable error. The upload itself
                               // has its own retry logic.
                               err = runWithRetry(w.ctx, func() error {
                                       var err2 error
                                       resp, err2 = call.Do()
                                       return err2
                               })
```
but alas as that issue showed, that initial assumption would cause body upload failures to retry indefinitely wrong so the fix is to remove it.

The problem however though is that by sometimes retrying and sometimes not retrying yet giving back a non-introspectable error, the callers cannot isolate between when to retry a response or not and thus why https://github.com/googleapis/google-cloud-go/issues/1507 exists.

### Proposal

Let's make a function SendAndRetryRequest or at least retry that initial request to get the resumable upload session and then users of these packages can reliably know that their requests will be retried for them.

/cc @jadekler @frankyn @broady

**Comment by odeke-em** [comment]
When we resolve this issue the update to https://code-review.googlesource.com/c/gocloud/+/44071 will just require an update to the go.mod file and then google-cloud-go doesn't have to do anything further.

**Comment by jadekler** [comment]
Rather than adding another method, could we make that initial post retry?

**Comment by jadekler** [comment]
There is... we could modify the generator and have it only add the code in the storage case. But, we should probably have some canned solution for this. It does seem odd that [the initial request before an `rx.Upload` is not retried](https://github.com/googleapis/google-api-go-client/blob/d1c9f49851b5339dea6bf7e4076b60a66e62be1f/mirror/v1/mirror-gen.go#L3506). Maybe they should all be retried? (not just storage)

cc @jba @frankyn

**Comment by tritone** [comment]
Noting for posterity here that we did end up scoping this specifically to storage for now. See #538 .
