### ISSUE TITLE
How do I separate status "STOPPED" from "RUNNABLE".

### ISSUE THREAD

**Issue by ozikot** [googleapis/google-api-go-client#394]
I want to separate stopped from runnable.
(distinguished in gcloud)

 Is there an effective measure now?

https://github.com/googleapis/google-api-go-client/blob/d1c9f49851b5339dea6bf7e4076b60a66e62be1f/sqladmin/v1beta4/sqladmin-gen.go#L758-L768

**Comment by jadekler** [comment]
cc @kurtisvg

**Comment by kurtisvg** [comment]
@ozikot - Although not very intuitive, you can tell an instance is stopped but ready to run when `state=RUNNABLE` and `settings.activationPolicy=NEVER`

**Comment by ozikot** [comment]
Thank you very much. 
I will look at it.
