### ISSUE TITLE
Add batch requests to Calendar API

### ISSUE THREAD

**Issue by mitinarseny** [googleapis/google-api-go-client#396]
There is no support for [batch requests](https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch) in [Go Calendar API Client](https://github.com/googleapis/google-api-go-client/tree/master/calendar/v3). It would be nice, if you add some)

P.S.: There is a [package](https://github.com/jfcote87/google-api-go-client/tree/master/batch) that allows to do it, but it would be better if it is in the official package from Google. Thank you!

**Comment by jadekler** [comment]
Hello! Unfortunately these clients are in maintenance mode - we won't be adding new features.
