### ISSUE TITLE
youtube LiveBroadcast EnableMonitorStream set to false is omitted

### ISSUE THREAD

**Issue by kmlx** [googleapis/google-api-go-client#401]
youtube.LiveBroadcast.ContentDetails.MonitorStream.EnableMonitorStream is missing when set to false (explanation in #54)

according to https://developers.google.com/youtube/v3/live/docs/liveBroadcasts#contentDetails.monitorStream

> boolean
> This value determines whether the monitor stream is enabled for the broadcast. If the monitor stream is enabled, then YouTube will broadcast the event content on a special stream intended only for the broadcaster's consumption. The broadcaster can use the stream to review the event content and also to identify the optimal times to insert cuepoints.

and according to:
https://developers.google.com/youtube/v3/live/life-of-a-broadcast#stage_3_test

> By default, broadcasts' monitor streams are enabled. You can disable a broadcast's monitor stream by setting the contentDetails.monitorStream.enableMonitorStream property to false when creating or updating that broadcast.

Would it be possible to have EnableMonitorStream as a ```*bool```? 

code in question:
https://github.com/googleapis/google-api-go-client/blob/master/youtube/v3/youtube-gen.go#L6702

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/google-api-go-client/+/49333

**Comment by kmlx** [comment]
thank you for this @jadekler
