### ISSUE TITLE
oauth2.TokeninfoCall returns "Invalid Value" when validating an ID Token

### ISSUE THREAD

**Issue by kunzese** [googleapis/google-api-go-client#403]
For testing purposes i want to validate an ID Token with the oauth2 package. Instead of returning a *Tokeninfo struct it results in an **Invalid Value** error.

go version:

```sh
$ go version
go version go1.11.5 darwin/amd64
```

Demo code:

```golang
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"

	"google.golang.org/api/oauth2/v2"
)

func main() {
	token := flag.String("token", "", "OIDC Token")
	flag.Parse()
	if *token == "" {
		flag.Usage()
		os.Exit(1)
	}
	ctx := context.Background()
	oauth2Service, err := oauth2.NewService(ctx)
	if err != nil {
		log.Fatal(err)
	}
	tokenInfo, err := oauth2Service.Tokeninfo().IdToken(*token).Do()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%+v\n", tokenInfo)
}
```

Execution:

```sh
$ GOOGLE_APPLICATION_CREDENTIALS=/path/to/credentials.json go run main.go -token $(gcloud auth print-identity-token)
2019/09/27 13:35:52 googleapi: got HTTP response code 400 with body: {"error_description":"Invalid Value"}
exit status 1
```

`curl` call against against the underlying Google API:

```sh
$ curl -X POST "https://www.googleapis.com/oauth2/v2/tokeninfo?id_token=$(gcloud auth print-identity-token)"
{
  "issued_to": "<removed>.apps.googleusercontent.com",
  "audience": "<removed>.apps.googleusercontent.com",
  "user_id": "<removed>",
  "expires_in": 3598,
  "email": "<removed>",
  "verified_email": true,
  "issuer": "https://accounts.google.com",
  "issued_at": <removed>
}
```

Update 1:

Digging a bit deeper i think this might by an issue with the https://www.googleapis.com/oauth2/v2/tokeninfo API.
The oauth2 package gets its http.Client from the transport/http package via [htransport.NewClient()](https://github.com/googleapis/google-api-go-client/blob/master/oauth2/v2/oauth2-gen.go#L103). After a few steps this http.Client gets a [oauth2 TokenSource](https://github.com/googleapis/google-api-go-client/blob/master/transport/http/dial.go#L89) with an access token from the supplied credentials file.

`curl` call against against the underlying Google API with an ID Token as *?id_token* parameter and an Access Token as *Authorization: Bearer* value:

```sh
$ curl -X POST "https://www.googleapis.com/oauth2/v2/tokeninfo?id_token=$(gcloud auth print-identity-token)" \
  -H "Authorization: Bearer $(gcloud auth print-access-token)"
{
  "error_description": "Invalid Value"
}
```

Lets try the same with a *?access_token* parameter:

```sh
curl -X POST "https://www.googleapis.com/oauth2/v2/tokeninfo?access_token=$(gcloud auth print-access-token)" \
  -H "Authorization: Bearer $(gcloud auth print-access-token)"
{
  "issued_to": "<removed>.apps.googleusercontent.com",
  "audience": "<removed>.apps.googleusercontent.com",
  "user_id": "<removed>",
  "scope": "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/appengine.admin https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/accounts.reauth openid",
  "expires_in": 3600,
  "email": "<removed>",
  "verified_email": true,
  "access_type": "offline"
}
```

So there is a different behavior in the https://www.googleapis.com/oauth2/v2/tokeninfo API depending on which parameter you use.

Update 2:

Workaround:

So i found an easy fix for this issue on client side. Just use:

```golang
oauth2Service, err := oauth2.NewService(ctx, option.WithoutAuthentication())
```

But it might be worth to have a look at this API behavior.

**Comment by jadekler** [comment]
Thanks for filing, and your _exceptional_ notes. Looks like the client authentication is clobbering the `oauth2Service.Tokeninfo()` call, AFAICT. I'm not sure the answer is to remove _all_ authentication (supply `WithoutAuthentication` all the time) is the right thing, since things like [UserinfoService](https://godoc.org/google.golang.org/api/oauth2/v2#UserinfoService) require auth (AFAICT).

Might be that the pragmatic option here is to add a note to the docs about this clobbering, and suggest `WithoutAuthentication` for some calls.

One more option is we could modify the generator to specifically handle this call differently, but I'm not super keen on that route wrt scalability / maintainability.

@broady any other ideas from your side? Kind of a funky auth edge case.

**Comment by codyoss** [comment]
If you are looking to validate ID tokens I suggest you try out our new `idtoken` package. [idtoken.Validate](https://pkg.go.dev/google.golang.org/api/idtoken?tab=doc#Validate)
