### ISSUE TITLE
Compute Client: option.WithCredentialsFile incompatible with option.WithHTTPClient

### ISSUE THREAD

**Issue by MartinWan** [googleapis/google-api-go-client#404]
I am creating the compute client like this:

`gce, err := compute.NewService(context.Background(), option.WithCredentialsFile(creds), option.WithHTTPClient(clientWithCerts)`

However, when I make try to instantiate an instance I get `googleapi: Error 401: Login Required, required`. Removing the `option.WithHTTPClient` and the issue is gone.

**Comment by jadekler** [comment]
Those two _do_ seem incompatible, but we should report a better error. cc @broady: WDYT about adding a panic to report the incompatibility, as we do elsewhere IIRC?

**Comment by broady** [comment]
Yes, these two options are incompatible. An error should be returned, there shouldn't be a panic.

**Comment by MartinWan** [comment]
I guess it says that in the documentation "When used, the WithHTTPClient option takes precedent over all other supplied options."

Probably don't want to return an error as that might break that is incorrectly using both

**Comment by twessling** [comment]
if these two are incompatible, what's the approach for using provided credentials(either file or raw bytes) along with proxy configuration (that usually goes on http.Transport inside the http.Client)? There must be a way without relying on env vars?

**Comment by codyoss** [comment]
For now, I would use the well known proxy env-var. We are considering adding a new client option in the future that might make this easier. https://github.com/googleapis/google-cloud-go/issues/1962

**Comment by twessling** [comment]
Hm, I'll have to look into that - might mean some refactoring on my side - not all http.Clients in that software should use the proxy. Thanks for the link, that's indeed the direction I was hoping to find something :)
