### ISSUE TITLE
Export table as CSV with headers

### ISSUE THREAD

**Issue by KinaneD** [googleapis/google-api-go-client#407]
We are running Google Cloud SQL with, now stable, Postgres 11. While exporting a table as CSV we noticed that the CSV has no headers.

We can't seem to find any way in `ExportContextSqlExportOptions` to specify that there should be a headers row in said CSV.

Any ways to work around this?

Thank you.

**Comment by jadekler** [comment]
@kurtisvg Any comments on this? Otherwise it's probably best to re-file against the actual service team (i'll provide a link shortly if we decide to go that route).

**Comment by kurtisvg** [comment]
I'm not sure offhand - please open an issue against the API on the [Cloud SQL issue tracker](https://issuetracker.google.com/issues/new?component=187202&template=0). Feel free to post the issue number here and I'll make sure to follow up.

**Comment by KinaneD** [comment]
Here is the issue https://issuetracker.google.com/issues/142012078

Thank you.
