### ISSUE TITLE
unflake TestGRPCHook

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-api-go-client#411]
https://sponge.corp.google.com/target?id=201aa0cd-4407-4441-a4fe-89924c5e0f82&target=cloud-go-libraries%2Fgoogle-api-go-client%2Fpresubmit%2Fmaster&searchFor=

```
--- FAIL: TestGRPCHook (0.01s)
    dial_test.go:57: DialGRPC: error context deadline exceeded, want nil
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa27299]

goroutine 11 [running]:
testing.tRunner.func1(0xc0002ee000)
	/usr/local/go/src/testing/testing.go:792 +0x6a7
panic(0xb1d520, 0x1061050)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
google.golang.org/grpc.(*ClientConn).Close(0x0, 0x0, 0x0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.20.1/clientconn.go:833 +0x69
panic(0xb1d520, 0x1061050)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
google.golang.org/grpc.(*ClientConn).Invoke(0x0, 0xc67ec0, 0xc000076780, 0xbb4097, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/google.golang.org/grpc@v1.20.1/call.go:32 +0x48
google.golang.org/grpc.Invoke(0xc67ec0, 0xc000076780, 0xbb4097, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/google.golang.org/grpc@v1.20.1/call.go:60 +0xe0
google.golang.org/api/transport/grpc.TestGRPCHook(0xc0002ee000)
	/root/go/src/google.golang.org/api/transport/grpc/dial_test.go:62 +0x530
testing.tRunner(0xc0002ee000, 0xbd9200)
	/usr/local/go/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x65a
FAIL	google.golang.org/api/transport/grpc	0.053s
?   	google.golang.org/api/transport/http	[no test files]
```

**Comment by escholtz** [comment]
I was able to reproduce this. Roughly 1 in 10,000 TestGRPCHook runs fail locally.

1. Why is there a panic? `Dial` is returned a nil `conn` pointer that the test reads from.

2. Why is `conn` nil? `grpc.DialContext` is reaching it's final `return cc, nil`. However, further up in the method is a very subtle defer that uses the named return values to stomp `return cc, nil`.

```go
func DialContext(ctx context.Context, target string, opts ...DialOption) (conn *ClientConn, err error) {
        // omitted
	defer func() {
		select {
		case <-ctx.Done():
			conn, err = nil, ctx.Err()
		default:
		}
	}()
        // omitted
	return cc, nil
}
```

3. Why is the context being cancelled? I modified the context package from the standard library to store a `debug.Stack()` on the `cancelCtx` type when the `cancel` method is called. I then created a custom error type so the stack could be retrieved outside of the context package via type assertion on the returned error. The stack indicated that the cancellation is coming from the `cancel()` call in `TestGRPCHook`:

```go
expectedDialer := grpc.WithDialer(func(addr string, timeout time.Duration) (net.Conn, error) {
        expected = true
        cancel()
        return nil, errors.New("expected")
})
```

Question: Modifying the context package seems kind of crazy. There must be a better way to trace the source of context cancellation?

**Comment by jadekler** [comment]
> There must be a better way to trace the source of context cancellation?

Good question. I'm actually not sure if there is. @dfawley do you know?

> Why is conn nil?

Feels like a use-of-not-ready connection kinda problem, naively. Nothing concrete pops to mind though.

> Why is there a panic?

Not sure, but most likely gRPC is behaving as-expected but we're doing something weird.

---------

Wish I had something more concrete than those. It seems like one that will take a bit of debugging, but might shed light on an actual bug.
