### ISSUE TITLE
Outputs in Deployment Config not being returned from Deployment Manager in google-api-go-client

### ISSUE THREAD

**Issue by daviddiefenderfer** [googleapis/google-api-go-client#420]
When generating a Deployment config, we can request specific outputs be returned such as getting the public IP after a vm has been deployed.
```
outputs:
  - name: IPAddress
    value: $(ref.vm.networkInterfaces[0].accessConfigs[0].natIP)
```
if you were to deploy this with the cli you would get a response with this `IPAddress` value populated. 
`gcloud deployment-manager deployments create test --config config.yaml`

However, this isn't the case if deploying from the google-api-go-client. The outputs don't seem to be in any of the deploymentmanager-gen.go structs

**Comment by jadekler** [comment]
Hello! This repository unfortunately only holds generated output: the team that develops the deployment manager is not involved in this repository. Would you mind re-filing this issue in the deployment manager issue tracker located at https://cloud.google.com/support/docs/issue-trackers? That will get you directly connected to the team. :)

Closing this for now, but happy to continue the conversation.
