### ISSUE TITLE
bundler: return error when Add item type differs from example type

### ISSUE THREAD

**Issue by escholtz** [googleapis/google-api-go-client#422]
When the type of the item being added to the bundle differs from the example type, reflect.Append will panic.

Perform a type check prior to reflect.Append and return an error if the types don't match.

**Comment by jba** [comment]
I think a panic is fine as long as we document that the type of the `Add` arg must be assignable to the itemExample type passed to `NewBundler`.

It's common for Go types that simulate genericity using `interface{}` to panic when the types don't match. See [sync.atomic.Value](https://godoc.org/sync/atomic#Value) for example.
