### ISSUE TITLE
You cannot use the verification method DNS_TXT to verify a site of type SITE

### ISSUE THREAD

**Issue by dan-leech** [googleapis/google-api-go-client#430]
I use `googleapis/google-api-go-client/siteverification/v1` like this:
**auth**:
```
verifService, err := google_siteverification.NewService(ctx, google_option.WithCredentialsFile(googleCloudConf.CredentialsJson))
```
**getToken**:
json for simplier, getting token is ok
```json
{
  "site": {
    "identifier": "test.net",
    "type": "INET_DOMAIN"
  },
  "verificationMethod": "DNS_TXT"
}
```
**insert**:
```
iRes, err := verifService.WebResource.Insert("DNS_TXT", nil).Do()
```
On insert I get `You cannot use the verification method DNS_TXT to verify a site of type SITE`

Also I tried web API from [developers.gogle.com](https://developers.google.com/site-verification/v1/webResource/insert?apix_params=%7B%22verificationMethod%22%3A%22DNS_TXT%22%2C%22resource%22%3A%7B%7D%7D) but I get the same result

What do I do wrong? Is there other method to verify a domain through a google service?

**Comment by jadekler** [comment]
Unfortunately these client libraries are all auto-generated: the API teams typically don't monitor these issues. I've reached out to the team that owners siteverification and hope to hear back soon.

**Comment by codyoss** [comment]
@dan-leech Did you ever get this issue resolved?

**Comment by codyoss** [comment]
Closing due to lack of response, please feel free to re-open if you are still having this issue.
