### ISSUE TITLE
Update doc of compute.Network to say when legacy VPC is created 

### ISSUE THREAD

**Issue by bigmikes** [googleapis/google-api-go-client#432]
**What I did:**
I tried to create a VPC in custom mode with the following piece of code:

```Go
func CreateVPC(ctx context.Context, ns *compute.NetworksService, name string) (*compute.Operation, error) {
	net := &compute.Network{
		Name:                  name,
	}
	return ns.Insert(projectID, net).Context(ctx).Do()
}
```

**What I expected:**
I expected to see a new VPC created with custom mode, since the default value of `AutoCreateSubnetworks` field in [`compute.Network`](https://godoc.org/google.golang.org/api/compute/v1#Network) is _false_.

**What I saw instead:**
I saw a new VPC created in _legacy_ mode rather than _custom_ mode. 

**How I solved:**
Apparently, even if `AutoCreateSubnetworks` is explicitely set to _false_, it is still omitted from request payload. Therefore, it seems that GCP backend interprets this request as a _legacy_ VPC creation. The only way I found to create a custom-mode VPC is to enforce the request to contain the `AutoCreateSubnetworks` field. In fact, the below code works:

```Go
func CreateVPC(ctx context.Context, ns *compute.NetworksService, name string) (*compute.Operation, error) {
	net := &compute.Network{
		Name:                  name,
		AutoCreateSubnetworks: false,
		// make sure AutoCreateSubnetworks field is included in request
		ForceSendFields: []string{"AutoCreateSubnetworks"},
	}
	return ns.Insert(projectID, net).Context(ctx).Do()
}
```

Now, is it possible to improve the `compute.Network` doc? Precisely, `AutoCreateSubnetworks` comment should say that it is omitted by default and a legacy VPC is created instead in that case. Also, doc should say explicitely that `AutoCreateSubnetworks` field should be included in payload through `ForceSendFields` if users want to create a non-legacy VPC.

There seems to be a related issue opened ~1 year ago:  #307.

Also see: https://stackoverflow.com/questions/59058750/gcp-compute-api-creates-vpc-in-legacy-mode/59067604#59067604

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/google-api-go-client/+/49350

**Comment by bigmikes** [comment]
Thanks for making the change @jadekler. One question though, now that `AutoCreateSubnetworks` is trinary, what is the difference between `nil` and `false`? Is it the following?

- True: VPC in auto mode;
- False: VPC in custom mode;
- Nil: Legacy VPC;

If so, would it be better to state this in comment?

**Comment by jadekler** [comment]
Correct, yes.

**Comment by codyoss** [comment]
The recommendation is to use ForceSendFields, as you have discovered. I am hesitant to change this field.
