### ISSUE TITLE
Slides API Client does not support Range type `FIXED_RANGE` with `StartIndex` = 0 (zero)

### ISSUE THREAD

**Issue by grokify** [googleapis/google-api-go-client#433]
Attempting to set Slides API StartIndex to 0 returns the following error:

`googleapi: Error 400: Invalid requests[2].updateTextStyle: The textRange startIndex must be specified for range type FIXED_RANGE, badRequest`

This happens while attempting the following which is a port from the Python example here:

https://www.youtube.com/watch?v=_O2aUCJyCoQ

```go
	reqs = []*slides.Request{
		{ // change word 1 in para 1 ("Bold") to bold
			UpdateTextStyle: &slides.UpdateTextStyleRequest{
				ObjectId: textboxID,
				Style: &slides.TextStyle{
					Bold: true,
				},
				TextRange: &slides.Range{
					Type:       "FIXED_RANGE",
					StartIndex: int64(0),
					EndIndex:   int64(4),
				},
				Fields: "bold",
			},
		},
```

The reason this happens is that in the type `Range`, the comment indicates this is required for `FIXED_RANGE` type but the JSON tag is set to `omitempty` so that zero values are omitted.

```go
// Range: Specifies a contiguous range of an indexed collection, such as
// characters in
// text.
type Range struct {
	// EndIndex: The optional zero-based index of the end of the
	// collection.
	// Required for `FIXED_RANGE` ranges.
	EndIndex int64 `json:"endIndex,omitempty"`

	// StartIndex: The optional zero-based index of the beginning of the
	// collection.
	// Required for `FIXED_RANGE` and `FROM_START_INDEX` ranges.
	StartIndex int64 `json:"startIndex,omitempty"`
```

Another issue is that some range types **require** these indexes to **not** be present. I was able to remove `omitempty` in a fork and received the following error:

`googleapi: Error 400: Invalid requests[5].createParagraphBullets: The textRange startIndex must not be specified for range type ALL, badRequest`

Seems like separate Range structs may be necessary.

**Comment by jadekler** [comment]
Looks like this question is about the slides API itself, and the error you're seeing is from the API. This repository, on the other hand, just houses the generator and auto-generated content for discovery-based APIs (https://www.googleapis.com/discovery/v1/apis). As such, no API teams monitor this issue tracker.

To get in touch with the slides team, would you mind re-filing this issue through the support channels listed at https://developers.google.com/slides/support?

**Comment by grokify** [comment]
@jadekler This is actually a client library issue. Then Range struct cannot handle all variations of the API.

The Client cannot handle the following API behavior:

* When Range Type is `ALL`, `startIndex` **must not** be present
* When Range Type is `FIXED_RANGE`, `startIndex **must** be present

Right now, `startIndex` of `0` and `type` of `FIXED_RANGE` is not implemented by the client.

**Comment by jadekler** [comment]
Ahh. Hm. Ok, thanks for the clarification! One-offs like this are tricky - we'll investigate.

**Comment by codyoss** [comment]
I think the best option we can do here is make both of these indexes pointer types. It is not the most ergonomic option, but it would allow both apis to work.
