### ISSUE TITLE
Support `WithProxy(proxy string)` ClientOption

### ISSUE THREAD

**Issue by lookuptable** [googleapis/google-api-go-client#434]
We have a binary that talks with multiple external services, and only communication with some services needs to be proxied. Thus we can not specify the proxy as an environment variable (as suggested in #221) since that will force all traffic to go through the proxy.

I'm wondering if it is okay to have a `WithProxy(proxyURL string)` `ClientOption` so that we can selectively configure proxies when creating clients for certain services.

Does this make sense?

**Comment by lookuptable** [comment]
cc @sarandia

**Comment by jadekler** [comment]
Sounds like what you're looking for is https://godoc.org/google.golang.org/api/option#WithEndpoint?

**Comment by sarandia** [comment]
We are trying to use it in the context of https://github.com/googleapis/google-api-go-client/blob/master/bigquery/v2/bigquery-gen.go. What should the endpoint be, if, say we're using a proxy with the URL 127.0.0.1:8888, and our request needs to be routed to https://bigquery.googleapis.com/bigquery/v2/?

The net/http library have the ability to define its own proxy https://golang.org/pkg/net/http/#ProxyURL, so perhaps it would still be more user-friendly to implement a WithProxy() option based on that?

**Comment by jadekler** [comment]
So, I take it you would like the following?

```
client library -> proxy -> bigquery API
```

Is so, it seems like your proxy should do the redirecting, not anything on the client library side.

> The net/http library have the ability to define its own proxy https://golang.org/pkg/net/http/#ProxyURL

I've never seen this, and don't really understand the docs. What does it do? Change the endpoint dynamically based on the outgoing request?

Also, if you'd like to use that, it seems like you could create a custom http client with your own http transport that has that proxy set, no? That http client would be passed in with https://godoc.org/google.golang.org/api/option#WithHTTPClient.

**Comment by sarandia** [comment]
I am not entirely clear what the net/http is implemented - it looks like it's trying to re-write the request based on the proxy endpoint provided.

We could use that, but we are trying to use this to access the BigQuery API. If we use WithHTTPClient(), then the BigQuery client will be created without applying the WithToken() option. This means that Oauth won't be set up properly. See https://github.com/googleapis/google-api-go-client/blob/master/transport/http/dial.go#L32. If we use WithHTTPClient then WithToken will be ignored.

We could create an HTTP client with both proxy and Oauth, then create a BigQuery client using WithHTTPClient(), but it would require us to copy lots of private fields and structs out of the BigQuery client library (e.g. endpoint, userAgentPrefix, and https://github.com/golang/go/blob/master/src/net/http/transport.go#L42). This doesn't seem like a very polished solution and is error-prone.

**Comment by jadekler** [comment]
You can use https://godoc.org/google.golang.org/api/transport/http#NewClient to get an authentication client (and pass it WithToken). :)

**Comment by sarandia** [comment]
Yeah, this is what I described as a work-around, but it's not the best solution because:
1. I will still need to copy https://github.com/golang/go/blob/master/src/net/http/transport.go#L42, with a bunch of magic numbers in the struct. After I created the client using WithToken, I will need to do something like
`baseTransportWithProxy := &http.Transport{
		Proxy: e.bigQueryProxy,
		DialContext: (&net.Dialer{
			Timeout:   30 * time.Second,
			KeepAlive: 30 * time.Second,
			DualStack: true,
		}).DialContext,
		ForceAttemptHTTP2:     true,
		MaxIdleConns:          100,
		IdleConnTimeout:       90 * time.Second,
		TLSHandshakeTimeout:   10 * time.Second,
		ExpectContinueTimeout: 1 * time.Second,
	}
	httpClientWithProxy.Transport.(*oauth2.Transport).Base = baseTransportWithProxy`

In order to add a proxy URL to the HTTP client.
Also, some constants defined in the BigQuery client library are private and need to be copied to my own code, making it hard to maintain. For example, I need to define these in my own code:
`const (
	bqProdAddr = "https://www.googleapis.com/bigquery/v2/"
	bqUserAgent = "gcloud-golang-bigquery/20160429"
)`

That's why we were hoping if the client library could support WithProxy() natively so we won't need to deal with the HTTP details that should be abstracted out from the user program:)

**Comment by jadekler** [comment]
You can use `http. DefaultTransport` and just override the single proxy field.

> For example, I need to define these in my own code:

Yes - that seems correct. It doesn't seem much to maintain, to me. In total it seems like - besides your proxy - it's only about 4 extra lines of code. This seems very far within reasonable to me.

**Comment by nifflerfox** [comment]
> Yeah, this is what I described as a work-around, but it's not the best solution because:
> 
> 1. I will still need to copy https://github.com/golang/go/blob/master/src/net/http/transport.go#L42, with a bunch of magic numbers in the struct. After I created the client using WithToken, I will need to do something like
> 
> ```
> baseTransportWithProxy := &http.Transport{
> 		Proxy: MY_OWN_PROXYURL_FUNC,
> 		DialContext: (&net.Dialer{
> 			Timeout:   30 * time.Second,
> 			KeepAlive: 30 * time.Second,
> 			DualStack: true,
> 		}).DialContext,
> 		ForceAttemptHTTP2:     true,
> 		MaxIdleConns:          100,
> 		IdleConnTimeout:       90 * time.Second,
> 		TLSHandshakeTimeout:   10 * time.Second,
> 		ExpectContinueTimeout: 1 * time.Second,
> 	}
> httpClientWithProxy.Transport.(*oauth2.Transport).Base = baseTransportWithProxy
> ```
> 
> In order to add a proxy URL to the HTTP client.
> Also, some constants defined in the BigQuery client library are private and need to be copied to my own code, making it hard to maintain. For example, I need to define these in my own code:
> 
> ```
> const (
>     bqProdAddr = "https://www.googleapis.com/bigquery/v2/"
>     bqUserAgent = "gcloud-golang-bigquery/20160429"
> )
> ```
> 
> That's why we were hoping if the client library could support WithProxy() natively so we won't need to deal with the HTTP details that should be abstracted out from the user program:)

it works. But I think WithProxy is a good option, or you can give an official demo to show how to build client with proxy.

**Comment by Random-Liu** [comment]
+1

**Comment by codyoss** [comment]
Instead of adding another configuration option what if we just used the function from the stdlib to detect a known environment variable. We could set our default proxy to this function: 
https://github.com/golang/go/blob/776a9d0958973bff6a66e61baa6a9a240ada4255/src/net/http/transport.go#L42-L43

**Comment by unixchad** [comment]
> We have a binary that talks with multiple external services, and only communication with some services needs to be proxied. Thus we can not specify the proxy as an environment variable (as suggested in #221) since that will force all traffic to go through the proxy.

+1 for WithProxy()

**Comment by unixchad** [comment]
> ```
> baseTransportWithProxy := &http.Transport{
> 		Proxy: MY_OWN_PROXYURL_FUNC,
> 		DialContext: (&net.Dialer{
> 			Timeout:   30 * time.Second,
> 			KeepAlive: 30 * time.Second,
> 			DualStack: true,
> 		}).DialContext,
> 		ForceAttemptHTTP2:     true,
> 		MaxIdleConns:          100,
> 		IdleConnTimeout:       90 * time.Second,
> 		TLSHandshakeTimeout:   10 * time.Second,
> 		ExpectContinueTimeout: 1 * time.Second,
> 	}
> httpClientWithProxy.Transport.(*oauth2.Transport).Base = baseTransportWithProxy
> ```

I was in a similar position as you with `google.golang.org/api/drive/v3`. FWIW you can also clone the base transport:
`base := http.DefaultTransport.(*http.Transport).Clone()` and then change `base.Proxy = YourProxyFunc()`

+1 for WithProxy()

**Comment by codyoss** [comment]
We are thinking about adding support for this via #1962.

**Comment by broady** [comment]
A couple thoughts...

Beginning to think that a `WithDialer` option that matches gRPC's type definition:

```
func WithDialer(f func(context.Context, string) (net.Conn, error)) DialOption
```

https://godoc.org/google.golang.org/grpc#WithContextDialer

We could use this for both our JSON/REST (net/http) and gRPC clients.

Then you can use [golang.org/x/net/proxy](https://godoc.org/golang.org/x/net/proxy).

However, x/net/proxy is kind of cumbersome to use because the return type is a Dialer interface that's context-unaware . (though the underlying type is, and I think can safely be typecast to `proxy.ContextDialer`

**Comment by codyoss** [comment]
This issue is now being tracked at googleapis/google-cloud-go#1962. This case should be considered when we evaluate options. If the decided solution does not end up supporting proxy settings this issue will be reopened to track that feature.

**Comment by harpratap** [comment]
@sarandia Can you provide the part where you create http client and pass it to your bigQuery client? I cannot seem to make it work with this -
```
hc, _, err := transport.NewHTTPClient(ctx, option.WithCredentialsFile("/auth/my-serviceaccount.json"))
if err != nil {
  log.Fatal(err)
}
client, err := storage.NewClient(ctx, option.WithHTTPClient(hc))
if err != nil {
  log.Fatal(err)
}
```
I keep getting `401, NoAuth` so not sure how to get an authenticated http client
