### ISSUE TITLE
Batched User.messages.get requests for GMail API

### ISSUE THREAD

**Issue by bzz** [googleapis/google-api-go-client#435]
A quick glance at the source code of Gmail API go client as well as the blog post on ["Discontinuing support for global HTTP batch endpoints"](https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html) both seems to indicate that [getting](https://developers.google.com/gmail/api/v1/reference/users/messages/get) multiple messages in a batch is not supported.

It would be really nice to be able to batch Get requests, same way as it's possible to do with Delete or Modify ones already, otherwise fetching even small number of messages <100 takes 10s of second.

**Comment by jadekler** [comment]
Hello! Unfortunately these clients are in maintenance mode - we won't be adding new features.

**Comment by bzz** [comment]
Thank you for prompt reply! @jadekler is there any advice on what client lib should be used instead?

**Comment by jadekler** [comment]
@bzz I'm honestly not sure - this repository / issue tracker is just for the auto-generated clients. We're pretty out of the loop about what the future plans for individual APIs are, I'm afraid. :/ It does look like gmail has a support page - https://developers.google.com/gmail/api/support. I would suggest asking there what the recommendation for bulk email downloads is. If you have trouble getting in touch with someone, ping back here and I'll try to poke a couple people on the gmail team for you.
