### ISSUE TITLE
Raise default GCS ChunkSize to 16MB

### ISSUE THREAD

**Issue by bjornleffler** [googleapis/google-api-go-client#437]
The sweet spot for uploading larger objects to GCS is using a ChunkSize around 16 MB. The default is currently 8MB. For larger (100MB) objects, uploaded from GCE, this results in a 10% performance improvement. I propose 16MB, rather than the 15MB chosen for the Java API, as it aligns nicely with 8MB boundaries.

This issue is similar to
https://github.com/googleapis/java-core/issues/86
Credit to @domZippilli for doing the research.

**Comment by bjornleffler** [comment]
Submitted https://github.com/bjornleffler/google-api-go-client/pull/1 to fix this.

**Comment by tritone** [comment]
We use gerrit for PRs to this repo (see https://github.com/googleapis/google-api-go-client/blob/master/CONTRIBUTING.md ). Feel free to create a PR using the process outlined there, or I can do so on your behalf if you don't feel like going through the setup steps.

**Comment by tritone** [comment]
Since I didn't hear from you, I opened https://code-review.googlesource.com/c/google-api-go-client/+/50290 . Feel free to review it or let me know if there's anything else I can add. Thanks for you help!
