### ISSUE TITLE
compute-gen.go is huge

### ISSUE THREAD

**Issue by y0ssar1an** [googleapis/google-api-go-client#438]
I'm not able to vendor this file because my company's git policy forbids checking in files larger than 5 MB. This file is 5.3 MB. Is there any way to shrink it?

```
vendor/google.golang.org/api/compute/v1/compute-gen.go
```

**Comment by codyoss** [comment]
On our end this is an auto-generated file that gets updated as the backing services server definitions gets updated, so I don't think there are any changes we can make to shrink the file size. That being said, on your end have you considered removing the docs from your vendored code? That should save a few MB.
