### ISSUE TITLE
oauth2: generate token interface

### ISSUE THREAD

**Issue by carnott-snap** [googleapis/google-api-go-client#439]
It appears that neither `oauth2/v1` nor `oauth2/v2` implement a client for `https://oauth2.googleapis.com/token`. Would it be possible to add this api interface to the appropriate package?

**Comment by codyoss** [comment]
Are you looking for this: https://github.com/golang/oauth2/blob/0f29369cfe4552d0e4bcddc57cc75f4d7e672a33/google/google.go#L24

**Comment by carnott-snap** [comment]
I have implemented a manual client with that value, but was wanting a full `TokenCall` interface:
```go
package oauth2

func NewService() *Service { /* ... */}

struct Service { /* ... */}

func (s *Service) Token() *TokenCall { /* ... */}

struct TokenCall { /* ... */}

func (c *TokenCall) Do(opts ...googleapi.CallOption) (*Token, error) { /* ... */}

struct TokenCall { /* ... */}
```

**Comment by codyoss** [comment]
If you are looking to generate tokens we now have a new `idtoken` api. https://pkg.go.dev/google.golang.org/api/idtoken?tab=doc 😄

**Comment by carnott-snap** [comment]
Does this support domain wide delegation, as implemented [here](https://git.sr.ht/~urandom/dwd/tree/master/dwd.go)?

**Comment by codyoss** [comment]
it does not yet support impersonation. We issue #378 to track that.
