### ISSUE TITLE
Support extra headers parameter for pagespeedonline

### ISSUE THREAD

**Issue by hakimelek** [googleapis/google-api-go-client#440]
As of pagespeedonline v5, it seems like passing extra HTTP headers is not supported when running a test. This is useful when passing custom cookies or overriding the user-agent. 

Other controls supported by the [lighthouse agent](https://github.com/GoogleChrome/lighthouse#cli-options) are nice to have as well.
```
  --throttling-method                  Controls throttling method         [choices: "devtools", "provided", "simulate"]
  --throttling.rttMs                   Controls simulated network RTT (TCP layer)
  --throttling.throughputKbps          Controls simulated network download throughput
  --throttling.requestLatencyMs        Controls emulated network RTT (HTTP layer)
  --throttling.downloadThroughputKbps  Controls emulated network download throughput
  --throttling.uploadThroughputKbps    Controls emulated network upload throughput
  --throttling.cpuSlowdownMultiplier   Controls simulated + emulated CPU throttling
  --extra-headers               Set extra HTTP Headers to pass with request  
```

**Comment by codyoss** [comment]
To do this, you could provide a custom client: https://stackoverflow.com/questions/51325704/adding-a-default-http-header-in-go

ClientOption: https://godoc.org/github.com/googleapis/google-api-go-client/option#WithHTTPClient
