### ISSUE TITLE
generator: gl-go value is not very useful

### ISSUE THREAD

**Issue by broady** [googleapis/google-api-go-client#447]
This library sends a header with each request:
`x-goog-api-client: gl-go/1.12.5 gdcl/....`

`1.12.5` is the version of Go that the generator was built with. This is not very useful. It would be better to make this a static value (so it doesn't look useful) or use the version of Go that the user is using (but I can't think of a good reason to do that either).

/cc @JustinBeckwith @tbpg

**Comment by codyoss** [comment]
This seems to have been fixed some time ago in 062a97fa4d41c3f23e4beb92ab38428b2626b483. Closing
