### ISSUE TITLE
Broken sql/sqladmin package

### ISSUE THREAD

**Issue by kacper-zylka** [googleapis/google-api-go-client#448]
Hello,

I've been getting this error since yesterday in our build tool, here it is reproduced:
```
> go get google.golang.org/api/...
can't load package: package google.golang.org/api/sqladmin/v1beta4: code in directory /Users/kacper/go/src/google.golang.org/api/sqladmin/v1beta4 expects import "google.golang.org/api/sql/v1beta4"
```

I believe [this](https://github.com/googleapis/google-api-go-client/commit/8c19f07ca61ae7b417f580832f8f7a91c8e16de8#diff-fc3696d32750cf4e3f741d7d50fda5f4L42-R42) change:

```
- package sqladmin // import "google.golang.org/api/sqladmin/v1beta4"
+ package sql // import "google.golang.org/api/sql/v1beta4"
```
 in ` sqladmin/v1beta4/sqladmin-gen.go` in release 0.16.0 is responsible. It looks like the package `sqladmin` was merged into package `sql` but it cannot compile because they are still in different directories?

Please let me know if this is indeed the issue or if the problem is somewhere on our side.

**Comment by tbpg** [comment]
Seems to be a problem on our side -- looking into it. Thank you for reporting this!

**Comment by broady** [comment]
Very strange. The changes to the JSON discovery doc should not have caused that.

https://code-review.googlesource.com/c/google-api-go-client/+/51393/2/sqladmin/v1beta4/sqladmin-api.json#25

Will investigate.

**Comment by broady** [comment]
The discovery doc changed substantially back in November:
https://code-review.googlesource.com/c/google-api-go-client/+/48474/2/sqladmin/v1beta4/sqladmin-api.json#b32

Strangely, it looks like sqladmin hadn't been re-generated since my manual re-generation (8c19f07ca61ae7b417f580832f8f7a91c8e16de8) even though the discovery doc had changed several times.

The root cause is certainly that the discovery doc says "sql" when the API name is "sqladmin".

Root discovery service says:

```
    {
      "kind": "discovery#directoryItem",
      "id": "sql:v1beta4",
      "name": "sql",
      "version": "v1beta4",
      "title": "Cloud SQL Admin API",
      "description": "API for Cloud SQL database instance management",
      "discoveryRestUrl": "https://sqladmin.googleapis.com/$discovery/rest?version=v1beta4",
      "icons": {
        "x16": "https://www.gstatic.com/images/branding/product/1x/googleg_16dp.png",
        "x32": "https://www.gstatic.com/images/branding/product/1x/googleg_32dp.png"
      },
      "documentationLink": "https://developers.google.com/cloud-sql/",
      "preferred": true
    },
    {
      "kind": "discovery#directoryItem",
      "id": "sqladmin:v1beta4",
      "name": "sqladmin",
      "version": "v1beta4",
      "title": "Cloud SQL Admin API",
      "description": "Creates and manages Cloud SQL instances, which provide fully managed MySQL or PostgreSQL databases.",
      "discoveryRestUrl": "https://www.googleapis.com/discovery/v1/apis/sqladmin/v1beta4/rest",
      "discoveryLink": "./apis/sqladmin/v1beta4/rest",
      "icons": {
        "x16": "https://www.gstatic.com/images/branding/product/1x/googleg_16dp.png",
        "x32": "https://www.gstatic.com/images/branding/product/1x/googleg_32dp.png"
      },
      "documentationLink": "https://cloud.google.com/sql/docs/reference/latest",
      "preferred": true
    },
```

But the discovery doc at https://www.googleapis.com/discovery/v1/apis/sqladmin/v1beta4/rest says:

```
{
  "basePath": "",
  "ownerDomain": "google.com",
  "name": "sql",
  "batchPath": "batch",
  "revision": "20200124",
  "documentationLink": "https://developers.google.com/cloud-sql/",
  "id": "sql:v1beta4",
  "title": "Cloud SQL Admin API",
...
```

notice how name and id say "sql" and not "sqladmin"

**Comment by broady** [comment]
I really don't understand what happened, but I regenerated everything again and now it's back to the way it should be.

https://code-review.googlesource.com/c/google-api-go-client/+/51550

**Comment by broady** [comment]
This is the diff between running `make all` vs `make local`:

```
-// Package sqladmin provides access to the Cloud SQL Admin API.
-//   import "google.golang.org/api/sqladmin/v1beta4"
-//   sqladminService, err := sqladmin.NewService(ctx)
-//   sqladminService, err := sqladmin.NewService(ctx, option.WithScopes(sqladmin.SqlserviceAdminScope))
-//   sqladminService, err := sqladmin.NewService(ctx, option.WithAPIKey("AIza..."))
-//   sqladminService, err := sqladmin.NewService(ctx, option.WithTokenSource(config.TokenSource(ctx, token)))
-package sqladmin // import "google.golang.org/api/sqladmin/v1beta4"
-       StorageAutoResize *bool `json:"storageAutoResize,omitempty"`
```

**Comment by tbpg** [comment]
Next step is a `v0.17.0` release, but leaving this closed.

You can depend on `v0.16.1-0.20200206160949-b1dd6985e76a` until we get that out.

**Comment by broady** [comment]
v0.17.0 is tagged.

**Comment by kacper-zylka** [comment]
Thank you all for looking into this so quickly!

**Comment by broady** [comment]
Thank you for flagging it.
