### ISSUE TITLE
internal/gensupport: resumable upload doesn't retry network errors or unexpected EOF when wrapped in url.Error

### ISSUE THREAD

**Issue by rogerhub** [googleapis/google-api-go-client#449]
I use the [google-cloud-go GCS client](https://github.com/googleapis/google-cloud-go/tree/master/storage), and I noticed that object uploads were failing sometimes with error messages like:

```
Post https://www.googleapis.com/upload/storage/v1/b/...: write tcp [2001:db8::]:...->[2001:db8::]:443: write: connection reset by peer
```

The GCS library delegates retry behavior to this package (google-api-go-client) -- see googleapis/google-cloud-go#1507 and [this test case](https://github.com/googleapis/google-cloud-go/blob/master/storage/retry_test.go).

This package defines retryable errors as:

```go
	var shouldRetry = func(status int, err error) bool {
		if 500 <= status && status <= 599 {
			return true
		}
		if status == statusTooManyRequests {
			return true
		}
		if err == io.ErrUnexpectedEOF {
			return true
		}
		if err, ok := err.(interface{ Temporary() bool }); ok {
			return err.Temporary()
		}
		return false
	}
```

I did a bit of testing, and I noticed that these errors are considered non-retryable:

1) A `*url.Error`, where the embedded error (i.e. `err.Unwrap()`) is io.ErrUnexpectedEOF.
2) A `*url.Error`, where the embedded error (i.e. `err.Unwrap()`) is a `*net.OpError` containing "write: connection reset by peer".

Some thinking here:

(1) is probably unintentional, since shouldRetry explicitly mentions that io.ErrUnexpectedEOF should be retried.

(2) seems retryable to me (although this is debatable). The "net" package says that connection reset errors are not Temporary() -- unless the operation is socket accept. However, that just means that the socket should be discarded. In the context of the overall resumable upload operation, this error should be considered a temporary network error and should be retried.

Anyway, the presence of these two errors make it so that uploads are unexpectedly fragile.

Here's my crappy attempt at a fix: (this suffices for my own use case)

```patch
diff --git a/internal/gensupport/resumable.go b/internal/gensupport/resumable.go
index e67ccd9a6..aa63fc7fe 100644
--- a/internal/gensupport/resumable.go
+++ b/internal/gensupport/resumable.go
@@ -9,6 +9,7 @@ import (
 	"errors"
 	"fmt"
 	"io"
+	"net"
 	"net/http"
 	"sync"
 	"time"
@@ -151,6 +152,29 @@ func (rx *ResumableUpload) transferChunk(ctx context.Context) (*http.Response, e
 	return res, nil
 }
 
+func shouldRetry(status int, err error) bool {
+	if 500 <= status && status <= 599 {
+		return true
+	}
+	if status == statusTooManyRequests {
+		return true
+	}
+	if err == io.ErrUnexpectedEOF {
+		return true
+	}
+	if _, ok := err.(*net.OpError); ok {
+		// Treat all network errors as temporary.
+		return true
+	}
+	if err, ok := err.(interface{ Unwrap() error }); ok {
+		return shouldRetry(status, err.Unwrap())
+	}
+	if err, ok := err.(interface{ Temporary() bool }); ok {
+		return err.Temporary()
+	}
+	return false
+}
+
 // Upload starts the process of a resumable upload with a cancellable context.
 // It retries using the provided back off strategy until cancelled or the
 // strategy indicates to stop retrying.
@@ -160,22 +184,6 @@ func (rx *ResumableUpload) transferChunk(ctx context.Context) (*http.Response, e
 // rx is private to the auto-generated API code.
 // Exactly one of resp or err will be nil.  If resp is non-nil, the caller must call resp.Body.Close.
 func (rx *ResumableUpload) Upload(ctx context.Context) (resp *http.Response, err error) {
-	var shouldRetry = func(status int, err error) bool {
-		if 500 <= status && status <= 599 {
-			return true
-		}
-		if status == statusTooManyRequests {
-			return true
-		}
-		if err == io.ErrUnexpectedEOF {
-			return true
-		}
-		if err, ok := err.(interface{ Temporary() bool }); ok {
-			return err.Temporary()
-		}
-		return false
-	}
-
 	// There are a couple of cases where it's possible for err and resp to both
 	// be non-nil. However, we expose a simpler contract to our callers: exactly
 	// one of resp and err will be non-nil. This means that any response body
```

**Comment by tbpg** [comment]
@broady, do you know if this is intentional? Marking as a P2 bug for now, but feel free to change.

**Comment by rogerhub** [comment]
Let me know if there's anything I can do to help debug this.

**Comment by tritone** [comment]
@rogerhub thanks very much for your report. I created #529 to resolve this; feel free to comment if you like.

I took a narrower approach to net.OpErr based on what kinds of socket-level errors we have heard about in recent customer complaints, rather than doing a blanket retry. If there are any other particular codes that you're seeing problems from, feel free to let me know.

**Comment by rogerhub** [comment]
@tritone Your approach looks good to me! Thank you for following up on this.

**Comment by rogerhub** [comment]
Actually, I may have spoken too soon. I vaguely remember that a broken connection is considered a non-temporary error from the socket (net) point of view, which makes sense (the socket is permanently dead). But this should be considered a temporary error from the API client's point of view. I think I initially wrote a fix like yours, but I ended up changing it to also include all network errors because of the mismatch of expectations.

But this was many months ago, and I don't have any evidence to support my claims.

**Comment by rogerhub** [comment]
Nevermind, I see you're matching specifically against connection reset errors. Carry on.

**Comment by tritone** [comment]
The fix for this has been released and also propagated into the latest release of cloud.google.com/go/storage .
