### ISSUE TITLE
compute: ListManagedInstances() seems to be missing Pages() method

### ISSUE THREAD

**Issue by geojaz** [googleapis/google-api-go-client#451]
In the v1 version of the api, i can't find a Pages method on the `InstanceGroupManagersListManagedInstancesCall` (which I believe is returned by `Compute().InstanceGroupManagers().ListManagedInstances()`). This method seems to be available on other permutations of InstanceGroups and existed in v0.beta. 

Am I missing something or did this one get overlooked? Thanks!

**Comment by tbpg** [comment]
@grayside, is this expected?

**Comment by rifelpet** [comment]
It looks like `Pages` was added in v0.22.0 so this should be safe to close out.

**Comment by codyoss** [comment]
https://pkg.go.dev/google.golang.org/api/compute/v1?tab=doc#InstanceGroupManagersListManagedInstancesCall.Pages
