### ISSUE TITLE
can't use PATCH/update to un-suspend a user

### ISSUE THREAD

**Issue by fitzboy** [googleapis/google-api-go-client#453]
I am trying to use Update to reinstate (un-suspend) a user, but it is a no-op because I am setting Suspended: false, but because `json:"suspended,omitempty"`, the json marshaller will omit the setting and hence they are not reinstated... I suspect it is the same with other fields like IncludeInGlobalAddressList and IpWhitelisted... Typically we would want to make it a *bool, but that would change everything then. Any ideas?

**Comment by tbpg** [comment]
What API is this for? Could you include a full code sample showing what you tried/ what you're trying to do?

**Comment by fitzboy** [comment]
I am trying to use this:
https://godoc.org/google.golang.org/api/admin/directory/v1#UsersUpdateCall.Do

and here is the User struct which shows the omit empty: https://github.com/googleapis/google-api-go-client/blob/master/admin/directory/v1/admin-gen.go#L3595

here is the code snippet:
import (	admin "google.golang.org/api/admin/directory/v1" )
gconf := &jwt.Config{
		Email:      envy.Get("GOOGLE_CLIENT_EMAIL", ""),
		PrivateKey: []byte(envy.Get("GOOGLE_CLIENT_PRIVATE_KEY", "")),
		Subject:    envy.Get("GOOGLE_CLIENT_SUBJECT", ""),
		Scopes: []string{
			"https://www.googleapis.com/auth/admin.directory.group",
			"https://www.googleapis.com/auth/admin.directory.user",
			"https://www.googleapis.com/auth/apps.groups.settings",
		},
		TokenURL: google.JWTTokenURL,
	}
	u := &admin.User{Suspended: false}
        gd, _ := admin.New(gconf.Client(context.Background()))
	_, err := gd.Users.Update(email, u).Do()
	if err != nil {
		log.Printf("unable to reinstate account for %s because %v", email, err)
	} else {
		log.Printf("reinstated account for %s", email)
	}

--> it doesn't return an error, it just doesn't do anything. When I do the same call but set Suspended: true, then the function works as expected. So basically, I can use the API fine to suspend a user, but I can't use it to reinstate/un-suspend a user.

**Comment by tbpg** [comment]
Thanks for the info. This does seem like a bug. But, I'm not sure what the fix is yet.

**Comment by tbpg** [comment]
In google-cloud-go, we have the `optional` package, which might be inspiration for how we should fix this: https://github.com/googleapis/google-cloud-go/blob/master/internal/optional/optional.go

I don't think we can remove the `omitempty` given the default would be `false` everywhere.

**Comment by tbpg** [comment]
A "breaking" change (`bool` -> `*bool`) for this might be OK, given it would be fixing a bug?

(Not committing to this, just throwing the idea out there.)

**Comment by fitzboy** [comment]
I found out how to do this. The answer was right in the documentation... I need to specify the Suspend field in the ForceSendFields array... https://github.com/googleapis/google-api-go-client/blob/master/admin/directory/v1/admin-gen.go#L3734

**Comment by tbpg** [comment]
Ahh. I'm gad you got it figured out and thanks for letting us know!

**Comment by hackneal** [comment]
@fitzboy could u describe this in details. How do u unsuspend the field by ForceSendFields?

**Comment by fitzboy** [comment]
@hackneal , my code looks like this (with comment above):
`	// now update the various main attributes
	// NOTE: you need to put any field into ForceSendFields for which a json:OmitEmpty would throw that field away. Hence IncludeInGlobalAddressList,
	// since it could be set to False, needs to be included there, else the update call would skip it
	gu := &admin.User{PrimaryEmail: u.PrimaryEmail, Name: name, OrgUnitPath: u.OrgUnitPath, IncludeInGlobalAddressList: u.IncludedInGlobalAddressList, ForceSendFields: []string{"IncludeInGlobalAddressList"}}
	_, err = GoogleDirectory.Users.Update(email, gu).Do()`
or another example (the reason I created the ticket): `	gu := &admin.User{Suspended: false, ForceSendFields: []string{"Suspended"}}
	_, err := GoogleDirectory.Users.Update(email, gu).Do()`
