### ISSUE TITLE
serviceusage: docs for batchEnable parent parameter should be projectId, not project number

### ISSUE THREAD

**Issue by seslattery** [googleapis/google-api-go-client#458]
The following comment should be changed from project number to project Id.  

`//       "description": "Parent to enable services on.\n\nAn example name would be:\n`projects/123` where `123` is the project number.\n\nThe `BatchEnableServices` method currently only supports projects.",`
https://github.com/googleapis/google-api-go-client/blob/master/serviceusage/v1/serviceusage-gen.go#L5944

It would also be great if more of the comment about the parent parameter could be exposed through godoc too.

**Comment by codyoss** [comment]
Thank you for the report!

**Comment by codyoss** [comment]
I believe a project number is also valid here, closing.
