### ISSUE TITLE
youtube: partner API, claims and assets

### ISSUE THREAD

**Issue by porjo** [googleapis/google-api-go-client#459]
As per: https://developers.google.com/youtube/partner & https://developers.google.com/youtube/partner/upload_claim_sample

I'm wondering if this part of the API is yet to be implemented for Go?

**Comment by codyoss** [comment]
If you are looking for the partner api, checkout https://pkg.go.dev/google.golang.org/api/youtubeanalytics/v2?tab=doc. Hope that helps!

**Comment by porjo** [comment]
I'm looking for the `claims` and `assets` objects described here: 
- https://developers.google.com/youtube/partner/docs/v1/claims
- https://developers.google.com/youtube/partner/docs/v1/assets

But not seeing those in any of the Go doc.

**Comment by Scoffins** [comment]
Any news on whether this will be implemented? Thanks.

**Comment by codyoss** [comment]
I don't believe there is anything announced publicly. The clients in this repository are auto-generated and appear as clients are released publicly. If you have a support contract, I suggest you reach out through that on timings/need. Sorry I can't be of more help.

**Comment by JanPetr** [comment]
Hello! I have the same question - I'd like to search Assets & Claims with Golang, but still cannot find it in the client. Is it implemented somewhere already or is it still missing from Golang client? Thank you!

**Comment by archy-bold** [comment]
Why isn't the Content ID API included in the client? It seems it's a massive afterthought for YouTube as retrieving things like assets is never simple.
