### ISSUE TITLE
Unpopulated values for returned Service Perimeters

### ISSUE THREAD

**Issue by gingersnapz** [googleapis/google-api-go-client#460]
The service perimeters struct highlights expected output to include:

CreateTime
UpdateTime
PerimeterType

However, the raw response for a list call (type ListServicePerimetersResponse) has null values for both CreateTime and UpdateTime for each returned service perimeter. Also, PerimeterType only returns a value if the type is a bridge: "PERIMETER_TYPE_BRIDGE". So "PERIMETER_TYPE_REGULAR" is never returned as a value.
https://github.com/googleapis/google-api-go-client/blob/master/accesscontextmanager/v1/accesscontextmanager-api.json#L1285

If these are not expected to have a value, perhaps the struct should remove them as expected output.

**Comment by codyoss** [comment]
Hey, sorry to hear you are having trouble with the api. I don't think I am much help in this case. You would need to ask this to the service team. This issue tracker deals more with the libraries themselves.(All clients are generated code). If you would like to open up a issue with the service team here is the link to do so: https://issuetracker.google.com
