### ISSUE TITLE
Drive API V3 file copy call documented poorly

### ISSUE THREAD

**Issue by gbooth27** [googleapis/google-api-go-client#461]
https://godoc.org/google.golang.org/api/drive/v3#FilesService.Copy I am trying to use this function but it is super unclear what the parameters are supposed to be there is both a argument for `fileId` and for an actual file struct  `file` there is no indication of which argument represents which file. is the `fileId` for the copied file? or is it for the destination file that will have the original file copied to. super unclear and i have yet to find a combination that works

**Comment by codyoss** [comment]
Hey, sorry you are having issues with the docs. If you need some more information on the api this can be a good resource: https://developers.google.com/drive/api/v3/reference/files/copy.

From those docs it looks like you are copying the fileId passed in with patch semantics.

**Comment by trumpetx** [comment]
This is a terrible resolution - docs are still awful
Is the argument for a *File a local file?  Remote File Location?  The api docs offer options for the new name of the file which would be copied next to the old one.  Is that consistent here?  It'd be one thing if the Go API mirrored the external API, but it does not.
