### ISSUE TITLE
Unexpected memory usage when uploading to storage buckets

### ISSUE THREAD

**Issue by AeroNotix** [googleapis/google-api-go-client#463]
Hi,

We have an application that copies in memory bytes to a Google storage bucket. Since the application literally reads bytes off the wire, then copies them into a bucket akin to the following code:

```go
object := bucketHandle.Object(name)
wc := object.NewWriter(ctx)
io.Copy(wc, io.Reader)
```

In our use-case there may be a lot of parallel requests firing off. We would like to have a well-known upper bound on the memory consumption of this application.

We attempted to achieve that by setting the ChunkSize to 8MiB:

```go
wc := object.NewWriter(ctx)
wc.ChunkSize = EightMiB
```

And wrapping the operation in a concurrency limiter. We can consistently make the application use 2x the expected amount of memory. Where the expected amount of memory is `(MaxConcurrentUploads x ChunkSize) +/- FixedOverhead`.

When profiling the main source of memory allocations is: 

https://github.com/googleapis/google-api-go-client/blob/4152e9ec7ef67ba5d6c94ff76a21716feb49f6b6/internal/gensupport/buffer.go#L26-L29

I was wondering, and was in the middle of implementing. Is there a reason why this couldn't benefit from using a sync.Pool of buffers? 

If there's a reason why such a technique isn't used - I can understand (and not waste my time implementing!).

If there's something else I didn't figure out, or information you need, please let me know.

**Comment by codyoss** [comment]
I will need to investigate this more and get back to you.

**Comment by codyoss** [comment]
I am not sure that there would be a good spot to add a pool. Right now every call has its own little buffer. Each request has the potential to have a different buffer size. So if n different buffer sizes exist, you would have n pools. Also, I am not sure how you would shut these down to get the memory back eventually.

**Comment by AeroNotix** [comment]
@codyoss there's potential here for applications to improve their memory usage if they had control over the buffer which `NewMediaBuffer` uses though. 

I wonder how much code is out there which has varying ChunkSizes within the same code base.

The pools can be part of the `BucketHandle` as well, rather than just a static package-level pool (even if you allowed for varying chunk sizes, e.g. a `map[int]sync.Pool`).

**Comment by codyoss** [comment]
Right now the use of `NewMediaBuffer`is contained to this repository. It might be tricky to get hooks into "cloud.google.com/go/storage". This seems like it would at a fair bit of complexity for users to manage.

If you were to pool the buffers you would save on allocs of memory and relieve gc overhead, but would still be memory bound 2x the pool size.

**Comment by AeroNotix** [comment]
Do you know the cause of it using 2x the memory I expect?

**Comment by codyoss** [comment]
There are two []byte. The one that backs your reader and the one used in `MediaBuffer{}`

**Comment by AeroNotix** [comment]
Ah! So I misunderstood how io.Copy would work if it is copying from a http.request.Body then. I assumed it would read bytes directly from the TCP socket into the destination buffer. I take it that's not the case then.

**Comment by codyoss** [comment]
It all depends if Reader/Writer. Checkout [Copy](https://golang.org/pkg/io/#Copy)

**Comment by AeroNotix** [comment]
Thinking about this more. @codyoss - I am not actually convinced of the reasoning you mention here.

The claim of "There are two []byte" doesn't seem correct, even if there are different Reader/Writer implementations. io.Copy will use an internal buffer of 32k if io.CopyBuffer is not used.

In my case I am using `io.Copy(storage.Writer, io.TeeReader)` where the `io.TeeReader` is reading from an `http.Request.Body`. As far as I can tell - none of these have a `io.ReaderFrom` or `io.WriteTo` implementation.

Furthermore, when making heap dumps the memory is entirely allocated to:

https://github.com/googleapis/google-api-go-client/blob/4152e9ec7ef67ba5d6c94ff76a21716feb49f6b6/internal/gensupport/buffer.go#L26-L29

There is no meaningful memory allocated elsewhere.

**Comment by codyoss** [comment]
I will try to come back and debug a little more later this week. Will reopen for now until I get a chance to dig further.

**Comment by codyoss** [comment]
Looked into this a bit. Ran a test both sequentially and in parallel where I set `wc.ChunkSize = EightMiB` and uploaded 10 files to storage. Here were my results of memory usage after the test

- Sequencial: Total allocs: 84MB | Sys: 71MB
- Parallel: Total allocs: 85 MB | Sys: 137 MB

I would expect allocs to be ~80MB which they were. I used `runtime.ReadMemStats` to dump out this information.

**Comment by AeroNotix** [comment]
Do you have the code to reproduce?

**Comment by codyoss** [comment]
The gist was
```go
        // create client and bucket handle
        MemUsage()
	//var wg sync.WaitGroup
	//wg.Add(10)
	for i := 1; i <= 10; i++ {
		//go func(i int) {
		upload(b, fmt.Sprintf("file-%d", i))
		//wg.Done()
		//}(i)
	}
	//wg.Wait()
        MemUsage()
```

```go
func upload(b *storage.BucketHandle, name string) {
	o := b.Object(name)
	wc := o.NewWriter(context.Background())
	wc.ChunkSize = 1000000 * 8 // 8MB
	defer wc.Close()
	f, err := os.Open(name)
	if err != nil {
		log.Fatal("unable to open file: %v", err)
	}
	io.Copy(wc, f)
	MemUsage()
}
```

```go
func MemUsage() {
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	fmt.Printf("TotalAlloc = %v MB", (m.TotalAlloc / 1024 / 1024))
	fmt.Printf("\tSys = %v MB\n", (m.Sys / 1024 / 1024))
}
```
