### ISSUE TITLE
drive: shortcut fields missing from File definition in SDK and Docs

### ISSUE THREAD

**Issue by ncw** [googleapis/google-api-go-client#464]
In the drive v3 API a new shortcut type was added: https://developers.google.com/drive/api/v3/shortcuts These are live on the drive web app and in use by users.

However these don't appear to be supported by the drive SDK. To be specific there are no `targetId` and `targetMimeType` fields in the `Files` type and the `shortcutDetails` field within the `Files` type is missing also.

Note that they aren't mentioned in the Files docs here: https://developers.google.com/drive/api/v3/reference/files which I think they should be!

**Comment by codyoss** [comment]
Hey,

Unfortunately I don't think I can help you much on this one.  These sdks are generated from a spec provided by the service team. If you would like to get these features added to the SDK more quickly I suggest opening an issue under the drive SDK on https://issuetracker.google.com.

**Comment by ncw** [comment]
Thanks @codyoss .

I created an issue here: https://issuetracker.google.com/issues/152865050

Any chance you could give them a poke internally too?

**Comment by ncw** [comment]
Shortcuts have landed in the SDK now :-)
