### ISSUE TITLE
storagetransfer: got error that Project id was not specified.

### ISSUE THREAD

**Issue by ma5aki-Y** [googleapis/google-api-go-client#466]
Hi, 
I attempt to get TransferOperations, in order to confirm the status and I got the below error.

My actual code is here:
```go
ctx := context.Background()
svc, err := storagetransfer.NewService(ctx)
if err != nil {
    return err
}
_, err := svc.TransferOperations.Get(jobName).Context(ctx).Do()
if err != nil {
    return err
}
```
Error: 
```
googleapi: Error 400: Project id was not specified., badRequest
```
In the case of that, How do I set the project id?
## Client
google.golang.org/api/storagetransfer/v1

## Describe Your Environment
- Go 1.12.4
- AWS Lambda

Already set credentials information to GOOGLE_APPLICATION_CREDENTIALS.

--

Thank you and best regards,

**Comment by tbpg** [comment]
How are you getting the job name? From the docs (https://pkg.go.dev/google.golang.org/api/storagetransfer/v1?tab=doc#TransferOperation):

```
	// Name: A globally unique ID assigned by the system.
```

So, I'd expect the job name to include the project ID. You can list current operations and print their names using the `List` call. Be sure to set [`Filter`](https://pkg.go.dev/google.golang.org/api/storagetransfer/v1?tab=doc#TransferOperationsListCall.Filter) to include the project ID.

Here are relevant docs for listing operations (doesn't include Go, though...): https://cloud.google.com/storage-transfer/docs/create-manage-transfer-program#check_transfer_operation_status

----

@tritone could we got the comment updated to make it more clear what `name` should be, assuming this works?

**Comment by ma5aki-Y** [comment]
@tbpg I attempt to use response value of `TransferJobs.Create` . But it does not work.
```go
job, err := svc.TransferJobs.Create(&storagetransfer.TransferJob{
	ProjectId: "",
	Status:    "ENABLED",
	Schedule: &storagetransfer.Schedule{...},
	TransferSpec: &storagetransfer.TransferSpec{...},
}).Context(ctx).Do()

if err != nil {
	return err
}

jobName := job.Name
```

So, I'll try your method that use the `List` call.  Thank you for your reply.
