### ISSUE TITLE
Have problem with google.golang.org/api@v0.21.0 requires

### ISSUE THREAD

**Issue by SagSaj** [googleapis/google-api-go-client#467]
When i try to use "google.golang.org/api/bigquery/v2"
I have error
go: google.golang.org/api@v0.21.0 requires
        cloud.google.com/go@v0.38.0 requires
        golang.org/x/sync@v0.0.0-20190227155943-e225da77a7e6/go.mod: verifying module: golang.org/x/sync@v0.0.0-20190227155943-e225da77a7e6/go.mod: malformed record data

go version
go version go1.14.1 darwin/amd64

I use gomod

**Comment by codyoss** [comment]
Can you give me more detail of how to reproduce this from scratch project? I tried to create a project from scratch, but it just worked. Here is what I did:

- Created my go mod file `go mod init example.com/ag467`
- `go get google.golang.org/api`
- Created a file that referenced "google.golang.org/api/bigquery/v2"
- `go mod tidy`
- `go run main.go` <- No errors

My mod file only has one entry "require google.golang.org/api v0.21.0"

**Comment by SagSaj** [comment]
go mod init example.com/ag467
go: creating new go.mod: module example.com/ag467
go mod tidy
go: finding module for package github.com/cloudflare/golz4
go: finding module for package github.com/evanphx/json-patch
go: finding module for package google.golang.org/api/iterator
go: finding module for package github.com/go-redis/redis
go: finding module for package github.com/google/uuid
go: finding module for package google.golang.org/api/option
go: finding module for package github.com/json-iterator/go
go: found github.com/go-redis/redis in github.com/go-redis/redis v6.15.7+incompatible
go: found github.com/google/uuid in github.com/google/uuid v1.1.1
go: found github.com/json-iterator/go in github.com/json-iterator/go v1.1.9
go: found google.golang.org/api/iterator in google.golang.org/api v0.21.0
go: found github.com/evanphx/json-patch in github.com/evanphx/json-patch v4.5.0+incompatible
go: found github.com/cloudflare/golz4 in github.com/cloudflare/golz4 v0.0.0-20150217214814-ef862a3cdc58
go: google.golang.org/api@v0.21.0 requires
        cloud.google.com/go@v0.38.0 requires
        golang.org/x/sync@v0.0.0-20190227155943-e225da77a7e6/go.mod: verifying module: golang.org/x/sync@v0.0.0-20190227155943-e225da77a7e6/go.mod: malformed record data

go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sagsaj/Library/Caches/go-build"
GOENV="/Users/sagsaj/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/sagsaj/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/sagsaj/Documents/Work/tests/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sj/cz104p016_b9wt_4dm40lrkm0000gn/T/go-build289939329=/tmp/go-build -gno-record-gcc-switches -fno-common"

I created only 
package main

import (
	"context"

	bq "google.golang.org/api/bigquery/v2"
)

func main() {
	ctx := context.Background()
	_, _ := bq.NewService(ctx)
}
thats it

**Comment by tbpg** [comment]
Would you mind running `go clean -modcache` then trying `go build` again? I tried it locally and it worked. So, the only difference _should, theoretically_ be what's in your local module cache. I don't notice anything out of the ordinary about your environment.

**Comment by SagSaj** [comment]
After go clean -modcache its working, thank you a lot)

**Comment by tbpg** [comment]
Great! I'm glad that worked. Let us know if you have any more issues. :)
