### ISSUE TITLE
admin/directory/v1: "invalid_scope" when using impersonated token source in Cloud Run

### ISSUE THREAD

**Issue by genevieveluyt** [googleapis/google-api-go-client#470]
We have an application running in Cloudrun and want it to be able to modify group membership in Gsuite, as well as make users into super admins. We want to be able to use the default application credentials available in Cloudrun to authenticate to the Admin Directory API. To do so we need the following scopes:

* `https://www.googleapis.com/auth/admin.directory.group.member` (to modify group membership)
* `https://www.googleapis.com/auth/admin.directory.user` (to make people into super admins)

When we try to add someone to a Gsuite group using the Admin Directory API, we get the following error:

```
“error”: “invalid_scope”,
“error_description”: “https://www.googleapis.com/auth/admin.directory.group.member,https://www.googleapis.com/auth/admin.directory.user is not a valid audience string.”
```

## Setup
* We granted the service account domain-wide delegation
* We added the required scopes in Gsuite admin console
* We use the following code to self-sign a JWT containing the delegated Gsuite admin user, exchange it for an access token, and use that to authenticate requests to the Admin Directory API: https://gist.github.com/julianvmodesto/ed73201703dac8a047ec35a24dce4524
```go
import (
    admin “google.golang.org/api/admin/directory/v1”
    “cloud.google.com/go/compute/metadata”
)

scopes := []string{
    // Add and remove members from Gsuite groups
    admin.AdminDirectoryGroupMemberScope,
    // Grant and revoke Gsuite super admin
    admin.AdminDirectoryUserScope,
}

serviceAccount, err := metadata.Get(“/instance/service-accounts/default/email”)
if err != nil {
    return err
}
tokenSource, err := newImpersonatedTokenSource(context.Background(), serviceAccount, scopes, gsuiteAdminUserEmail)
if err != nil {
    return err
}
adminClient, err = admin.NewService(ctx, option.WithTokenSource(tokenSource))
```

## Additional context
* Requesting only the `https://www.googleapis.com/auth/admin.directory.group.readonly` scope in the code does not result in the above error and we are able to successfully use the Admin Directory client to read group membership, so the error seems to be specific to the other scopes we are requesting
* The same behaviour seems to be present in the NodeJS client: https://github.com/googleapis/google-api-nodejs-client/issues/1381. Their fix of removing the offending scope is not viable for us
* Using a JSON file with credentials downloaded from the console makes everything work, but that kind of defeats the purpose of application default credentials and we would prefer not to use static credentials
* We tried obtaining a token from the metadata server, but as far as we could tell it also does not support specifying a subject (https://cloud.google.com/compute/docs/instances/verifying-instance-identity#request_signature)
* Related issue about user impersonation not being supported in Go: https://github.com/googleapis/google-api-go-client/issues/378#issuecomment-607304257

cc @natalysheinin

**Comment by codyoss** [comment]
You might find some information that helps in #465.

Looking quickly at the gist, I am not sure that code fills out the scopes correctly. Looking at the [docs for ClaimSet](https://pkg.go.dev/golang.org/x/oauth2@v0.0.0-20200107190931-bf48bf16ab8d/jws?tab=doc#ClaimSet). 

> 	Scope string `json:"scope,omitempty"` // space-delimited list of the permissions the application requests

**Comment by genevieveluyt** [comment]
Ah yes you're right, that did the trick! Thanks a lot @codyoss !

**Comment by codyoss** [comment]
Glad I could help 😄
