### ISSUE TITLE
run: Details in error message dropped by googleapi.CheckResponse

### ISSUE THREAD

**Issue by rileykarson** [googleapis/google-api-go-client#473]
I work on the Terraform Google Provider, where we often consume these generated service clients. We're using the `googleapi.CheckResponse` function to parse errors returned from GCP, however it's proved insufficient in this case.

The Cloud Run API returns a standard [details object](https://aip.dev/193#details) as defined by http://aip.dev/193. [This gist](https://gist.github.com/rileykarson/afae14a58e51d4e5d71e918386e86c9b) provides an example error response I received. The details object isn't recognised, and only the shared fields (message / code) are properly parsed. Unfortunately, this API returns the string "The request has errors" as the message, resulting in the near-useless `Error()` string of `googleapi: Error 400: The request has errors`.

Given that this is now the standard error format per the AIP, I believe this library should parse the format into a useful error.

Original issue: https://github.com/terraform-providers/terraform-provider-google/issues/6099
Google-internal followup with Cloud Run: b/153896811

**Comment by codyoss** [comment]
Thanks for the report! I have ran into debugging woes in the past as well with the error messages generated. I will check out the aip and see what we can do.
