### ISSUE TITLE
sheets/v4: Unable to distinguish type of EffectiveValue between cells containing "=FALSE" and "=0"

### ISSUE THREAD

**Issue by yjwong** [googleapis/google-api-go-client#474]
In Go, the `EffectiveValue` of cells with the `=FALSE` or `=0` value is indistinguishable. However, through the raw JSON returned by the API, we can see that their EffectiveValue objects are structured differently:

For the case of `=FALSE`:

```json
"effectiveValue": {
  "boolValue": false
}
```

For the case of `=0`:

```json
"effectiveValue": {
  "numberValue": 0
}
```

However, since the zero value of booleans and integers in Go is `false` and `0` respectively, the parsed structs available through the API are identical.

Namely, when printed with `%+v`, the contents of the structs are:

```
&{BoolValue:false ErrorValue:<nil> FormulaValue: NumberValue:0 StringValue: ForceSendFields:[] NullFields:[]}
```

There's the `.NullFields` field on the `EffectiveValue`,  however it seems to be only for write operations and is always an empty slice in the two cases above.

How would one go about distinguishing the type of `EffectiveValue` in this case?

**Comment by codyoss** [comment]
Hey,

That is a very good question. The default values of the builtin types make this hard to distinguish. I think this is a case we the API should be updated to make the following fields in [ExtendedValue](https://pkg.go.dev/google.golang.org/api/sheets/v4?tab=doc#ExtendedValue) pointer types: `BoolValue`, `FormulaValue`, `NumberValue`, `StringValue`.

**Comment by yjwong** [comment]
Hey @codyoss, thanks for responding!

Is there anything I can help with, for example with a pull request?

**Comment by codyoss** [comment]
@yjwong I should be able to handle this, thank you for the offer though. 😄
