### ISSUE TITLE
Issue with deleting last alias IP in a nic in Compute API

### ISSUE THREAD

**Issue by om-saran** [googleapis/google-api-go-client#476]
I'm using the [UpdateNetworkInterface](https://pkg.go.dev/google.golang.org/api/compute/v1?tab=doc#InstancesService.UpdateNetworkInterface) on v0.22.0.

When I want to remove the last alias IP, I make the UpdateNetworkInterface call and pass a NetworkInterface struct with an empty slice of AliasIpRange. This does not remove the alias IP range -- verified this on the GCP console and the response of GET API on the instance.

I'm guessing the reason is having the `omitempty` json tag in the [NetworkInterface](https://pkg.go.dev/google.golang.org/api/compute/v1?tab=doc#NetworkInterface) struct.

**Comment by codyoss** [comment]
Yes you are right, you can use the `ForceSendFields` to force this to go through.

**Comment by om-saran** [comment]
Thanks! 
I did not know about `ForceSendFields`, somehow missed that in the documentation. 

This solves the issue for me.

**Comment by codyoss** [comment]
Glad I could help!
