### ISSUE TITLE
cloudasset.AssetType is empty after json.Unmarshal

### ISSUE THREAD

**Issue by gleichda** [googleapis/google-api-go-client#479]
After switching to cloudasset.Asset https://github.com/googleapis/go-genproto/issues/364 (thanks for that hint) now when parsing the asset via json.Unmarshal Asset.AssetType is empty. 
This is due to the fact that the asset JSON is using the name `asset_type` where the lib is refering to it as `AssetType` in https://github.com/googleapis/google-api-go-client/blob/v0.24.0/cloudasset/v1/cloudasset-gen.go#L207

Also tested with a 

main.go
```go
package main

import (
	"encoding/json"
	"io/ioutil"
	"log"

	"google.golang.org/api/cloudasset/v1"
)

func main() {
	file, err := ioutil.ReadFile("asset.json")
	if err != nil {
		log.Panic(err)
	}

	var myAsset cloudasset.Asset
	err = json.Unmarshal(file, &myAsset)
	if err != nil {
		log.Panic(err)
	}
	log.Printf("%q\n", myAsset.AssetType)
}
```

asset.json
```json
{
  "name": "//cloudresourcemanager.googleapis.com/projects/123456789012",
  "asset_type": "cloudresourcemanager.googleapis.com/Project",
  "resource": {
    "version": "v1",
    "discovery_document_uri": "https://cloudresourcemanager.googleapis.com/$discovery/rest?version=v1",
    "discovery_name": "Project",
    "parent": "//cloudresourcemanager.googleapis.com/folders/234567890121",
    "data": {
      "createTime": "2018-08-08T08:04:36.279Z",
      "labels": {
        "env": "dev",
        "product": "my"
      },
      "lifecycleState": "ACTIVE",
      "name": "my-project",
      "parent": {
        "id": "234567890121",
        "type": "folder"
      },
      "projectId": "my-project-id",
      "projectNumber": "123456789012"
    }
  },
  "ancestors": [
    "projects/123456789012",
    "folders/234567890121",
    "organizations/345678901212"
  ]
}
```

## Actual behaviour
$ go run main.go
""

## Expected behaviour
$ go run main.go
"//cloudresourcemanager.googleapis.com/projects/123456789012"

**Comment by codyoss** [comment]
Where did you get that json from? Trying to figure out where the discrepancy is.

**Comment by gleichda** [comment]
Doing an export into a GCS bucket via Cloud Scheduler:
![grafik](https://user-images.githubusercontent.com/15176026/81949982-b68d4000-9603-11ea-9ef7-c849925c3df7.png)

**Comment by codyoss** [comment]
Sorry, I did mislead you a bit. You were right originally when you were using go-genproto. The issue was not using the correct unmarshalling library. The following should work:
```go
package main

import (
	"io/ioutil"
	"log"

	"github.com/golang/protobuf/proto"
	"google.golang.org/genproto/googleapis/cloud/asset/v1"
	"google.golang.org/protobuf/encoding/protojson"
)

func main() {
	file, err := ioutil.ReadFile("asset.json")
	if err != nil {
		log.Panic(err)
	}

	var myAsset asset.Asset
	m := proto.MessageV2(&myAsset)
	err = protojson.Unmarshal(file, m)
	if err != nil {
		log.Panic(err)
	}
	log.Printf("%v", myAsset)
}
```

The conversion to the new proto type should be unnecessary soon, but required for now.

**Comment by codyoss** [comment]
Closing issue as I believe the above solution should work. If it does not, please feel free to re-open.
