### ISSUE TITLE
Youtube API Etag

### ISSUE THREAD

**Issue by immersivevreducation** [googleapis/google-api-go-client#483]
I'm not sure this would be the right place but there you go.

Based on daily quota costs I'm trying to implemented what's described on documentation about Etags.

So I'm hitting the endpoint below on Postman
 https://www.googleapis.com/youtube/v3/search?channelId=UCO1cgjhGzsSYb1rsB4bFe4Q&key=

And with the response I extract the etag

![image](https://user-images.githubusercontent.com/23338451/82147748-bf6e5380-9847-11ea-8238-a7f3e24577cb.png)

and place it on the header of my next request to the same endpoint (If_none_match: etag).

The expected results would be a 304 but what I do get is a 200 and no matter what, the etag from the response keeps changing.

Does anyone knows if the implementation is right and perhaps this is a legit bug?

**Comment by codyoss** [comment]
If you are using https://pkg.go.dev/google.golang.org/api/youtube/v3?tab=doc#SearchListCall.IfNoneMatch the operation should only fail if the etag stayed the same. You are saying that the etag does indeed change right? So it should be a success.

**Comment by immersivevreducation** [comment]
@codyoss Two things here, 
- as the content from that response has not changed it technically return the same etag, that's my understanding on the API documentation, unless I'm miing something here.
- if the etag being used on a consecutive request (few secs apart) it should also return a 304, because nothing has / was really changed within that short period, would you agree with that?

**Comment by codyoss** [comment]
1) My understanding of etags is they are like a fingerprint. Should only change if something about the resource changes
2) I am not familiar enough with this api to know the volatile nature of the data. But in general, yes if the resource has not changed a 304 should be returned. The api documentation calls this out as well: https://developers.google.com/youtube/v3/getting-started

 It looks like the backend team supports questions on stackoverflow: https://developers.google.com/youtube/v3/support.

I suggest trying to reach out to them there.

**Comment by immersivevreducation** [comment]
Thanks a lot @codyoss  I have tried there before and there are loads of unanswered (similar / same) questions around that subject, some suggestions about three years old but nothing that either myself or others have already unsuccessfully tried. Long journey but trying t get to the bottom of it somehow and any assistance at this stage is more than welcome.

**Comment by codyoss** [comment]
Closing. I don't think I can provide any more more details around this topic. One more place to try is the product teams issue tracker: https://issuetracker.google.com/issues/new?component=186600&template=874803. Sorry I could not be of more help here.
