### ISSUE TITLE
idtoken: should validate expiry and possibly issuer

### ISSUE THREAD

**Issue by broady** [googleapis/google-api-go-client#484]
Currently the idtoken package verifies audience and that the JWT is valid.

But it doesn't validate that `exp` is in the future.

It's possible we should check the issuer, too - it should be `https://accounts.google.com`

Updates #160.

**Comment by codyoss** [comment]
In the case of IAP, the issuer is `https://cloud.google.com/iap`.

**Comment by codyoss** [comment]
Also for other tokens it look like it can be one of two values...: `https://accounts.google.com`, `accounts.google.com`

https://developers.google.com/identity/sign-in/web/backend-auth

**Comment by codyoss** [comment]
Also also, for ESP we say that the issuer can be a hostname or an email.[1](https://cloud.google.com/endpoints/docs/openapi/openapi-extensions#x-google-issuer) I am not sure we need to support this flow with this API though.

**Comment by broady** [comment]
Hmmm, let's not check the issuer. The fact that it's signed by Google and unexpired I think is "enough" validation.

**Comment by codyoss** [comment]
Awesome, as expiry has been added I will close this issue.
