### ISSUE TITLE
transport/grpc: support option.WithAPIKey

### ISSUE THREAD

**Issue by broady** [googleapis/google-api-go-client#485]
google.golang.org/ap/option says:

```
API Keys can only be used for JSON-over-HTTP APIs, including those under the import path google.golang.org/api/....
```

Not true, though, API keys can be used with gRPC.

Need to use the x-api-key metadata key:

```
ctx = metadata.NewOutgoingContext(ctx, metadata.Pairs("x-api-key", ...))
```

**Comment by broady** [comment]
sorry, reading this now it doesn't look like a doc bug.

**Comment by broady** [comment]
https://github.com/googleapis/google-api-go-client/blob/334f1cf68ef2ac2ae0ae06c6423b982b81aa607b/transport/grpc/dial.go#L119-L121

**Comment by broady** [comment]
Workaround:
```
ctx = metadata.AppendToOutgoingContext(ctx, "x-goog-api-key", key)
```

**Comment by zhoub** [comment]
Any better fix for this issue ?

**Comment by codyoss** [comment]
@zhoub As of right now, I think this is still the best solution.
