### ISSUE TITLE
Gmail messages.List().Do() returning failedPrecondition with no information

### ISSUE THREAD

**Issue by khipkin** [googleapis/google-api-go-client#507]
Here is my entire program:

```
package main

import (
	"context"
	"log"

	"google.golang.org/api/gmail/v1"
	"google.golang.org/api/option"
)

const (
	googleCredentialsFile = "credentials.json"
)

func main() {
	ctx := context.Background()

	client, err := gmail.NewService(ctx,
		option.WithScopes(gmail.GmailReadonlyScope, gmail.GmailMetadataScope, gmail.MailGoogleComScope),
		option.WithCredentialsFile(googleCredentialsFile))
	if err != nil {
		log.Fatalf("Failed to create new Gmail service: %v", err)
	}

	resp, err := client.Users.Messages.List("kaitlinhipkin@gmail.com").LabelIds("Receipts").Q("is:unread").Do()
	if err != nil {
		log.Fatalf("Failed to list receipts: %v", err)
	}
	for _, m := range resp.Messages {
		log.Printf("\tGot message: %s", m.ThreadId)
	}
}

```

credentials.json is a service account credentials file from https://console.cloud.google.com/iam-admin/serviceaccounts. My project number is `517131610127`, if that helps.

Every single time I run the code, I just get this, with absolutely nothing helpful:

```
$ go run main.go
2020/05/23 20:53:55 Failed to list receipts: googleapi: Error 400: Bad Request, failedPrecondition
exit status 1
```

What am I missing? Google search has been entirely unhelpful since I have so little to go on.

**Comment by codyoss** [comment]
Hello, can you please confirm what version of `google.golang.org/api/gmail/v1`you are pulling in?

**Comment by khipkin** [comment]
Hi! How do I tell what version I have?

**Comment by codyoss** [comment]
If you are using modules it would be the version recorded for `google.golang.org/api` in your `go.mod` file.

I just want to make sure you had one of the most recent releases as there have been some improvements to error messages recently.

Another way to go about this would be running `go get -u google.golang.org/api`. Then re-run your program and see if you get more details.

**Comment by khipkin** [comment]
I ran `go get -u google.golang.org/api` as you recommended, then ran my program again and got the same error.

```
$ go get -u google.golang.org/api
package google.golang.org/api: google.golang.org/api is a custom import path for https://github.com/googleapis/google-api-go-client, but C:\Users\kaitl\go\src\google.golang.org\api is checked out from https://code.googlesource.com/google-api-go-client

$ go run main.go
2020/05/26 17:13:54 Failed to list receipts: googleapi: Error 400: Bad Request, failedPrecondition
exit status 1
```

**Comment by codyoss** [comment]
I can reproduce this, I _think_ this has something to do with authentication actually. Possibly impersonated credentials. Related googleapis/google-auth-library-nodejs#898

**Comment by codyoss** [comment]
Related googleapis/google-api-ruby-client#385

**Comment by codyoss** [comment]
After some research this is what I have learned:
- The issue really has to authorization.
- You can use a service account, but in this case you would need to do some impersonating of credentials and have domain-wide-delegation set. We don't currently support impersonating directly today, but I think their are some projects you can find on GitHub to aid with this. See #378.
- Another option would be to make use of end-user oauth token and pass along the token source with `option.WithTokenSource`

Sorry there is currently not a simpler solution at this time.

**Comment by khipkin** [comment]
Okay. Since there is currently no way to do this, can you at least do something about the useless error message? Based on the FR you linked, many people have wasted a lot of time on this issue with no clue what the problem is/was.

**Comment by codyoss** [comment]
The error message is the raw message received from the backend service; these generated clients are not hiding any details. In order to get a better error message in this case a feature request should be raised to product team. They have an [issue tracker here](https://issuetracker.google.com/issues?q=status:open%20componentid:191602%2B%20type:bug).

**Comment by khipkin** [comment]
Done. https://issuetracker.google.com/issues/157590195

If anyone else encounters this problem, please star the above issue!

**Comment by codyoss** [comment]
Thanks!
