### ISSUE TITLE
Creating dynamic links fails due to wrong validation or serialization of request

### ISSUE THREAD

**Issue by pepsighan** [googleapis/google-api-go-client#516]
When I am trying to create a short dynamic link like:
```
res, err := dynLink.ShortLinks.Create(&firebasedynamiclinks.CreateShortDynamicLinkRequest{
		DynamicLinkInfo: &firebasedynamiclinks.DynamicLinkInfo{
			Link: deepLink,
			AndroidInfo: &firebasedynamiclinks.AndroidInfo{
				AndroidPackageName: cfg.AndroidPackageName,
			},
			DynamicLinkDomain: cfg.DynamicLinkDomainPrefix,
		},
	}).Do()
```

It fails with the error:
```
googleapi: Error 400: Invalid Dynamic Link domain: 'https://example-1101.page.link/' or Domain Uri Prefix: ''. Expecting exactly one. Dynamic Link Domain isPresent = false, Domain URI prefix isPresent = false,  [https://firebase.google.com/docs/dynamic-links/rest#create_a_short_link_from_parameters], badRequest
``` 

The json tags on the input says that empty fields are omitted. Why are both being sent? And it should not fail when even both are sent according to the documentation. The doc says:
1. DynamicLinkDomain required if missing DomainUriPrefix.
2. DomainUriPrefix will fallback to DynamicLinkDomain is this field is missing.

**Comment by codyoss** [comment]
I verified that the client library is sending this to the backend. I am not quite sure about what the error actually means. My assumption is something else is at play here, but the error message is not telling us what it is. I would suggest reaching out to the backend team with one of the resources on their support page: https://firebase.google.com/support
