### ISSUE TITLE
API for fetching VpcConnectors is missing

### ISSUE THREAD

**Issue by AdallomRoy** [googleapis/google-api-go-client#518]
REST API:
https://cloud.google.com/sdk/gcloud/reference/compute/networks/vpc-access/connectors/list

There is no way to perform this listing using the Go client, please advise.

Thanks

**Comment by codyoss** [comment]
You are correct. It is up to the backend product team whether or not they wish to have client libraries generated for their service. This service does have a REST API: https://cloud.google.com/vpc/docs/reference/vpcaccess/rest#discovery-document. If you would like to see a Go client for this service I suggest reaching out through that products support page.
