### ISSUE TITLE
healthcare: FHIR search path is malformed

### ISSUE THREAD

**Issue by sam-virta** [googleapis/google-api-go-client#522]
In this [path](https://github.com/googleapis/google-api-go-client/blob/master/healthcare/v1/healthcare-api.json#L2042) `fhir` is wrong and should be replaced with the value from `SearchResourcesRequest.ResourceType`.

Example Response: 
```
{"issue": [
    {
      "code": "not-supported",
      "details": {
        "text": "bad_resource_type"
      },
      "diagnostics": "unsupported resource type: fhir",
      "severity": "error"
    }
  ],
  "resourceType": "OperationOutcome"
}","severity":"error","time":"2020-06-04T17:00:54-07:00"}
```

**Comment by tbpg** [comment]
cc @noerog

**Comment by codyoss** [comment]
@sam-virta, is this still an issue for you?

**Comment by codyoss** [comment]
Closing due to lack of response.
