### ISSUE TITLE
QueryTimeSeriesRequest

### ISSUE THREAD

**Issue by benpollard** [googleapis/google-api-go-client#525]
Can anybody point me in the right direction for how to use MQL in the V3 monitoring API.

I see the QueryTimeSeriesRequest type but its not clear to me how to dispatch this request.

Thanks!

**Comment by codyoss** [comment]
I transfered this issue as I believe `google.golang.org/api/monitoring/v3` is the client being referenced.

**Comment by codyoss** [comment]
Here is some docs for the backing api(not using the client library) that should point you in the right direction. Looks like you want to add the mql string to Query field.

**Comment by benpollard** [comment]
@codyoss is there planned support for this in the client library?

**Comment by codyoss** [comment]
When you say planned support for this client library what do you mean?

**Comment by benpollard** [comment]
Apologies if my terminology is incorrect - I'm tryin dispatch a request of type QueryTimeSeriesRequest. However, I do not see a way to do this in the go client library. I can list the time series with a filter but I want to use MQL rather than filters.

**Comment by codyoss** [comment]
```go
client, err := monitoring.NewService(context.Background())
if err != nil {
   ...
}
resp, err := client. Projects. TimeSeries.Query("some-name", &monitoring.QueryTimeSeriesRequest{
   ...
}).Do().
```

**Comment by benpollard** [comment]
Thank you for taking the time to explain this. I was using: https://github.com/googleapis/google-cloud-go/blob/master/monitoring/apiv3/metric_client.go

Thanks again!

**Comment by codyoss** [comment]
It may at some point, I am not sure. Although this client is deprecated in favor of the other, it is still updated and has no sunset date. So if there is functionality that is only available to use in this library feel free to use it.
