### ISSUE TITLE
Drives.List() not working with the Q parameter, despite using working Q value

### ISSUE THREAD

**Issue by Spazzlo** [googleapis/google-api-go-client#530]
I've been trying to search drives using the Q parameter, but I keep getting errors. Here's my code (driveService is declared elsewhere, but I use it elsewhere so I know it's fine):

```go
// works
foundDrive, err := driveService.Drives.List().Do()
if err != nil {
	log.Printf("Error getting drive: %v\n", err)
	panic("uh oh")
}
log.Printf("First item: %v", foundDrive.Items[0])

// errors
foundDrive, err = driveService.Drives.List().Q("name contains 'confidential'").Do()
if err != nil {
	log.Printf("Error getting drive: %v\n", err)
	panic("uh oh")
}
log.Printf("First item: %v", foundDrive.Items[0])
```
And here's my output:
```
2020/06/12 09:08:27 First item: &{ <snip> }
2020/06/12 09:08:27 Error getting drive: googleapi: Error 400: Invalid query, invalid
panic: uh oh
<snip>
```

This doesn't make sense to me, as I'm copying the contents of Q from [this Google document](https://developers.google.com/drive/api/v3/search-shareddrives#query_search_examples).

Environment details:
```
OS: Linux Mint
Go Version: go1.14.4 linux/amd64
Api Client Version: v0.26.0
```

**Comment by codyoss** [comment]
@sqrrrl Do you have any insight here?

**Comment by sqrrrl** [comment]
Searching for shared drives by name requires also setting useDomainAccess=true and running as a domain admin. Not entirely sure *why* we restrict name searches vs. restricting the return values to Drives that user has access to, but that's the current restriction.

Looks like the docs are inconsistent in explaining this: 
https://developers.google.com/drive/api/v3/ref-search-terms -- name field is correctly footnoted.
https://developers.google.com/drive/api/v3/search-shareddrives - name query example is not footnoted.

Will file a bug for the docs and check if there's an feature request to relax name queries for non-admins.

**Comment by codyoss** [comment]
Ahh, @Spazzlo so I think you need to also use ` driveService.Drives.List().Q("name contains 'confidential'").UseDomainAdminAccess(true).Do()` and do some impersonation which it not yet well supported in these libraries. Please see #378 for more details/work-arounds for impersonation.

**Comment by Spazzlo** [comment]
Thanks for the info! Those docs really confused me there; I'm not a domain admin so I guess I'll just have to list all the drives I have access to then check each for the name.
