### ISSUE TITLE
YouTube API List Method

### ISSUE THREAD

**Issue by kwilliamnrys** [googleapis/google-api-go-client#536]
The List method for *VideosService (and I imagine for the other List methods as well) takes in a []string as a parameter, but when you call it with a []string, there is a compile-time error:

"cannot use (type []string) as type string in argument to videosService.List"

If I pass in a string literal, however, the code works.

**Comment by codyoss** [comment]
Thanks for the report, I will look into this and let you know what I find.

**Comment by codyoss** [comment]
Out of curiosity, when you say "If I pass in a string literal, however, the code works.". How are you passing a string literal if the method takes a slice?

**Comment by kwilliamnrys** [comment]
> Out of curiosity, when you say "If I pass in a string literal, however, the code works.". How are you passing a string literal if the method takes a slice?

For some reason, the code compiles despite me passing in a string literal. I have no idea how. I was inspired by sample code provided by YouTube: https://developers.google.com/youtube/v3/quickstart/go

**Comment by codyoss** [comment]
Ah, I think you were looking at the docs for the new version of this client, but locally you have the old version. Can you confirm what version of `google.golang.org/api` you are running and run `go env` for me?

**Comment by kwilliamnrys** [comment]
> Ah, I think you were looking at the docs for the new version of this client, but locally you have the old version. Can you confirm what version of `google.golang.org/api` you are running and run `go env` for me?

How do I check which version of the API I have and what should I be looking for when I run `go env`

**Comment by codyoss** [comment]
1. Are you using Go Modules for dependencies? If so check your go.mod. If not look at the code please search the youtube code for the string `gdcl/20` and let me know it's full value.
2. Can you share the value of `GO111MODULE`
3. Can you share the value of `go version`

**Comment by kwilliamnrys** [comment]
> 1. Are you using Go Modules for dependencies? If so check your go.mod. If not look at the code please search the youtube code for the string `gdcl/20` and let me know it's full value.
> 2. Can you share the value of `GO111MODULE`
> 3. Can you share the value of `go version`

Just checked go.mod. I had the wrong version. Thank you very much!

**Comment by codyoss** [comment]
No problem, glad I could help. 😄
