### ISSUE TITLE
iam: Markdown links in comments are handled incorrectly

### ISSUE THREAD

**Issue by hegemonic** [googleapis/google-api-go-client#544]
When a Markdown link appears in a proto comment that's used for a Go struct, that link can get split across multiple lines and rendered in the comments as-is. Example from [`iam/v1/iam-gen.go`](https://github.com/googleapis/google-api-go-client/blob/db1157f86c79a0df6bbdab53ad52c4b78980f580/iam/v1/iam-gen.go#L1350):

```go
// ...previous lines omitted...
// based on attributes of the request, the resource, or both. To learn
// which
// resources support conditions in their IAM policies, see the
// [IAM
// documentation](https://cloud.google.com/iam/help/conditions/resource-p
// olicies).
```

Here's how this gets rendered on [`pkg.go.dev`](https://pkg.go.dev/google.golang.org/api/iam/v1?tab=doc):

![5toDyUtmsfG](https://user-images.githubusercontent.com/1522391/85154883-e506c800-b20c-11ea-8414-f261097a6d39.png)

**Comment by codyoss** [comment]
Thanks for pointing this out.

**Comment by codyoss** [comment]
Tracking issue on 712.
