### ISSUE TITLE
Unclear how to disable IPV6 completely on clients

### ISSUE THREAD

**Issue by mauricio** [googleapis/google-api-go-client#545]
Hello folks,

We're running on an environment where we don't have IPV6 support so we tried disabling it like this:

`	
        config, err := google.JWTConfigFromJSON(credentialsJSON, ""https://www.googleapis.com/auth/calendar" ")
	if err != nil {
		return nil, err
	}

	dialer := &net.Dialer{
		Timeout: time.Second * 10,
	}

	tcp4Transport := &http.Transport{
		Dial: func(network, addr string) (net.Conn, error) {
			return dialer.Dial("tcp4", addr)
		},
		DialContext: func(ctx context.Context, network, addr string) (net.Conn, error) {
			return dialer.DialContext(ctx, "tcp4", addr)
		},
		TLSHandshakeTimeout: gcalDialTimeout,
		MaxIdleConns:        5,
		IdleConnTimeout:     time.Minute,
	}

	client := &http.Client{
		Transport: &oauth2.Transport{
			Base:   tcp4Transport,
			Source: config.TokenSource(context.Background()),
		},
	}
`

And this seems to work most of the time until it fails with something like:

>  Post "https://www.googleapis.com/calendar/v3/calendars/xxxxxxxxxxx_4b1anatsriq7r7habl4e4g4j80%40group.calendar.google.com/events?alt=json&prettyPrint=false": dial tcp4: address www.googleapis.com: no suitable address found

Is there a way we can completely disable IPV6 in this case?

Also, there's no way to disable it for the token source itself as it doesn't look like we can provide a dialer so we also see IPV6 issues when trying to pull tokens:

>  Post "https://www.googleapis.com/calendar/v3/calendars/xxxxxxxxxxxx_4b1anatsriq7r7habl4e4g4j80%40group.calendar.google.com/events?alt=json&prettyPrint=false": oauth2: cannot fetch token: Post "https://accounts.google.com/o/oauth2/token": dial tcp [2607:f8b0:4006:815::200d]:443: connect: cannot assign requested address

This is all in Go 1.14.4 and Linux.

**Comment by codyoss** [comment]
> Is there a way we can completely disable IPV6 in this case?

I think you have the write idea of passing in your own Dial functions

> Also, there's no way to disable it for the token source itself as it doesn't look like we can provide a dialer so we also see IPV6 issues when trying to pull tokens.

You are correct. There is no current way to configure this client.

cc @broady

**Comment by mauricio** [comment]
@codyoss we did that and it doesn't work, this happens eventually:

> Post "https://www.googleapis.com/calendar/v3/calendars/xxxxxxxxxxx_4b1anatsriq7r7habl4e4g4j80%40group.calendar.google.com/events?alt=json&prettyPrint=false": dial tcp4: address www.googleapis.com: no suitable address found

Would you folks take a PR to allow configuring a dialer for the token source?

**Comment by codyoss** [comment]
Sorry I lost track of this issue. Were you able to find a solution?

If you want to pass an HTTP Client used for token fetches you can do that by embedding one in the context passed to `config.TokenSource`. Here is an example: https://pkg.go.dev/golang.org/x/oauth2?tab=doc#example-Config-CustomHTTP

**Comment by codyoss** [comment]
I believe the supplying the client through the context as mentioned above should work here. Let me know if it did not.
