### ISSUE TITLE
idtoken claims

### ISSUE THREAD

**Issue by peterwillis** [googleapis/google-api-go-client#547]
Since the ID token is always validated against google, it would be nice if the payload was more specific than just the base set for a generic jwt. I am thinking of the set shown here:

https://developers.google.com/identity/protocols/oauth2/openid-connect#obtainuserinfo

**Comment by codyoss** [comment]
Additional claims can always be found in `idtoken.Payload.Claims`: https://pkg.go.dev/google.golang.org/api/idtoken?tab=doc#Payload
