### ISSUE TITLE
healthcare: duplicate query param key

### ISSUE THREAD

**Issue by nhue2310** [googleapis/google-api-go-client#550]
- I was try to search FHIR resource with `_include` query param like below
```
queries := []googleapi.CallOption{}

queryPractitioner := helper.QueryParamOpt{
	Key:   "_include",
	Value: practitionerID,
}
queries = append(queries, queryPractitioner)
queryOrganization := helper.QueryParamOpt{
	Key:   "_include",
	Value: "organizationID",
}
queries = append(queries, queryOrganization)
hs, err := newHealthService()
r, err := hs.Projects.Locations.Datasets.FhirStores.Fhir.Search(parent).Do(queries)
```
### Expect
`https://healthcare.googleapis.com/v1/projects/x/locations/x/datasets/x/fhirStores/x/fhir/PractitionerRole?_include=Practitioner&_include=Organization`
### Real result
`https://healthcare.googleapis.com/v1/projects/x/locations/x/datasets/x/fhirStores/x/fhir/PractitionerRole?_include=Organization`
 => Search result is incorrect
Seem like this libs didn't support it

As you can see on [this line](https://github.com/googleapis/google-api-go-client/blob/8809fe2216f75c184cf682992f90bd98f325c278/internal/gensupport/params.go#L28), lib will replace query with same key.

So, How can i add new duplicate key without replace old one ?

**Comment by codyoss** [comment]
Can you please show how you are using `queryPractitioner` & `queryOrganization` in the snippet provided above.

**Comment by nhue2310** [comment]
@codyoss 
Sorry, i updated detail
`queryPractitioner & queryOrganization` has been appended into queries.

**Comment by codyoss** [comment]
Thanks, I will need to do some digging and then I will get back to you.

**Comment by tbpg** [comment]
cc @noerog

**Comment by hue-n-gnk** [comment]
@codyoss  Hi, how is it going?
It's more than 1 year for the digging. Do you have a plan for fixing it?

**Comment by codyoss** [comment]
@hue-n-gnk Sorry, this slipped off my radar. I have just opened a PR that should unblock this use-case. Thanks for pinging the issue!
