### ISSUE TITLE
youtube: using false bool values in insert and update methods does nothing

### ISSUE THREAD

**Issue by asticode** [googleapis/google-api-go-client#554]
Hey guys,

First off, thanks for this awesome library, it saves us all a lot of time! ❤️ 

However I'm experiencing a specific issue that raises a bigger issue: when trying to set `LiveBroadcastStatus.SelfDeclaredMadeForKids` to `false` explicitely on a `liveBroadcast.insert`, it does nothing and the Live Streaming UI still asks whether the live broadcast is made for kids.

Indeed the `json` tag of [LiveBroadcastStatus.SelfDeclaredMadeForKids](https://github.com/googleapis/google-api-go-client/blob/master/youtube/v3/youtube-gen.go#L2688) contains `omitempty`, therefore if the value is `false`, it won't appear in the marshaled JSON and won't be sent to Google API.

A common fix would be to use a `*bool` instead of `bool`, that way it can represent 3 states : `not filled`, `false` or `true`.

Is there something I'm missing?

Thanks in advance.
Cheers

**Comment by codyoss** [comment]
You can use [ForceSendFields](https://github.com/googleapis/google-api-go-client/blob/master/youtube/v3/youtube-gen.go#L2696) 😄
