### ISSUE TITLE
Admin API - Users: update Request - Error 409: Entity already exists

### ISSUE THREAD

**Issue by CoreyGriffin** [googleapis/google-api-go-client#556]
All of a sudden running into `409` errors when making user update requests ... having the same issue with the [google-api-python-client](https://github.com/googleapis/google-api-python-client) ([x-post](https://github.com/googleapis/google-api-python-client/issues/949))

The request seems to succeed and actually make the changes to the account in G Suite but then returns `googleapi: Error 409: Entity already exists., duplicate`. This is relatively new behavior so not sure if it is a result of a change on the API side.

The context here is account deprovisioning so current order of operations from our perspective is:
- Set `suspended` to `true`
- Set `"includeInGlobalAddressList"` to `false`
- Remove any aliases
- Change the primary email
- Send `Users: update` request
- Send `Users.aliases: delete` request to remove original email

## Expected Response
- `200 Status Code` 
- updated `User Resource`

## Actual Response
- Updates **are** made in G Suite
- `409 Status Code`
- `Error: 409: Entity already exists., duplicate`.

Any ideas here...seems like the update call should be idempotent but maybe we're running into a race condition when we make the update call on the backend?

**Comment by codyoss** [comment]
This sounds like a backend service error to me. I suggest that you open an issue on the [Admin SDK Issue Tracker](https://issuetracker.google.com/savedsearches/566232). Being that this is happening in two of our client libraries, I think we can rule out the issue being here.
