### ISSUE TITLE
option: unable to determine the type of an option.ClientOption

### ISSUE THREAD

**Issue by hengfengli** [googleapis/google-api-go-client#558]
When we provide both `option.WithoutAuthentication()` and `option.WithCredentialsFile("/path/to/key.json")`, it throws an error: 

```bash
2020/06/26 13:57:26 options.WithoutAuthentication is incompatible with any option that provides credentials
```

In cloud spanner client lib, when we set `SPANNER_EMULATOR_HOST`, it will set `option.WithoutAuthentication()` and so the following code will throw an error: 

```go
client, err := NewClientWithConfig(
    context.Background(),
    "projects/p/instances/i/databases/d",
    ClientConfig{},
    []option.ClientOption{option.WithCredentialsFile("/path/to/key.json")}...,
)
```

One possible solution is to remove `option.WithCredentialsFile()` from the list when `SPANNER_EMULATOR_HOST` is set. However, this is impossible right now because we can't determine the type of an `option.ClientOption`.

I wonder is it possible to have a `Type()` method for `option.ClientOption`? 

```go
// A ClientOption is an option for a Google API client.
type ClientOption interface {
	Apply(*internal.DialSettings)
        Type() string
}
```

With `Type()`, we can filter certain types of client options as needed. 

Related issues: https://github.com/googleapis/google-cloud-go/issues/1917

**Comment by hengfengli** [comment]
Same problem makes the solution impossible in https://github.com/googleapis/google-cloud-go/issues/1975. 

ADC is checked inside: 

https://github.com/googleapis/google-cloud-go/blob/d4e53b5eb0fefbd9f2af8dd3fd881050a46a8fb2/spanner/client.go#L172

However, we are unable to move the check of pool settings forward: 

https://github.com/googleapis/google-cloud-go/blob/d4e53b5eb0fefbd9f2af8dd3fd881050a46a8fb2/spanner/client.go#L176-L179

Because we don't know whether or not the list `opts` of `option.ClientOption` has an `option.WithGRPCConnectionPool`. We can't tell it. 

If we can tell the type of `option.ClientOption`, then we can compare `config.NumChannels` and `option.WithGRPCConnectionPool` before calling `gtransport.DialPool`.

**Comment by codyoss** [comment]
> When we provide both option.WithoutAuthentication() and option.WithCredentialsFile("/path/to/key.json")

This is intentional. I am not sure it makes sense to have both set.

> ... it will set option.WithoutAuthentication() and so the following code will throw an error

Is there a reason `option. WithCredentialsFile` can just not be passed in?

> I wonder is it possible to have a Type() method for option.ClientOption?

In general adding a method to an interface is a breaking change. Although, here it might technically be possible since the interface references internal which makes it impossible for others to implement.

> Same problem makes the solution impossible in googleapis/google-cloud-go#1975.

One solution for this one is to make it an integration test.

cc @broady Do you have thoughts on this issue?

**Comment by hengfengli** [comment]
> This is intentional. I am not sure it makes sense to have both set.

The case happens when a user sets a `option.WithCredentialsFile("/path/to/key.json")` in the source code. Then, the user wants to run this code against the emulator so `SPANNER_EMULATOR_HOST` is set and `option.WithoutAuthentication()` is enabled. In this case, the above error will happen. This requires the user to change the source code by removing `option.WithCredentialsFile("/path/to/key.json")`. This would conflict with our purpose to use `SPANNER_EMULATOR_HOST` that avoids users to change their source code. 

> Is there a reason option. WithCredentialsFile can just not be passed in?

Explained as above. This requires the user to update their source code. 

> One solution for this one is to make it an integration test.

I am not sure if I understand it. Can you please explain a bit more?

**Comment by broady** [comment]
I don't want to break the abstraction, out of principle. We found a couple other cases like this where it was tempting to break it, but we ended up adding "internal" options, not to be used by end developers:
https://godoc.org/google.golang.org/api/option/internaloption

Interestingly, those options are all to do with endpoints, and so is emulators, in a way. So it's probably a good match.

I suggest adding
```
internaloption.WithEmulator(...)
```

which handles credentials and endpoints correctly for emulators, specifically.

**Comment by hengfengli** [comment]
`internaloption.WithEmulator(...)` sounds good to me.

**Comment by hengfengli** [comment]
@codyoss  I just want to follow up with this issue. Is there any plan/schedule for this?

**Comment by codyoss** [comment]
I recently added, it is not in a released version yet, `SkipDialSettingsValidation`: [link](https://github.com/googleapis/google-api-go-client/blob/f10cc94b4f1ec2f17bebd8f39f16c6e8822f6658/option/internaloption/internaloption.go#L44). Maybe you could also pass this in the case of an emulator? It basically is for cases like this where "I know how this works, trust me" :) `DailSettings.NoAuth` is checked before trying ADC, so I believe this should work: [link](https://github.com/googleapis/google-api-go-client/blob/f10cc94b4f1ec2f17bebd8f39f16c6e8822f6658/transport/grpc/dial.go#L118).

Does this seem like it would work for you? I can get a release cut early next week so you could at least try it out.

**Comment by hengfengli** [comment]
Thanks for the update. I will try it out once it is released.

**Comment by codyoss** [comment]
[v0.30.0](https://github.com/googleapis/google-api-go-client/releases/tag/v0.30.0) Should have that new internal option. Let me know if that does not work for you and we can look at a different approach.

**Comment by hengfengli** [comment]
This issue has been fixed: https://github.com/googleapis/google-cloud-go/pull/2701/files. @codyoss Thanks for adding the new internal option.
