### ISSUE TITLE
androidpublisher: non informative errors

### ISSUE THREAD

**Issue by Trane9991** [googleapis/google-api-go-client#559]
Hello,
we are having some errors from the server like `googleapi: Error 400: Invalid Value, invalid` which doesn't say what is wrong at all.

I found similar issues:
- https://stackoverflow.com/questions/41091275/error-400-invalid-value-invalid
- https://github.com/Pallinder/go-iap/issues/3
- https://github.com/googleapis/google-cloud-go/issues/196.

The only thing left is to guess what can be wrong with the request. Any help regarding this?

Thanks!

**Comment by codyoss** [comment]
@Trane9991 Sorry you are having issues, can you please post a small reproducer so I can assist you better.

**Comment by Trane9991** [comment]
Hey. Unfortunately, I can not.
We do IAP purchases verification of behalf of users of our SDK, so we just pass the data that the client gave to us.
And this is part of the problem because this is probably misusage of misconfiguration on their side, however, because of the non-informative error we don't know what exactly they (or us) did wrong.

We suspect that this could be the following issue, https://github.com/Pallinder/go-iap/issues/3#issuecomment-363884377.
So, probably, our customers provide us with the subscription purchase ID while marking it as a product purchase, or vice versa, but we can't be sure.

**Comment by codyoss** [comment]
What version of `google.golang.org/api` are you using?

**Comment by codyoss** [comment]
Closing due to lack of response.

**Comment by Trane9991** [comment]
Sorry, @codyoss, forgot about this one:
`google.golang.org/api v0.29.0`
