### ISSUE TITLE
idtoken: client created with WithCredentialsJSON failed

### ISSUE THREAD

**Issue by marvin5064** [googleapis/google-api-go-client#565]
trying to use idtoken with google service account for cloud function execution 

I got error `multiple credential options provided` from [this line](https://github.com/googleapis/google-api-go-client/blob/8809fe2216f75c184cf682992f90bd98f325c278/internal/settings.go#L76-L78)

example:
```
idtoken.NewClient(ctx, endpoint, option.WithCredentialsJSON([]byte("service account json payload")))
```

with `option.WithCredentialsFile`, it seems working fine, probably because of the [backwards compatibility](https://github.com/googleapis/google-api-go-client/blob/8809fe2216f75c184cf682992f90bd98f325c278/internal/settings.go#L76) introduced 2 years ago (which didn't count in the CredentialJSON one)

with the todo listed [here](https://github.com/googleapis/google-api-go-client/blob/8809fe2216f75c184cf682992f90bd98f325c278/internal/settings.go#L56), shall we remove other cred options from [here](https://github.com/googleapis/google-api-go-client/blob/8809fe2216f75c184cf682992f90bd98f325c278/idtoken/idtoken.go#L53), only keep a tokensource before entire next line?

**Comment by codyoss** [comment]
Thanks for the report, we will get this fixed. For now, a couple workarounds:

- Write JSON to a tempfile
- Do similar logic found in NewClient, but only pass in the relevant ClientOptions
