### ISSUE TITLE
storage: Question about go sdk for Google Cloud Storage

### ISSUE THREAD

**Issue by deka108** [googleapis/google-api-go-client#586]
Hi,

I wanted to ask about the status of https://github.com/googleapis/google-api-go-client/ and its future roadmap. For some context, I have been using the high-level client library at https://github.com/googleapis/google-cloud-go/. From my understanding, that client library used the raw auto-generated API from this package. However, I have some use case which are not covered by the high-level client library but might or might not be supported by calling the direct API of the raw package. 

However, in the overview of https://pkg.go.dev/google.golang.org/api@v0.29.0/storage/v1?tab=doc, it is mentioned that this package is DEPRECATED, so I still have some reservations before using this package.

My questions are:
1. Is this package being deprecated or will be deprecated in the future?
2. Is safe to use this package directly if we vendor it? 
3. What are the repercussions if we use this package directly instead of the client library?

Thank you.

**Comment by codyoss** [comment]
1. There is no plan to remove this package, we just recommend using cloud.google.com/go/storage as it is nicer to work with.
2. Yup.
3. This whole repository is full of client libraries. The client libraries found in this package are all HTTP based. Whereas most-all of the clients in cloud.google.com/go are gRPC based. `storage` is an exception to this rule and is just a wrapper around this repositories HTTP based client, as you have observed. Feel free to use these libraries if they are exposing things you can't get at in [storage](https://pkg.go.dev/cloud.google.com/go/storage?tab=doc).

Followup question for you: What features in this repositories storage client do you feel are missing in the other?

cc @tritone

**Comment by deka108** [comment]
I'm still figuring out how to best do the uploading process for large files under GCS. 
Our use case is related to low-level filesystem requests that we would map to cloud store APIs. Thus, having a fine-grained control over what and when the actual HTTP upload request is sent would be nice (eg: streaming upload / buffer vs bufferless, dynamic chunked size, etc.)

A little bit of background: I think in the best case we would love to use an API that is similar to [parallel multipart upload in S3](https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html). However, it seems that there is no equivalent feature to concurrent MPU in the original JSON API for GCS. GCS supports [composite objects](https://cloud.google.com/storage/docs/composite-objects), however some of its features are very limiting thus we plan to use the sequential chunked resumable upload request for uploading large files.

If I'm understanding correctly, the `cloud.google.com/go/storage` used a Writer object but the actual chunking and HTTP request is being called under `google.golang.org/api`. Although, looking deeper through the source code it seems that the mechanism for chunking and resumable upload is abstracted already under `gensupport` in `google.golang.org/api`?

**Comment by tritone** [comment]
You're correct that we don't have support for parallel multipart upload, though we do have support for object composition via this library-- so using this library, it's possible to use parallel goroutines to upload component objects and then compose them at the end (and I've definitely seen applications which take this approach).

As described in the [docs for Writer.ChunkSize](https://pkg.go.dev/cloud.google.com/go/storage?tab=doc#Writer), you do have control over the type of upload request used via this parameter:

* Input size > ChunkSize: chunked resumable upload will be used
* Input size < ChunkSize: single multipart upload will be used, with a buffer of size ChunkSize
* ChunkSize == 0: single multipart upload will be used, unbuffered (this also necessarily disables request retries)

You're correct that uploads in google-api-go-client are delegated to the resumable media code in gensupport. I don't think you'll be able to gain much additional control over the request type by using google.golang.org/api/storage/v1 directly.

Hope this helps!

**Comment by deka108** [comment]
Okay, I have two follow-up questions:

1. For the chunked upload when does each chunk request actually get sent to the server? Is each chunk
- sent as soon as the chunked buffer is full (data inside buffer == ChunkSize)
- sent as soon as the flush / close is called (buffer is not full, usually the case for the last chunk)
? 

2. If we're using `Writer` object from `cloud.google.com/go/storage` when does the actual chunk request get sent to the server? We can write bytes to the `Writer` object using `Write([]byte)` or `io.Copy(writer, body)`, however, the actual upload request is delegated to the resumable media so I was wondering how this work.

Thank you.
