### ISSUE TITLE
storage: question about upload mechanism for Google Cloud Storage

### ISSUE THREAD

**Issue by deka108** [googleapis/google-api-go-client#588]
I have some follow up questions for upload request related to my question in https://github.com/googleapis/google-api-go-client/issues/586

1. For the chunked upload when does each chunk request actually get sent to the server? Is each chunk
- sent as soon as the chunked buffer is full (data inside buffer == ChunkSize)
- sent as soon as the flush / close is called (buffer is not full, usually the case for the last chunk)
?

2. If we're using Writer object from cloud.google.com/go/storage when does the actual chunk request get sent to the server? We can write bytes using Write([]byte) or io.Copy(writer, body). However, since the actual upload request is delegated to the resumable media I was wondering how this work.

Thank you.

**Comment by codyoss** [comment]
The docs for Writer go into these details: https://pkg.go.dev/cloud.google.com/go/storage?tab=doc#Writer

Here is a link to the underlying [implementation](https://github.com/googleapis/google-api-go-client/blob/master/internal/gensupport/buffer.go#L34) and [this](https://github.com/googleapis/google-api-go-client/blob/dec4990267b387639de624cd235758ea649d3a46/internal/gensupport/resumable.go#L127) is how it is used.

You have the right idea overall.
