### ISSUE TITLE
Support for Bussiness Messaging private API?

### ISSUE THREAD

**Issue by Elessar8** [googleapis/google-api-go-client#597]
Are there any plans to support the official bussiness messaging and communications API? 
The discovery document is located here: https://businessmessages.googleapis.com/$discovery/rest?version=v1 but it is only accesible with an API-key (which I have). 

However, since it is not listed on https://www.googleapis.com/discovery/v1/apis I have to generate the library code myself. According to comments made in https://github.com/googleapis/google-api-go-client/issues/283 and https://github.com/googleapis/google-api-go-client/issues/416 this is not a supported workflow.

What is the preferred way of working? I'd rather not generate and link everything myself if possible.

**Comment by codyoss** [comment]
As mentioned in #283 this repository will only generate libraries from that public listing. If you want to try out the generator and see if it works for you can. You would need to clone this repo and generate from within it as the code it generates will rely upon some internal packages here. If you have a support contact you can reach out through them to see if/when the service team is planning on adding this api to the public listing.
