### ISSUE TITLE
Webfonts: incorrect api endpoint? Receiving 404 not found responses only.

### ISSUE THREAD

**Issue by eriklott** [googleapis/google-api-go-client#601]
v0.29.0

When using the `google.golang.org/api/webfonts/v1` package to list webfonts, I'm receiving only **404 Not Found** responses. I could be wrong, but is the internal webfonts `basepath` const incorrect?
https://github.com/googleapis/google-api-go-client/blob/v0.29.0/webfonts/v1/webfonts-gen.go#L77

The `basepath` is currently `https://www.googleapis.com/`. If I change the Basepath on the service client to `https://webfonts.googleapis.com/ `or `https://www.googleapis.com/webfonts` the client functions normally.

```
client, _ := webfonts.NewService(ctx, option.WithAPIKey("AIz..."))
// This client won't work

client.BasePath = "https://webfonts.googleapis.com/"
// This client will work

client.BasePath = "https://www.googleapis.com/webfonts/"
// This client will work
```

**Comment by codyoss** [comment]
Thanks for the report, we will look into this. For now it looks like you have a workaround. You could also make use of the option `WithEndpoint`: https://pkg.go.dev/google.golang.org/api/option?tab=doc#WithEndpoint

**Comment by eriklott** [comment]
`WithEndpoint` solution feels a little better, so I'll use that. Thanks for the tip.

**Comment by codyoss** [comment]
This is fixed, but has not been released yet. https://github.com/googleapis/google-api-go-client/blob/56379540dde61c59a1f2556eaf628829c0a759dd/webfonts/v1/webfonts-gen.go#L77

I will get a release cut today or tomorrow.
