### ISSUE TITLE
Unable to go get gensupport

### ISSUE THREAD

**Issue by TatyanaBol** [googleapis/google-api-go-client#622]
This can be reproduced by doing

`go get -d  google.golang.org/api/gensupport`

with output:

`go get google.golang.org/api/gensupport: module google.golang.org/api@upgrade found (v0.30.0), but does not contain package google.golang.org/api/gensupport
`

**Comment by taitelman** [comment]
maybe #398 is the same ?

**Comment by codyoss** [comment]
`gensupport` is an internal package: https://github.com/googleapis/google-api-go-client/tree/master/internal/gensupport

This has been the case since https://github.com/googleapis/google-api-go-client/releases/tag/v0.11.0.
