### ISSUE TITLE
cloudidentity: can't set permissions

### ISSUE THREAD

**Issue by derekperkins** [googleapis/google-api-go-client#637]
Whenever we try and use this package, we get permission denied errors. When going to edit a custom role, there are no cloudidentity permissions available. I can create/patch an organization role with those permissions as shown, but then the role editor shows that they are hidden. Once those permissions are added to a role, I can no longer add that role to a service account, and any service accounts it is attached to no longer show it as an active role. 

Any feedback on how can we use this api?

```
{
  "error": {
    "code": 403,
    "message": "Error(2015): Actor does not have permission to create group 'workspaces-tandyspace@nozzle.io'.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ResourceInfo",
        "resourceType": "cloudidentity.googleapis.com/Group",
        "owner": "domain:cloudidentity.googleapis.com",
        "description": "Error(2015): Actor does not have permission to create group 'workspaces-tandyspace@nozzle.io'."
      }
    ]
  }
}
```

![image](https://user-images.githubusercontent.com/3588778/91107223-01224d80-e632-11ea-9add-d5f72fd6a143.png)

![image](https://user-images.githubusercontent.com/3588778/91107290-23b46680-e632-11ea-93f5-73bc46d9de61.png)

cc @mordfustang21 @whizard

**Comment by codyoss** [comment]
Thanks for the through report. I need to investigate a little and get back to you when I know a little more.

**Comment by derekperkins** [comment]
As we've kept digging, we're still getting stuck. Following the instructions [here](https://cloud.google.com/identity/docs/how-to/setup#auth-no-dwd), we've added the service account to the Groups Admin role inside G Suite, still with no luck. https://developers.google.com/admin-sdk/directory/v1/reference/roleAssignments/insert

For reference, we tried to tackle this 5 months ago and were unsuccessful even with your help, and when this new seemingly more GCP native api was announced, we were excited to tried it, but the process has been just as frustrating this time.
https://github.com/googleapis/google-api-go-client/issues/465

**Comment by derekperkins** [comment]
We've also tried via `gcloud beta identity groups` and gotten the same errors, so it is likely a server-side issue. It would be nice to get some Go examples on https://cloud.google.com/identity/docs/how-to/setup#auth-no-dwd

**Comment by codyoss** [comment]
> It would be nice to get some Go examples on https://cloud.google.com/identity/docs/how-to/setup#auth-no-dwd

It sounds like the feature is pre-GA which is might be why we don't have better language coverage for that sample.
To do something similar in Go thought you could use the following two client options when creating your client:

```go
svc, err := cloudidentity.NewService(ctx, option.WithCredentialsFile("/path/to/a/file"), option.WithScopes("scope1", "scope2", "etc"))
``

**Comment by codyoss** [comment]
Just to follow up here, I have pinged some people internally and seeing if I can find out more. A couple of questions that came up:

1. Are you using setIAMPolicy to grant permissions to create groups? These permissions should be instead granted from the Admin Console I believe.

2. What is your current setting for creating groups in the Admin Console?("Anyone in this domain can create groups", "Only domain admins can create groups").

3. Can you provide a snippet of how you are creating the client? I am trying to understand your auth flow better. Are you trying to impersonate an admin?

**Comment by derekperkins** [comment]
1. Yes, setIAMPolicy is what we tried first. When that didn't work, we [found the docs](https://github.com/googleapis/google-api-go-client/issues/637#issuecomment-680217857) about adding it via the G Suite api. There's no way to add a service account via the console. The service account in question now has the Groups Admin role.

1. "Anyone in this domain can create groups"

1. @mordfustang21 Can you send your client setup?

**Comment by MordFustang21** [comment]
We aren't doing anything special just.
```go
client, err := cloudidentity.NewService(c)
if err != nil {
	return nil, err
}
```

**Comment by codyoss** [comment]
@MordFustang21 Can or have you tried to pass the scopes recommended [here](https://cloud.google.com/identity/docs/how-to/setup#authenticating_and_authorizing_the_service_account)?

For you, this would look something like:

```go
client, err := cloudidentity.NewService(c, option.WithScopes("https://www.googleapis.com/auth/cloud-identity.groups",
          "https://www.googleapis.com/auth/admin.directory.group",
          "https://www.googleapis.com/auth/admin.directory.group.member",
          "https://www.googleapis.com/auth/apps.groups.settings"))
```

**Comment by codyoss** [comment]
Also, not sure this has any information you have not already looked at, but the gSuite updates blog did publish [this article](https://gsuiteupdates.googleblog.com/2020/08/use-service-accounts-google-groups-without-domain-wide-delegation.html) yesterday.

**Comment by MordFustang21** [comment]
Tried again using the scopes provided and a couple others and am still receiving 
`Actor does not have permission to create group` errors
```go
client, err := cloudidentity.NewService(c, option.WithCredentialsFile("service-creds.json"), option.WithScopes([]string{
	"https://www.googleapis.com/auth/cloud-identity.groups",
	"https://www.googleapis.com/auth/admin.directory.group",
	"https://www.googleapis.com/auth/admin.directory.group.member",
	"https://www.googleapis.com/auth/apps.groups.settings",
	"https://www.googleapis.com/auth/cloud-platform",
}...))
if err != nil {
	return nil, err
}
```

**Comment by codyoss** [comment]
If you have a support contract with GCP I suggest reaching out through that channel as they can help take a deeper look here. Now that you are passing in the correct scopes the only thing that I can think this could be is an issue with the service account not having the correct permission structure.

**Comment by codyoss** [comment]
Were you able to get this working or find an viable workaround?

**Comment by derekperkins** [comment]
Thanks for the follow up, we still have not been able to get this working. We opened a case with our support contract, but that has been slow going.

**Comment by derekperkins** [comment]
Still working through this with support. They have yet to even understand the issue after a few weeks and apparently haven't read any of what we've done here.

**Comment by codyoss** [comment]
@derekperkins I am going to close this issue out for now since this was being worked on with the support channel. I don't think the issue here is within the generated client. If the generated clients do require changes to support this though please feel free to reach back out.
