### ISSUE TITLE
gensupport: allow passing in buffer for uploads to reduce allocations

### ISSUE THREAD

**Issue by zimnx** [googleapis/google-api-go-client#638]
When uploading lots of files using ObjectStorage.Insert(), **each file** allocates his own buffer. This results in increased CPU usage and high RSS memory.

Graph below shows how many space was allocated during upload of ~30k of 10MB files:
![Selection_132](https://user-images.githubusercontent.com/3951334/90792638-ff434c00-e30a-11ea-9088-240c5d204252.png)

User should be able to pass his own buffer and be responsible for allocations or library shouldn't be so wasteful.

Pull request which adds user facing insert option is here: #632, I was asked to an open issue to discuss it. 
cc. @tritone @codyoss

**Comment by codyoss** [comment]
@zimnx Thanks!

**Comment by codyoss** [comment]
I think we have addressed this some some newer APIs, but I will let @tritone correct me if that is not correct. Closing.
