### ISSUE TITLE
idtoken: support providing custom certificate URLs

### ISSUE THREAD

**Issue by keyslapperdev** [googleapis/google-api-go-client#640]
The current documentation for Google Chat bot verification shows

> All bearer tokens sent with requests from Google chat will have chat@system.gserviceaccount.com as the issuee, with the audience field specifying the target bot's project number from the Google API Console. For example, if the request is for a bot with the project number 1234567890, then the audience is 1234567890.

In their code examples they show that the url to get the keys for validation should be https://www.googleapis.com/service_accounts/v1/metadata/x509/ + ${theAboveIsuee}

As of now this repo doesn't support the kind of JWT validation specified in the docs. 

I feel a solution would be to create a module, or extend current functionality, to validate JWT provided a url.

**Comment by codyoss** [comment]
Thanks for the feature request!

**Comment by dennbagas** [comment]
Is there any update about this feature?

**Comment by codyoss** [comment]
Closing in favor of linked issue.
