### ISSUE TITLE
In v0.31, Directory API User.CustomSchemas is broken

### ISSUE THREAD

**Issue by Schparky** [googleapis/google-api-go-client#651]
The `CustomSchemas` property of `User` in the Directory API is broken. It was formerly a `map[string]json.RawMessage` but was changed to `map[string]UserCustomProperties`. `UserCustomProperties` is now defined as an empty struct:
```
// UserCustomProperties: JSON template for a set of custom properties
// (i.e. all fields in a particular schema)
type UserCustomProperties struct {
}
```

**Comment by codyoss** [comment]
Thanks for the report. This is a known issue and will be fixed in the next release. I will keep this open until a new release is cut with the fix. For now, please continue to use v0.30.0.

**Comment by codyoss** [comment]
This is now fixed on HEAD and will be released early next week.
