### ISSUE TITLE
support impersonating admin users for gSuite APIs

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-api-go-client#652]
Followup tracking issue to #378.

**Comment by carnott-snap** [comment]
Is it possible to implement this feature using default credentials without minting subtokens like I do in `git.sr.ht/~urandom/dwd`?

**Comment by codyoss** [comment]
@carnott-snap When you say "without minting subtokens" what do you mean?

**Comment by carnott-snap** [comment]
I use environments where only the application default credentials are accessable, so no json service account keys. If you look at the linked library, I achieve gsuite admin impersonation via making a new `oauth2.Token` based on the response from `cloud.google.com/go/iam/credentials/apiv1.IamCredentialsClient.SignJwt`. This new token correctly impersonates the admin, and I can confirm works as expected in production environments, but setting up the rpc and refreshing the token adds quite a bit of complexity and some runtime overhead. Furthermore, my api does not play nice with delegation and impersonation, e.g. one@appspot.gserviceaccount.com -deledates-> two@appspot.gserviceaccount.com -impersonates-> admin@example.com.

**Comment by codyoss** [comment]
If the question is, would we support application default credentials(ADC) for sourcing the base credentials -- the answer is yes.

**Comment by codyoss** [comment]
Now in a main release: https://github.com/googleapis/google-api-go-client/releases/tag/v0.46.0
