### ISSUE TITLE
SDK Leaving Connections Open

### ISSUE THREAD

**Issue by profsmallpine** [googleapis/google-api-go-client#665]
We recently upgraded from v0.22.0 to v.0.31.0, and we were hit with numerous "too many files open". After downgrading, these errors stopped occurring. There is the obvious culprit where go's default http client does not specify a timeout. I could not find any changes from 22 -> 31 that would cause this issue, but it must be hidden in there somewhere. Any ideas?

**Comment by codyoss** [comment]
I need a little more information to go off of here.

- What clients are your creating, how many?
- Can you provide a code snippet to reproduce?
- Can you paste the full error message as received and show where you get it from?
- What version of Go are you using?

If you are creating multiple clients, you should not need to. They are thread safe. I have seen similar errors to this in the past because a new HTTP client could be created for each client, depending on version and options passed in. [Here is the code](https://github.com/googleapis/google-api-go-client/blob/a8730908f5e20dbafca4793397aab3b6753cad2c/transport/http/dial.go#L170-L191) where the default transport is created.

**Comment by profsmallpine** [comment]
We are syncing many gmail accounts using push notifications. When a webhook hits our application, we call:

`service, err := gmail.NewService(ctx, option.WithScopes(gmail.GmailReadonlyScope), option.WithTokenSource(s.Config.TokenSource(ctx, token)))`

which creates a new client on the fly. I am assuming you are saying this is not necessary. We can create a service when the app starts up and use that? If so, how would I load the oauth2.Token?

**Comment by codyoss** [comment]
>  I am assuming you are saying this is not necessary. We can create a service when the app starts up and use that...

Yes.

> If so, how would I load the oauth2.Token?

How are you getting your `token` variable today? Most users of these libraries will they don't need to pass in a TokenSource as, by default, our clients try to load credentials by ADC. See the [following link](https://pkg.go.dev/golang.org/x/oauth2/google#FindDefaultCredentials) about how we try to source credentials for you. If you are using a service account in your local environment I suggest passing the following option instead: [WithServiceAccountFile](https://pkg.go.dev/google.golang.org/api/option#WithServiceAccountFile).

**Comment by profsmallpine** [comment]
The ClientID + ClientSecret are passed in via the config above when the app starts up, defined by:

```
Config: &oauth2.Config{
	RedirectURL:  os.Getenv("BASE_URL") + "/sources/google/callback",
	ClientID:     os.Getenv("GOOGLE_OAUTH_CLIENT_ID"),
	ClientSecret: os.Getenv("GOOGLE_OAUTH_CLIENT_SECRET"),
	Scopes:       []string{gmail.GmailReadonlyScope},
	Endpoint:     google.Endpoint,
},
```

However, the access and refresh token comes from our database for each different gmail account we are managing:

```
token := &oauth2.Token{
	AccessToken:  source.AccessToken,
	RefreshToken: source.RefreshToken,
	Expiry:       time.Unix(source.TokenExpiresAt, 0),
}
```

This is how the token is defined. It's not immediately clear to me how this would get loaded if we have a single client.

**Comment by codyoss** [comment]
Thank you for better explaining your use-case. One option that might work for you is something like this:

```go
	trans := &oauth2.Transport{
		Source: ts, // Your TokenSource
		Base:   http.DefaultTransport,
	}
	httpClient := &http.Client{Transport: trans}
	gmail.NewService(ctx, option.WithHTTPClient(httpClient))
```

This would still create a client for each webhook response, but you are re-using the same underlying transport.

**Comment by codyoss** [comment]
I believe the solution posted above should work for you. Closing due to lack of response.
