### ISSUE TITLE
Apigee - Organizations.Apis.Get(...) fails to Unmarshal successful response

### ISSUE THREAD

**Issue by blucas** [googleapis/google-api-go-client#667]
### Golang Version
1.14
### Client Library & Version
[apigee/v1](https://github.com/googleapis/google-api-go-client/tree/v0.31.0/apigee/v1) - v0.31.0
### Problem
When attempting to unmarshal the HTTP response received from `Organizations.Apis.Get()` the following error is returned:
> Error json: invalid use of ,string struct tag, trying to unmarshal unquoted value into int64

### Assessment
`GoogleCloudApigeeV1EntityMetadata` declares `CreatedAt` and `LastModifiedAt` will be marshalled into `string` and unmarshalled from `string` within the `struct` `json` tag.  This is incorrect.

```go
type GoogleCloudApigeeV1EntityMetadata struct {
	// CreatedAt: Time at which the API proxy was created, in milliseconds
	// since epoch.
	CreatedAt int64 `json:"createdAt,omitempty,string"`

	// LastModifiedAt: Time at which the API proxy was most recently
	// modified, in milliseconds since epoch.
	LastModifiedAt int64 `json:"lastModifiedAt,omitempty,string"`
}
````

The actual response from Apigee's API uses a numeric for `metaData.createdAt` and `metaData.lastModifiedAt`:
```
HTTP/1.1 200 OK
Access-Control-Allow-Headers: origin
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 3628800
Connection: keep-alive
Content-Length: 309
Content-Type: application/json
Date: Wed, 16 Sep 2020 19:36:08 GMT
Server: Apigee LB
Vary: Accept-Encoding
{
  "metaData": {
    "createdAt": 1586872499230,
    "createdBy": "<redacted>",
    "lastModifiedAt": 1592500092266,
    "lastModifiedBy": "<redacted>",
    "subType": "null"
  },
  "name": "<redacted>",
  "revision": [
    "1",
    "2",
    "3"
  ]
}
```

**Comment by codyoss** [comment]
This client is auto-generated, and according to the spec this is right: https://github.com/googleapis/google-api-go-client/blob/master/apigee/v1/apigee-api.json#L7029-L7032. But looking at your your output it seems to be a wrong. Could you open an issue on issuetracker.google.com?

**Comment by blucas** [comment]
@codyoss Thanks for the quick reply.  I've tried to raise the issue on the link you provided, but I'm unsure as to what **Component** I'm supposed to use for the issue.  Can you help me identify the correct choice so I can raise the issue?

**Comment by codyoss** [comment]
I was unable to find a public component, but I did file an issue internally on your behalf. 

Internal Issue: 168736975

I will post back when I hear more.

**Comment by blucas** [comment]
Thanks @codyoss

**Comment by codyoss** [comment]
@blucas Can you please confirm the url for your cURL output you gave?

**Comment by codyoss** [comment]
It appears the response is not from https://apigee.googleapis.com which is the API this client is intended to work with.

**Comment by blucas** [comment]
@codyoss sorry for the late response.  That is correct, instead of using apigee.googleapis.com I am using Apigee Edge.  I assumed the APIs would be the same.  I guess that is not the case 😞
