### ISSUE TITLE
Apigee - Organizations.Apis.Create question

### ISSUE THREAD

**Issue by blucas** [googleapis/google-api-go-client#669]
### Golang Version
1.14
### Client Library & Version
[apigee/v1](https://github.com/googleapis/google-api-go-client/tree/v0.31.0/apigee/v1) - v0.31.0
### Question
According to the documentation `Organizations.Apis.Create(...)` supports  "Import an API proxy configuration bundle", but I'm not sure how to accomplish this.  The documentation states one must supply a `GoogleApiHttpBody` but that `struct` does not include a field for the raw binary data.  Instead its `Data` field is declared as a `string`.

So is this a bug?  If not, can someone provide a working example of calling the `Organizations.Apis.Create` API and uploading the archive required by the Apigee [Import API Proxy](https://apidocs.apigee.com/management/apis/post/organizations/%7Borg_name%7D/apis-0) REST endpoint.

Also, I believe this affects other, similarly functioning, REST endpoints such as Apigee [Import a Shared Flow](https://apidocs.apigee.com/shared-flow-api/apis/post/organizations/%7Borg_name%7D/sharedflows)

**Comment by codyoss** [comment]
Thanks for the question.

> So is this a bug?
No, some APIs have a type like this. The data field here represents an arbitrary config Payload.

I would recommend asking this question over in the [Apigee Customer Support](https://community.apigee.com/content/apigee-customer-support).
