### ISSUE TITLE
UnmarshallJSON() for type Route in compute.v1 go sdk

### ISSUE THREAD

**Issue by chiragtayal** [googleapis/google-api-go-client#671]
https://godoc.org/google.golang.org/api/compute/v1#Route
```
type Route
     func (s *Route) MarshalJSON() ([]byte, error)
```

I am receiving `v1.compute.routes.insert` AuditLog from Pubsub then trying to unmarshall into compute.Route and it fails with following error
```
unable to decode route request: json: cannot unmarshal string into Go struct field Route.priority of type int64
```

AuditLog:
```
request: {
     destRange: "10.180.49.96/28"
     description: "custom route created by controller ctayal-cc1 for subnet"
     network: "projects/<projectID>/global/networks/service-vpc"
     name: "rt--10-180-49-96--28--via--10-180-43-3"
     nextHopIp: "10.180.43.3"
     priority: "1000"
     @type: "type.googleapis.com/compute.routes.insert"
}
```

Code:
```
        var route compute.Route
	if err := json.Unmarshal([]byte(request), &route); err != nil {
		log.Errorf("unable to decode route request: %s", err)
		return ""
	}
```

**Comment by codyoss** [comment]
Thanks for the report. The error seems valid to me here, the type declared in the schema for Route.Priority is indeed a integer not a string:

```json
{
    "Route": {
        "description": "Represents a Route resource.\n\nA route defines a path from VM instances in the VPC network to a specific destination. This destination can be inside or outside the VPC network. For more information, read the Routes overview. (== resource_for {$api_version}.routes ==)",
        "id": "Route",
        "properties": {
            "priority": {
                "annotations": {
                    "required": [
                        "compute.routes.insert"
                    ]
                },
                "description": "The priority of this route. Priority is used to break ties in cases where there is more than one matching route of equal prefix length. In cases where multiple routes have equal prefix length, the one with the lowest-numbered priority value wins. The default value is `1000`. The priority value must be from `0` to `65535`, inclusive.",
                "format": "uint32",
                "type": "integer"
            }
        }
    }
}
```

Cloud you please file this issue [here](https://issuetracker.google.com/issues/new?component=187203&template=1162662).

**Comment by jsandler18** [comment]
Hello, my team received this issue, and it seems like an error with UnmarshalJSON.  Javascript and by extension JSON does not have integer types.  The only number type is a [64-bit double-precision floating point number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number).  Doubles cannot fully represent all possible Int64, so when AuditLogs are converted from Proto to JSON, all Int64 are converted to strings to ensure that they are correct.  

UnmarshalJSON must be able to recognize that int64 may be strings for this reason.

**Comment by misho-kr** [comment]
The JSON format clearly allows for integers -- https://www.json.org/json-en.html

Also, if I understand correctly the description of this issue, the problem is the JSON audit-log event does not match the schema which is used to generate the `compute.Route` struct in Go:

https://raw.githubusercontent.com/googleapis/google-api-go-client/master/compute/v1/compute-api.json

```json
        "priority": {
          "annotations": {
            "required": [
              "compute.routes.insert"
            ]
          },
          "description": "The priority of this route. Priority is used to break ties in cases where there is more than one matching route of equal prefix length. In cases where multiple routes have equal prefix length, the one with the lowest-numbered priority value wins. The default value is `1000`. The priority value must be from `0` to `65535`, inclusive.",
          "format": "uint32",
          "type": "integer"
        },
```

**Comment by codyoss** [comment]
@jsandler18 This appears to be an issue with the discovery doc spec. Here is how a another api handles a similar field: https://github.com/googleapis/google-api-go-client/blob/0a77335b68ee0dbe83a16c60a8a9426a4dfba370/localservices/v1/localservices-api.json#L245-L249

Notice even though the format is an int the type is a string. This tells the libraries how to unmarshall the data. Cloud you please link me on the internal issue this is being tracked on?
