### ISSUE TITLE
idtoken: Missing IAP JWT validation steps

### ISSUE THREAD

**Issue by DerekDuchesne** [googleapis/google-api-go-client#672]
It looks like several of the guidelines to validate IAP JWTs defined in https://cloud.google.com/iap/docs/signed-headers-howto#verifying_the_jwt_payload are skipped. Google's own provided library doesn't seem to be providing the best practice documented.

- No 30 second skew when validating `exp`.
- `iat` is not validated.
- `iss` is not validated. (This validation is also recommended for generic ID tokens here: https://developers.google.com/identity/sign-in/web/backend-auth#verify-the-integrity-of-the-id-token)

Is there a reason these are missing? If not, would it be possible to add them?

**Comment by codyoss** [comment]
The idtoken package may be used outside of the context of IAP, in which case the issuer is not `https://cloud.google.com/iap`. The implementation is meant to be generic to fit for a few different use-cases. For this reason we return the parsed payload so the caller can validate any additional claims that fit their use-case.

**Comment by someone1** [comment]
It seems to [acknowledge](https://github.com/googleapis/google-api-go-client/blob/master/idtoken/validate.go#L27) that some tokens will come from IAP though - so wouldn't it already be aware of the separate use cases and can implement the best practices recommended?

**Comment by someone1** [comment]
@codyoss - to work around this package and implement best practices for IAP (allowing 30 second skew for expiration), we would have to ignore the returned `err` from this package if we are protecting IAP and the error text matches 
`idtoken: token expired`

It would be useful if the package did the check itself, or at least exports the expiration error so we aren't forced into error string matching.

The package is great in that it works across multiple deployments (CloudRun IAM, IAP, etc.) and does 90% of the required heavy lifting (e.g. token parsing, certificate lookup/parsing, caching, etc.) It falls short in ways that could be addressed with non-breaking changes. Please let me know if you'd be open to a PR to address the concerns outlined here, I'd be happy to submit one.

**Comment by codyoss** [comment]
Hey,

First off, thanks for bring this to my attention. I have brought these changes up to internal stakeholders. I want to make sure that we would drive a change like this consistently across the various languages we provide client libraries for. For now, I am putting this on hold until we have a consensus around what the different libraries are validating and what they should. I will ping back when I know more.

**Comment by tonglil** [comment]
Would you accept PRs for validating things like token issued after expiry and other JWT fields?

> These client libraries are officially supported by Google. However, the libraries are considered complete and are in maintenance mode. This means that we will address critical bugs and security issues but will not add any new features.

**Comment by codyoss** [comment]
@tonglil That comment is more in relation to the auto-generated clients found in this repository, not the auth libraries that also happen to live in this repository.

**Comment by someone1** [comment]
doing some homework here, the python [google-auth](https://google-auth.readthedocs.io/en/latest/index.html) package does do more than the `idtoken` golang package in question:

* It will [validate issuers](https://github.com/googleapis/google-auth-library-python/blob/master/google/oauth2/id_token.py#L153)
* Has built-in support for [Firebase token authentication ](https://github.com/googleapis/google-auth-library-python/blob/master/google/oauth2/id_token.py#L177)(though notably missing IAP tokens as `idtoken` supports)
* Supports a user supplied `certs_url` to it's [validate function](https://github.com/googleapis/google-auth-library-python/blob/master/google/oauth2/id_token.py#L111) - maybe this is enough to support IAP with our own issuer check?
* Validates both `iat` and `exp`, both with a skew: https://github.com/googleapis/google-auth-library-python/blob/master/google/auth/jwt.py#L174:1

I look forward to hear what the stakeholders think Google supplied packages should support - I'd hope at minimum it'd be their documented best practices. Looks like at least one other Google-supplied package does.

**Comment by codyoss** [comment]
Closing this issue for now as by design. Method states what it is validating today and returns a payload so further validation may be done by the use should they choose.
