### ISSUE TITLE
service-account.json should be moved into testdata dir

### ISSUE THREAD

**Issue by AlexandraRoatis** [googleapis/google-api-go-client#688]
The [service-account.json](https://github.com/googleapis/google-api-go-client/blob/master/internal/service-account.json) file used for [testing](https://github.com/googleapis/google-api-go-client/blob/e3feaebafd82a4d315b4e3562ce80588abf64619/internal/creds_test.go#L40) is copied by `go mod vendor` to other projects where it can be marked as a security vulnerability by automated tooling.

Proposed solution: If the file is moved into a `testdata` directory `go mod vendor` will ignore it.

**Comment by codyoss** [comment]
Thanks for the report, opened a PR.
