### ISSUE TITLE
Can't import google.golang.org/api/smartdevicemanagement/v1

### ISSUE THREAD

**Issue by MyMirelHub** [googleapis/google-api-go-client#697]
*Version*:  go1.15.2 linux/amd64

To reproduce

```sh
go get -u google.golang.org/api/smartdevicemanagement/v1
```
or 

```sh
go mod tidy                                             
```
*Output:*
```console
go get google.golang.org/api/smartdevicemanagement/v1: module google.golang.org/api@upgrade found (v0.32.0), but does not contain package google.golang.org/api/smartdevicemanagement/v1
```

Package is here https://github.com/googleapis/google-api-go-client/blob/master/smartdevicemanagement/v1/smartdevicemanagement-gen.go

**Comment by MyMirelHub** [comment]
It seems like it hasn't been published yet https://pkg.go.dev/mod/google.golang.org/api?tab=packages

**Comment by codyoss** [comment]
@MyMirelHub Correct. This client was added after the last release. I anticipate a release sometime this week. But if you want to experiment before the next release is cut you can always pull head: `go get google.golang.org/api@HEAD`
