### ISSUE TITLE
can't import google.golang.org/api/calendar/v3

### ISSUE THREAD

**Issue by wildwind123** [googleapis/google-api-go-client#699]
`go get -v google.golang.org/api/calendar/v3`
`get "google.golang.org/api/calendar/v3": found meta tag get.metaImport{Prefix:"google.golang.org/api", VCS:"git", RepoRoot:"https://github.com/googleapis/google-api-go-client"} at //google.golang.org/api/calendar/v3?go-get=1
get "google.golang.org/api/calendar/v3": verifying non-authoritative meta tag
google.golang.org/api (download)`
already 3 hours have passed, but i can import different package from github. Or this package too heavy ?

**Comment by tbpg** [comment]
Thanks for the report. We recommend using Go Modules with a module proxy. By default, Go uses proxy.golang.org. That will dramatically speed up your dependency downloads (https://dev.to/tbpalsulich/why-go-modules-are-faster-than-gopath-blj) and insulate you from failures like this.
