### ISSUE TITLE
Change display name and organizer in Google Calendar API

### ISSUE THREAD

**Issue by AldoPL-UT** [googleapis/google-api-go-client#702]
I want to create event via google calendar api using Go. I found out that the sender is whoever responsible in client_id I provide in the google API, in this case me. Can I edit this sender, so that it is not sent from me? I want the sender to be whoever create the event via my program. (I have the user database so I can retrieve the displayname from my DB)

Also about editing the organizer, I tried to use move action but it only moves the event, not change the organizer. Is there other way to edit organizer?

**Comment by codyoss** [comment]
Hey,

Thanks for the questions.

> Can I edit this sender, so that it is not sent from me?

Yes, but it can be a little tricky. It involves domain-wide-delegation and impersonating a user. This is not yet fully supported in these libraries. It is possible, but it takes a little extra work to get done right now. Please see discussion on #378 for some pointers about how to do this today.

> Is there other way to edit organizer

From glancing at [the docs](https://developers.google.com/calendar/v3/reference/events/move), the move API is the correct thing to use here. If this is not working I suggest asking for help by one of the ways mentioned on the [Calendar API support page](https://developers.google.com/calendar/support)
