### ISSUE TITLE
Google hangout chat space api call return error

### ISSUE THREAD

**Issue by cention-mujibur-rahman** [googleapis/google-api-go-client#704]
Hello all,
I am having trouble while calling the SpacesListCall -> Do(). It is because,
https://github.com/googleapis/google-api-go-client/blob/85852b8ab6693201138dc654eb0a4ab786257a79/chat/v1/chat-gen.go#L1959
The above line expecting a query param which is not right. 
In the documention here (https://developers.google.com/hangouts/chat/reference/rest/v1/spaces/list) is straight forward which doesnt need to provide a query params. So the code could be conditional at line: https://github.com/googleapis/google-api-go-client/blob/85852b8ab6693201138dc654eb0a4ab786257a79/chat/v1/chat-gen.go#L1959

**Comment by codyoss** [comment]
Hey @cention-mujibur-rahman,

Are you getting an error? 

If you look two lines above the quoted line you will see some default URL parameters are added onto all requests, so the encoding is always needed.

**Comment by cention-mujibur-rahman** [comment]
Hey codyoss,
Sorry for late reply.
Nevermind, I used to do http request than the pkg. I'll step by step error details later time.

Thanks

**Comment by codyoss** [comment]
Okay. Closing this for now. Please feel free to re-open or create a new issue if you have some steps.
