### ISSUE TITLE
sql: instance user deletion has no username param

### ISSUE THREAD

**Issue by csandanov** [googleapis/google-api-go-client#709]
I've noticed there's no username in params in sql service method for db instance user deletion. Is this a bug?

https://github.com/googleapis/google-api-go-client/blob/master/sql/v1beta4/sql-gen.go#L10580

**Comment by codyoss** [comment]
It looks to be optional and can be added with: https://github.com/googleapis/google-api-go-client/blob/0fbc62c070ac4e4fa4f988bde7db83efe4d4808e/sql/v1beta4/sql-gen.go#L10596.
