### ISSUE TITLE
compute: misformatted comment for Operation

### ISSUE THREAD

**Issue by dowgird** [googleapis/google-api-go-client#712]
This is the docstring generated for Operation:
```
// *
// [Global](/compute/docs/reference/rest/{$api_version}/globalOperations)
//  *
// [Regional](/compute/docs/reference/rest/{$api_version}/regionOperation
// s) *
// [Zonal](/compute/docs/reference/rest/{$api_version}/zoneOperations)
//
// Y
// ou can use an operation resource to manage asynchronous API requests.
```

It's weirdly formatted and renderss badly in HTML, for example here: https://pkg.go.dev/google.golang.org/api@v0.33.0/compute/v1#Operation

I'm referring to compute/v0.alpha/compute-gen.go, PR #707

**Comment by codyoss** [comment]
Thanks for pointing this out. Appears to be the same issue as #544. I will track the progress of the issue here and close other issues. Also related to #457.
