### ISSUE TITLE
Bug: missed "google.golang.org/grpc/naming" package

### ISSUE THREAD

**Issue by ololosha228** [googleapis/google-api-go-client#713]
Looks like sheets api is broken.

```
~/go/src/google.golang.org/api/internal/pool.go:10:2: cannot find package "google.golang.org/grpc/naming" in any of:
        /home/me/.local/usr/local/go/src/google.golang.org/grpc/naming (from $GOROOT)
        /home/me/go/src/google.golang.org/grpc/naming (from $GOPATH)
```

gomod is on, fetched all updates which i could find. week ago this lib was worked so well.

@codyoss

**Comment by ololosha228** [comment]
Found possible problem:

Original git repo ([this one](https://code.googlesource.com/google-api-go-client)) is outdated. Go get couldn't find **this** repo, cause it has single remote, which is google git, who knews.


@codyoss  it is necessary to check google git repo, is it working well, if not, chek out go get softlink to this repository

**Comment by codyoss** [comment]
This repository is now considered the source of truth, with the other being a mirror. Please update your remotes accordingly.

I will look into why there are syncing issues.

**Comment by ololosha228** [comment]
@codyoss thanks for fast respond! As i said, looks like google git just doesn't have remote data of this repo (which is helps `go get` to pull updates from github releases and not google). Maybe it can solve this trouble.

## To guys, who came to this issue from search how to fix:

I simply forcely deleted old repo from gopath, and run `go get -u -v` and that's works:

```
rm -rf $GOPATH/src/google.golang.org/api
go get -u -v google.golang.org/api/...
```
