### ISSUE TITLE
androidpublisher: PaymentState should be a pointer type

### ISSUE THREAD

**Issue by henriqueoelze** [googleapis/google-api-go-client#727]
Working with the api, I notice that PendingState is not using a pointer, but the value 0 is a valid information to business:
https://github.com/googleapis/google-api-go-client/blob/8001663557ac8d144131ea92d9829a0d8e668ab7/androidpublisher/v3/androidpublisher-gen.go#L1932

I believe will be best to change it to a pointer like the `PurchaseType` (example).

I notice that because when I call the `.MarshalJSON()` the field disappeared. 

If allowed, I can submit this PR.

**Comment by codyoss** [comment]
It looks like the case when this is not sent is when a subscription has lapsed or expired. I think it should be possible to check the `UserCancellationTimeMillis` and `ExpiryTimeMillis` currently to see if you need to look at payment state, right?

But I agree, this field could be made a pointer type to remove any ambiguity. These files are auto-generated, so it is the generator that needs to be updated to make such a change. If you want to make the change we happily accept pull requests. But I can make the change too, let me know what you think.

**Comment by henriqueoelze** [comment]
Thanks @codyoss . Fell free to implement, it is not a problem at all for me 😄 .
My suggestion of a pull request is more related to timing, so if it will take a lot of time because of priorities, I can help with that, otherwise, go ahead.

**Comment by leearmstrong** [comment]
Hey all, I see this didn't make it but am seeing the same thing and would like it to be a `*int64` ideally.
