### ISSUE TITLE
Apigee's method organizations.environments.list missing?

### ISSUE THREAD

**Issue by alexanderad** [googleapis/google-api-go-client#742]
It appears there is a missing method `organizations.environments.list` (https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments/list)

It does not appear in both spec file `apigee-api.json` and a generated service code `apigee-gen.go`:
```
$ git log -1                                                                                                                                                  master
commit 01a2d4e004c304c156b8d1c450e0a4eac5a65ffc (HEAD -> master, origin/master, origin/HEAD)
Author: Yoshi Automation Bot <yoshi-automation@google.com>
Date:   Wed Nov 4 07:22:15 2020 -0800

    feat(all): auto-regenerate discovery clients (#739)

$ fgrep -r organizations.environments.list apigee | wc -l
0
```

Others, like `.create` or `.get` are present:
```
$ fgrep -r organizations.environments.create apigee
apigee/v1/apigee-gen.go:// method id "apigee.organizations.environments.create":
apigee/v1/apigee-gen.go:// Do executes the "apigee.organizations.environments.create" call.
apigee/v1/apigee-gen.go:	//   "id": "apigee.organizations.environments.create",
apigee/v1/apigee-api.json:              "id": "apigee.organizations.environments.create",
```

**Comment by codyoss** [comment]
Hey,

The spec is pulled from the public listing: "https://apigee.googleapis.com/$discovery/rest?version=v1". You are right it appears to not be there yet. I am not sure when this method was added but sometimes they can take a little bit of time to roll out. Once the public listing is updated the new method will be auto-generated to the client library. I will leave this issue open for now and check back on a later date to see if the method does roll-out in the coming weeks.

**Comment by alexanderad** [comment]
Ah, I see. I'm going to raise this question with GCP/Apigee support to see if there anything they can do. Environment is one of the foundational entities in Apigee Hybrid, I believe it exists for quite some time now.

**Comment by codyoss** [comment]
Since it appears you have raised this though a support channel I will close out this issue. Once the api is publicly available in the spec it will be generated.
