### ISSUE TITLE
Sheet cell values read as zero

### ISSUE THREAD

**Issue by dwrz** [googleapis/google-api-go-client#748]
We are sporadically seeing sheet cell values read as zero, when instead those cells hold values calculated by formulas. We are using `google.golang.org/api v0.31.0` with ` go1.15.4 linux/amd64`. Re-reading the sheets sometimes fixes this immediately, other times, it will take a few attempts before the sheet is read correctly. 

This problem started on October 27. Unfortunately, I'm not sure if the issue is within this client, or the Sheets API itself.

**Comment by codyoss** [comment]
Hey,

This sounds like more of a backend service question or bug. I would recommend reaching out with one of the recommendations on that teams [support page](https://developers.google.com/sheets/api/support).

**Comment by dwrz** [comment]
Hello, @codyoss the issue eventually disappeared for us, but returned this week. 

I filed a report on the Issue Tracker, here: https://issuetracker.google.com/issues/179925692. I am not sure the engineer that responded to that request understood the issue (they suggested implementing try/catch), but there seems to be an insinuation there that the issue is on the client side.

Do you have any insights?
