### ISSUE TITLE
drive: FilesGetCall.Download did not unmarshal the body in the error response

### ISSUE THREAD

**Issue by aofei** [googleapis/google-api-go-client#752]
Just now I happened to notice that the [`FilesGetCall.Download`](https://github.com/googleapis/google-api-go-client/blob/84df58a8914832693858b396c6099dee1756bf13/drive/v3/drive-gen.go#L7050) threw me this error:

```bash
googleapi: got HTTP response code 403 with body: {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=xxxxxxxxxxxxxx","extendedHelp":"https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=xxxxxxxxxxxxxx"}],"code":403,"message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=xxxxxxxxxxxxxx"}}
```

The returned `error` is still [`*googleapi.Error`](https://pkg.go.dev/google.golang.org/api/googleapi#Error), which is fine. But in its fields, only `Code` and `Body` have values. This caused me to be unable to handle errors through the `Errors` field as usual.

So, does this work as designed?

**Comment by tbpg** [comment]
Thanks for the issue. I'm not sure why that's the case for this call. Here is what appears to be the relevant function:
https://github.com/googleapis/google-api-go-client/blob/84df58a8914832693858b396c6099dee1756bf13/googleapi/googleapi.go#L165-L178

Note that it doesn't try to parse the body as JSON, per the function comment. It seems that all `"media"` requests use `CheckMediaResponse`, which makes sense based on naming! See https://github.com/googleapis/google-api-go-client/search?q=checkmediaresponse.

Error parsing came up for #473. So, let's wait for @codyoss. Notably, https://google.aip.dev/193 doesn't call out media requests as different.

`CheckMediaResponse` was added in https://github.com/googleapis/google-api-go-client/commit/0a735f7ec81c85ce7ec31bf7a67e125ef62266ec 6 years ago, so it's possible that it's now safe to assume JSON.

**Comment by codyoss** [comment]
Thanks for the issue @aofei. @tbpg I assume this is a special case for storage, at least I know that api does not conform to the aip and has xml endpoints... We could keep using this method for storage and move all other apis to use `CheckResponse`. That way we can give the opportunity to parse out extra info for apis that conform but not slow down storage errors that we know will not parse into JSON.

**Comment by tbpg** [comment]
> We could keep using this method for storage and move all other apis to use `CheckResponse`.

Sounds good to me.
