### ISSUE TITLE
Never ending pagination of reports.activities.list

### ISSUE THREAD

**Issue by Rahul-chunduru** [googleapis/google-api-go-client#755]
I have observed that in some cases, Reports API response has the same `nextPageToken` even though the Activities.Items.length = 0. In such cases, the current *ActivitiesListCall  Pages(..) method - google-api-go-client/admin/reports/v1/admin-gen.go: line 1320, shall loop indefinitely. 

To avoid this, a check for Activities.Items.length == 0 should also be used as a stopping condition in disjunction.

**Comment by tbpg** [comment]
Thanks for the issue. From https://google.aip.dev/158: 
> If the end of the collection has been reached, the next_page_token field must be empty. This is the only way to communicate "end-of-collection" to users.

So, this appears to be a bug in the underlying API. Would you mind filing an issue at https://issuetracker.google.com/? There isn't much we can do on the client library side, as we should follow the AIP. So, I'm going to close this.
