### ISSUE TITLE
Chat: Token element in DeprecatedEvent

### ISSUE THREAD

**Issue by daveneeley** [googleapis/google-api-go-client#763]
The [chat api](https://chat.googleapis.com/$discovery/rest?version=v1) specifies a Token element for DeprecatedEvent, with the following description:

```
token: {
type: "string",
description: "A secret value that bots can use to verify if a request is from Google. The token is randomly generated by Google, remains static, and can be obtained from the Google Chat API configuration page in the Cloud Console. Developers can revoke/regenerate it if needed from the same page."
}
```

In absence of #640, I was hoping to use this as an alternate method for validating incoming messages with the go client. All the generated clients have the same language, but the facility for revoking/regenerating the token was not obvious to me. 
Could you shed some light on how this should be done?

**Comment by tbpg** [comment]
Thanks for the issue. Off of the top of my head, I'm not sure what the answer is. I looked at the Chat API Configuration page, but didn't see any mentions of a token...

**Comment by codyoss** [comment]
I might try to reach out through one of the methods listed on the [Chat API support page](https://developers.google.com/hangouts/chat/support).

**Comment by codyoss** [comment]
Since this issue does not seem related to the generated client I suggest reaching out though the link provided above.
