### ISSUE TITLE
dataflow : unknown field 'Environment' in struct literal of type LaunchFlexTemplateParameter

### ISSUE THREAD

**Issue by Liu-Chunhui** [googleapis/google-api-go-client#765]
Hi team,

I am using the latest DataFlow API v0.35.0 `google.golang.org/api/dataflow/v1b3`.

I tried to execute/run a DataFlow flex template job from `Cloud Functions` and received following error:

```
unknown field 'Environment' in struct literal of type dataflow.LaunchFlexTemplateParameter; Error ID: 975560ac
```

But the document shows `Environment` is available https://pkg.go.dev/google.golang.org/api@v0.35.0/dataflow/v1b3#LaunchFlexTemplateParameter

Thanks

John

**Comment by tbpg** [comment]
Hey @Liu-Chunhui, would you mind sharing a complete code sample and what version of google.golang.org/api you're using? Is this an error returned from the API or a compiler error?

**Comment by codyoss** [comment]
I think you should only be getting an error like that if you are using an older version of google.golang.org/api. It looks like this field was not added until v0.33.0. I would double check and make sure you are [specifying your dependencies](https://cloud.google.com/functions/docs/first-go#specifying_dependencies) correctly for your cloud function. Please feel free to reopen if you are still having issues after trying this out.
