### ISSUE TITLE
idtoken: Impersonation support

### ISSUE THREAD

**Issue by mterwill** [googleapis/google-api-go-client#777]
#625 added support for impersonating service accounts where clients authenticate with an access token. It does not support ID tokens, generated with [`projects.serviceAccounts.generateIdToken`](https://cloud.google.com/iam/docs/reference/credentials/rest/v1/projects.serviceAccounts/generateIdToken). The `idtoken` package accordingly does not support impersonation:

https://github.com/googleapis/google-api-go-client/blob/c9160e8cf25085a29a4d3267e1b6ee5ad961c17c/idtoken/idtoken.go#L81-L83

I would like to use my application default credentials to impersonate a service account to authenticate to Cloud Run. Any plans to support impersonation in the `idtoken` package?

**Comment by codyoss** [comment]
Yes, this is something that I would like to. The work has just not been prioritized yet. I will update this issue when there are plans to add this support in.

**Comment by mterwill** [comment]
@codyoss I took a pass at implementing this!

**Comment by codyoss** [comment]
Thank you for your interests in this feature! I am going to hold off on reviewing the PR for now though as we are still figuring out the impersonation story across the various languages we support for our clients today, this is one reason the feature is in an experimental status today. I will post back here when I have a better picture of what we would like to support. 

In the meantime though you still should be able to do this style of impersonation today, it just takes a little more work. Use the impersonation option to create an [iamcredentials.Service](https://pkg.go.dev/google.golang.org/api@v0.36.0/iamcredentials/v1#NewService). Then you can use the [GenerateIdToken](https://pkg.go.dev/google.golang.org/api@v0.36.0/iamcredentials/v1#ProjectsServiceAccountsService.GenerateIdToken) to get an idtoken. Hope that helps in the meantime.

**Comment by mterwill** [comment]
Sounds good, thanks!

**Comment by codyoss** [comment]
Thanks for understanding!

**Comment by codyoss** [comment]
Please try out our impersonate preview and feel free to provide any feedback: https://github.com/googleapis/google-api-go-client/releases/tag/v0.44.0-impersonate-preview

**Comment by mterwill** [comment]
@codyoss – works great, thanks! Any idea when the new package will be generally released?

**Comment by codyoss** [comment]
@mterwill  Planning on cutting a release with this next week. Can follow https://github.com/googleapis/google-api-go-client/pull/991 for progress. A release will be cut shortly after the cherry pick.

**Comment by mterwill** [comment]
Thank you!

**Comment by codyoss** [comment]
Now in a main release: https://github.com/googleapis/google-api-go-client/releases/tag/v0.46.0
