### ISSUE TITLE
GroupsMigration archive insert issue

### ISSUE THREAD

**Issue by boom3k** [googleapis/google-api-go-client#778]
```
media, _:= os.Open("test.eml")
mediaOption := googleapi.MediaOption()
res, _:= service.Archive.Insert("groupemail@domain.com").Media(media, mediaOption).Do()
```

Error :
Missing argument to conversion to 'googleapi.MediaOption': googleapi.MediaOption()

--------------------------------------------------------------------------------------------------------------------------
Also, when using service.Archive.Insert without the mediaOption parameter it breaks stating that the file was not inserted due to it not being a "message/rfc822" type, yet when I use this API and file in Java it works perfectly.

2nd Error:
googleapi: Error 400: Media type 'text/plain; charset=utf-8' is not supported. , badRequest
panic: googleapi: Error 400: Media type 'text/plain; charset=utf-8' is not supported. , badRequest

**Comment by codyoss** [comment]
Hey,

MeidaOptions are an optional argument, so if you don't have one to pass you can write: 'service.Archive.Insert("groupemail@domain.com").Media(media).Do()'

Although an option that is commonly set in cases like these is `googleapi.ContentType("something")` which will set the Context-Type header for uploads. Hope that helps!

**Comment by boom3k** [comment]
Understood, but when I try to upload an eml I get the following error:
googleapi: Error 400: Media type 'text/plain; charset=utf-8' is not supported. , badRequest
panic: googleapi: Error 400: Media type 'text/plain; charset=utf-8' is not supported. , badRequest

Here is the code:
`media, err := os.Open("x.eml")
	if err != nil {
		log.Println(err.Error())
		panic(err)
	}

	res, err := service.Archive.Insert("groupemail@domain.com").Media(media).Do()
	if err != nil {
		log.Println(err.Error())
		panic(err)
	}`

Anyway to force the upload to be set as "message/rfc822"?

**Comment by codyoss** [comment]
As I mentioned above [googleapi.ContentType](https://pkg.go.dev/google.golang.org/api/googleapi#ContentType) is used to set the header. Have you given that a try?

**Comment by boom3k** [comment]
Yes that worked! I wish there was more documentation that helped explain that directly. My team was blaming this one the library but this is more of a documentation thing. Thank you so much @codyoss!
