### ISSUE TITLE
idtoken: Option to add Proxy to the RoundTripper

### ISSUE THREAD

**Issue by utsavgupta** [googleapis/google-api-go-client#802]
At the moment there is no straightforward way of adding a proxy url to the round tripper.

The iapClient.Transport cannot be converted to *http.Transport either.

Can we have an option to specify an initial transport in while creating a new client ? Or at least pass the Proxy URL ?

**Comment by codyoss** [comment]
Hey @utsavgupta,

If you would like to set a proxy we have two options today that might work for you.

1. You can pass in your own http.Client with [option.WithHTTPClient](https://pkg.go.dev/google.golang.org/api/option#WithHTTPClient). You would need to make sure this client provides the proper authentication. I would recommend using one of the methods from the [transport/http](https://pkg.go.dev/google.golang.org/api/transport/http) package and wrapping that according to your needs.
2. The language actually provides an environment variable you can set to set the proxy globally. This is `HTTP_PROXY` you can find more information on this variable in the [net/http](https://golang.org/pkg/net/http/#RoundTripper) package.

In the future we are considering adding a RoundTripper option to make things like this a little easier. Here is the [issue](https://github.com/googleapis/google-cloud-go/issues/1962) where you can track that if you like.

Hope that helps!

**Comment by harpratap** [comment]
@codyoss Slightly off tangent, but how does one get an authenticated http client from the transport package?

**Comment by codyoss** [comment]
When creating the `http.Client` be sure to pass in the scopes required for the requests you will be making: `option.WithScopes`.

**Comment by harpratap** [comment]
@codyoss Thanks, that seems to make it work partially. But now it looks like the storage APIs are being called through the proxy but not the oauth2 API. Any idea how to make ALL of the calls made by this Storage client go through this proxy?
My current implementation is here - https://github.com/rakutentech/shibuya/pull/9/commits/4f219ede882d216caa8e6cc44c43a501d489f274

**Comment by codyoss** [comment]
If you are setting the proxy on the client you and not through an environment variable you will need to make sure the oauth2 client also uses that client as well. This can be achieved by setting a context value with [oauth.HTTPClient](https://pkg.go.dev/golang.org/x/oauth2#pkg-variables). Hope that helps.
