### ISSUE TITLE
idtoken: invalid token, token must have three segments error

### ISSUE THREAD

**Issue by ArchanaArige** [googleapis/google-api-go-client#804]
I am validating the idToken issued by Google, using this package. But I am getting the error " invalid token, token must have three segments; found 2 ".  IdToken is in the right format. Please guide.

**Comment by codyoss** [comment]
This check guarantees the to token contains three base64 encoded segments separated by a `.`. It sounds like whatever token was sent to this method does not match the format.

A couple of questions: 
- Can you confirm what you token looks like, does it match this format?
-  Are you able to reproduce this locally?
- Where/How are you getting this token?

**Comment by codyoss** [comment]
Closing due to lack of response. Please feel free to re-open if you are still having issues and can share more information.

**Comment by SantiiRepair** [comment]
```go
panic: idtoken: invalid token, token must have three segments; found 2

```
