### ISSUE TITLE
Google Ads API Support

### ISSUE THREAD

**Issue by Volcore** [googleapis/google-api-go-client#814]
Hi,

Happy new year and thanks for this great project!

It doesn't look like the Google Ads API (https://developers.google.com/google-ads/api/docs/client-libs) is currently supported in Go. It seems like google-api-go-client would be the place it would live at.

Is this going to happen, and is there an ETA for when it will happen? We're currently holding off (and have been for at least 6 months), but we are starting to look into alternative, less elegant solutions to tap into that API from our Go services.

Thanks!

**Comment by codyoss** [comment]
Hey,

Thanks for your interest in Ads client libraries. This project is used to generate apis from Googles public discovery doc listing, which Ads is not a part of. I suggest sending this request through the [Ads forums](https://groups.google.com/g/adwords-api).
