### ISSUE TITLE
cloudshell: AddPublicKeyRequest.Key documentation malformed / unclear

### ISSUE THREAD

**Issue by guywithacube** [googleapis/google-api-go-client#821]
The comment for AddPublicKeyRequest.Key is not readable.

```
// AddPublicKeyRequest: Request message for AddPublicKey.
type AddPublicKeyRequest struct {
	// Key: Key that should be added to the environment. Supported formats
	// are `ssh-dss` (see RFC4253), `ssh-rsa` (see RFC4253),
	// `ecdsa-sha2-nistp256` (see RFC5656), `ecdsa-sha2-nistp384` (see
	// RFC5656) and `ecdsa-sha2-nistp521` (see RFC5656). It should be
	// structured as , where part is encoded with Base64.
	Key string `json:"key,omitempty"`

...
```

Specifically, the last sentence:
> It should be structured as , where part is encoded with Base64.

It appears similarly malformed on [the documentation for the REST API](https://cloud.google.com/shell/docs/reference/rest/v1/users.environments/addPublicKey#google.cloud.shell.v1.CloudShellService.AddPublicKey).

**Comment by codyoss** [comment]
Thanks for the report I will file an internal issue to get this fixed as this repository just generates code from the public discovery document listing. This should read:

"It should be structured as <format> <content>, where <content> part is encoded with Base64."

Internal bug: 177220782

**Comment by guywithacube** [comment]
@codyoss 

I just wanted to confirm, do you mean to say that it _should_ read as:

> It should be structured as , where part is encoded with Base64.

Or is it meant to read as otherwise?

Thanks for the help! 🙂

**Comment by codyoss** [comment]
Whoops I copied the incorrect text. Should be:

`It should be structured as <format> <content>, where <content> part is encoded with Base64.`

**Comment by guywithacube** [comment]
Fantastic.

Thank you!
