### ISSUE TITLE
Creating consent errors out must specify user_id matching

### ISSUE THREAD

**Issue by sunkararp** [googleapis/google-api-go-client#826]
When our app tried to create the user consent, it got the below error... 

`_{ "error": { "code": 400, "message": "Consents must specify user_id matching "^[\\p{L}\\p{N}_\\-]{1,256}$".", "status": "INVALID_ARGUMENT" } }_`

Any help to resolve this error is much appreciated.

Below is the consent payload...
`{
   'user_id': 'removed@4privacy.com',
   'policies': [{
     'resource_attributes': [{
       'attribute_definition_id': 'data identifiable',
       'values': ['identifiable']
     }],
     'authorization_rule': {
       'expression': 'requester_identity == \'clinical-admin\'',
    }
   },{
     'resource_attributes': [{
       'attribute_definition_id': 'data_identifiable',
       'values': ['de-identified']
     }],
     'authorization_rule': {
       'expression': 'requester_identity in [\'internal-researcher\', \'external-researcher\']'
      }
   }],
   'consent_artifact': 'projects/mypocproject-285122/locations/us-central1/datasets/ayushman_consent_dataset/consentStores/ayushman_consent_store/consentArtifacts/b5e3298e-50ff-4737-b6a5-7a803bb36f48',
   'ttl': '86400s'
}`

Below is the consentArtifacts creation, result...
`{
    "name": "projects/mypocproject-285122/locations/us-central1/datasets/ayushman_consent_dataset/consentStores/ayushman_consent_store/consentArtifacts/b5e3298e-50ff-4737-b6a5-7a803bb36f48",
    "userId": "removed@4privacy.com",
    "userSignature": {
       "userId": "removed@4privacy.com",
       "signatureTime": "2021-01-14T04:25:35Z"
    },
    "consentContentVersion": "v1",
    "metadata": {
       "Idp": "4privacy",
       "client": "mobile"
    }
}`

**Comment by codyoss** [comment]
@sunkararp Can you please provide me with some more information here.

1. Where version of the library are you using.
2. What client are you using?
3. Can you provide a simple reproducer?

**Comment by sunkararp** [comment]
I was using simple plain vanilla code samples from Google docs from [here](https://cloud.google.com/healthcare/docs/quickstart)

#1:
- C:\Program Files (x86)\Google\Cloud SDK>gcloud version
--Google Cloud SDK 323.0.0
-- bq 2.0.64
--core 2021.01.08
-- gsutil 4.57

#2:
- I was POSTing json payload using windows Powershell, followed this [link](https://cloud.google.com/healthcare/docs/how-tos/consent-creating#healthcare-create-consent-cli-powershell)
- Windows10, OS Build 18363.1316

#3:
PROJECT_ID: mypocproject-285122
LOCATION: us-central1
DATASET_IS: ayushman_consent_dataset
CONSENT_STORE_ID: ayushman_consent_store

- Consent Artifact creation
`$cred = gcloud auth application-default print-access-token
$headers = @{ Authorization = "Bearer $cred" }

Invoke-WebRequest `
  -Method Post `
  -Headers $headers `
  -ContentType: "application/consent+json; charset=utf-8" `
  -Body "{
       'user_id': 'removed@4privacy.com',
       'user_signature' : {
         'user_id': 'removed@4privacy.com',
         'signature_time': {
           'seconds': 1610598335 }
      },
       'consent_content_screenshots': [
         { 'raw_bytes': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAAGYktHRAD/AP8A/6C9p5MAAAMASURBVEhLrZXNSxRxGMe/szPj7IuKSmZrLyKxRQUWi0tFyXaxSyjqwVvdOuQ/kNAh6tS5PXSKqE4RoVkQ2UGWhIg1ig4FKZFmalmsurZv89bzzIyY2+xMQR94lmef55nnmee3z/NbwSTwF+RyOaTTaWSzWQwMDCASiTgeH7iAH6lUyozFYmZnZ6cZj8fNnp4eM5PJOF5vfDuYmJjA0NAQotEoShpQVIFCSUV+ZRG3b91EMpl0It3xLdDb24tPC1kIoozugyL64zJOHJJw6soKGpqaMTrywIl0x7dAtO0Axi62I3FEATQDUClcCgCGjl3n5zE/89qJdIcivYnU1SNxTMH4k1lKLpAlgKfP5oBaEbIs2kEe+BZ4NUxvvWJgS5tcJ2fizSVWvPEf0+xbIH0BqGumDqgYI9N75ZaB5A2gscO2VcG3AytBeAdQ1h0DwXo46puc+etFw10q0nLS1r9OAmeXbN0H3wILNPe144OQP48ipNEXoijJKO3uR/70PURly1QVzyN6NK0hNQUsrRahCCaKwSaSRijQsbRWwHXyjVGMF1U7GP+oY2pRQ7gmgAK98eCHPuxdfmj5Zpr7cH/fiNVRvmwg0Sqhu919ZF0LGGS5OllEgxKAQJNo0lwWaZNVp1+Zhimoq2Q16S6jKS4ZuNwVtKa3Etcjev/dQFAUrOQMJwrpZdSrtrDONstHMRz7btkZ4QpcC6zTvG8mt6WS3+0cy8+4UeVHpre3PmnPiqYlG8mYSjvL1ohNPKdIJO/smmEJ6xu42d3T+xRg7KMSEKF5D0m2sM49bhyjF65T9HJBR3pWQ0gW8C1v4vG0SpMlQA7Zf5Nq4ScCtBdnYjJawgIKdIUn2yQcbf1zVF0LvPii4fmcDkUSKBGg0HNyqAaZO9csf+LcMBUpo0RXEo90STPRtUfE8Z3UXgWuRxSmxHyfcWlOUKBlzdMtoUoRS1hnG/s4hmMj1K0brgUOt4jYvy1AC2RilWSNJFcCfqyuW8I629jHMRzbsf0fNvn/AfwCSs2ZCyv04v4AAAAASUVORK5CYII=' }],
       'consent_content_version': 'v1',
       'metadata': {'client': 'mobile'}
    }" `
  -Uri "https://healthcare.googleapis.com/v1beta1/projects/mypocproject-285122/locations/us-central1/datasets/ayushman_consent_dataset/consentStores/ayushman_consent_store/consentArtifacts" | Select-Object -Expand Content`
- Consent creation
`$cred = gcloud auth application-default print-access-token
$headers = @{ Authorization = "Bearer $cred" }

Invoke-WebRequest `
  -Method Post `
  -Headers $headers `
  -ContentType: "application/consent+json; charset=utf-8" `
  -Body "{
       'user_id': 'removed@4privacy.com',
       'policies': [{
         'resource_attributes': [{
           'attribute_definition_id': 'data_identifiable',
           'values': ['identifiable']
         }],
         'authorization_rule': {
           'expression': 'requester_identity == \'clinical-admin\'',
        }
       },{
         'resource_attributes': [{
           'attribute_definition_id': 'data_identifiable',
           'values': ['de-identified']
         }],
         'authorization_rule': {
           'expression': 'requester_identity in [\'internal-researcher\', \'external-researcher\']'
          }
       }],
       'consent_artifact': 'projects/mypocproject-285122/locations/us-central1/datasets/ayushman_consent_dataset/consentStores/ayushman_consent_store/consentArtifacts/e6871732-fe17-47aa-8045-c722cb918519',
       'ttl': '86400s'
    }" `
  -Uri "https://healthcare.googleapis.com/v1beta1/projects/mypocproject-285122/locations/us-central1/datasets/ayushman_consent_dataset/consentStores/ayushman_consent_store/consents" | Select-Object -Expand Content`

**Comment by codyoss** [comment]
It appears you might be looking for help with the healthcare api. I would suggest reaching out on one of the contact methods on the [healthcare support page](https://cloud.google.com/healthcare/docs/getting-support). This issue tracker is for Go client libraries. Hope the link is useful.
