### ISSUE TITLE
compute.v1.DisksService.CreateSnapshot not creating snapshot, but no errors (quota hit for snapshots, but API reports no errors)

### ISSUE THREAD

**Issue by arianitu** [googleapis/google-api-go-client#832]
I'm using the API method:

```
gceSnap := compute.Snapshot{
      Name:        snapshotName,
      Description: getSnapshotTags(tags, disk.Description, b.log),
}

op, err := gce.Disks.CreateSnapshot("project", volumeAZ, volumeID, &gceSnap).Do()

```

This method successfully gets called, err == nil and I have printed op.Error and op.Warnings, the first is nil and the second is an empty array.

When I look at the returned operation, it says the status is "RUNNING". In reality, the disk snapshot does not get created, nor is there an API errors reported when I go to https://console.developers.google.com/apis/api/compute.googleapis.com/metrics

**EDIT:**

Seems to happen when you hit a Quota limit.

**Comment by arianitu** [comment]
I do have the operation id if there is a way to take a look at it. In the operation response, it returns a link like so:

```
https://www.googleapis.com/compute/v1/projects/project-name/zones/us-east1-c/operations/operation-ID-HERE
```

Is there a way to look at this after the fact?

**Comment by arianitu** [comment]
This is the debug code I used as well:

```
	op, err := b.gce.Disks.CreateSnapshot(b.snapshotProject, volumeAZ, volumeID, &gceSnap).Do()
	b.log.Printf("op is: %v", op)
	b.log.Println("op error", op.Error)
	if op.Error != nil {
		b.log.Println("op.Error.Errors", op.Error.Errors)
	}
	b.log.Println("warning:", op.Warnings)
	b.log.Println("op.status..", op.Status)
	b.log.Println("op.status.message", op.StatusMessage)

```

It gets passed all of these with no errors.

**Comment by arianitu** [comment]
It looks like I'm hitting a Quota, but the API is not responding with an error when a quota is hit. I attempted to create a snapshot from the UI and I got the correct message:

"Max 1,000 snapshots reached".

Does the API not support errors when quotas are hit?

**Comment by codyoss** [comment]
The first request is unlikely to have issues as it returns a long running operation. You will want to check the status of the operation. Here is an example of how to do that: https://github.com/googleapis/google-api-go-client/blob/99672a90d8e348f86d7e8862e1769a05da26e74a/examples/operation_progress.go#L34
