### ISSUE TITLE
run: Client doesn't replace routes if app is running in Cloud Run.

### ISSUE THREAD

**Issue by mpokryva** [googleapis/google-api-go-client#856]
**Client**

v1 Cloud Run (https://pkg.go.dev/google.golang.org/api/run/v1?utm_source=godoc)

**Environment**

* Cloud Run

* Using gcr.io/distroless/static image

**Go Environment**

Not related to go environment, only specified library.

**Code**

```
import  (
    "google.golang.org/api/run/v1"
    "context"
    "os"
)

service, err := run.NewService(ctx)
if err != nil {
	return err
}
call := run.NewNamespacesConfigurationsService(service).Get(os.Getenv("K_CONFIGURATION"))
config, err := call.Context(ctx).Do()
if err != nil {
	return err
}
```

**Expected behavior**

https://cloud.google.com/run/docs/reference/rest/v1/namespaces.configurations/get#path-parameters says:

> For Cloud Run (fully managed), replace {namespace_id} with the project ID or number. It takes the form namespaces/{namespace_id}/configurations/{configuration_id}.

**Actual behavior**

The client does not automatically replace this path, so it can't be used in Cloud Run. The generated `NamespacesConfigurationsGetCall` has the appropriate path (`apis/serving.knative.dev/v1/namespaces/{namespacesId}/configurations/{configurationsId}`), but doesn't actually use this path.

Also, another small bug, there's no `{namespace_id}`. The path specified at https://cloud.google.com/run/docs/reference/rest/v1/namespaces.configurations/get#http-request is `GET https://{endpoint}/apis/serving.knative.dev/v1/{name}`.

**Comment by codyoss** [comment]
Hey,

I see a couple of mistakes here.

1. Cloud run uses region endpoints so you will need to set an endpoint override.
2. Looking at the docs it seems name should be formatted: `namespaces/%s/configurations/%s`

Here is an example of a some code that seemed to work for me, I think you should be able to adapt it to your usecase:

```go
import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"

	"google.golang.org/api/option"
	run "google.golang.org/api/run/v1"
)

func main() {
	if err := http.ListenAndServe(":8080", nil); err != nil {
		log.Fatal(err)
	}
}

func handler(w http.ResponseWriter, r *http.Request) {
	ctx := context.Background()
        // replace region with what is appropriate for you.
	service, err := run.NewService(ctx, option.WithEndpoint("https://us-central1-run.googleapis.com/"))
	if err != nil {
		http.Error(w, err.Error(), 400)
		return
	}
	config, err := service.Namespaces.Configurations.
                // swap in your project ID, you can also get it dynamically from the metadata server
		Get(fmt.Sprintf("namespaces/%s/configurations/%s", googleCloudProjectID, os.Getenv("K_CONFIGURATION"))).
		Context(ctx).
		Do()
	if err != nil {
		http.Error(w, err.Error(), 400)
		return
	}
	fmt.Fprintf(w, "conf: %v", config)
}
```

Hope that helps!
