### ISSUE TITLE
sheets: Error on defineing multiple ranges.

### ISSUE THREAD

**Issue by eamirgh** [googleapis/google-api-go-client#864]
There is an unclarity in defining multiple ranges on sheets v4 API since there is no example in the documents.
To reproduce:
On the QuickStart example if we use a multiple ranged string, for example `Sheet1!A12:C12,Sheet1!A14:C14,Sheet1!A29:C29,Sheet1!A31:C31,Sheet1!A46:C46`
or
`Sheet1!A12:C12,A14:C14,A29:C29,A31:C31,A46:C46` ,
which are a valid range in sheet1 sheet, We will get "Unable to write data to sheet: googleapi: Error 400: Invalid data[0]: Unable to parse range:..."  error in both `Update` and `BatchUpdate` Methods.

**Comment by codyoss** [comment]
Hey,

This client is auto-generated and the issue tracker here is used more so for the generated code itself. It sounds like your question is related to the API itself. I would recommend reaching out from one of the ways listed on the [Sheets Support Page](https://developers.google.com/sheets/api/support). Hope the helps.
