### ISSUE TITLE
Fields with type bool and json tag omitempty should be *bool

### ISSUE THREAD

**Issue by 0marq** [googleapis/google-api-go-client#900]
Hello,

I was using the `sqladmin` package (google.golang.org/api/sqladmin/v1beta4) and I encountered a bug.

When creating an CloudSQL instance I tried to disable the public IP address. I had to do so by setting the field `Settings.IpConfiguration.Ipv4Enabled` with value false, but the Golang Google API Client kept creating an instance without the expected value.

To debug what was happening, I printed the payload generated by `InstancesInsertCall.Do`. To do so, I copied the line 
`googleapi.WithoutDataWrapper.JSONReader(c.databaseinstance)` and pasted it in my code to check the body.

It turned out the field `Ipv4Enabled` was not set in the json payload because I was setting the value at `false` and the json annotation contained the tag `omitempty`, which made the golang json parser think it was empty. 
It would not have been an issue if CloudSQL did not assign a public IP address by default to every instance.

I see two possible fixes here:
- Change the CloudSQL API to create, by default, instances without public IP address, but I am guessing this solution won't be available before a long time.
- Update all structures containing a field with type `bool` and tag `omitempty` to change the type of this field to `*bool`. 

I suggest updating all the structures since I am guessing I won't be the only one to encounter this bug and that it might happen on other packages and structures as well. But for the moment I only care about the `sqladmin.DatabaseInstance` structure.

If you wish to check for yourselves, here is the golang code

```go
package main

import (
	"io/ioutil"
	"log"

	"google.golang.org/api/googleapi"
	sqladmin "google.golang.org/api/sqladmin/v1beta4"
)

func main() {
	dbInstance := &sqladmin.DatabaseInstance{
		DatabaseVersion: "POSTGRES_11",
		Name:            "myinstanceid",
		Region:          "europe-west1",
		Settings: &sqladmin.Settings{
			IpConfiguration: &sqladmin.IpConfiguration{
				Ipv4Enabled:    false,
				PrivateNetwork: "projects/myprojectid/global/networks/myvpc",
			},
			Tier: "db-custom-1-4096",
			MaintenanceWindow: &sqladmin.MaintenanceWindow{
				Day:  6,
				Hour: 3,
			},
		},
	}

	body, err := googleapi.WithoutDataWrapper.JSONReader(dbInstance)
	if err != nil {
		log.Fatalf("Error creating body : %s", err)
	}
	bodyContent, err := ioutil.ReadAll(body)
	if err != nil {
		log.Fatalf("Error reading body : %s", err)
	}
	log.Print(string(bodyContent))
}
```

And here is the returned json body
```json
{
    "databaseVersion": "POSTGRES_11",
    "name": "myinstanceid",
    "region": "europe-west1",
    "settings": {
        "ipConfiguration": {
            "privateNetwork": "projects/myprojectid/global/networks/myvpc"
        },
        "maintenanceWindow": {
            "day": 6,
            "hour": 3
        },
        "tier": "db-custom-1-4096"
    }
}
```

What's your input on this ? Did you already have this issue in mind and do you think it can be solved soon ?

**Comment by codyoss** [comment]
Hey @0marq this is a design choice by this api. To get around false values, and other default values, being sent please see: [ForceSendFields](https://pkg.go.dev/google.golang.org/api#hdr-ForceSendFields).

**Comment by 0marq** [comment]
Works like a charm ! Thanks for the tip and the quick answer !
