### ISSUE TITLE
Cannot remove RecoveryPhone from users via directoryv1 API

### ISSUE THREAD

**Issue by xrstf** [googleapis/google-api-go-client#901]
I have a user in my organization who has a recovery phone number set. I want to remove this phone number via the go client, but the request never has any effect. I can _add_ and _change_ the recovery phone, but never remove it. I tried v0.36.0 and v0.4.0.

Playing around with the codebase a bit, removing the `omitempty` flag from the `User` struct's `RecoveryPhone` field fixes the problem immediately.

The same applies to the RecoveryEmail and I guess many other string fields?

**Comment by xrstf** [comment]
NB: This can be fixed by manually setting ForceSendFields like so:

```go
newUser.ForceSendFields = []string{"RecoveryEmail", "RecoveryPhone"}

updatedUser, err := myDirectoryService.Users.Update("user@example.com", newUser).Do()
if err != nil {
	return nil, err
}
```

**Comment by codyoss** [comment]
ForceSendFields is the correct way to handle this case.
