### ISSUE TITLE
seems can not get the newest revision immediately after the file changed on gdrive

### ISSUE THREAD

**Issue by timestee** [googleapis/google-api-go-client#906]
using api v3 to list and sync excel files on gdrive.

```golang
const fieldsContent = "nextPageToken, files(id, name,version, mimeType, size, md5Checksum,modifiedTime,lastModifyingUser,webViewLink)"
const qInParent     = "'%s'  in parents"
const trashFalse    = " and trashed=false"
func (d *Drive) testList(id string)  {
	var driveService *drive.Service
	var pageToken string
	// .....init the service
	fileList, err := driveService.Files.List().Q(fmt.Sprintf(qInParent, id)+trashFalse).
		Fields(fieldsContent).
		PageSize(pageSize).PageToken(pageToken).Do()
	// ... print the files
}
```

Just a simple test case.

At `2021-03-04T15:14:16+08:00`, got test.xlsx state: 
Md5Checksum: 668395eb4b0db465efaf631df3aefd86
ModifiedTime: 2021-03-04T07:13:02.100Z

At `2021-03-04T15:16:06+08:00`, got test.xlsx state: 
Md5Checksum: 668395eb4b0db465efaf631df3aefd86
ModifiedTime: 2021-03-04T07:13:02.100Z

At `2021-03-04T15:16:28+08:00`, got test.xlsx state: 
Md5Checksum: 6155d40b7376d8c675c02ebd5a2394e9
ModifiedTime: 2021-03-04T07:13:48.638Z

The file first change at time: `2021-03-04T07:13:02.100Z`, second change at time:  `2021-03-04T07:13:48.638Z`, but through the api, we can not get the changed file's info immediately, may be delayed a few minutes, perhaps 10 minutes sometime.

Update:
After edit the file on gdrive , download the file through api within several minutes. Still can not get the latest file, still got the previous one.
 ```golang resp, err := d.driveService.Files.Get(info.Id).Download() ```

**Comment by codyoss** [comment]
Hey,

This issue tracker is primarily used to report issues related to the generated code itself. If you have specific questions for a given API I would recommend reaching out by one of the methods listed on that services support page. In that case of Drive that can be [found here](https://developers.google.com/drive/api/v3/support). Please reach back out here if you find your answer though to help others with the same question in the future. Thanks.
