### ISSUE TITLE
Client crashing when homedir set to /dev/null

### ISSUE THREAD

**Issue by danielkucera** [googleapis/google-api-go-client#926]
We used to use user `guest` which has home set to `/dev/null`
With version 0.15 it was working fine. After upgrading to latest release, we started to get following error:
```
open /dev/null/.secureConnect/context_aware_metadata.json: not a directory
```
this is most probably caused by following commit:
https://github.com/googleapis/google-api-go-client/commit/c130fbf47401c663846f83d9b1b553dce7af0478

There is a condition which is true when the file does not exist:

https://github.com/googleapis/google-api-go-client/blob/master/transport/cert/default_cert.go#L80

but the case when the path is incorrectly built on top of an existing file instead of folder is not handled and ends with an error.

https://github.com/googleapis/google-api-go-client/blob/master/transport/cert/default_cert.go#L85

For better backward compatibility it would be better to return nil,nil in case of any file opening error.

**Comment by codyoss** [comment]
Hey,

Are you setting `GOOGLE_API_USE_CLIENT_CERTIFICATE` to true? I believe this is the correct behavior for this feature. If you would like to use this auth feature and keep /dev/null set I suggest using the client option instead: [option.WithClientCertSource](https://pkg.go.dev/google.golang.org/api/option#WithClientCertSource).

**Comment by danielkucera** [comment]
I see now, we were using version v0.30.0 where the default behavior is to check if the file exists and no such variable is checked:

https://github.com/googleapis/google-api-go-client/blob/dcbe36d62163edc6a7dca06c1d9f34881a2283b7/transport/cert/default_cert.go#L62-L70

**Comment by codyoss** [comment]
This feature appears to be guarded by an environment variable in the current release. Closing as I believe the requested behavior is the way it works on latest.
