### ISSUE TITLE
Bug: admin api sdk can not handle zero-value correct

### ISSUE THREAD

**Issue by 3ks** [googleapis/google-api-go-client#938]
# Backgroud

I wanna to control the [User](https://pkg.go.dev/google.golang.org/api/admin/directory/v1@v0.13.0#User) state through the API.

The principle is to modify the value of the `Suspended` field through the SDK

# Actual situation

I can only disable users, but not enable them.

# Problem Cause

```go
type User struct {
        ... 

	// Suspended: Indicates if user is suspended.
	Suspended bool `json:"suspended,omitempty"`

       ...
}
```

When I want to enable the account, I need to assign `Suspended` to false, but for `bool`, false is its zero value, so the final request sent will not contain that field (`omitempty`).

When I want to disable the account, I need to assign `Suspended` to true, which is not a zero value, so it works fine.

# Solution

Change `bool` to `*bool`, it's works well for me.

# Others

I've noticed a lot of similar problems with this Repo, and if they want to work properly, the acquisitions all need to make the same changes.

**Comment by codyoss** [comment]
Please reference docs on [ForceSendFields](https://pkg.go.dev/google.golang.org/api#hdr-ForceSendFields).

**Comment by 3ks** [comment]
That's great thank you, it's due to my lack of proficiency with the SDK.

**Comment by codyoss** [comment]
No worries, glad I could help!
