### ISSUE TITLE
docs: improve godoc generation for functions

### ISSUE THREAD

**Issue by kortschak** [googleapis/google-api-go-client#950]
The godoc comments that are generated for the Go API client code lacks information that is present for other languages, for example python.

Take for example the YouTube live broadcasts API functions. In the `liveBroadCasts` [`insert`](https://googleapis.github.io/google-api-python-client/docs/dyn/youtube_v3.liveBroadcasts.html#insert) documentation all the input parameters are described.

```
insert(part, body=None, onBehalfOfContentOwner=None, onBehalfOfContentOwnerChannel=None, x__xgafv=None)

Inserts a new stream for the authenticated user.

Args:
  part: string, The *part* parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include. The part properties that you can include in the parameter value are id, snippet, contentDetails, and status. (required) (repeated)
  body: object, The request body.
    The object takes the form of:

<yada...>
```

In the Go client documentation for the cognate [`Insert`](https://pkg.go.dev/google.golang.org/api/youtube/v3#LiveBroadcastsService.Insert) method the input parameters are not described completely.

> ```
> func (r *LiveBroadcastsService) Insert(part []string, livebroadcast *LiveBroadcast) *LiveBroadcastsInsertCall
> ```
>
> Insert: Inserts a new stream for the authenticated user. 

The composite type `LiveBroadcast` documents some of the inputs, but the `parts` parameter is left undocumented, although this information is available to the code generator as seen in the python docs.

Please emit documentation comments for input parameters that do not have documentation already associated with them (i.e. the structs defined in google.golang.org/api/...).

**Comment by codyoss** [comment]
Thanks for the suggestion. I will take a look and see how other languages are handling this today.
