### ISSUE TITLE
Return more structured errors (e.g. when deleting resources)

### ISSUE THREAD

**Issue by thozza** [googleapis/google-api-go-client#960]
I'm implementing a Go code, which will clean up resources after canceled CloudBuild job. The resources include instances and disks. Disks are used by the instances which are being cleaned up.

I'm doing the operations in this order:
1. Delete all Instances left after the canceled CloudBuild job.
2. Delete all disks left after the canceled CloudBuild job.

However while I'm trying to delete disks, I'm getting a `resourceInUseByAnotherResource` error, because the instance that I deleted in the previous step has not been really deleted yet.

The problem from my point of view is that the error returned from `compute.Service.Disks.Delete(<PROJECT_ID>, <ZONE>, <DISK>).Context(ctx).Do()` is not structured and the only way to figure out the exact error from it, is through parsing the error string. Returning `googleapi.Error` with more detailed information  would be much easier to use programmatically.

The Go client library could expose more structured error objects and/or implement convenience methods to check for the reason of the error, similar to `googleapi.IsNotModified()`

An example REST API response:
```json
{
  "error": {
    "code": 400,
    "message": "The disk resource 'projects/<PROJECT>/zones/us-central1-a/disks/<DISK>' is already being used by 'projects/<PROJECT>/zones/us-central1-a/instances/<INSTANCE>'",
    "errors": [
      {
        "message": "The disk resource 'projects/<PROJECT>/zones/us-central1-a/disks/<DISK>' is already being used by 'projects/<PROJECT>/zones/us-central1-a/instances/<INSTANCE>'",
        "domain": "global",
        "reason": "resourceInUseByAnotherResource"
      }
    ]
  }
}
```
At least having the `reason` as part of the error structure returned by the Go client library would be nice.

However maybe I'm doing it all wrong, but I was not able to find any relevant clue in the documentation or on the Internet. Sure, I can parse the error message, but that seems wrong to me. Another thing that I could do is to explicitly check if the previously deleted instance still exists and wait until it does not, but that also seems not ideal.

I'll be thankful if you would consider the RFE to return more structured error or alternatively if you point me to a documentation on how to properly clean up disks right after deleting an instance which was using them.

Thanks!

**Comment by codyoss** [comment]
If you need to inspect the error the current recommendation is to convert it to a `*googleapi.Error`: See the following example in our docs: https://pkg.go.dev/google.golang.org/api#hdr-Inspecting_errors
