### ISSUE TITLE
flatPath missing in the discovery document's RestMethod

### ISSUE THREAD

**Issue by mikhailshilkov** [googleapis/google-api-go-client#961]
[`RestMethod`](https://github.com/googleapis/google-api-go-client/blob/2855950c5037c80caea1dbd6cec6e9e21a91e9f4/discovery/v1/discovery-gen.go#L698) struct should define a `FlatPath` property which is widely used in the existing discovery documents and is outlined in the [API reference](https://developers.google.com/discovery/v1/reference/apis):

> resources.(key).methods.(key).flatPath | string | The URI path of this REST method in (RFC 6570) format without level 2 features ({+var}).  Supplementary to the path property.

**Comment by codyoss** [comment]
This issue tracker is used mainly for the generated client themselves. This appears to be a feature request for the discovery service. I have filled an internal bug 184288835 raising this feature request.

**Comment by codyoss** [comment]
@mikhailshilkov It [has been added](https://github.com/googleapis/google-api-go-client/blob/3d19c369d96f0bcb8a31548a4df4325840c29542/discovery/v1/discovery-gen.go#L709)!

Thank you for pointing this out!
